Dillo: dw::oof::OOFFloatsMgr::SortedFloatsVector Class Reference
dw::oof::OOFFloatsMgr::SortedFloatsVector Class Reference
Public Member Functions
SortedFloatsVector (OOFFloatsMgr *oofm, Side side)
int findFloatIndex (OOFAwareWidget *lastGB, int lastExtIndex)
int find (int y, int start, int end)
int findFirst (int y, int h, OOFAwareWidget *lastGB, int lastExtIndex, int *lastReturn)
int findLastBeforeSideSpanningIndex (int sideSpanningIndex)
void put (Float *vloat)
lout::container::typed::Iterator
< Float > iterator ()
int size ()
Float * get (int pos)
void clear ()
Private Attributes
OOFFloatsMgr * oofm
Side side
Private Attributes inherited from lout::container::typed::Collection< Float >
untyped::Collection * base
Additional Inherited Members
Private Member Functions inherited from lout::container::typed::Vector< Float >
Vector (int initSize, bool ownerOfObjects)
void put (Float *newElement, int newPos=-1)
void insert (Float *newElement, int pos)
int insertSorted (Float *newElement, object::Comparator *comparator=&object::standardComparator)
void remove (int pos)
Float * get (int pos) const
void clear ()
void sort (object::Comparator *comparator=&object::standardComparator)
int bsearch (Float *key, bool mustExist, int start, int end, object::Comparator *comparator=&object::standardComparator)
int bsearch (Float *key, bool mustExist, object::Comparator *comparator=&object::standardComparator)
Private Member Functions inherited from lout::container::typed::Collection< Float >
Collection ()
~Collection ()
bool equals (Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Iterator< Float > iterator ()
int size ()
Private Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Detailed Description
This list is kept sorted.
To prevent accessing methods of the base class in an uncontrolled way, the inheritance is private, not public; this means that all methods must be delegated (see iterator(), size() etc. below.)
TODO Update comment: still sorted, but ...
More: add() and change() may check order again.
Constructor & Destructor Documentation
dw::oof::OOFFloatsMgr::SortedFloatsVector::SortedFloatsVector (OOFFloatsMgr * oofm, Side side) inline
References oofm, and side.
Member Function Documentation
void dw::oof::OOFFloatsMgr::SortedFloatsVector::clear () inline
References lout::container::typed::Vector< T >::clear().
int dw::oof::OOFFloatsMgr::SortedFloatsVector::find (int y, int start, int end)
y is given relative to the container.
References DBG_OBJ_ENTER_O, DBG_OBJ_LEAVE_VAL_O, and dw::oof::OOFFloatsMgr::Float::yReal.
int dw::oof::OOFFloatsMgr::SortedFloatsVector::findFirst (int y, int h, OOFAwareWidget * lastGB, int lastExtIndex, int * lastReturn)
References DBG_OBJ_ENTER_O, DBG_OBJ_LEAVE_VAL_O, and DBG_OBJ_MSGF_O.
Referenced by dw::oof::OOFFloatsMgr::getBorder(), dw::oof::OOFFloatsMgr::getFloatHeight(), and dw::oof::OOFFloatsMgr::hasFloat().
int dw::oof::OOFFloatsMgr::SortedFloatsVector::findFloatIndex (OOFAwareWidget * lastGB, int lastExtIndex)
References dw::oof::OOFFloatsMgr::Float::CompareGBAndExtIndex::compare(), DBG_OBJ_ENTER_O, DBG_OBJ_LEAVE_O, DBG_OBJ_MSGF_O, and dw::oof::OOFFloatsMgr::Float::index.
Referenced by dw::oof::OOFFloatsMgr::getClearPosition().
int dw::oof::OOFFloatsMgr::SortedFloatsVector::findLastBeforeSideSpanningIndex (int sideSpanningIndex)
References dw::oof::OOFFloatsMgr::Float::sideSpanningIndex.
Referenced by dw::oof::OOFFloatsMgr::tellPosition1().
Float* dw::oof::OOFFloatsMgr::SortedFloatsVector::get (int pos) inline
References lout::container::typed::Vector< T >::get().
Referenced by dw::oof::OOFFloatsMgr::containerSizeChangedForChildren(), dw::oof::OOFFloatsMgr::drawFloats(), dw::oof::OOFFloatsMgr::getBorder(), dw::oof::OOFFloatsMgr::getClearPosition(), dw::oof::OOFFloatsMgr::getFloatHeight(), dw::oof::OOFFloatsMgr::getFloatsExtremes(), dw::oof::OOFFloatsMgr::getFloatsSize(), dw::oof::OOFFloatsMgr::getFloatWidgetAtPoint(), dw::oof::OOFFloatsMgr::getWidget(), dw::oof::OOFFloatsMgr::markSizeChange(), dw::oof::OOFFloatsMgr::sizeAllocateFloats(), and dw::oof::OOFFloatsMgr::tellPosition1().
lout::container::typed::Iterator<Float> dw::oof::OOFFloatsMgr::SortedFloatsVector::iterator () inline
References lout::container::typed::Collection< T >::iterator().
void dw::oof::OOFFloatsMgr::SortedFloatsVector::put (Float * vloat)
References dw::oof::OOFFloatsMgr::Float::index, and lout::container::typed::Vector< T >::put().
Referenced by dw::oof::OOFFloatsMgr::addWidgetOOF().
int dw::oof::OOFFloatsMgr::SortedFloatsVector::size () inline
References lout::container::typed::Collection< T >::size().
Referenced by dw::oof::OOFFloatsMgr::addWidgetOOF(), dw::oof::OOFFloatsMgr::containerSizeChangedForChildren(), dw::oof::OOFFloatsMgr::drawFloats(), dw::oof::OOFFloatsMgr::getFloatsExtremes(), dw::oof::OOFFloatsMgr::getFloatsSize(), dw::oof::OOFFloatsMgr::getFloatWidgetAtPoint(), dw::oof::OOFFloatsMgr::getNumWidgets(), dw::oof::OOFFloatsMgr::getWidget(), dw::oof::OOFFloatsMgr::OOFFloatsMgr(), and dw::oof::OOFFloatsMgr::sizeAllocateFloats().
Member Data Documentation
OOFFloatsMgr* dw::oof::OOFFloatsMgr::SortedFloatsVector::oofm private
Referenced by SortedFloatsVector().
Side dw::oof::OOFFloatsMgr::SortedFloatsVector::side private
Referenced by SortedFloatsVector().
The documentation for this class was generated from the following files:
dw/ooffloatsmgr.hh
dw/ooffloatsmgr.cc