Dillo: form::Form::RadioButtonResourceDecorator Class Reference
form::Form::RadioButtonResourceDecorator Class Reference
Decorates instances of dw::core::ui::RadioButtonResource.
Public Member Functions
RadioButtonResourceDecorator (const char *name, dw::core::ui::RadioButtonResource *resource, const char **values)
~RadioButtonResourceDecorator ()
const char * getValue ()
Public Member Functions inherited from form::Form::ResourceDecorator
const char * getName ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Private Attributes
dw::core::ui::RadioButtonResource * resource
const char ** values
Additional Inherited Members
Protected Member Functions inherited from form::Form::ResourceDecorator
ResourceDecorator (const char *name)
~ResourceDecorator ()
Detailed Description
Decorates instances of dw::core::ui::RadioButtonResource.
This class has to be instantiated only once for a group of radio buttons.
Constructor & Destructor Documentation
form::Form::RadioButtonResourceDecorator::RadioButtonResourceDecorator (const char * name, dw::core::ui::RadioButtonResource * resource, const char ** values)
form::Form::RadioButtonResourceDecorator::~RadioButtonResourceDecorator ()
Member Function Documentation
const char * form::Form::RadioButtonResourceDecorator::getValue () virtual
Implements form::Form::ResourceDecorator.
References dw::core::ui::RadioButtonResource::GroupIterator::getNext(), dw::core::ui::RadioButtonResource::groupIterator(), dw::core::ui::RadioButtonResource::GroupIterator::hasNext(), dw::core::ui::ToggleButtonResource::isActivated(), and dw::core::ui::RadioButtonResource::GroupIterator::unref().
Member Data Documentation
dw::core::ui::RadioButtonResource* form::Form::RadioButtonResourceDecorator::resource private
const char** form::Form::RadioButtonResourceDecorator::values private
The documentation for this class was generated from the following files:
test/form.hh
test/form.cc