Dillo: dw::core::Layout::LinkReceiver Class Reference
dw::core::Layout::LinkReceiver Class Reference
#include <layout.hh>
Public Member Functions
virtual bool enter (Widget *widget, int link, int img, int x, int y)
Called, when a link is entered, left, or the position has changed.
virtual bool press (Widget *widget, int link, int img, int x, int y, EventButton *event)
Called, when the user has pressed the mouse button on a link (but not yet released).
virtual bool release (Widget *widget, int link, int img, int x, int y, EventButton *event)
Called, when the user has released the mouse button on a link.
virtual bool click (Widget *widget, int link, int img, int x, int y, EventButton *event)
Called, when the user has clicked on a link.
Public Member Functions inherited from lout::signal::Receiver
Receiver ()
~Receiver ()
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Member Function Documentation
bool dw::core::Layout::LinkReceiver::click (Widget * widget, int link, int img, int x, int y, EventButton * event) virtual
Called, when the user has clicked on a link.
For mouse interaction, this is equivalent to "press" and "release" on the same link. In this case, event contains the "release" event.
When activating links via keyboard is supported, only a "clicked" signal will be emitted, and event will be NULL.
Referenced by dw::core::Layout::LinkEmitter::emitToReceiver().
bool dw::core::Layout::LinkReceiver::enter (Widget * widget, int link, int img, int x, int y) virtual
Called, when a link is entered, left, or the position has changed.
When a link is entered, this method is called with the respective arguments. When a link is left, this method is called with all three arguments (link, x, y) set to -1.
When coordinates are supported, a change of the coordinates also causes emitting this signal.
Referenced by dw::core::Layout::LinkEmitter::emitToReceiver().
bool dw::core::Layout::LinkReceiver::press (Widget * widget, int link, int img, int x, int y, EventButton * event) virtual
Called, when the user has pressed the mouse button on a link (but not yet released).
The causing event is passed as event.
Referenced by dw::core::Layout::LinkEmitter::emitToReceiver().
bool dw::core::Layout::LinkReceiver::release (Widget * widget, int link, int img, int x, int y, EventButton * event) virtual
Called, when the user has released the mouse button on a link.
The causing event is passed as event.
Referenced by dw::core::Layout::LinkEmitter::emitToReceiver().
The documentation for this class was generated from the following files:
dw/layout.hh
dw/layout.cc