Dillo: dw::AlignedTextblock::List Class Reference
dw::AlignedTextblock::List Class Reference
Public Member Functions
List ()
int add (AlignedTextblock *textblock)
void unref (int pos)
int getMaxValue ()
void setMaxValue (int maxValue)
int size ()
AlignedTextblock * getTextblock (int pos)
int getValue (int pos)
void setValue (int pos, int value)
Private Member Functions
~List ()
Private Attributes
lout::misc::SimpleVector
< AlignedTextblock * > * textblocks
lout::misc::SimpleVector< int > * values
int maxValue
int refCount
Constructor & Destructor Documentation
dw::AlignedTextblock::List::~List () private
dw::AlignedTextblock::List::List ()
References maxValue, refCount, textblocks, and values.
Member Function Documentation
int dw::AlignedTextblock::List::add (AlignedTextblock * textblock) inline
Referenced by dw::AlignedTextblock::setRefTextblock().
int dw::AlignedTextblock::List::getMaxValue () inline
References maxValue.
Referenced by dw::AlignedTextblock::updateValue().
AlignedTextblock* dw::AlignedTextblock::List::getTextblock (int pos) inline
References lout::misc::SimpleVector< T >::get().
Referenced by dw::AlignedTextblock::updateValue().
int dw::AlignedTextblock::List::getValue (int pos) inline
References lout::misc::SimpleVector< T >::get().
Referenced by dw::AlignedTextblock::updateValue().
void dw::AlignedTextblock::List::setMaxValue (int maxValue) inline
References maxValue.
Referenced by dw::AlignedTextblock::updateValue().
void dw::AlignedTextblock::List::setValue (int pos, int value) inline
References lout::misc::SimpleVector< T >::set().
Referenced by dw::AlignedTextblock::updateValue().
int dw::AlignedTextblock::List::size () inline
References lout::misc::SimpleVector< T >::size().
Referenced by dw::AlignedTextblock::updateValue().
void dw::AlignedTextblock::List::unref (int pos)
Referenced by dw::AlignedTextblock::~AlignedTextblock().
Member Data Documentation
int dw::AlignedTextblock::List::maxValue private
Referenced by getMaxValue(), List(), and setMaxValue().
int dw::AlignedTextblock::List::refCount private
Referenced by List().
lout::misc::SimpleVector<AlignedTextblock*>* dw::AlignedTextblock::List::textblocks private
Referenced by List().
lout::misc::SimpleVector<int>* dw::AlignedTextblock::List::values private
Referenced by List().
The documentation for this class was generated from the following files:
dw/alignedtextblock.hh
dw/alignedtextblock.cc