Dillo: dw::core::Layout Class Reference
dw::core::Layout Class Reference
The central class for managing and drawing a widget tree.
#include <layout.hh>
Classes
class Anchor
class Emitter
class LayoutImgRenderer
class LinkEmitter
class LinkReceiver
class Receiver
Receiver interface different signals.
Public Member Functions
Layout (Platform *platform)
~Layout ()
void connectLink (LinkReceiver *receiver)
bool emitLinkEnter (Widget *w, int link, int img, int x, int y)
bool emitLinkPress (Widget *w, int link, int img, int x, int y, EventButton *event)
bool emitLinkRelease (Widget *w, int link, int img, int x, int y, EventButton *event)
bool emitLinkClick (Widget *w, int link, int img, int x, int y, EventButton *event)
void addWidget (Widget *widget)
void setWidget (Widget *widget)
void attachView (View *view)
Attach a view to the layout.
void detachView (View *view)
bool getUsesViewport ()
int getWidthViewport ()
int getHeightViewport ()
int getScrollPosX ()
int getScrollPosY ()
void scrollTo (HPosition hpos, VPosition vpos, int x, int y, int width, int height)
Scrolls all viewports, so that the region [x, y, width, height] is seen, according to hpos and vpos.
void scroll (ScrollCommand)
void setAnchor (const char *anchor)
void expose (View *view, Rectangle *area)
bool buttonPress (View *view, int numPressed, int x, int y, ButtonState state, int button)
This function is called by a view, to delegate a button press event.
void containerSizeChanged ()
bool buttonRelease (View *view, int numPressed, int x, int y, ButtonState state, int button)
This function is called by a view, to delegate a button press event.
bool motionNotify (View *view, int x, int y, ButtonState state)
This function is called by a view, to delegate a motion notify event.
void enterNotify (View *view, int x, int y, ButtonState state)
This function is called by a view, to delegate a enter notify event.
void leaveNotify (View *view, ButtonState state)
This function is called by a view, to delegate a leave notify event.
void scrollPosChanged (View *view, int x, int y)
void viewportSizeChanged (View *view, int width, int height)
Platform * getPlatform ()
int textWidth (style::Font *font, const char *text, int len)
char * textToUpper (const char *text, int len)
char * textToLower (const char *text, int len)
int nextGlyph (const char *text, int idx)
int prevGlyph (const char *text, int idx)
float dpiX ()
float dpiY ()
style::Font * createFont (style::FontAttrs *attrs, bool tryEverything)
bool fontExists (const char *name)
style::Color * createColor (int color)
style::Tooltip * createTooltip (const char *text)
void cancelTooltip ()
Imgbuf * createImgbuf (Imgbuf::Type type, int width, int height, double gamma)
void copySelection (const char *text)
ui::ResourceFactory * getResourceFactory ()
void connect (Receiver *receiver)
FindtextState::Result search (const char *str, bool caseSens, int backwards)
See dw::core::FindtextState::search.
void resetSearch ()
See dw::core::FindtextState::resetSearch.
void setBgColor (style::Color *color)
void setBgImage (style::StyleImage *bgImage, style::BackgroundRepeat bgRepeat, style::BackgroundAttachment bgAttachment, style::Length bgPositionX, style::Length bgPositionY)
style::Color * getBgColor ()
style::StyleImage * getBgImage ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Public Attributes
LinkEmitter linkEmitter
lout::misc::ZoneAllocator * textZone
Private Types
enum ButtonEventType { BUTTON_PRESS, BUTTON_RELEASE, MOTION_NOTIFY }
Private Member Functions
void detachWidget (Widget *widget)
Widget * getWidgetAtPoint (int x, int y)
void moveToWidget (Widget *newWidgetAtPoint, ButtonState state)
void moveToWidgetAtPoint (int x, int y, ButtonState state)
Emit the necessary crossing events, when the mouse pointer has moved to position (x,);.
void moveOutOfView (ButtonState state)
Emit the necessary crossing events, when the mouse pointer has moved out of the view.
bool processMouseEvent (MousePositionEvent *event, ButtonEventType type)
Common processing of press, release and motion events.
bool buttonEvent (ButtonEventType type, View *view, int numPressed, int x, int y, ButtonState state, int button)
void resizeIdle ()
void setSizeHints ()
void draw (View *view, Rectangle *area)
void scrollTo0 (HPosition hpos, VPosition vpos, int x, int y, int width, int height, bool scrollingInterrupted)
void scrollIdle ()
void adjustScrollPos ()
int currHScrollbarThickness ()
int currVScrollbarThickness ()
void updateAnchor ()
char * addAnchor (Widget *widget, const char *name)
char * addAnchor (Widget *widget, const char *name, int y)
void changeAnchor (Widget *widget, char *name, int y)
void removeAnchor (Widget *widget, char *name)
void setCursor (style::Cursor cursor)
void updateCursor ()
void queueDraw (int x, int y, int width, int height)
void queueDrawExcept (int x, int y, int width, int height, int ex, int ey, int ewidth, int eheight)
void queueResize (bool extremesChanged)
void removeWidget ()
void enterResizeIdle ()
void leaveResizeIdle ()
Static Private Member Functions
static bool calcScrollInto (int targetValue, int requestedSize, int *value, int viewportSize)
Private Attributes
LayoutImgRenderer * layoutImgRenderer
Emitter emitter
Platform * platform
View * view
Widget * topLevel
Widget * widgetAtPoint
lout::container::typed::Vector
< Widget > * queueResizeList
style::Color * bgColor
style::StyleImage * bgImage
style::BackgroundRepeat bgRepeat
style::BackgroundAttachment bgAttachment
style::Length bgPositionX
style::Length bgPositionY
style::Cursor cursor
int canvasWidth
int canvasAscent
int canvasDescent
bool usesViewport
bool drawAfterScrollReq
int scrollX
int scrollY
int viewportWidth
int viewportHeight
bool canvasHeightGreater
int hScrollbarThickness
int vScrollbarThickness
HPosition scrollTargetHpos
VPosition scrollTargetVpos
int scrollTargetX
int scrollTargetY
int scrollTargetWidth
int scrollTargetHeight
char * requestedAnchor
int scrollIdleId
int resizeIdleId
bool scrollIdleNotInterrupted
lout::container::typed::HashTable
< lout::object::String, Anchor > * anchorsTable
SelectionState selectionState
FindtextState findtextState
int resizeIdleCounter
int queueResizeCounter
int sizeAllocateCounter
int sizeRequestCounter
int getExtremesCounter
Friends
class Widget
Detailed Description
The central class for managing and drawing a widget tree.
See also
Dillo Widget Overview, Layout and Widgets, Layout and Views
Member Enumeration Documentation
enum dw::core::Layout::ButtonEventType private
Enumerator
BUTTON_PRESS
BUTTON_RELEASE
MOTION_NOTIFY
Constructor & Destructor Documentation
dw::core::Layout::Layout (Platform * platform)
References dw::core::style::CURSOR_DEFAULT, DBG_OBJ_ASSOC_CHILD, DBG_OBJ_CREATE, DBG_OBJ_SET_NUM, platform, and dw::core::Platform::setLayout().
dw::core::Layout::~Layout ()
References DBG_OBJ_DELETE, and platform.
Member Function Documentation
char * dw::core::Layout::addAnchor (Widget * widget, const char * name) private
Used, when the widget is not allocated yet.
Referenced by dw::core::Widget::addAnchor().
char * dw::core::Layout::addAnchor (Widget * widget, const char * name, int y) private
References dw::core::Layout::Anchor::name, dw::core::Layout::Anchor::widget, and dw::core::Layout::Anchor::y.
void dw::core::Layout::addWidget (Widget * widget)
References dw::core::Widget::container, DBG_OBJ_ASSOC, DBG_OBJ_SET_PTR_O, DBG_OBJ_SET_SYM, dw::IMPL_POS, dw::core::Widget::layout, dw::core::Widget::notifySetAsTopLevel(), dw::core::Widget::stackingContextMgr, and dw::core::Widget::stackingContextWidget.
void dw::core::Layout::adjustScrollPos () private
References lout::misc::max(), and lout::misc::min().
void dw::core::Layout::attachView (View * view)
Attach a view to the layout.
It will become a child of the layout, and so it will be destroyed, when the layout will be destroyed.
References DBG_OBJ_ASSOC_CHILD, DBG_OBJ_SET_NUM, dw::core::View::getHScrollbarThickness(), dw::core::View::getVScrollbarThickness(), lout::misc::max(), platform, dw::core::View::scrollTo(), dw::core::View::setBgColor(), dw::core::View::setCanvasSize(), dw::core::View::setCursor(), dw::core::View::setLayout(), dw::core::View::setViewportSize(), and dw::core::View::usesViewport().
Referenced by dw::fltk::ui::FltkComplexButtonResource::createNewWidget(), dw::fltk::FltkPreview::FltkPreview(), main(), and dw::fltk::ui::FltkComplexButtonResource::setLayout().
bool dw::core::Layout::buttonEvent (ButtonEventType type, View * view, int numPressed, int x, int y, ButtonState state, int button) private
Referenced by buttonPress(), and buttonRelease().
bool dw::core::Layout::buttonPress (View * view, int numPressed, int x, int y, ButtonState state, int button) inline
This function is called by a view, to delegate a button press event.
numPressed is 1 for simple presses, 2 for double presses etc. (more that 2 is never needed), x and y the world coordinates, and button the number of the button pressed.
References BUTTON_PRESS, and buttonEvent().
Referenced by dw::fltk::FltkViewBase::handle().
bool dw::core::Layout::buttonRelease (View * view, int numPressed, int x, int y, ButtonState state, int button) inline
This function is called by a view, to delegate a button press event.
Arguments are similar to dw::core::Layout::buttonPress.
References BUTTON_RELEASE, and buttonEvent().
Referenced by dw::fltk::FltkViewBase::handle().
bool dw::core::Layout::calcScrollInto (int targetValue, int requestedSize, int * value, int viewportSize) static private
void dw::core::Layout::cancelTooltip () inline
References dw::core::Platform::cancelTooltip().
Referenced by dw::fltk::FltkViewBase::handle().
void dw::core::Layout::changeAnchor (Widget * widget, char * name, int y) private
References dw::core::Layout::Anchor::widget, and dw::core::Layout::Anchor::y.
Referenced by dw::core::Widget::changeAnchor().
void dw::core::Layout::connect (Receiver * receiver) inline
References dw::core::Layout::Emitter::connectLayout().
void dw::core::Layout::connectLink (LinkReceiver * receiver) inline
References dw::core::Layout::LinkEmitter::connectLink().
Referenced by main().
void dw::core::Layout::containerSizeChanged ()
References DBG_OBJ_ENTER0, and DBG_OBJ_LEAVE.
void dw::core::Layout::copySelection (const char * text) inline
References dw::core::Platform::copySelection().
style::Color* dw::core::Layout::createColor (int color) inline
References dw::core::Platform::createColor().
Referenced by dw::core::style::Color::create().
style::Font* dw::core::Layout::createFont (style::FontAttrs * attrs, bool tryEverything) inline
References dw::core::Platform::createFont().
Referenced by dw::core::style::Font::create0().
Imgbuf* dw::core::Layout::createImgbuf (Imgbuf::Type type, int width, int height, double gamma) inline
References dw::core::Platform::createImgbuf().
Referenced by imageInitTimeout(), solution1(), solution2(), and solution3().
style::Tooltip* dw::core::Layout::createTooltip (const char * text) inline
References dw::core::Platform::createTooltip().
Referenced by dw::core::style::Tooltip::create().
int dw::core::Layout::currHScrollbarThickness () private
int dw::core::Layout::currVScrollbarThickness () private
void dw::core::Layout::detachView (View * view)
Todo:
Actually, viewportMarkerWidthDiff and viewportMarkerHeightDiff have to be recalculated here, since the effective (i.e. maximal) values may change, after the view has been detached. Same applies to the usage of viewports.
References platform, and dw::core::View::setLayout().
void dw::core::Layout::detachWidget (Widget * widget) private
References dw::core::Iterator::getContent(), dw::core::Widget::iterator(), dw::core::Widget::layout, dw::core::Iterator::next(), dw::core::Iterator::unref(), and dw::core::Content::widget.
float dw::core::Layout::dpiX () inline
References dw::core::Platform::dpiX().
float dw::core::Layout::dpiY () inline
References dw::core::Platform::dpiY().
void dw::core::Layout::draw (View * view, Rectangle * area) private
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, dw::core::style::drawBackgroundImage(), dw::core::View::finishDrawing(), dw::core::Rectangle::height, dw::core::Rectangle::intersectsWith(), lout::misc::max(), dw::core::View::startDrawing(), dw::core::Rectangle::width, dw::core::Rectangle::x, and dw::core::Rectangle::y.
Referenced by expose().
bool dw::core::Layout::emitLinkClick (Widget * w, int link, int img, int x, int y, EventButton * event) inline
References dw::core::Layout::LinkEmitter::emitClick().
bool dw::core::Layout::emitLinkEnter (Widget * w, int link, int img, int x, int y) inline
References dw::core::Layout::LinkEmitter::emitEnter().
bool dw::core::Layout::emitLinkPress (Widget * w, int link, int img, int x, int y, EventButton * event) inline
References dw::core::Layout::LinkEmitter::emitPress().
bool dw::core::Layout::emitLinkRelease (Widget * w, int link, int img, int x, int y, EventButton * event) inline
References dw::core::Layout::LinkEmitter::emitRelease().
void dw::core::Layout::enterNotify (View * view, int x, int y, ButtonState state)
This function is called by a view, to delegate a enter notify event.
Arguments are similar to dw::core::Layout::buttonPress.
References dw::core::Widget::enterNotify().
Referenced by dw::fltk::FltkViewBase::handle().
void dw::core::Layout::enterResizeIdle () inline private
void dw::core::Layout::expose (View * view, Rectangle * area) inline
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, draw(), dw::core::Rectangle::height, dw::core::Rectangle::width, dw::core::Rectangle::x, and dw::core::Rectangle::y.
Referenced by dw::fltk::FltkViewBase::draw().
bool dw::core::Layout::fontExists (const char * name) inline
References dw::core::Platform::fontExists().
Referenced by dw::core::style::Font::exists().
style::Color* dw::core::Layout::getBgColor () inline
References bgColor.
Referenced by dw::core::style::drawBackground().
style::StyleImage* dw::core::Layout::getBgImage () inline
References bgImage.
Referenced by dw::core::style::drawBackground().
int dw::core::Layout::getHeightViewport () inline
References viewportHeight.
Referenced by dw::core::Iterator::scrollTo().
Platform* dw::core::Layout::getPlatform () inline
References platform.
ui::ResourceFactory* dw::core::Layout::getResourceFactory () inline
References dw::core::Platform::getResourceFactory().
Referenced by main().
int dw::core::Layout::getScrollPosX () inline
References scrollX.
int dw::core::Layout::getScrollPosY () inline
References scrollY.
bool dw::core::Layout::getUsesViewport () inline
References usesViewport.
Referenced by dw::core::Iterator::scrollTo().
Widget * dw::core::Layout::getWidgetAtPoint (int x, int y) private
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, and dw::core::Widget::getWidgetAtPoint().
Referenced by moveToWidgetAtPoint().
int dw::core::Layout::getWidthViewport () inline
References viewportWidth.
Referenced by dw::core::Iterator::scrollTo().
void dw::core::Layout::leaveNotify (View * view, ButtonState state)
This function is called by a view, to delegate a leave notify event.
Arguments are similar to dw::core::Layout::buttonPress.
References dw::core::Widget::leaveNotify().
Referenced by dw::fltk::FltkViewBase::handle().
void dw::core::Layout::leaveResizeIdle () inline private
bool dw::core::Layout::motionNotify (View * view, int x, int y, ButtonState state)
This function is called by a view, to delegate a motion notify event.
Arguments are similar to dw::core::Layout::buttonPress.
Referenced by dw::fltk::FltkViewBase::handle(), and dw::fltk::FltkViewport::positionChanged().
void dw::core::Layout::moveOutOfView (ButtonState state) inline private
Emit the necessary crossing events, when the mouse pointer has moved out of the view.
References moveToWidget().
void dw::core::Layout::moveToWidget (Widget * newWidgetAtPoint, ButtonState state) private
References dw::core::EventCrossing::currentWidget, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::core::Widget::enterNotify(), dw::core::Widget::getNearestCommonAncestor(), dw::core::Widget::getParent(), dw::core::Widget::getTopLevel(), dw::core::EventCrossing::lastWidget, dw::core::Widget::leaveNotify(), and dw::core::MouseEvent::state.
Referenced by moveOutOfView(), and moveToWidgetAtPoint().
void dw::core::Layout::moveToWidgetAtPoint (int x, int y, ButtonState state) inline private
Emit the necessary crossing events, when the mouse pointer has moved to position (x,);.
References getWidgetAtPoint(), and moveToWidget().
int dw::core::Layout::nextGlyph (const char * text, int idx) inline
References dw::core::Platform::nextGlyph().
Referenced by dw::fltk::FltkWidgetView::drawText().
int dw::core::Layout::prevGlyph (const char * text, int idx) inline
References dw::core::Platform::prevGlyph().
bool dw::core::Layout::processMouseEvent (MousePositionEvent * event, ButtonEventType type) private
Common processing of press, release and motion events.
This function depends on that move_to_widget_at_point() has been called before.
References lout::misc::assertNotReached(), dw::core::Widget::buttonPress(), dw::core::Widget::buttonRelease(), dw::core::Widget::getAllocation(), dw::core::Widget::getParent(), dw::core::Widget::isButtonSensitive(), lout::misc::min(), dw::core::Widget::motionNotify(), dw::core::Allocation::x, dw::core::MousePositionEvent::xCanvas, dw::core::Allocation::y, and dw::core::MousePositionEvent::yCanvas.
void dw::core::Layout::queueDraw (int x, int y, int width, int height) private
References dw::core::Rectangle::height, dw::core::Rectangle::isEmpty(), dw::core::Rectangle::width, dw::core::Rectangle::x, and dw::core::Rectangle::y.
void dw::core::Layout::queueDrawExcept (int x, int y, int width, int height, int ex, int ey, int ewidth, int eheight) private
References lout::misc::max(), and lout::misc::min().
void dw::core::Layout::queueResize (bool extremesChanged) private
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, and platform.
void dw::core::Layout::removeAnchor (Widget * widget, char * name) private
Referenced by dw::core::Widget::removeAnchor().
void dw::core::Layout::removeWidget () private
Bug:
Some more attributes must be reset here.
void dw::core::Layout::resetSearch () inline
See dw::core::FindtextState::resetSearch.
References dw::core::FindtextState::resetSearch().
Referenced by resetCallback().
void dw::core::Layout::resizeIdle () private
References dw::core::Widget::allocateQueued(), dw::core::Allocation::ascent, dw::core::Requisition::ascent, DBG_OBJ_ENTER0, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, DBG_OBJ_SET_SYM, dw::core::Allocation::descent, dw::core::Requisition::descent, dw::core::Widget::extremesQueued(), lout::container::typed::Iterator< T >::hasNext(), dw::core::Widget::resizeQueued(), dw::core::Widget::setFlags(), dw::core::Widget::unsetFlags(), dw::core::Allocation::width, dw::core::Requisition::width, dw::core::Allocation::x, and dw::core::Allocation::y.
void dw::core::Layout::scroll (ScrollCommand cmd)
References dw::core::View::scroll().
void dw::core::Layout::scrollIdle () private
References dw::core::HPOS_CENTER, dw::core::HPOS_INTO_VIEW, dw::core::HPOS_LEFT, dw::core::HPOS_NO_CHANGE, dw::core::HPOS_RIGHT, dw::core::VPOS_BOTTOM, dw::core::VPOS_CENTER, dw::core::VPOS_INTO_VIEW, dw::core::VPOS_NO_CHANGE, and dw::core::VPOS_TOP.
void dw::core::Layout::scrollPosChanged (View * view, int x, int y)
Referenced by dw::fltk::FltkViewport::scrollTo(), and dw::fltk::FltkPreviewWindow::scrollTo().
void dw::core::Layout::scrollTo (HPosition hpos, VPosition vpos, int x, int y, int width, int height)
Scrolls all viewports, so that the region [x, y, width, height] is seen, according to hpos and vpos.
Referenced by dw::fltk::FltkViewBase::manageTabToFocus(), and dw::core::Iterator::scrollTo().
void dw::core::Layout::scrollTo0 (HPosition hpos, VPosition vpos, int x, int y, int width, int height, bool scrollingInterrupted) private
References platform.
FindtextState::Result dw::core::Layout::search (const char * str, bool caseSens, int backwards) inline
See dw::core::FindtextState::search.
References dw::core::FindtextState::search().
Referenced by findCallback().
void dw::core::Layout::setAnchor (const char * anchor)
Sets the anchor to scroll to.
Referenced by anchorCallback().
void dw::core::Layout::setBgColor (style::Color * color)
References dw::core::style::Color::ref().
void dw::core::Layout::setBgImage (style::StyleImage * bgImage, style::BackgroundRepeat bgRepeat, style::BackgroundAttachment bgAttachment, style::Length bgPositionX, style::Length bgPositionY)
References dw::core::style::StyleImage::putExternalImgRenderer(), dw::core::style::StyleImage::ref(), dw::core::style::StyleImage::removeExternalImgRenderer(), and dw::core::style::StyleImage::unref().
Referenced by main().
void dw::core::Layout::setCursor (style::Cursor cursor) private
Referenced by dw::core::Widget::setCursor().
void dw::core::Layout::setSizeHints () private
void dw::core::Layout::setWidget (Widget * widget)
References DBG_OBJ_ASSOC_CHILD.
Referenced by main(), and textTimeout().
char* dw::core::Layout::textToLower (const char * text, int len) inline
References dw::core::Platform::textToLower().
char* dw::core::Layout::textToUpper (const char * text, int len) inline
References dw::core::Platform::textToUpper().
int dw::core::Layout::textWidth (style::Font * font, const char * text, int len) inline
References dw::core::Platform::textWidth().
Referenced by dw::AlignedTableCell::getValue().
void dw::core::Layout::updateAnchor () private
Todo:
Copy comment from old docs.
References dw::core::HPOS_NO_CHANGE, platform, dw::core::VPOS_TOP, and dw::core::Layout::Anchor::y.
void dw::core::Layout::updateCursor () private
References dw::core::style::CURSOR_DEFAULT.
void dw::core::Layout::viewportSizeChanged (View * view, int width, int height)
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_SET_NUM, and DBG_OBJ_SET_SYM.
Referenced by dw::fltk::FltkViewport::resize(), and dw::fltk::FltkViewBase::setLayout().
Friends And Related Function Documentation
friend class Widget friend
Member Data Documentation
lout::container::typed::HashTable<lout::object::String, Anchor>* dw::core::Layout::anchorsTable private
style::BackgroundAttachment dw::core::Layout::bgAttachment private
style::Color* dw::core::Layout::bgColor private
Referenced by getBgColor().
style::StyleImage* dw::core::Layout::bgImage private
Referenced by getBgImage().
style::Length dw::core::Layout::bgPositionX private
style::Length dw::core::Layout::bgPositionY private
style::BackgroundRepeat dw::core::Layout::bgRepeat private
int dw::core::Layout::canvasAscent private
int dw::core::Layout::canvasDescent private
bool dw::core::Layout::canvasHeightGreater private
int dw::core::Layout::canvasWidth private
style::Cursor dw::core::Layout::cursor private
bool dw::core::Layout::drawAfterScrollReq private
Emitter dw::core::Layout::emitter private
FindtextState dw::core::Layout::findtextState private
int dw::core::Layout::getExtremesCounter private
Referenced by dw::core::Widget::enterGetExtremes(), dw::core::Widget::getExtremesEntered(), and dw::core::Widget::leaveGetExtremes().
int dw::core::Layout::hScrollbarThickness private
LayoutImgRenderer* dw::core::Layout::layoutImgRenderer private
LinkEmitter dw::core::Layout::linkEmitter
Platform* dw::core::Layout::platform private
Referenced by getPlatform().
int dw::core::Layout::queueResizeCounter private
Referenced by dw::core::Widget::enterQueueResize(), dw::core::Widget::leaveQueueResize(), and dw::core::Widget::queueResizeEntered().
lout::container::typed::Vector<Widget>* dw::core::Layout::queueResizeList private
char* dw::core::Layout::requestedAnchor private
int dw::core::Layout::resizeIdleCounter private
Referenced by dw::core::Widget::resizeIdleEntered().
int dw::core::Layout::resizeIdleId private
int dw::core::Layout::scrollIdleId private
bool dw::core::Layout::scrollIdleNotInterrupted private
int dw::core::Layout::scrollTargetHeight private
HPosition dw::core::Layout::scrollTargetHpos private
VPosition dw::core::Layout::scrollTargetVpos private
int dw::core::Layout::scrollTargetWidth private
int dw::core::Layout::scrollTargetX private
int dw::core::Layout::scrollTargetY private
int dw::core::Layout::scrollX private
Referenced by getScrollPosX().
int dw::core::Layout::scrollY private
Referenced by getScrollPosY().
SelectionState dw::core::Layout::selectionState private
Referenced by dw::core::Widget::selectionHandleEvent().
int dw::core::Layout::sizeAllocateCounter private
Referenced by dw::core::Widget::enterSizeAllocate(), dw::core::Widget::leaveSizeAllocate(), and dw::core::Widget::sizeAllocateEntered().
int dw::core::Layout::sizeRequestCounter private
Referenced by dw::core::Widget::enterSizeRequest(), dw::core::Widget::leaveSizeRequest(), and dw::core::Widget::sizeRequestEntered().
lout::misc::ZoneAllocator* dw::core::Layout::textZone
Widget* dw::core::Layout::topLevel private
bool dw::core::Layout::usesViewport private
Referenced by getUsesViewport().
View* dw::core::Layout::view private
int dw::core::Layout::viewportHeight private
Referenced by getHeightViewport().
int dw::core::Layout::viewportWidth private
Referenced by getWidthViewport().
int dw::core::Layout::vScrollbarThickness private
Widget * dw::core::Layout::widgetAtPoint private
The documentation for this class was generated from the following files:
dw/layout.hh
dw/layout.cc