Dillo: dw::Hyphenator Class Reference
dw::Hyphenator Class Reference
#include <hyphenator.hh>
Public Member Functions
Hyphenator (const char *patFile, const char *excFile, int pack=256)
~Hyphenator ()
int * hyphenateWord (core::Platform *platform, const char *word, int *numBreaks)
void saveTrie (FILE *fp)
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Static Public Member Functions
static Hyphenator * getHyphenator (const char *language)
static bool isHyphenationCandidate (const char *word)
Private Member Functions
void insertPattern (TrieBuilder *trieBuilder, char *s)
void insertException (char *s)
void hyphenateSingleWord (core::Platform *platform, char *wordLc, int offset, lout::misc::SimpleVector< int > *breakPos)
bool isCharPartOfActualWord (char *s)
Private Attributes
Trie * trie
lout::container::typed::HashTable
< lout::object::ConstString,
lout::container::typed::Vector
< lout::object::Integer > > * exceptions
Static Private Attributes
static
lout::container::typed::HashTable
< lout::object::String,
Hyphenator > * hyphenators
Constructor & Destructor Documentation
dw::Hyphenator::Hyphenator (const char * patFile, const char * excFile, int pack = 256)
References dw::TrieBuilder::createTrie(), and LEN.
dw::Hyphenator::~Hyphenator ()
Member Function Documentation
Hyphenator * dw::Hyphenator::getHyphenator (const char * language) static
Referenced by hyphenateWord().
void dw::Hyphenator::hyphenateSingleWord (core::Platform * platform, char * wordLc, int offset, lout::misc::SimpleVector< int > * breakPos) private
Hyphenate a single word, which only consists of lowercase characters. Store break positions + "offset" in "breakPos".
References lout::misc::SimpleVector< T >::get(), lout::container::typed::Vector< T >::get(), lout::object::Integer::getValue(), lout::misc::SimpleVector< T >::increase(), lout::misc::max(), lout::misc::min(), lout::unicode::nextUtf8Char(), lout::unicode::numUtf8Chars(), lout::misc::SimpleVector< T >::set(), lout::misc::SimpleVector< T >::setSize(), lout::misc::SimpleVector< T >::size(), and lout::container::typed::Collection< T >::size().
int * dw::Hyphenator::hyphenateWord (core::Platform * platform, const char * word, int * numBreaks)
Given a word, returns a list of the possible hyphenation points.
References lout::misc::SimpleVector< T >::detachArray(), dw::core::Platform::nextGlyph(), lout::misc::SimpleVector< T >::size(), and dw::core::Platform::textToLower().
Referenced by hyphenateWord(), and dw::Textblock::hyphenateWord().
void dw::Hyphenator::insertException (char * s) private
References lout::container::typed::Vector< T >::put(), and lout::container::typed::Collection< T >::size().
void dw::Hyphenator::insertPattern (TrieBuilder * trieBuilder, char * s) private
References lout::misc::SimpleVector< T >::getArray(), dw::TrieBuilder::insert(), lout::misc::SimpleVector< T >::set(), and lout::misc::SimpleVector< T >::setSize().
bool dw::Hyphenator::isCharPartOfActualWord (char * s) private
Test whether the character on which "s" points (UTF-8) is an actual part of the word. Other characters at the beginning and end are ignored.
TODO Currently only suitable for English and German. TODO Only lowercase. (Uppercase not needed.)
References lout::unicode::decodeUtf8(), and lout::unicode::isAlpha().
bool dw::Hyphenator::isHyphenationCandidate (const char * word) static
Simple test to avoid much costs. Passing it does not mean that the word can be hyphenated.
void dw::Hyphenator::saveTrie (FILE * fp) inline
References dw::Trie::save().
Referenced by main().
Member Data Documentation
lout::container::typed::HashTable<lout::object::ConstString, lout::container::typed::Vector <lout::object::Integer> >* dw::Hyphenator::exceptions private
HashTable< String, Hyphenator > * dw::Hyphenator::hyphenators static private
Initial value:
=
   new HashTable <String, Hyphenator> (true, true)
Trie* dw::Hyphenator::trie private
The documentation for this class was generated from the following files:
dw/hyphenator.hh
dw/hyphenator.cc