Dillo: dw::fltk::ui::FltkSpecificResource< I > Class Template Reference
dw::fltk::ui::FltkSpecificResource< I > Class Template Reference
#include <fltkui.hh>
Public Member Functions
FltkSpecificResource (FltkPlatform *platform)
~FltkSpecificResource ()
void sizeAllocate (core::Allocation *allocation)
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void setStyle (core::style::Style *style)
bool isEnabled ()
void setEnabled (bool enabled)
Public Member Functions inherited from dw::fltk::ui::FltkResource
~FltkResource ()
virtual void attachView (FltkView *view)
virtual void detachView (FltkView *view)
void sizeAllocate (core::Allocation *allocation)
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void setStyle (core::style::Style *style)
bool isEnabled ()
void setEnabled (bool enabled)
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Additional Inherited Members
Protected Member Functions inherited from dw::fltk::ui::FltkResource
FltkResource (FltkPlatform *platform)
void init (FltkPlatform *platform)
virtual Fl_Widget * createNewWidget (core::Allocation *allocation)=0
virtual void setWidgetStyle (Fl_Widget *widget, core::style::Style *style)
void setDisplayed (bool displayed)
bool displayed ()
Protected Attributes inherited from dw::fltk::ui::FltkResource
FltkView * view
Fl_Widget * widget
core::Allocation allocation
FltkPlatform * platform
core::style::Style * style
Constructor & Destructor Documentation
template<class I > dw::fltk::ui::FltkSpecificResource< I >::FltkSpecificResource (FltkPlatform * platform)
References DBG_OBJ_BASECLASS, and DBG_OBJ_CREATE.
template<class I > dw::fltk::ui::FltkSpecificResource< I >::~FltkSpecificResource ()
References DBG_OBJ_DELETE.
Member Function Documentation
template<class I > void dw::fltk::ui::FltkSpecificResource< I >::draw (core::View * view, core::Rectangle * area, core::DrawingContext * context)
References dw::fltk::ui::FltkResource::draw().
template<class I > bool dw::fltk::ui::FltkSpecificResource< I >::isEnabled ()
References dw::fltk::ui::FltkResource::isEnabled().
template<class I > void dw::fltk::ui::FltkSpecificResource< I >::setEnabled (bool enabled)
References dw::fltk::ui::FltkResource::setEnabled().
template<class I > void dw::fltk::ui::FltkSpecificResource< I >::setStyle (core::style::Style * style)
References dw::fltk::ui::FltkResource::setStyle().
template<class I > void dw::fltk::ui::FltkSpecificResource< I >::sizeAllocate (core::Allocation * allocation)
References dw::fltk::ui::FltkResource::sizeAllocate().
The documentation for this class was generated from the following files:
dw/fltkui.hh
dw/fltkui.cc