Dillo: dw::fltk::FltkPreviewButton Class Reference
dw::fltk::FltkPreviewButton Class Reference
#include <fltkpreview.hh>
Public Member Functions
FltkPreviewButton (int x, int y, int w, int h, dw::core::Layout *layout, const char *label=0)
~FltkPreviewButton ()
int handle (int event)
Private Attributes
FltkPreviewWindow * window
Constructor & Destructor Documentation
dw::fltk::FltkPreviewButton::FltkPreviewButton (int x, int y, int w, int h, dw::core::Layout * layout, const char * label = 0)
References image, and window.
dw::fltk::FltkPreviewButton::~FltkPreviewButton ()
Member Function Documentation
int dw::fltk::FltkPreviewButton::handle (int event)
Bug:
Some parts are missing.
References dw::fltk::FltkPreviewWindow::hideWindow(), dw::fltk::FltkPreviewWindow::scrollTo(), dw::fltk::FltkPreviewWindow::showWindow(), and window.
Member Data Documentation
FltkPreviewWindow* dw::fltk::FltkPreviewButton::window private
Referenced by FltkPreviewButton(), and handle().
The documentation for this class was generated from the following files:
dw/fltkpreview.hh
dw/fltkpreview.cc