Dillo: dw::core::ui::ResourceFactory Class Reference
dw::core::ui::ResourceFactory Class Reference abstract
A factory for the common resource.
#include <ui.hh>
Public Member Functions
virtual LabelButtonResource * createLabelButtonResource (const char *label)=0
virtual ComplexButtonResource * createComplexButtonResource (Widget *widget, bool relief)=0
virtual ListResource * createListResource (ListResource::SelectionMode selectionMode, int rows)=0
virtual OptionMenuResource * createOptionMenuResource ()=0
virtual EntryResource * createEntryResource (int size, bool password, const char *label, const char *placeholder)=0
virtual MultiLineTextResource * createMultiLineTextResource (int cols, int rows, const char *placeholder)=0
virtual CheckButtonResource * createCheckButtonResource (bool activated)=0
virtual RadioButtonResource * createRadioButtonResource (RadioButtonResource *groupedWith, bool activated)=0
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Detailed Description
A factory for the common resource.
Member Function Documentation
virtual CheckButtonResource* dw::core::ui::ResourceFactory::createCheckButtonResource (bool activated) pure virtual
Implemented in dw::fltk::FltkPlatform::FltkResourceFactory.
Referenced by main().
virtual ComplexButtonResource* dw::core::ui::ResourceFactory::createComplexButtonResource (Widget * widget, bool relief) pure virtual
Implemented in dw::fltk::FltkPlatform::FltkResourceFactory.
Referenced by main().
virtual EntryResource* dw::core::ui::ResourceFactory::createEntryResource (int size, bool password, const char * label, const char * placeholder) pure virtual
Implemented in dw::fltk::FltkPlatform::FltkResourceFactory.
Referenced by main().
virtual LabelButtonResource* dw::core::ui::ResourceFactory::createLabelButtonResource (const char * label) pure virtual
Implemented in dw::fltk::FltkPlatform::FltkResourceFactory.
Referenced by main().
virtual ListResource* dw::core::ui::ResourceFactory::createListResource (ListResource::SelectionMode selectionMode, int rows) pure virtual
Implemented in dw::fltk::FltkPlatform::FltkResourceFactory.
Referenced by main().
virtual MultiLineTextResource* dw::core::ui::ResourceFactory::createMultiLineTextResource (int cols, int rows, const char * placeholder) pure virtual
Implemented in dw::fltk::FltkPlatform::FltkResourceFactory.
Referenced by main().
virtual OptionMenuResource* dw::core::ui::ResourceFactory::createOptionMenuResource () pure virtual
Implemented in dw::fltk::FltkPlatform::FltkResourceFactory.
Referenced by main().
virtual RadioButtonResource* dw::core::ui::ResourceFactory::createRadioButtonResource (RadioButtonResource * groupedWith, bool activated) pure virtual
Implemented in dw::fltk::FltkPlatform::FltkResourceFactory.
Referenced by main().
The documentation for this class was generated from the following file:
dw/ui.hh