Dillo: dw::SimpleTableCell Class Reference
dw::SimpleTableCell Class Reference
#include <simpletablecell.hh>
Public Member Functions
SimpleTableCell (bool limitTextWidth)
~SimpleTableCell ()
int applyPerWidth (int containerWidth, core::style::Length perWidth)
int applyPerHeight (int containerHeight, core::style::Length perHeight)
bool isBlockLevel ()
bool usesMaxGeneratorWidth ()
Public Member Functions inherited from dw::Textblock
Textblock (bool limitTextWidth)
~Textblock ()
core::Iterator * iterator (core::Content::Type mask, bool atEnd)
Return an iterator for this widget.
void flush ()
void addText (const char *text, size_t len, core::style::Style *style)
void addText (const char *text, core::style::Style *style)
void addWidget (core::Widget *widget, core::style::Style *style)
bool addAnchor (const char *name, core::style::Style *style)
void addSpace (core::style::Style *style)
void addBreakOption (core::style::Style *style, bool forceBreak)
void addParbreak (int space, core::style::Style *style)
void addLinebreak (core::style::Style *style)
void handOverBreak (core::style::Style *style)
void changeLinkColor (int link, int newColor)
void changeWordStyle (int from, int to, core::style::Style *style, bool includeFirstSpace, bool includeLastSpace)
void updateReference (int ref)
void widgetRefSizeChanged (int externalIndex)
void clearPositionChanged ()
void oofSizeChanged (bool extremesChanged)
int getGeneratorX (int oofmIndex)
int getGeneratorY (int oofmIndex)
int getGeneratorWidth (int callerX, int callerWidth)
int getMaxGeneratorWidth ()
bool usesMaxGeneratorWidth ()
bool isPossibleOOFContainer (int oofmIndex)
bool isPossibleOOFContainerParent (int oofmIndex)
Public Member Functions inherited from dw::RegardingBorder
RegardingBorder ()
~RegardingBorder ()
Public Member Functions inherited from dw::oof::OOFAwareWidget
OOFAwareWidget ()
~OOFAwareWidget ()
core::Requisition * getRequisitionWithoutOOF ()
bool doesWidgetOOFInterruptDrawing (Widget *widget)
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
Public Member Functions inherited from dw::core::Widget
void setDeleteCallback (DW_Callback_t func, void *data)
Widget ()
~Widget ()
bool resizeQueued ()
bool extremesQueued ()
bool needsResize ()
bool needsAllocate ()
bool allocateQueued ()
bool extremesChanged ()
bool wasAllocated ()
void setParent (Widget *parent)
void setQuasiParent (Widget *quasiParent)
void setGenerator (Widget *generator)
style::Style * getStyle ()
Allocation * getAllocation ()
bool inAllocation (int x, int y)
int boxOffsetX ()
int boxRestWidth ()
int boxDiffWidth ()
int boxOffsetY ()
int boxRestHeight ()
int boxDiffHeight ()
void sizeRequest (Requisition *requisition, int numPos=0, Widget **references=NULL, int *x=NULL, int *y=NULL)
This method is a wrapper for Widget::sizeRequestImpl(); it calls the latter only when needed.
void getExtremes (Extremes *extremes, int numPos=0, Widget **references=NULL, int *x=NULL, int *y=NULL)
Wrapper for Widget::getExtremesImpl().
void sizeAllocate (Allocation *allocation)
Wrapper for Widget::sizeAllocateImpl, calls the latter only when needed.
void calcExtraSpace (int numPos, Widget **references, int *x, int *y)
Calculates dw::core::Widget::extraSpace.
int getAvailWidth (bool forceValue)
int getAvailHeight (bool forceValue)
void correctRequisition (Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
void correctExtremes (Extremes *extremes, bool useAdjustmentWidth)
int calcWidth (style::Length cssValue, int refWidth, Widget *refWidget, int limitMinWidth, bool forceValue)
void calcFinalWidth (style::Style *style, int refWidth, Widget *refWidget, int limitMinWidth, bool forceValue, int *finalWidth)
int calcHeight (style::Length cssValue, bool usePercentage, int refHeight, Widget *refWidget, bool forceValue)
int getMinWidth (Extremes *extremes, bool forceValue)
Used to evaluate Widget::adjustMinWidth.
virtual bool isPossibleContainer ()
void containerSizeChanged ()
bool intersects (Widget *refWidget, Rectangle *area, Rectangle *intersection)
Calculates the intersection of the visible allocation (i. e. the intersection with the visible parent allocation) and "area" (in widget coordinates referring to "refWidget"), returned in intersection (in widget coordinates).
void drawInterruption (View *view, Rectangle *area, DrawingContext *context)
Widget * getWidgetAtPointInterrupted (int x, int y, GettingWidgetAtPointContext *context)
bool buttonPress (EventButton *event)
bool buttonRelease (EventButton *event)
bool motionNotify (EventMotion *event)
void enterNotify (EventCrossing *event)
void leaveNotify (EventCrossing *event)
virtual void setStyle (style::Style *style)
Change the style of a widget.
void setBgColor (style::Color *bgColor)
Set the background "behind" the widget, if it is not the background of the parent widget, e.g. the background of a table row.
style::Color * getBgColor ()
Get the actual background of a widget.
void drawBox (View *view, style::Style *style, Rectangle *area, int x, int y, int width, int height, bool inverse)
Draw borders and background of a widget part, which allocation is given by (x, y, width, height) (widget coordinates).
void drawWidgetBox (View *view, Rectangle *area, bool inverse)
Draw borders and background of a widget.
void drawSelected (View *view, Rectangle *area)
void setButtonSensitive (bool buttonSensitive)
bool isButtonSensitive ()
Widget * getParent ()
Widget * getContainer ()
Widget * getTopLevel ()
Get the widget at the root of the tree, this widget is part from.
int getLevel ()
Get the level of the widget within the tree.
int getGeneratorLevel ()
Get the level of the widget within the tree, regarting the generators, not the parents.
Widget * getNearestCommonAncestor (Widget *otherWidget)
Get the widget with the highest level, which is a direct ancestor of widget1 and widget2.
WidgetReference * getWidgetReference ()
void setWidgetReference (WidgetReference *widgetReference)
Widget * getGenerator ()
Layout * getLayout ()
void scrollTo (HPosition hpos, VPosition vpos, int x, int y, int width, int height)
void getMarginArea (int *xMar, int *yMar, int *widthMar, int *heightMar)
void getBorderArea (int *xBor, int *yBor, int *widthBor, int *heightBor)
void getPaddingArea (int *xPad, int *yPad, int *widthPad, int *heightPad)
Return the padding area (content plus padding).
virtual void removeChild (Widget *child)
Public Member Functions inherited from lout::identity::IdentifiableObject
IdentifiableObject ()
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
int getClassId ()
Returns the class identifier.
const char * getClassName ()
Return the name, under which the class of this object was registered.
bool instanceOf (int otherClassId)
Returns, whether this class is an instance of the class, given by otherClassId, or of a sub class of this class.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Static Public Attributes
static int CLASS_ID = -1
Static Public Attributes inherited from dw::Textblock
static int CLASS_ID = -1
Static Public Attributes inherited from dw::RegardingBorder
static int CLASS_ID = -1
Static Public Attributes inherited from dw::oof::OOFAwareWidget
static int CLASS_ID = -1
Static Public Attributes inherited from dw::core::Widget
static int CLASS_ID = -1
Protected Member Functions
int getAvailWidthOfChild (Widget *child, bool forceValue)
int getAvailHeightOfChild (Widget *child, bool forceValue)
void correctRequisitionOfChild (Widget *child, core::Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
void correctExtremesOfChild (Widget *child, core::Extremes *extremes, bool useAdjustmentWidth)
bool getAdjustMinWidth ()
bool adjustExtraSpaceWhenCorrectingRequisitionByOOF ()
Protected Member Functions inherited from dw::Textblock
void queueDrawRange (int index1, int index2)
int calcVerticalBorder (int widgetPadding, int widgetBorder, int widgetMargin, int lineBorderTotal, int lineMarginTotal)
void getWordExtremes (Word *word, core::Extremes *extremes)
void justifyLine (Line *line, int diff)
Line * addLine (int firstWord, int lastWord, int newLastOofPos, bool temporary, int minHeight)
void rewrap ()
void fillParagraphs ()
void initNewLine ()
void calcBorders (int lastOofRef, int height)
void showMissingLines ()
void removeTemporaryLines ()
void decorateText (core::View *view, core::style::Style *style, core::style::Color::Shading shading, int x, int yBase, int width)
void drawText (core::View *view, core::style::Style *style, core::style::Color::Shading shading, int x, int y, const char *text, int start, int len, bool isStart, bool isEnd)
void drawWord (Line *line, int wordIndex1, int wordIndex2, core::View *view, core::Rectangle *area, int xWidget, int yWidgetBase)
void drawWord0 (int wordIndex1, int wordIndex2, const char *text, int totalWidth, bool drawHyphen, core::style::Style *style, core::View *view, core::Rectangle *area, int xWidget, int yWidgetBase)
void drawSpace (int wordIndex, core::View *view, core::Rectangle *area, int xWidget, int yWidgetBase)
void drawLine (Line *line, core::View *view, core::Rectangle *area, core::DrawingContext *context)
int findLineIndex (int y)
int findLineIndexWhenNotAllocated (int y)
int findLineIndexWhenAllocated (int y)
int findLineIndex (int y, int ascent)
int findLineOfWord (int wordIndex)
Find the line of word wordIndex.
int findParagraphOfWord (int wordIndex)
Find the paragraph of word wordIndex.
Word * findWord (int x, int y, bool *inSpace)
Find the index of the word, or -1.
Word * addWord (int width, int ascent, int descent, short flags, core::style::Style *style)
void breakAdded ()
void initWord (int wordNo)
void cleanupWord (int wordNo)
void removeWordImgRenderer (int wordNo)
void setWordImgRenderer (int wordNo)
void removeSpaceImgRenderer (int wordNo)
void setSpaceImgRenderer (int wordNo)
void fillWord (int wordNo, int width, int ascent, int descent, short flags, core::style::Style *style)
void fillSpace (int wordNo, core::style::Style *style)
void setBreakOption (Word *word, core::style::Style *style, int breakPenalty1, int breakPenalty2, bool forceBreak)
bool isBreakAllowedInWord (Word *word)
bool isBreakAllowed (core::style::Style *style)
int textWidth (const char *text, int start, int len, core::style::Style *style, bool isStart, bool isEnd)
void calcTextSize (const char *text, size_t len, core::style::Style *style, core::Requisition *size, bool isStart, bool isEnd)
bool calcSizeOfWidgetInFlow (int wordIndex, Widget *widget, core::Requisition *size)
bool findSizeRequestReference (Widget *reference, int *xRef=NULL, int *yRef=NULL)
bool findSizeRequestReference (int oofmIndex, int *xRef=NULL, int *yRef=NULL)
bool mustBorderBeRegarded (Line *line)
bool mustBorderBeRegarded (int lineNo)
int lineYOffsetWidget (Line *line, core::Allocation *allocation)
int lineYOffsetWidget (Line *line)
int lineYOffsetCanvas (Line *line, core::Allocation *allocation)
int lineYOffsetCanvas (Line *line)
int lineYOffsetWidget (int lineIndex)
int lineYOffsetWidget (int lineIndex, core::Allocation *allocation)
int lineYOffsetCanvas (int lineIndex)
int calcPenaltyIndexForNewLine ()
RegardingBorder * getWidgetRegardingBorderForLine (Line *line)
RegardingBorder * getWidgetRegardingBorderForLine (int lineNo)
RegardingBorder * getWidgetRegardingBorderForLine (int firstWord, int lastWord)
int yOffsetOfLineToBeCreated (int *lastMargin=NULL)
int yOffsetOfLineCreated (Line *line)
bool sendSelectionEvent (core::SelectionState::EventType eventType, core::MousePositionEvent *event)
Send event to selection.
void processWord (int wordIndex)
virtual int wordWrap (int wordIndex, bool wrapAll)
int wrapWordInFlow (int wordIndex, bool wrapAll)
int wrapWordOofRef (int wordIndex, bool wrapAll)
void balanceBreakPosAndHeight (int wordIndex, int firstIndex, int *searchUntil, bool tempNewLine, int penaltyIndex, bool borderIsCalculated, bool *thereWillBeMoreSpace, bool wrapAll, int *diffWords, int *wordIndexEnd, int *lastFloatPos, bool regardBorder, int *height, int *breakPos)
int searchBreakPos (int wordIndex, int firstIndex, int *searchUntil, bool tempNewLine, int penaltyIndex, bool thereWillBeMoreSpace, bool wrapAll, int *diffWords, int *wordIndexEnd, int *addIndex1=NULL)
int searchMinBap (int firstWord, int lastWordm, int penaltyIndex, bool thereWillBeMoreSpace, bool correctAtEnd)
int considerHyphenation (int firstIndex, int breakPos)
bool isHyphenationCandidate (Word *word)
int calcLinePartHeight (int firstWord, int lastWord)
void handleWordExtremes (int wordIndex)
void correctLastWordExtremes ()
int getLineShrinkability (int lastWordIndex)
int getLineStretchability (int lastWordIndex)
int hyphenateWord (int wordIndex, int *addIndex1=NULL)
void moveWordIndices (int wordIndex, int num, int *addIndex1=NULL)
void accumulateWordForLine (int lineIndex, int wordIndex)
void accumulateWordData (int wordIndex)
int calcLineBreakWidth (int lineIndex)
void initLine1Offset (int wordIndex)
void alignLine (int lineIndex)
void calcTextOffset (int lineIndex, int totalWidth)
void drawLevel (core::View *view, core::Rectangle *area, int level, core::DrawingContext *context)
Widget * getWidgetAtPointLevel (int x, int y, int level, core::GettingWidgetAtPointContext *context)
void sizeRequestImpl (core::Requisition *requisition, int numPos, Widget **references, int *x, int *y)
int numSizeRequestReferences ()
See Sizes of Dillo Widgets (or Size requisitions depending on positions).
Widget * sizeRequestReference (int index)
See Sizes of Dillo Widgets (or Size requisitions depending on positions).
void getExtremesSimpl (core::Extremes *extremes)
Simple variant, to be implemented by widgets with extremes not depending on positions.
int numGetExtremesReferences ()
See Sizes of Dillo Widgets (or Size requisitions depending on positions).
Widget * getExtremesReference (int index)
See Sizes of Dillo Widgets (or Size requisitions depending on positions).
void notifySetAsTopLevel ()
This method is called after a widget has been set as the top of a widget tree.
void notifySetParent ()
This method is called after a widget has been added to a parent.
void sizeAllocateImpl (core::Allocation *allocation)
See Sizes of Dillo Widgets.
void calcExtraSpaceImpl (int numPos, Widget **references, int *x, int *y)
int getAvailWidthOfChild (core::Widget *child, bool forceValue)
int getAvailHeightOfChild (core::Widget *child, bool forceValue)
void containerSizeChangedForChildren ()
bool affectsSizeChangeContainerChild (Widget *child)
bool usesAvailWidth ()
Must be implemengted by a method returning true, when getAvailWidth() is called.
void resizeDrawImpl ()
Called after sizeAllocateImpl() to redraw necessary areas. By default the whole widget is redrawn.
void markSizeChange (int ref)
See Sizes of Dillo Widgets.
void markExtremesChange (int ref)
See Sizes of Dillo Widgets.
bool isBlockLevel ()
bool buttonPressImpl (core::EventButton *event)
bool buttonReleaseImpl (core::EventButton *event)
bool motionNotifyImpl (core::EventMotion *event)
void enterNotifyImpl (core::EventCrossing *event)
void leaveNotifyImpl (core::EventCrossing *event)
void removeChild (Widget *child)
void addText0 (const char *text, size_t len, short flags, core::style::Style *style, core::Requisition *size)
void calcTextSizes (const char *text, size_t textLen, core::style::Style *style, int numBreaks, int *breakPos, core::Requisition *wordSize)
int getGeneratorRest (int oofmIndex)
Protected Member Functions inherited from dw::oof::OOFAwareWidget
bool isParentRefOOF (int parentRef)
int makeParentRefInFlow (int inFlowSubRef)
int getParentRefInFlowSubRef (int parentRef)
int makeParentRefOOF (int oofmIndex, int oofmSubRef)
int getParentRefOOFSubRef (int parentRef)
int getParentRefOOFIndex (int parentRef)
oof::OutOfFlowMgr * getParentRefOutOfFlowMgr (int parentRef)
bool isWidgetOOF (Widget *widget)
int getWidgetInFlowSubRef (Widget *widget)
int getWidgetOOFSubRef (Widget *widget)
int getWidgetOOFIndex (Widget *widget)
oof::OutOfFlowMgr * getWidgetOutOfFlowMgr (Widget *widget)
OutOfFlowMgr * searchOutOfFlowMgr (int oofmIndex)
void initOutOfFlowMgrs ()
void correctRequisitionByOOF (core::Requisition *requisition, void(*splitHeightFun)(int, int *, int *))
void correctExtremesByOOF (core::Extremes *extremes)
void sizeAllocateStart (core::Allocation *allocation)
void sizeAllocateEnd ()
void containerSizeChangedForChildrenOOF ()
void drawOOF (core::View *view, core::Rectangle *area, core::DrawingContext *context)
Widget * getWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext *context)
Widget * getWidgetOOFAtPoint (int x, int y, core::GettingWidgetAtPointContext *context)
void removeChild (Widget *child)
Protected Member Functions inherited from dw::core::Widget
int getHeight ()
int getContentWidth ()
int getContentHeight ()
StackingContextMgr * getNextStackingContextMgr ()
void printFlag (Flags f)
void setFlags (Flags f)
void unsetFlags (Flags f)
void queueDraw ()
void queueDrawArea (int x, int y, int width, int height)
void queueResize (int ref, bool extremesChanged)
virtual void sizeRequestImpl (Requisition *requisition, int numPos, Widget **references, int *x, int *y)
See Sizes of Dillo Widgets.
virtual void sizeRequestSimpl (Requisition *requisition)
Simple variant, to be implemented by widgets with sizes not depending on positions.
virtual void getExtremesImpl (Extremes *extremes, int numPos, Widget **references, int *x, int *y)
See Sizes of Dillo Widgets.
virtual void calcExtraSpaceImpl (int numPos, Widget **references, int *x, int *y)
The actual implementation for calculating dw::core::Widget::extraSpace.
virtual void correctRequisitionOfChild (Widget *child, Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
void correctReqWidthOfChild (Widget *child, Requisition *requisition, bool allowDecreaseWidth)
void correctReqHeightOfChild (Widget *child, Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseHeight)
virtual void correctExtremesOfChild (Widget *child, Extremes *extremes, bool useAdjustmentWidth)
virtual bool affectedByContainerSizeChange ()
virtual bool affectsSizeChangeContainerChild (Widget *child)
virtual bool usesAvailHeight ()
Must be implemengted by a method returning true, when getAvailHeight() is called.
char * addAnchor (const char *name)
char * addAnchor (const char *name, int y)
void changeAnchor (char *name, int y)
void removeAnchor (char *name)
void setCursor (style::Cursor cursor)
bool selectionHandleEvent (SelectionState::EventType eventType, Iterator *it, int charPos, int linkNo, MousePositionEvent *event)
Protected Member Functions inherited from lout::identity::IdentifiableObject
void registerName (const char *className, int *classId)
This method must be called in the constructor for the sub class. See class comment for details.
Additional Inherited Members
Public Types inherited from dw::oof::OOFAwareWidget
enum {
SL_START, SL_BACKGROUND, SL_SC_BOTTOM, SL_IN_FLOW,
SL_OOF_REF, SL_OOF_CONT, SL_SC_TOP, SL_END
}
Static Public Member Functions inherited from dw::Textblock
static void setPenaltyHyphen (int penaltyHyphen)
static void setPenaltyHyphen2 (int penaltyHyphen2)
static void setPenaltyEmDashLeft (int penaltyLeftEmDash)
static void setPenaltyEmDashRight (int penaltyRightEmDash)
static void setPenaltyEmDashRight2 (int penaltyRightEmDash2)
static void setStretchabilityFactor (int stretchabilityFactor)
static bool mustAddBreaks (core::style::Style *style)
Static Public Member Functions inherited from dw::oof::OOFAwareWidget
static const char * stackingLevelText (int level)
static bool testStyleFloat (core::style::Style *style)
static bool testStyleAbsolutelyPositioned (core::style::Style *style)
static bool testStyleFixedlyPositioned (core::style::Style *style)
static bool testStyleRelativelyPositioned (core::style::Style *style)
static bool testStylePositioned (core::style::Style *style)
static bool testStyleOutOfFlow (core::style::Style *style)
static bool testWidgetFloat (Widget *widget)
static bool testWidgetAbsolutelyPositioned (Widget *widget)
static bool testWidgetFixedlyPositioned (Widget *widget)
static bool testWidgetRelativelyPositioned (Widget *widget)
static bool testWidgetPositioned (Widget *widget)
static bool testWidgetOutOfFlow (Widget *widget)
Static Public Member Functions inherited from dw::core::Widget
static void setAdjustMinWidth (bool adjustMinWidth)
static void adjustHeight (int *height, bool allowDecreaseHeight, int ascent, int descent)
Public Attributes inherited from dw::core::Widget
int parentRef
This value is defined by the parent widget, and used for incremential resizing.
Protected Types inherited from dw::oof::OOFAwareWidget
enum {
OOFM_FLOATS, OOFM_ABSOLUTE, OOFM_RELATIVE, OOFM_FIXED,
NUM_OOFM
}
enum { PARENT_REF_OOFM_BITS = 3, PARENT_REF_OOFM_MASK = (1 << PARENT_REF_OOFM_BITS) - 1 }
Protected Types inherited from dw::core::Widget
enum Flags {
RESIZE_QUEUED = 1 << 0, EXTREMES_QUEUED = 1 << 1, NEEDS_RESIZE = 1 << 2, NEEDS_ALLOCATE = 1 << 3,
ALLOCATE_QUEUED = 1 << 4, EXTREMES_CHANGED = 1 << 5, WAS_ALLOCATED = 1 << 6
}
Static Protected Member Functions inherited from dw::Textblock
static int getSpaceShrinkability (struct Word *word)
static int getSpaceStretchability (struct Word *word)
Static Protected Member Functions inherited from dw::oof::OOFAwareWidget
static int getOOFMIndex (Widget *widget)
static bool isOOFContainer (Widget *widget, int oofmIndex)
Protected Attributes inherited from dw::Textblock
bool hasListitemValue
int leftInnerPadding
int line1Offset
int line1OffsetEff
bool ignoreLine1OffsetSometimes
bool mustQueueResize
bool limitTextWidth
int redrawY
int lastWordDrawn
core::SizeParams sizeRequestParams
int lineBreakWidth
int wrapRefLines
int wrapRefParagraphs
int wrapRefLinesFCX
int wrapRefLinesFCY
bool newLineHasFloatLeft
bool newLineHasFloatRight
int newLineLeftBorder
int newLineRightBorder
int newLineLeftFloatHeight
int newLineRightFloatHeight
int newLineAscent
int newLineDescent
lout::misc::SimpleVector< Line > * lines
lout::misc::SimpleVector
< Paragraph > * paragraphs
int nonTemporaryLines
lout::misc::NotSoSimpleVector
< Word > * words
lout::misc::SimpleVector
< Anchor > * anchors
struct {
int index
int nChar
} hlStart [core::HIGHLIGHT_NUM_LAYERS]
struct {
int index
int nChar
} hlEnd [core::HIGHLIGHT_NUM_LAYERS]
int hoverLink
int numSizeReferences
Widget * sizeReferences [NUM_OOFM]
Protected Attributes inherited from dw::oof::OOFAwareWidget
OOFAwareWidget * oofContainer [NUM_OOFM]
OutOfFlowMgr * outOfFlowMgr [NUM_OOFM]
core::Requisition requisitionWithoutOOF
Protected Attributes inherited from dw::core::Widget
WidgetImgRenderer * widgetImgRenderer
Allocation allocation
The current allocation: size and position, always relative to the canvas.
Layout * layout
style::Box extraSpace
Space around the margin box. Allocation is extraSpace + margin + border + padding + contents.
StackingContextMgr * stackingContextMgr
Set iff this widget constitutes a stacking context, as defined by CSS.
Widget * stackingContextWidget
The bottom-most ancestor (or this) for which stackingContextMgr is set.
Static Protected Attributes inherited from dw::Textblock
static int penalties [PENALTY_NUM][2]
static int stretchabilityFactor = 100
Static Protected Attributes inherited from dw::oof::OOFAwareWidget
static const char * OOFM_NAME [NUM_OOFM]
Constructor & Destructor Documentation
dw::SimpleTableCell::SimpleTableCell (bool limitTextWidth)
References CLASS_ID, DBG_OBJ_CREATE, and lout::identity::IdentifiableObject::registerName().
dw::SimpleTableCell::~SimpleTableCell ()
References DBG_OBJ_DELETE.
Member Function Documentation
bool dw::SimpleTableCell::adjustExtraSpaceWhenCorrectingRequisitionByOOF () protected virtual
Reimplemented from dw::oof::OOFAwareWidget.
References dw::tablecell::adjustExtraSpaceWhenCorrectingRequisitionByOOF().
int dw::SimpleTableCell::applyPerHeight (int containerHeight, core::style::Length perHeight) virtual
Reimplemented from dw::core::Widget.
References dw::tablecell::applyPerHeight().
int dw::SimpleTableCell::applyPerWidth (int containerWidth, core::style::Length perWidth) virtual
Reimplemented from dw::core::Widget.
References dw::tablecell::applyPerWidth().
void dw::SimpleTableCell::correctExtremesOfChild (Widget * child, core::Extremes * extremes, bool useAdjustmentWidth) protected
References dw::tablecell::correctCorrectedExtremesOfChild(), dw::core::Widget::correctExtremesOfChild(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE, dw::core::Extremes::maxWidth, dw::core::Extremes::maxWidthIntrinsic, dw::core::Extremes::minWidth, and dw::core::Extremes::minWidthIntrinsic.
void dw::SimpleTableCell::correctRequisitionOfChild (Widget * child, core::Requisition * requisition, void(*)(int, int *, int *) splitHeightFun, bool allowDecreaseWidth, bool allowDecreaseHeight) protected
References dw::core::Requisition::ascent, lout::misc::boolToStr(), dw::tablecell::correctCorrectedRequisitionOfChild(), dw::core::Widget::correctRequisitionOfChild(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE, dw::core::Requisition::descent, and dw::core::Requisition::width.
bool dw::SimpleTableCell::getAdjustMinWidth () protected virtual
Reimplemented from dw::core::Widget.
References dw::tablecell::getAdjustMinWidth().
int dw::SimpleTableCell::getAvailHeightOfChild (Widget * child, bool forceValue) protected
References dw::tablecell::correctAvailHeightOfChild(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE, and dw::Textblock::getAvailHeightOfChild().
int dw::SimpleTableCell::getAvailWidthOfChild (Widget * child, bool forceValue) protected
References dw::tablecell::correctAvailWidthOfChild(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE, and dw::Textblock::getAvailWidthOfChild().
bool dw::SimpleTableCell::isBlockLevel () virtual
Reimplemented from dw::core::Widget.
References dw::tablecell::isBlockLevel().
bool dw::SimpleTableCell::usesMaxGeneratorWidth () virtual
Reimplemented from dw::oof::OOFAwareWidget.
References dw::tablecell::usesMaxGeneratorWidth().
Member Data Documentation
int dw::SimpleTableCell::CLASS_ID = -1 static
Referenced by SimpleTableCell().
The documentation for this class was generated from the following files:
dw/simpletablecell.hh
dw/simpletablecell.cc