Dillo: lout::container::typed::Iterator< T > Class Template Reference
lout::container::typed::Iterator< T > Class Template Reference
Typed version of container::untyped::Iterator.
#include <container.hh>
Public Member Functions
Iterator ()
Iterator (const Iterator< T > &it2)
Iterator (Iterator< T > &it2)
~Iterator ()
Iterator & operator= (const Iterator< T > &it2)
Iterator & operator= (Iterator< T > &it2)
bool hasNext ()
T * getNext ()
Private Attributes
untyped::Iterator base
Friends
class Collection< T >
Detailed Description
template<class T>
class lout::container::typed::Iterator< T >
Typed version of container::untyped::Iterator.
Constructor & Destructor Documentation
template<class T> lout::container::typed::Iterator< T >::Iterator () inline
template<class T> lout::container::typed::Iterator< T >::Iterator (const Iterator< T > & it2) inline
template<class T> lout::container::typed::Iterator< T >::Iterator (Iterator< T > & it2) inline
template<class T> lout::container::typed::Iterator< T >::~Iterator () inline
Member Function Documentation
template<class T> T* lout::container::typed::Iterator< T >::getNext () inline
Referenced by dw::core::Region::addRectangle(), dw::ImageMapsList::ImageMap::draw(), dw::fltk::FltkViewBase::draw(), dw::ImageMapsList::ImageMap::link(), and dw::fltk::FltkPlatform::removeIdle().
template<class T> bool lout::container::typed::Iterator< T >::hasNext () inline
Referenced by dw::core::Region::addRectangle(), dw::fltk::FltkImgbuf::copyRow(), dw::ImageMapsList::ImageMap::draw(), dw::fltk::FltkViewBase::draw(), lout::signal::Emitter::emitBool(), lout::signal::Emitter::emitVoid(), dw::fltk::FltkImgbuf::getScaledBuf(), dw::ImageMapsList::ImageMap::link(), dw::fltk::FltkImgbuf::newScan(), dw::fltk::FltkPlatform::removeIdle(), dw::core::Layout::resizeIdle(), lout::signal::Emitter::~Emitter(), and lout::signal::Receiver::~Receiver().
template<class T> Iterator& lout::container::typed::Iterator< T >::operator= (const Iterator< T > & it2) inline
template<class T> Iterator& lout::container::typed::Iterator< T >::operator= (Iterator< T > & it2) inline
Friends And Related Function Documentation
template<class T> friend class Collection< T > friend
Member Data Documentation
template<class T> untyped::Iterator lout::container::typed::Iterator< T >::base private
Referenced by lout::container::typed::Iterator< dw::fltk::ui::FltkRadioButtonResource >::Iterator(), lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::Widget > >::iterator(), and lout::container::typed::Iterator< dw::fltk::ui::FltkRadioButtonResource >::operator=().
The documentation for this class was generated from the following file:
lout/container.hh