Dillo: dw::fltk::FltkColor Class Reference
dw::fltk::FltkColor Class Reference
#include <fltkplatform.hh>
Static Public Member Functions
static FltkColor * create (int color)
Static Public Member Functions inherited from dw::core::style::Color
static Color * create (Layout *layout, int color)
Public Attributes
int colors [SHADING_NUM]
Private Member Functions
FltkColor (int color)
~FltkColor ()
Static Private Attributes
static
lout::container::typed::HashTable
< dw::core::style::ColorAttrs,
FltkColor > * colorsTable
Additional Inherited Members
Public Types inherited from dw::core::style::Color
enum Shading {
SHADING_NORMAL, SHADING_INVERSE, SHADING_DARK, SHADING_LIGHT,
SHADING_NUM
}
Public Member Functions inherited from dw::core::style::Color
void ref ()
void unref ()
Public Member Functions inherited from dw::core::style::ColorAttrs
ColorAttrs (int color)
int getColor ()
bool equals (lout::object::Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions inherited from dw::core::style::Color
Color (int color)
virtual ~Color ()
int shadeColor (int color, Shading shading)
Protected Attributes inherited from dw::core::style::ColorAttrs
int color
Constructor & Destructor Documentation
dw::fltk::FltkColor::FltkColor (int color) private
References dw::core::style::ColorAttrs::color, colors, dw::core::style::Color::shadeColor(), dw::core::style::Color::SHADING_DARK, dw::core::style::Color::SHADING_INVERSE, dw::core::style::Color::SHADING_LIGHT, and dw::core::style::Color::SHADING_NORMAL.
Referenced by create().
dw::fltk::FltkColor::~FltkColor () private
References colorsTable.
Member Function Documentation
FltkColor * dw::fltk::FltkColor::create (int color) static
References dw::core::style::ColorAttrs::color, dw::core::style::ColorAttrs::ColorAttrs(), colorsTable, and FltkColor().
Referenced by dw::fltk::FltkPlatform::createColor().
Member Data Documentation
int dw::fltk::FltkColor::colors[SHADING_NUM]
Referenced by FltkColor(), and dw::fltk::ui::FltkResource::setWidgetStyle().
container::typed::HashTable< dw::core::style::ColorAttrs, FltkColor > * dw::fltk::FltkColor::colorsTable static private
Initial value:
=
      new container::typed::HashTable <dw::core::style::ColorAttrs,
                                       FltkColor> (false, false)
Referenced by create(), and ~FltkColor().
The documentation for this class was generated from the following files:
dw/fltkplatform.hh
dw/fltkplatform.cc