Dillo: lout::container::typed::List< T > Class Template Reference
lout::container::typed::List< T > Class Template Reference
Typed version of container::untyped::List.
#include <container.hh>
Public Member Functions
List (bool ownerOfObjects)
void clear ()
void append (T *element)
bool insertBefore (object::Object *beforeThis, object::Object *neew)
bool removeRef (T *element)
bool remove (T *element)
bool detachRef (T *element)
bool isEmpty () const
T * getFirst () const
T * getLast () const
Public Member Functions inherited from lout::container::typed::Collection< T >
Collection ()
~Collection ()
bool equals (Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Iterator< T > iterator ()
int size ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Additional Inherited Members
Protected Attributes inherited from lout::container::typed::Collection< T >
untyped::Collection * base
Detailed Description
template<class T>
class lout::container::typed::List< T >
Typed version of container::untyped::List.
Constructor & Destructor Documentation
template<class T> lout::container::typed::List< T >::List (bool ownerOfObjects) inline
Member Function Documentation
template<class T> void lout::container::typed::List< T >::append (T * element) inline
Referenced by dw::fltk::FltkViewport::addGadget(), and dw::fltk::FltkPlatform::attachResource().
template<class T> void lout::container::typed::List< T >::clear () inline
Referenced by dw::core::Region::clear().
template<class T> bool lout::container::typed::List< T >::detachRef (T * element) inline
template<class T> T* lout::container::typed::List< T >::getFirst () const inline
template<class T> T* lout::container::typed::List< T >::getLast () const inline
template<class T> bool lout::container::typed::List< T >::insertBefore (object::Object * beforeThis, object::Object * neew) inline
template<class T> bool lout::container::typed::List< T >::isEmpty () const inline
template<class T> bool lout::container::typed::List< T >::remove (T * element) inline
template<class T> bool lout::container::typed::List< T >::removeRef (T * element) inline
Referenced by dw::fltk::FltkPlatform::detachResource().
The documentation for this class was generated from the following file:
lout/container.hh