Dillo: lout::container::typed::Stack< T > Class Template Reference
lout::container::typed::Stack< T > Class Template Reference
Typed version of container::untyped::Stack.
#include <container.hh>
Public Member Functions
Stack (bool ownerOfObjects)
void push (T *object)
void pushUnder (T *object)
T * getTop () const
void pop ()
Public Member Functions inherited from lout::container::typed::Collection< T >
Collection ()
~Collection ()
bool equals (Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Iterator< T > iterator ()
int size ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Additional Inherited Members
Protected Attributes inherited from lout::container::typed::Collection< T >
untyped::Collection * base
Detailed Description
template<class T>
class lout::container::typed::Stack< T >
Typed version of container::untyped::Stack.
Constructor & Destructor Documentation
template<class T> lout::container::typed::Stack< T >::Stack (bool ownerOfObjects) inline
References lout::container::typed::Collection< T >::base.
Member Function Documentation
template<class T> T* lout::container::typed::Stack< T >::getTop () const inline
References lout::container::typed::Collection< T >::base.
Referenced by main(), and testStackAsQueue().
template<class T> void lout::container::typed::Stack< T >::pop () inline
References lout::container::typed::Collection< T >::base.
Referenced by main(), and testStackAsQueue().
template<class T> void lout::container::typed::Stack< T >::push (T * object) inline
References lout::container::typed::Collection< T >::base.
Referenced by main().
template<class T> void lout::container::typed::Stack< T >::pushUnder (T * object) inline
References lout::container::typed::Collection< T >::base.
Referenced by testStackAsQueue().
The documentation for this class was generated from the following file:
lout/container.hh