Dillo: dw::core::SizeParams Class Reference
dw::core::SizeParams Class Reference
Hold arguments passed to dw::core::Widget::sizeRequest and dw::core::Widget::getExtremes, as described in Size requisitions depending on positions.
#include <tools.hh>
Public Member Functions
SizeParams ()
SizeParams (int numPos, Widget **references, int *x, int *y)
SizeParams (const SizeParams &other)
~SizeParams ()
SizeParams & operator= (const SizeParams &other)
void fill (int numPos, Widget **references, int *x, int *y)
void forChild (Widget *parent, Widget *child, int xRel, int yRel, SizeParams *childParams)
bool findReference (Widget *reference, int *x, int *y)
bool isEquivalent (SizeParams *other)
int getNumPos ()
Widget ** getReferences ()
int * getX ()
int * getY ()
Widget * getReference (int i)
int getX (int i)
int getY (int i)
Private Member Functions
void init ()
void cleanup ()
void debugPrint ()
Private Attributes
int numPos
Widget ** references
int * x
int * y
Detailed Description
Hold arguments passed to dw::core::Widget::sizeRequest and dw::core::Widget::getExtremes, as described in Size requisitions depending on positions.
Constructor & Destructor Documentation
dw::core::SizeParams::SizeParams ()
References DBG_OBJ_CREATE, and lout::misc::init().
dw::core::SizeParams::SizeParams (int numPos, Widget ** references, int * x, int * y)
References DBG_OBJ_CREATE, and lout::misc::init().
dw::core::SizeParams::SizeParams (const SizeParams & other)
References DBG_OBJ_CREATE, lout::misc::init(), numPos, references, x, and y.
dw::core::SizeParams::~SizeParams ()
References DBG_OBJ_DELETE.
Member Function Documentation
void dw::core::SizeParams::cleanup () private
References lout::misc::init().
void dw::core::SizeParams::debugPrint () inline private
References DBG_IF_RTFL, DBG_OBJ_ARRSET_NUM, DBG_OBJ_ARRSET_PTR, DBG_OBJ_SET_NUM, and numPos.
Referenced by forChild().
void dw::core::SizeParams::fill (int numPos, Widget ** references, int * x, int * y)
References DBG_OBJ_ENTER, and DBG_OBJ_LEAVE.
bool dw::core::SizeParams::findReference (Widget * reference, int * x, int * y)
References DBG_OBJ_ENTER, and DBG_OBJ_LEAVE_VAL.
void dw::core::SizeParams::forChild (Widget * parent, Widget * child, int xRel, int yRel, SizeParams * childParams)
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, debugPrint(), numPos, dw::core::Widget::numSizeRequestReferences(), references, dw::core::Widget::sizeRequestReference(), x, and y.
int dw::core::SizeParams::getNumPos () inline
References numPos.
Widget* dw::core::SizeParams::getReference (int i) inline
Widget** dw::core::SizeParams::getReferences () inline
References references.
int* dw::core::SizeParams::getX () inline
References x.
int dw::core::SizeParams::getX (int i) inline
int* dw::core::SizeParams::getY () inline
References y.
int dw::core::SizeParams::getY (int i) inline
void dw::core::SizeParams::init () private
bool dw::core::SizeParams::isEquivalent (SizeParams * other)
Compares two instances, but considers a change in the order of the reference widgets as equivalent.
References lout::misc::boolToStr(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, numPos, references, x, and y.
Referenced by dw::core::Widget::getExtremes(), and dw::core::Widget::sizeRequest().
SizeParams & dw::core::SizeParams::operator= (const SizeParams & other)
References lout::misc::init(), numPos, references, x, and y.
Member Data Documentation
int dw::core::SizeParams::numPos private
Referenced by debugPrint(), forChild(), getNumPos(), isEquivalent(), operator=(), and SizeParams().
Widget** dw::core::SizeParams::references private
Referenced by forChild(), getReferences(), isEquivalent(), operator=(), and SizeParams().
int* dw::core::SizeParams::x private
Referenced by forChild(), getX(), isEquivalent(), operator=(), and SizeParams().
int * dw::core::SizeParams::y private
Referenced by forChild(), getY(), isEquivalent(), operator=(), and SizeParams().
The documentation for this class was generated from the following files:
dw/tools.hh
dw/tools.cc