Dillo: lout::container::typed::HashTable< K, V > Class Template Reference
lout::container::typed::HashTable< K, V > Class Template Reference
Typed version of container::untyped::HashTable.
#include <container.hh>
Public Member Functions
HashTable (bool ownerOfKeys, bool ownerOfValues, int tableSize=251)
void put (K *key, V *value)
V * get (K *key) const
Public Member Functions inherited from lout::container::typed::HashSet< K >
HashSet (bool owner, int tableSize=251)
void put (K *object)
bool contains (K *object) const
bool remove (K *object)
Public Member Functions inherited from lout::container::typed::Collection< K >
Collection ()
~Collection ()
bool equals (Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Iterator< K > iterator ()
int size ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Additional Inherited Members
Protected Member Functions inherited from lout::container::typed::HashSet< K >
HashSet ()
Protected Attributes inherited from lout::container::typed::Collection< K >
untyped::Collection * base
Detailed Description
template<class K, class V>
class lout::container::typed::HashTable< K, V >
Typed version of container::untyped::HashTable.
Constructor & Destructor Documentation
template<class K, class V> lout::container::typed::HashTable< K, V >::HashTable (bool ownerOfKeys, bool ownerOfValues, int tableSize = 251) inline
Member Function Documentation
template<class K, class V> V* lout::container::typed::HashTable< K, V >::get (K * key) const inline
Referenced by dw::fltk::FltkFont::create(), dw::core::style::Style::create(), and dw::fltk::FltkFont::initSystemFonts().
template<class K, class V> void lout::container::typed::HashTable< K, V >::put (K * key, V * value) inline
Referenced by dw::core::style::Style::create(), and testHashTable().
The documentation for this class was generated from the following file:
lout/container.hh