Dillo: lout::signal::Receiver Class Reference
lout::signal::Receiver Class Reference
The base class for signal receiver base classes.
#include <signal.hh>
Public Member Functions
Receiver ()
~Receiver ()
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Private Member Functions
void connectTo (Emitter *emitter)
void unconnectFrom (Emitter *emitter)
Private Attributes
container::typed::List< Emitter > * emitters
Friends
class Emitter
Detailed Description
The base class for signal receiver base classes.
If defining a signal group, a sub class of this class must be defined, in which only the abstract signal methods must be defined.
See also
signal
Constructor & Destructor Documentation
lout::signal::Receiver::Receiver ()
lout::signal::Receiver::~Receiver ()
References lout::container::typed::Iterator< T >::hasNext(), and lout::signal::Emitter::unconnect().
Member Function Documentation
void lout::signal::Receiver::connectTo (Emitter * emitter) private
Referenced by lout::signal::Emitter::connect().
void lout::signal::Receiver::intoStringBuffer (misc::StringBuffer * sb) virtual
Store a textual representation of the object in a misc::StringBuffer.
This is used by object::Object::toString.
Reimplemented from lout::object::Object.
References lout::misc::StringBuffer::append().
void lout::signal::Receiver::unconnectFrom (Emitter * emitter) private
Referenced by lout::signal::Emitter::~Emitter().
Friends And Related Function Documentation
friend class Emitter friend
Member Data Documentation
container::typed::List<Emitter>* lout::signal::Receiver::emitters private
The documentation for this class was generated from the following files:
lout/signal.hh
lout/signal.cc