Dillo: dw::oof::OOFPosRelMgr Class Reference
dw::oof::OOFPosRelMgr Class Reference
#include <oofposrelmgr.hh>
Public Member Functions
OOFPosRelMgr (OOFAwareWidget *container)
~OOFPosRelMgr ()
void markSizeChange (int ref)
void markExtremesChange (int ref)
void calcWidgetRefSize (core::Widget *widget, core::Requisition *size)
void getSize (core::Requisition *containerReq, int *oofWidth, int *oofHeight)
void getExtremes (core::Extremes *containerExtr, int *oofMinWidth, int *oofMaxWidth)
bool dealingWithSizeOfChild (core::Widget *child)
int getAvailWidthOfChild (core::Widget *child, bool forceValue)
int getAvailHeightOfChild (core::Widget *child, bool forceValue)
Public Member Functions inherited from dw::oof::OOFPositionedMgr
OOFPositionedMgr (OOFAwareWidget *container)
~OOFPositionedMgr ()
void sizeAllocateStart (OOFAwareWidget *caller, core::Allocation *allocation)
void sizeAllocateEnd (OOFAwareWidget *caller)
void containerSizeChangedForChildren ()
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
core::Widget * getWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext *context)
void addWidgetInFlow (OOFAwareWidget *widget, OOFAwareWidget *parent, int externalIndex)
int addWidgetOOF (core::Widget *widget, OOFAwareWidget *generator, int externalIndex)
void moveExternalIndices (OOFAwareWidget *generator, int oldStartIndex, int diff)
void tellPosition1 (core::Widget *widget, int x, int y)
Called before tellPosition2, see there for more.
void tellPosition2 (core::Widget *widget, int x, int y)
Called after tellPosition1.
void tellIncompletePosition1 (core::Widget *generator, core::Widget *widget, int x, int y)
void tellIncompletePosition2 (core::Widget *generator, core::Widget *widget, int x, int y)
bool containerMustAdjustExtraSpace ()
int getLeftBorder (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getRightBorder (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
bool hasFloatLeft (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
bool hasFloatRight (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getLeftFloatHeight (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getRightFloatHeight (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getClearPosition (OOFAwareWidget *widget)
bool affectsLeftBorder (core::Widget *widget)
bool affectsRightBorder (core::Widget *widget)
bool mayAffectBordersAtAll ()
int getNumWidgets ()
core::Widget * getWidget (int i)
Public Member Functions inherited from dw::oof::OutOfFlowMgr
OutOfFlowMgr ()
virtual ~OutOfFlowMgr ()
Protected Member Functions
void sizeAllocateChildren ()
bool posXAbsolute (Child *child)
bool posYAbsolute (Child *child)
int getChildPosX (Child *child, int refWidth)
int getChildPosY (Child *child, int refHeight)
int getChildPosDim (core::style::Length posCssValue, core::style::Length negCssValue, int refPos, int refLength)
int getChildPosX (Child *child)
int getChildPosY (Child *child)
Protected Member Functions inherited from dw::oof::OOFPositionedMgr
bool getPosLeft (core::Widget *child, int availWidth, int *result)
bool getPosRight (core::Widget *child, int availWidth, int *result)
bool getPosTop (core::Widget *child, int availHeight, int *result)
bool getPosBottom (core::Widget *child, int availHeight, int *result)
bool getPosBorder (core::style::Length cssValue, int refLength, int *result)
bool allChildrenConsideredForSize ()
bool allChildrenConsideredForExtremes ()
bool doChildrenExceedContainer ()
bool generatorPosDefined (Child *child)
int generatorPosX (Child *child)
int generatorPosY (Child *child)
bool posXDefined (Child *child)
bool posYDefined (Child *child)
Additional Inherited Members
Protected Types inherited from dw::oof::OOFPositionedMgr
enum { NOT_ALLOCATED, IN_ALLOCATION, WAS_ALLOCATED }
Protected Attributes inherited from dw::oof::OOFPositionedMgr
OOFAwareWidget * container
core::Allocation containerAllocation
enum
dw::oof::OOFPositionedMgr:: { ... } containerAllocationState
lout::container::typed::Vector
< Child > * children
lout::container::typed::HashTable
< lout::object::TypedPointer
< dw::core::Widget >, Child > * childrenByWidget
Constructor & Destructor Documentation
dw::oof::OOFPosRelMgr::OOFPosRelMgr (OOFAwareWidget * container)
References DBG_OBJ_CREATE.
dw::oof::OOFPosRelMgr::~OOFPosRelMgr ()
References DBG_OBJ_DELETE.
Member Function Documentation
void dw::oof::OOFPosRelMgr::calcWidgetRefSize (core::Widget * widget, core::Requisition * size) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::Requisition::ascent, dw::oof::OOFAwareWidget::CLASS_ID, DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, dw::core::Requisition::descent, lout::identity::IdentifiableObject::instanceOf(), dw::core::Widget::sizeRequest(), and dw::core::Requisition::width.
bool dw::oof::OOFPosRelMgr::dealingWithSizeOfChild (core::Widget * child) virtual
Reimplemented from dw::oof::OOFPositionedMgr.
int dw::oof::OOFPosRelMgr::getAvailHeightOfChild (core::Widget * child, bool forceValue) virtual
Implements dw::oof::OutOfFlowMgr.
References lout::misc::notImplemented().
int dw::oof::OOFPosRelMgr::getAvailWidthOfChild (core::Widget * child, bool forceValue) virtual
Implements dw::oof::OutOfFlowMgr.
References lout::misc::notImplemented().
int dw::oof::OOFPosRelMgr::getChildPosDim (core::style::Length posCssValue, core::style::Length negCssValue, int refPos, int refLength) protected
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, DBG_OBJ_MSGF, and dw::oof::OOFPositionedMgr::getPosBorder().
Referenced by getChildPosX(), and getChildPosY().
int dw::oof::OOFPosRelMgr::getChildPosX (Child * child, int refWidth) protected
References dw::core::style::StyleAttrs::boxDiffWidth(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, dw::oof::OOFPositionedMgr::generatorPosX(), getChildPosDim(), dw::core::Widget::getStyle(), dw::core::style::StyleAttrs::left, dw::core::style::StyleAttrs::right, dw::oof::OOFPositionedMgr::Child::widget, and dw::oof::OOFPositionedMgr::Child::x.
Referenced by getChildPosX(), getExtremes(), getSize(), and sizeAllocateChildren().
int dw::oof::OOFPosRelMgr::getChildPosX (Child * child) inline protected
References dw::oof::OOFPositionedMgr::container, dw::core::Widget::getAvailWidth(), and getChildPosX().
int dw::oof::OOFPosRelMgr::getChildPosY (Child * child, int refHeight) protected
References dw::core::style::StyleAttrs::bottom, dw::core::style::StyleAttrs::boxDiffHeight(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, dw::oof::OOFPositionedMgr::generatorPosY(), getChildPosDim(), dw::core::Widget::getStyle(), dw::core::style::StyleAttrs::top, dw::oof::OOFPositionedMgr::Child::widget, and dw::oof::OOFPositionedMgr::Child::y.
Referenced by getChildPosY(), getSize(), and sizeAllocateChildren().
int dw::oof::OOFPosRelMgr::getChildPosY (Child * child) inline protected
References dw::oof::OOFPositionedMgr::container, dw::core::Widget::getAvailHeight(), and getChildPosY().
void dw::oof::OOFPosRelMgr::getExtremes (core::Extremes * containerExtr, int * oofMinWidth, int * oofMaxWidth) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::oof::OOFPositionedMgr::children, dw::oof::OOFPositionedMgr::Child::consideredForExtremes, getChildPosX(), dw::core::Widget::getExtremes(), lout::misc::max(), dw::core::Extremes::maxWidth, dw::core::Extremes::minWidth, dw::oof::OOFPositionedMgr::posXDefined(), and dw::oof::OOFPositionedMgr::Child::widget.
void dw::oof::OOFPosRelMgr::getSize (core::Requisition * containerReq, int * oofWidth, int * oofHeight) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::Requisition::ascent, dw::oof::OOFPositionedMgr::children, dw::oof::OOFPositionedMgr::Child::consideredForSize, DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, dw::core::Requisition::descent, getChildPosX(), getChildPosY(), lout::misc::max(), dw::oof::OOFPositionedMgr::posXDefined(), dw::oof::OOFPositionedMgr::posYDefined(), dw::core::Widget::sizeRequest(), dw::oof::OOFPositionedMgr::Child::widget, and dw::core::Requisition::width.
void dw::oof::OOFPosRelMgr::markExtremesChange (int ref) virtual
Reimplemented from dw::oof::OOFPositionedMgr.
void dw::oof::OOFPosRelMgr::markSizeChange (int ref) virtual
Reimplemented from dw::oof::OOFPositionedMgr.
References dw::oof::OOFPositionedMgr::children, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::oof::OOFPositionedMgr::Child::externalIndex, dw::oof::OOFPositionedMgr::Child::generator, and dw::oof::OOFAwareWidget::widgetRefSizeChanged().
bool dw::oof::OOFPosRelMgr::posXAbsolute (Child * child) protected virtual
Implements dw::oof::OOFPositionedMgr.
bool dw::oof::OOFPosRelMgr::posYAbsolute (Child * child) protected virtual
Implements dw::oof::OOFPositionedMgr.
void dw::oof::OOFPosRelMgr::sizeAllocateChildren () protected virtual
Implements dw::oof::OOFPositionedMgr.
References dw::core::Allocation::ascent, dw::core::Requisition::ascent, dw::oof::OOFPositionedMgr::children, dw::oof::OOFPositionedMgr::containerAllocation, DBG_OBJ_ENTER0, DBG_OBJ_LEAVE, dw::core::Allocation::descent, dw::core::Requisition::descent, getChildPosX(), getChildPosY(), dw::core::Widget::sizeAllocate(), dw::core::Widget::sizeRequest(), dw::oof::OOFPositionedMgr::Child::widget, dw::core::Allocation::width, dw::core::Requisition::width, dw::core::Allocation::x, and dw::core::Allocation::y.
The documentation for this class was generated from the following files:
dw/oofposrelmgr.hh
dw/oofposrelmgr.cc