Dillo: lout::container::untyped::Iterator Class Reference
lout::container::untyped::Iterator Class Reference
This is a small wrapper for AbstractIterator, which may be used directly, not as a pointer, to makes memory management simpler.
#include <container.hh>
Public Member Functions
Iterator ()
Iterator (const Iterator &it2)
Iterator (Iterator &it2)
~Iterator ()
Iterator & operator= (const Iterator &it2)
Iterator & operator= (Iterator &it2)
bool hasNext ()
object::Object * getNext ()
Private Member Functions
Iterator (Collection0::AbstractIterator *impl)
Private Attributes
Collection0::AbstractIterator * impl
Friends
class Collection
Detailed Description
This is a small wrapper for AbstractIterator, which may be used directly, not as a pointer, to makes memory management simpler.
Constructor & Destructor Documentation
lout::container::untyped::Iterator::Iterator (Collection0::AbstractIterator * impl) inline private
References impl.
lout::container::untyped::Iterator::Iterator ()
lout::container::untyped::Iterator::Iterator (const Iterator & it2)
References impl, and lout::container::untyped::Collection0::AbstractIterator::ref().
lout::container::untyped::Iterator::Iterator (Iterator & it2)
References impl, and lout::container::untyped::Collection0::AbstractIterator::ref().
lout::container::untyped::Iterator::~Iterator ()
Member Function Documentation
object::Object* lout::container::untyped::Iterator::getNext () inline
References lout::container::untyped::Collection0::AbstractIterator::getNext().
Referenced by lout::container::typed::Iterator< dw::fltk::ui::FltkRadioButtonResource >::getNext().
bool lout::container::untyped::Iterator::hasNext () inline
References lout::container::untyped::Collection0::AbstractIterator::hasNext().
Referenced by lout::container::typed::Iterator< dw::fltk::ui::FltkRadioButtonResource >::hasNext(), and lout::container::untyped::Collection::intoStringBuffer().
Iterator & lout::container::untyped::Iterator::operator= (const Iterator & it2)
References impl, and lout::container::untyped::Collection0::AbstractIterator::ref().
Iterator & lout::container::untyped::Iterator::operator= (Iterator & it2)
References impl, and lout::container::untyped::Collection0::AbstractIterator::ref().
Friends And Related Function Documentation
friend class Collection friend
Member Data Documentation
Collection0::AbstractIterator* lout::container::untyped::Iterator::impl private
Referenced by Iterator(), and operator=().
The documentation for this class was generated from the following files:
lout/container.hh
lout/container.cc