Dillo: dw::oof::OOFPosAbsLikeMgr Class Reference
dw::oof::OOFPosAbsLikeMgr Class Reference abstract
#include <oofposabslikemgr.hh>
Public Member Functions
OOFPosAbsLikeMgr (OOFAwareWidget *container)
~OOFPosAbsLikeMgr ()
void calcWidgetRefSize (core::Widget *widget, core::Requisition *size)
void getSize (core::Requisition *containerReq, int *oofWidth, int *oofHeight)
void getExtremes (core::Extremes *containerExtr, int *oofMinWidth, int *oofMaxWidth)
int getAvailWidthOfChild (core::Widget *child, bool forceValue)
int getAvailHeightOfChild (core::Widget *child, bool forceValue)
Public Member Functions inherited from dw::oof::OOFPositionedMgr
OOFPositionedMgr (OOFAwareWidget *container)
~OOFPositionedMgr ()
void sizeAllocateStart (OOFAwareWidget *caller, core::Allocation *allocation)
void sizeAllocateEnd (OOFAwareWidget *caller)
void containerSizeChangedForChildren ()
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void markSizeChange (int ref)
void markExtremesChange (int ref)
core::Widget * getWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext *context)
void addWidgetInFlow (OOFAwareWidget *widget, OOFAwareWidget *parent, int externalIndex)
int addWidgetOOF (core::Widget *widget, OOFAwareWidget *generator, int externalIndex)
void moveExternalIndices (OOFAwareWidget *generator, int oldStartIndex, int diff)
void tellPosition1 (core::Widget *widget, int x, int y)
Called before tellPosition2, see there for more.
void tellPosition2 (core::Widget *widget, int x, int y)
Called after tellPosition1.
void tellIncompletePosition1 (core::Widget *generator, core::Widget *widget, int x, int y)
void tellIncompletePosition2 (core::Widget *generator, core::Widget *widget, int x, int y)
bool containerMustAdjustExtraSpace ()
int getLeftBorder (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getRightBorder (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
bool hasFloatLeft (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
bool hasFloatRight (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getLeftFloatHeight (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getRightFloatHeight (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getClearPosition (OOFAwareWidget *widget)
bool affectsLeftBorder (core::Widget *widget)
bool affectsRightBorder (core::Widget *widget)
bool mayAffectBordersAtAll ()
bool dealingWithSizeOfChild (core::Widget *child)
int getNumWidgets ()
core::Widget * getWidget (int i)
Public Member Functions inherited from dw::oof::OutOfFlowMgr
OutOfFlowMgr ()
virtual ~OutOfFlowMgr ()
Protected Member Functions
virtual int containerBoxOffsetX ()=0
virtual int containerBoxOffsetY ()=0
virtual int containerBoxRestWidth ()=0
virtual int containerBoxRestHeight ()=0
int containerBoxDiffWidth ()
int containerBoxDiffHeight ()
bool haveExtremesChanged ()
void sizeAllocateChildren ()
bool posXAbsolute (Child *child)
bool posYAbsolute (Child *child)
void calcPosAndSizeChildOfChild (Child *child, int refWidth, int refHeight, int *xPtr, int *yPtr, int *widthPtr, int *ascentPtr, int *descentPtr)
void calcHPosAndSizeChildOfChild (Child *child, int refWidth, int origChildWidth, int *xPtr, int *widthPtr)
void calcVPosAndSizeChildOfChild (Child *child, int refHeight, int origChildAscent, int origChildDescent, int *yPtr, int *ascentPtr, int *descentPtr)
Protected Member Functions inherited from dw::oof::OOFPositionedMgr
bool getPosLeft (core::Widget *child, int availWidth, int *result)
bool getPosRight (core::Widget *child, int availWidth, int *result)
bool getPosTop (core::Widget *child, int availHeight, int *result)
bool getPosBottom (core::Widget *child, int availHeight, int *result)
bool getPosBorder (core::style::Length cssValue, int refLength, int *result)
bool allChildrenConsideredForSize ()
bool allChildrenConsideredForExtremes ()
bool doChildrenExceedContainer ()
bool generatorPosDefined (Child *child)
int generatorPosX (Child *child)
int generatorPosY (Child *child)
bool posXDefined (Child *child)
bool posYDefined (Child *child)
Additional Inherited Members
Protected Types inherited from dw::oof::OOFPositionedMgr
enum { NOT_ALLOCATED, IN_ALLOCATION, WAS_ALLOCATED }
Protected Attributes inherited from dw::oof::OOFPositionedMgr
OOFAwareWidget * container
core::Allocation containerAllocation
enum
dw::oof::OOFPositionedMgr:: { ... } containerAllocationState
lout::container::typed::Vector
< Child > * children
lout::container::typed::HashTable
< lout::object::TypedPointer
< dw::core::Widget >, Child > * childrenByWidget
Constructor & Destructor Documentation
dw::oof::OOFPosAbsLikeMgr::OOFPosAbsLikeMgr (OOFAwareWidget * container)
References DBG_OBJ_CREATE.
dw::oof::OOFPosAbsLikeMgr::~OOFPosAbsLikeMgr ()
References DBG_OBJ_DELETE.
Member Function Documentation
void dw::oof::OOFPosAbsLikeMgr::calcHPosAndSizeChildOfChild (Child * child, int refWidth, int origChildWidth, int * xPtr, int * widthPtr) protected
References dw::core::style::absLengthVal(), dw::core::Widget::boxDiffWidth(), containerBoxDiffWidth(), containerBoxOffsetX(), containerBoxRestWidth(), DBG_OBJ_MSG, DBG_OBJ_MSGF, dw::oof::OOFPositionedMgr::generatorPosX(), dw::oof::OOFPositionedMgr::getPosLeft(), dw::oof::OOFPositionedMgr::getPosRight(), dw::core::Widget::getStyle(), dw::core::style::isAbsLength(), dw::core::style::isPerLength(), dw::core::style::multiplyWithPerLength(), dw::core::style::perLengthVal_useThisOnlyForDebugging(), dw::oof::OOFPositionedMgr::Child::widget, dw::core::style::StyleAttrs::width, and dw::oof::OOFPositionedMgr::Child::x.
Referenced by calcPosAndSizeChildOfChild(), and getExtremes().
void dw::oof::OOFPosAbsLikeMgr::calcPosAndSizeChildOfChild (Child * child, int refWidth, int refHeight, int * xPtr, int * yPtr, int * widthPtr, int * ascentPtr, int * descentPtr) protected
References dw::core::Requisition::ascent, calcHPosAndSizeChildOfChild(), calcVPosAndSizeChildOfChild(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE, dw::core::Requisition::descent, dw::core::Widget::sizeRequest(), dw::oof::OOFPositionedMgr::Child::widget, and dw::core::Requisition::width.
Referenced by getSize(), and sizeAllocateChildren().
void dw::oof::OOFPosAbsLikeMgr::calcVPosAndSizeChildOfChild (Child * child, int refHeight, int origChildAscent, int origChildDescent, int * yPtr, int * ascentPtr, int * descentPtr) protected
References dw::core::style::absLengthVal(), dw::core::Widget::boxDiffHeight(), containerBoxDiffHeight(), containerBoxOffsetY(), DBG_OBJ_MSG, DBG_OBJ_MSGF, dw::oof::OOFPositionedMgr::generatorPosY(), dw::oof::OOFPositionedMgr::getPosBottom(), dw::oof::OOFPositionedMgr::getPosTop(), dw::core::Widget::getStyle(), dw::core::style::StyleAttrs::height, dw::core::style::isAbsLength(), dw::core::style::isPerLength(), dw::core::style::multiplyWithPerLength(), dw::core::style::perLengthVal_useThisOnlyForDebugging(), dw::core::splitHeightPreserveAscent(), dw::oof::OOFPositionedMgr::Child::widget, and dw::oof::OOFPositionedMgr::Child::y.
Referenced by calcPosAndSizeChildOfChild().
void dw::oof::OOFPosAbsLikeMgr::calcWidgetRefSize (core::Widget * widget, core::Requisition * size) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::Requisition::ascent, dw::core::Requisition::descent, and dw::core::Requisition::width.
int dw::oof::OOFPosAbsLikeMgr::containerBoxDiffHeight () inline protected
References containerBoxOffsetY(), and containerBoxRestHeight().
Referenced by calcVPosAndSizeChildOfChild(), getAvailHeightOfChild(), getSize(), and sizeAllocateChildren().
int dw::oof::OOFPosAbsLikeMgr::containerBoxDiffWidth () inline protected
References containerBoxOffsetX(), and containerBoxRestWidth().
Referenced by calcHPosAndSizeChildOfChild(), getAvailWidthOfChild(), getExtremes(), getSize(), and sizeAllocateChildren().
virtual int dw::oof::OOFPosAbsLikeMgr::containerBoxOffsetX () protected pure virtual
Implemented in dw::oof::OOFPosAbsMgr, and dw::oof::OOFPosFixedMgr.
Referenced by calcHPosAndSizeChildOfChild(), containerBoxDiffWidth(), and sizeAllocateChildren().
virtual int dw::oof::OOFPosAbsLikeMgr::containerBoxOffsetY () protected pure virtual
Implemented in dw::oof::OOFPosAbsMgr, and dw::oof::OOFPosFixedMgr.
Referenced by calcVPosAndSizeChildOfChild(), containerBoxDiffHeight(), and sizeAllocateChildren().
virtual int dw::oof::OOFPosAbsLikeMgr::containerBoxRestHeight () protected pure virtual
Implemented in dw::oof::OOFPosAbsMgr, and dw::oof::OOFPosFixedMgr.
Referenced by containerBoxDiffHeight().
virtual int dw::oof::OOFPosAbsLikeMgr::containerBoxRestWidth () protected pure virtual
Implemented in dw::oof::OOFPosAbsMgr, and dw::oof::OOFPosFixedMgr.
Referenced by calcHPosAndSizeChildOfChild(), and containerBoxDiffWidth().
int dw::oof::OOFPosAbsLikeMgr::getAvailHeightOfChild (core::Widget * child, bool forceValue) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::Widget::calcHeight(), dw::oof::OOFPositionedMgr::container, containerBoxDiffHeight(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSG, DBG_OBJ_MSGF, dw::core::Widget::getAvailHeight(), dw::oof::OOFPositionedMgr::getPosBottom(), dw::oof::OOFPositionedMgr::getPosTop(), dw::core::Widget::getStyle(), dw::core::style::StyleAttrs::height, dw::core::style::LENGTH_AUTO, lout::misc::max(), dw::core::style::StyleAttrs::maxHeight, and dw::core::style::StyleAttrs::minHeight.
int dw::oof::OOFPosAbsLikeMgr::getAvailWidthOfChild (core::Widget * child, bool forceValue) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::Widget::calcFinalWidth(), dw::oof::OOFPositionedMgr::container, containerBoxDiffWidth(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSG, DBG_OBJ_MSGF, dw::core::Widget::getAvailWidth(), dw::core::Widget::getMinWidth(), dw::oof::OOFPositionedMgr::getPosLeft(), dw::oof::OOFPositionedMgr::getPosRight(), dw::core::Widget::getStyle(), dw::core::style::LENGTH_AUTO, lout::misc::max(), dw::core::style::StyleAttrs::maxWidth, dw::core::style::StyleAttrs::minWidth, and dw::core::style::StyleAttrs::width.
void dw::oof::OOFPosAbsLikeMgr::getExtremes (core::Extremes * containerExtr, int * oofMinWidth, int * oofMaxWidth) virtual
Implements dw::oof::OutOfFlowMgr.
References calcHPosAndSizeChildOfChild(), dw::oof::OOFPositionedMgr::children, dw::oof::OOFPositionedMgr::Child::consideredForExtremes, containerBoxDiffWidth(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::core::Widget::getExtremes(), lout::misc::max(), dw::core::Extremes::maxWidth, dw::core::Extremes::minWidth, dw::oof::OOFPositionedMgr::posXDefined(), and dw::oof::OOFPositionedMgr::Child::widget.
void dw::oof::OOFPosAbsLikeMgr::getSize (core::Requisition * containerReq, int * oofWidth, int * oofHeight) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::Requisition::ascent, calcPosAndSizeChildOfChild(), dw::oof::OOFPositionedMgr::children, dw::oof::OOFPositionedMgr::Child::consideredForSize, dw::oof::OOFPositionedMgr::container, containerBoxDiffHeight(), containerBoxDiffWidth(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, dw::core::Requisition::descent, dw::core::Widget::getAvailHeight(), dw::core::Widget::getAvailWidth(), lout::misc::max(), dw::oof::OOFPositionedMgr::posXDefined(), dw::oof::OOFPositionedMgr::posYDefined(), and dw::core::Requisition::width.
bool dw::oof::OOFPosAbsLikeMgr::haveExtremesChanged () protected
bool dw::oof::OOFPosAbsLikeMgr::posXAbsolute (Child * child) protected virtual
Implements dw::oof::OOFPositionedMgr.
References lout::misc::boolToStr(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, dw::core::Widget::getStyle(), dw::core::style::isAbsLength(), dw::core::style::isPerLength(), dw::core::style::StyleAttrs::left, dw::core::style::StyleAttrs::right, and dw::oof::OOFPositionedMgr::Child::widget.
bool dw::oof::OOFPosAbsLikeMgr::posYAbsolute (Child * child) protected virtual
Implements dw::oof::OOFPositionedMgr.
References lout::misc::boolToStr(), dw::core::style::StyleAttrs::bottom, DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, dw::core::Widget::getStyle(), dw::core::style::isAbsLength(), dw::core::style::isPerLength(), dw::core::style::StyleAttrs::top, and dw::oof::OOFPositionedMgr::Child::widget.
void dw::oof::OOFPosAbsLikeMgr::sizeAllocateChildren () protected virtual
Implements dw::oof::OOFPositionedMgr.
References dw::core::Allocation::ascent, calcPosAndSizeChildOfChild(), dw::oof::OOFPositionedMgr::children, dw::oof::OOFPositionedMgr::container, dw::oof::OOFPositionedMgr::containerAllocation, containerBoxDiffHeight(), containerBoxDiffWidth(), containerBoxOffsetX(), containerBoxOffsetY(), DBG_OBJ_ENTER0, DBG_OBJ_LEAVE, dw::core::Allocation::descent, dw::core::Widget::getAvailHeight(), dw::core::Widget::getAvailWidth(), dw::core::Widget::sizeAllocate(), dw::oof::OOFPositionedMgr::Child::widget, dw::core::Allocation::width, dw::core::Allocation::x, and dw::core::Allocation::y.
The documentation for this class was generated from the following files:
dw/oofposabslikemgr.hh
dw/oofposabslikemgr.cc