Dillo: lout::container::typed::Vector< T > Class Template Reference
lout::container::typed::Vector< T > Class Template Reference
Typed version of container::untyped::Vector.
#include <container.hh>
Public Member Functions
Vector (int initSize, bool ownerOfObjects)
void put (T *newElement, int newPos=-1)
void insert (T *newElement, int pos)
int insertSorted (T *newElement, object::Comparator *comparator=&object::standardComparator)
void remove (int pos)
T * get (int pos) const
void clear ()
void sort (object::Comparator *comparator=&object::standardComparator)
int bsearch (T *key, bool mustExist, int start, int end, object::Comparator *comparator=&object::standardComparator)
int bsearch (T *key, bool mustExist, object::Comparator *comparator=&object::standardComparator)
Public Member Functions inherited from lout::container::typed::Collection< T >
Collection ()
~Collection ()
bool equals (Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Iterator< T > iterator ()
int size ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Additional Inherited Members
Protected Attributes inherited from lout::container::typed::Collection< T >
untyped::Collection * base
Detailed Description
template<class T>
class lout::container::typed::Vector< T >
Typed version of container::untyped::Vector.
Constructor & Destructor Documentation
template<class T> lout::container::typed::Vector< T >::Vector (int initSize, bool ownerOfObjects) inline
Member Function Documentation
template<class T> int lout::container::typed::Vector< T >::bsearch (T * key, bool mustExist, int start, int end, object::Comparator * comparator = &object::standardComparator) inline
Referenced by testVector2(), and testVector3().
template<class T> int lout::container::typed::Vector< T >::bsearch (T * key, bool mustExist, object::Comparator * comparator = &object::standardComparator) inline
template<class T> void lout::container::typed::Vector< T >::clear () inline
Referenced by dw::oof::OOFFloatsMgr::SortedFloatsVector::clear().
template<class T> T* lout::container::typed::Vector< T >::get (int pos) const inline
Referenced by dw::core::DeepIterator::clone(), dw::core::DeepIterator::compareTo(), dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), lout::identity::IdentifiableObject::getClassName(), dw::Hyphenator::hyphenateSingleWord(), and dw::oof::OOFFloatsMgr::moveExternalIndices().
template<class T> void lout::container::typed::Vector< T >::insert (T * newElement, int pos) inline
template<class T> int lout::container::typed::Vector< T >::insertSorted (T * newElement, object::Comparator * comparator = &object::standardComparator) inline
Referenced by testVector2().
template<class T> void lout::container::typed::Vector< T >::put (T * newElement, int newPos = -1) inline
Referenced by dw::oof::OOFFloatsMgr::addWidgetOOF(), dw::core::DeepIterator::clone(), dw::core::DeepIterator::DeepIterator(), dw::Hyphenator::insertException(), dw::oof::OOFFloatsMgr::SortedFloatsVector::put(), testVector1(), and testVector3().
template<class T> void lout::container::typed::Vector< T >::remove (int pos) inline
template<class T> void lout::container::typed::Vector< T >::sort (object::Comparator * comparator = &object::standardComparator) inline
Referenced by testVector1().
The documentation for this class was generated from the following file:
lout/container.hh