Dillo: dw::fltk::FltkView Class Reference
dw::fltk::FltkView Class Reference abstract
This interface adds some more methods for all flkt-based views.
#include <fltkplatform.hh>
Public Member Functions
virtual bool usesFltkWidgets ()=0
virtual void addFltkWidget (Fl_Widget *widget, core::Allocation *allocation)
virtual void removeFltkWidget (Fl_Widget *widget)
virtual void allocateFltkWidget (Fl_Widget *widget, core::Allocation *allocation)
virtual void drawFltkWidget (Fl_Widget *widget, core::Rectangle *area)
Public Member Functions inherited from dw::core::View
virtual void setLayout (Layout *layout)=0
This methods notifies the view, that it has been attached to a layout.
virtual void setCanvasSize (int width, int ascent, int descent)=0
Set the canvas size.
virtual void setCursor (style::Cursor cursor)=0
Set the cursor appearance.
virtual void setBgColor (style::Color *color)=0
Set the background of the view.
virtual bool usesViewport ()=0
Return, whether this view uses a viewport.
virtual int getHScrollbarThickness ()=0
Get the thickness of the horizontal scrollbar, when it is visible.
virtual int getVScrollbarThickness ()=0
Get the thickness of the vertical scrollbar, when it is visible.
virtual void scrollTo (int x, int y)=0
Scroll the vieport to the given position.
virtual void scroll (ScrollCommand)
Scroll the viewport as commanded.
virtual void setViewportSize (int width, int height, int hScrollbarThickness, int vScrollbarThickness)=0
Set the viewport size.
virtual void startDrawing (Rectangle *area)=0
Called before drawing.
virtual void finishDrawing (Rectangle *area)=0
Called after drawing.
virtual void queueDraw (Rectangle *area)=0
Queue a region, which is given in canvas coordinates, for drawing.
virtual void queueDrawTotal ()=0
Queue the total viewport for drawing.
virtual void cancelQueueDraw ()=0
Cancel a draw queue request.
virtual void drawPoint (style::Color *color, style::Color::Shading shading, int x, int y)=0
virtual void drawLine (style::Color *color, style::Color::Shading shading, int x1, int y1, int x2, int y2)=0
virtual void drawTypedLine (style::Color *color, style::Color::Shading shading, style::LineType type, int width, int x1, int y1, int x2, int y2)=0
virtual void drawRectangle (style::Color *color, style::Color::Shading shading, bool filled, int x, int y, int width, int height)=0
virtual void drawArc (style::Color *color, style::Color::Shading shading, bool filled, int centerX, int centerY, int width, int height, int angle1, int angle2)=0
virtual void drawPolygon (style::Color *color, style::Color::Shading shading, bool filled, bool convex, Point *points, int npoints)=0
virtual void drawText (style::Font *font, style::Color *color, style::Color::Shading shading, int x, int y, const char *text, int len)=0
virtual void drawSimpleWrappedText (style::Font *font, style::Color *color, style::Color::Shading shading, int x, int y, int w, int h, const char *text)=0
virtual void drawImage (Imgbuf *imgbuf, int xRoot, int yRoot, int x, int y, int width, int height)=0
virtual View * getClippingView (int x, int y, int width, int height)=0
virtual void mergeClippingView (View *clippingView)=0
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Detailed Description
This interface adds some more methods for all flkt-based views.
Member Function Documentation
void dw::fltk::FltkView::addFltkWidget (Fl_Widget * widget, core::Allocation * allocation) virtual
Reimplemented in dw::fltk::FltkWidgetView.
Referenced by dw::fltk::ui::FltkResource::attachView().
void dw::fltk::FltkView::allocateFltkWidget (Fl_Widget * widget, core::Allocation * allocation) virtual
Reimplemented in dw::fltk::FltkWidgetView.
Referenced by dw::fltk::ui::FltkEntryResource::sizeAllocate().
void dw::fltk::FltkView::drawFltkWidget (Fl_Widget * widget, core::Rectangle * area) virtual
Reimplemented in dw::fltk::FltkWidgetView, and dw::fltk::FltkPreview.
Referenced by dw::fltk::ui::FltkResource::draw().
void dw::fltk::FltkView::removeFltkWidget (Fl_Widget * widget) virtual
Reimplemented in dw::fltk::FltkWidgetView.
virtual bool dw::fltk::FltkView::usesFltkWidgets () pure virtual
Implemented in dw::fltk::FltkWidgetView, and dw::fltk::FltkPreview.
Referenced by dw::fltk::ui::FltkResource::attachView(), dw::fltk::ui::FltkComplexButtonResource::attachView(), and dw::fltk::ui::FltkResource::draw().
The documentation for this class was generated from the following files:
dw/fltkplatform.hh
dw/fltkplatform.cc