Dillo: dw::core::DeepIterator Class Reference
dw::core::DeepIterator Class Reference
A stack of iterators, to iterate recursively through a widget tree.
#include <iterator.hh>
Classes
class Stack
Public Member Functions
DeepIterator (Iterator *it)
Create a new deep iterator from an existing dw::core::Iterator.
~DeepIterator ()
lout::object::Object * clone ()
Return an exact copy of the object.
DeepIterator * createVariant (Iterator *it)
Iterator * getTopIterator ()
Content * getContent ()
bool isEmpty ()
bool next ()
Move iterator forward and store content it.
bool prev ()
Move iterator backward and store content it.
DeepIterator * cloneDeepIterator ()
int compareTo (lout::object::Comparable *other)
Compare two objects, this and other.
void highlight (int start, int end, HighlightLayer layer)
Highlight a part of the current content.
void getAllocation (int start, int end, Allocation *allocation)
Return the shape, which a part of the item, the iterator points on, allocates.
void unhighlight (int direction, HighlightLayer layer)
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Static Public Member Functions
static void scrollTo (DeepIterator *it1, DeepIterator *it2, int start, int end, HPosition hpos, VPosition vpos)
Private Member Functions
DeepIterator ()
Widget * getRespectiveParent (Widget *widget)
int getRespectiveLevel (Widget *widget)
Static Private Member Functions
static Iterator * searchDownward (Iterator *it, Content::Type mask, bool fromEnd)
static Iterator * searchSideward (Iterator *it, Content::Type mask, bool fromEnd)
static Widget * getRespectiveParent (Widget *widget, Content::Type mask)
static int getRespectiveLevel (Widget *widget, Content::Type mask)
Private Attributes
Stack stack
Content::Type mask
Content content
bool hasContents
Detailed Description
A stack of iterators, to iterate recursively through a widget tree.
This class is similar to dw::core::Iterator, but not created by a widget, but explicitly from another iterator. Deep iterators do not have the limitation, that iteration is only done within a widget, instead, child widgets are iterated through recursively.
Constructor & Destructor Documentation
dw::core::DeepIterator::DeepIterator () inline private
Referenced by dw::core::CharIterator::CharIterator(), clone(), and createVariant().
dw::core::DeepIterator::DeepIterator (Iterator * it)
Create a new deep iterator from an existing dw::core::Iterator.
The content of the return value will be the content of it. If within the widget tree, there is no non-widget content, the resulting deep iterator is empty (denoted by dw::core::DeepIterator::stack == NULL).
Notes:
The mask of i" must include DW_CONTENT_WIDGET, but dw::core::DeepIterator::next will never return widgets.
References dw::core::Content::ANY_WIDGET, dw::core::Iterator::cloneIterator(), content, dw::core::Iterator::getContent(), dw::core::Iterator::getMask(), getRespectiveLevel(), getRespectiveParent(), dw::core::Iterator::getWidget(), dw::core::Content::getWidget(), hasContents, dw::core::Widget::iterator(), mask, dw::core::Iterator::next(), lout::container::typed::Vector< T >::put(), searchDownward(), searchSideward(), stack, dw::core::Content::type, dw::core::Iterator::unref(), dw::core::Content::WIDGET_OOF_CONT, and dw::core::Content::WIDGET_OOF_REF.
dw::core::DeepIterator::~DeepIterator ()
Member Function Documentation
object::Object * dw::core::DeepIterator::clone () virtual
Return an exact copy of the object.
Reimplemented from lout::object::Object.
References content, DeepIterator(), lout::container::typed::Vector< T >::get(), hasContents, mask, lout::container::typed::Vector< T >::put(), lout::container::typed::Collection< T >::size(), and stack.
Referenced by cloneDeepIterator(), and dw::core::Iterator::scrollTo().
DeepIterator* dw::core::DeepIterator::cloneDeepIterator () inline
References clone().
Referenced by dw::core::CharIterator::clone(), dw::core::SelectionState::copy(), dw::core::CharIterator::highlight(), dw::core::SelectionState::highlight0(), and dw::core::CharIterator::unhighlight().
int dw::core::DeepIterator::compareTo (lout::object::Comparable * other) virtual
Compare two objects, this and other.
Return a value < 0, when this is less than other, a value > 0, when this is greater than other, or 0, when this and other are equal.
If c1.equals(c2) (as defined in Object), c1.compareTo(c2) must be 0, but, unlike you may expect, the reversed is not necessarily true. This method returns 0, if, according to the rules for sorting, there is no difference, but there may still be differences (not relevant for sorting), which "equals" will care about.
Implements lout::object::Comparable.
References lout::container::typed::Vector< T >::get(), lout::container::typed::Collection< T >::size(), and stack.
Referenced by dw::core::SelectionState::adjustSelection(), dw::core::SelectionState::copy(), dw::core::CharIterator::highlight(), dw::core::SelectionState::highlight0(), dw::core::Iterator::scrollTo(), and dw::core::CharIterator::unhighlight().
DeepIterator * dw::core::DeepIterator::createVariant (Iterator * it)
Todo:
Not yet implemented, and actually not yet needed very much.
References DeepIterator().
Referenced by dw::core::SelectionState::adjustSelection().
void dw::core::DeepIterator::getAllocation (int start, int end, Allocation * allocation) inline
Return the shape, which a part of the item, the iterator points on, allocates.
The parameters start and end have the same meaning as in DwIterator::highlight().
References dw::core::Iterator::getAllocation(), and dw::core::DeepIterator::Stack::getTop().
Referenced by dw::core::Iterator::scrollTo().
Content* dw::core::DeepIterator::getContent () inline
References content.
Referenced by dw::core::SelectionState::copy(), dw::core::CharIterator::highlight(), and dw::core::SelectionState::highlight0().
int dw::core::DeepIterator::getRespectiveLevel (Widget * widget, Content::Type mask) static private
References dw::core::Widget::getGeneratorLevel(), dw::core::Widget::getLevel(), and dw::core::Content::WIDGET_OOF_REF.
Referenced by DeepIterator(), and getRespectiveLevel().
int dw::core::DeepIterator::getRespectiveLevel (Widget * widget) inline private
References getRespectiveLevel().
Widget * dw::core::DeepIterator::getRespectiveParent (Widget * widget, Content::Type mask) static private
References dw::core::Widget::getGenerator(), dw::core::Widget::getParent(), and dw::core::Content::WIDGET_OOF_REF.
Referenced by DeepIterator(), getRespectiveParent(), and searchSideward().
Widget* dw::core::DeepIterator::getRespectiveParent (Widget * widget) inline private
References getRespectiveParent().
Iterator* dw::core::DeepIterator::getTopIterator () inline
References dw::core::DeepIterator::Stack::getTop().
Referenced by dw::core::SelectionState::copy(), and dw::core::SelectionState::correctCharPos().
void dw::core::DeepIterator::highlight (int start, int end, HighlightLayer layer) inline
Highlight a part of the current content.
Unhighlight the current content by passing -1 as start (see also (dw::core::Iterator::unhighlight). For text, start and end define the characters, otherwise, the shape is defined as [0, 1], i.e. for highlighting a whole dw::core::Content, pass 0 and >= 1.
References dw::core::DeepIterator::Stack::getTop(), and dw::core::Iterator::highlight().
Referenced by dw::core::SelectionState::adjustSelection(), dw::core::CharIterator::highlight(), and dw::core::SelectionState::highlight0().
bool dw::core::DeepIterator::isEmpty ()
References hasContents.
Referenced by dw::core::SelectionState::buttonPress().
bool dw::core::DeepIterator::next ()
Move iterator forward and store content it.
Returns true on success.
References dw::core::Content::ANY_WIDGET, content, dw::core::Content::END, dw::core::Iterator::getContent(), dw::core::DeepIterator::Stack::getTop(), dw::core::Content::getWidget(), dw::core::Widget::iterator(), mask, dw::core::Iterator::next(), dw::core::DeepIterator::Stack::pop(), dw::core::DeepIterator::Stack::push(), lout::container::typed::Collection< T >::size(), stack, and dw::core::Content::type.
Referenced by dw::core::SelectionState::copy(), dw::core::CharIterator::highlight(), dw::core::SelectionState::highlight0(), dw::core::CharIterator::next(), dw::core::Iterator::scrollTo(), and dw::core::CharIterator::unhighlight().
bool dw::core::DeepIterator::prev ()
Move iterator backward and store content it.
Returns true on success.
References dw::core::Content::ANY_WIDGET, content, dw::core::Iterator::getContent(), dw::core::DeepIterator::Stack::getTop(), dw::core::Content::getWidget(), dw::core::Widget::iterator(), mask, dw::core::DeepIterator::Stack::pop(), dw::core::Iterator::prev(), dw::core::DeepIterator::Stack::push(), lout::container::typed::Collection< T >::size(), stack, dw::core::Content::START, and dw::core::Content::type.
Referenced by dw::core::CharIterator::prev().
static void dw::core::DeepIterator::scrollTo (DeepIterator * it1, DeepIterator * it2, int start, int end, HPosition hpos, VPosition vpos) inline static
References dw::core::DeepIterator::Stack::getTop(), dw::core::Iterator::scrollTo(), and stack.
Referenced by dw::core::CharIterator::scrollTo().
Iterator * dw::core::DeepIterator::searchDownward (Iterator * it, Content::Type mask, bool fromEnd) static private
References dw::core::Content::ANY_WIDGET, dw::core::Iterator::getContent(), dw::core::Content::getWidget(), dw::core::Widget::iterator(), dw::core::Content::type, and dw::core::Iterator::unref().
Referenced by DeepIterator(), and searchSideward().
Iterator * dw::core::DeepIterator::searchSideward (Iterator * it, Content::Type mask, bool fromEnd) static private
References dw::core::Content::ANY_WIDGET, lout::misc::assertNotReached(), dw::core::Iterator::cloneIterator(), dw::core::Iterator::getContent(), dw::core::Iterator::getMask(), getRespectiveParent(), dw::core::Iterator::getWidget(), dw::core::Widget::iterator(), searchDownward(), dw::core::Content::type, and dw::core::Iterator::unref().
Referenced by DeepIterator().
void dw::core::DeepIterator::unhighlight (int direction, HighlightLayer layer) inline
References dw::core::DeepIterator::Stack::getTop(), and dw::core::Iterator::unhighlight().
Referenced by dw::core::SelectionState::highlight0(), and dw::core::CharIterator::unhighlight().
Member Data Documentation
Content dw::core::DeepIterator::content private
Referenced by clone(), DeepIterator(), getContent(), next(), and prev().
bool dw::core::DeepIterator::hasContents private
Referenced by clone(), DeepIterator(), and isEmpty().
Content::Type dw::core::DeepIterator::mask private
Referenced by clone(), DeepIterator(), next(), and prev().
Stack dw::core::DeepIterator::stack private
Referenced by clone(), compareTo(), DeepIterator(), next(), prev(), and scrollTo().
The documentation for this class was generated from the following files:
dw/iterator.hh
dw/iterator.cc