Dillo: dw::Textblock::TextblockIterator Class Reference
dw::Textblock::TextblockIterator Class Reference
#include <textblock.hh>
Public Member Functions
TextblockIterator (Textblock *textblock, core::Content::Type mask, bool atEnd)
lout::object::Object * clone ()
void highlight (int start, int end, core::HighlightLayer layer)
void unhighlight (int direction, core::HighlightLayer layer)
void getAllocation (int start, int end, core::Allocation *allocation)
Static Public Member Functions
static TextblockIterator * createWordIndexIterator (Textblock *textblock, core::Content::Type mask, int wordIndex)
Protected Member Functions
int numContentsInFlow ()
void getContentInFlow (int index, core::Content *content)
Constructor & Destructor Documentation
dw::Textblock::TextblockIterator::TextblockIterator (Textblock * textblock, core::Content::Type mask, bool atEnd)
Member Function Documentation
object::Object * dw::Textblock::TextblockIterator::clone ()
References dw::Textblock::TextblockIterator.
Textblock::TextblockIterator * dw::Textblock::TextblockIterator::createWordIndexIterator (Textblock * textblock, core::Content::Type mask, int wordIndex) static
References dw::Textblock::TextblockIterator.
void dw::Textblock::TextblockIterator::getAllocation (int start, int end, core::Allocation * allocation)
References dw::core::Widget::allocation, dw::core::Allocation::ascent, dw::core::Requisition::ascent, dw::Textblock::Line::borderAscent, dw::core::Widget::boxOffsetX(), dw::Textblock::Word::content, dw::core::Allocation::descent, dw::core::Requisition::descent, dw::Textblock::Word::effSpace, dw::Textblock::findLineOfWord(), dw::Textblock::Line::firstWord, dw::Textblock::Word::flags, dw::core::Widget::getStyle(), dw::Textblock::index, dw::Textblock::Line::lastWord, dw::Textblock::leftInnerPadding, dw::Textblock::line1OffsetEff, dw::Textblock::lines, dw::Textblock::lineYOffsetCanvas(), dw::core::style::StyleAttrs::margin, lout::misc::max(), lout::misc::min(), dw::Textblock::mustBorderBeRegarded(), dw::Textblock::newLineLeftBorder, dw::Textblock::Word::size, dw::Textblock::Word::style, dw::core::Content::TEXT, dw::core::Content::text, dw::Textblock::Line::textOffset, dw::Textblock::textWidth(), dw::core::style::Box::top, dw::core::Content::type, dw::core::Content::widget, dw::core::Content::WIDGET_IN_FLOW, dw::core::Allocation::width, dw::core::Requisition::width, dw::Textblock::Word::WORD_END, dw::Textblock::Word::WORD_START, dw::Textblock::words, dw::core::Allocation::x, dw::core::Allocation::y, and dw::Textblock::yOffsetOfLineToBeCreated().
void dw::Textblock::TextblockIterator::getContentInFlow (int index, core::Content * content) protected
References dw::Textblock::words.
void dw::Textblock::TextblockIterator::highlight (int start, int end, core::HighlightLayer layer)
References DBG_IF_RTFL, DBG_OBJ_ARRATTRSET_NUM_O, DBG_OBJ_ENTER_O, DBG_OBJ_LEAVE_O, DBG_OBJ_MSGF_O, lout::misc::StringBuffer::getChars(), dw::Textblock::hlEnd, dw::Textblock::hlStart, dw::Textblock::index, lout::identity::IdentifiableObject::intoStringBuffer(), dw::Textblock::nChar, and dw::Textblock::queueDrawRange().
int dw::Textblock::TextblockIterator::numContentsInFlow () protected
void dw::Textblock::TextblockIterator::unhighlight (int direction, core::HighlightLayer layer)
References DBG_IF_RTFL, DBG_OBJ_ARRATTRSET_NUM_O, DBG_OBJ_ENTER_O, DBG_OBJ_LEAVE_O, DBG_OBJ_MSGF_O, lout::misc::StringBuffer::getChars(), dw::Textblock::hlEnd, dw::Textblock::hlStart, dw::Textblock::index, lout::identity::IdentifiableObject::intoStringBuffer(), dw::Textblock::nChar, and dw::Textblock::queueDrawRange().
The documentation for this class was generated from the following files:
dw/textblock.hh
dw/textblock_iterator.cc