Dillo: dw::oof::OOFPositionedMgr Class Reference
dw::oof::OOFPositionedMgr Class Reference abstract
#include <oofpositionedmgr.hh>
Classes
class Child
Public Member Functions
OOFPositionedMgr (OOFAwareWidget *container)
~OOFPositionedMgr ()
void sizeAllocateStart (OOFAwareWidget *caller, core::Allocation *allocation)
void sizeAllocateEnd (OOFAwareWidget *caller)
void containerSizeChangedForChildren ()
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void markSizeChange (int ref)
void markExtremesChange (int ref)
core::Widget * getWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext *context)
void addWidgetInFlow (OOFAwareWidget *widget, OOFAwareWidget *parent, int externalIndex)
int addWidgetOOF (core::Widget *widget, OOFAwareWidget *generator, int externalIndex)
void moveExternalIndices (OOFAwareWidget *generator, int oldStartIndex, int diff)
void tellPosition1 (core::Widget *widget, int x, int y)
Called before tellPosition2, see there for more.
void tellPosition2 (core::Widget *widget, int x, int y)
Called after tellPosition1.
void tellIncompletePosition1 (core::Widget *generator, core::Widget *widget, int x, int y)
void tellIncompletePosition2 (core::Widget *generator, core::Widget *widget, int x, int y)
bool containerMustAdjustExtraSpace ()
int getLeftBorder (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getRightBorder (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
bool hasFloatLeft (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
bool hasFloatRight (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getLeftFloatHeight (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getRightFloatHeight (int y, int h, OOFAwareWidget *lastGen, int lastExtIndex)
int getClearPosition (OOFAwareWidget *widget)
bool affectsLeftBorder (core::Widget *widget)
bool affectsRightBorder (core::Widget *widget)
bool mayAffectBordersAtAll ()
bool dealingWithSizeOfChild (core::Widget *child)
int getNumWidgets ()
core::Widget * getWidget (int i)
Public Member Functions inherited from dw::oof::OutOfFlowMgr
OutOfFlowMgr ()
virtual ~OutOfFlowMgr ()
virtual void calcWidgetRefSize (core::Widget *widget, core::Requisition *size)=0
virtual void getSize (core::Requisition *containerReq, int *oofWidth, int *oofHeight)=0
virtual void getExtremes (core::Extremes *containerExtr, int *oofMinWidth, int *oofMaxWidth)=0
virtual int getAvailWidthOfChild (core::Widget *child, bool forceValue)=0
virtual int getAvailHeightOfChild (core::Widget *child, bool forceValue)=0
Protected Types
enum { NOT_ALLOCATED, IN_ALLOCATION, WAS_ALLOCATED }
Protected Member Functions
bool getPosLeft (core::Widget *child, int availWidth, int *result)
bool getPosRight (core::Widget *child, int availWidth, int *result)
bool getPosTop (core::Widget *child, int availHeight, int *result)
bool getPosBottom (core::Widget *child, int availHeight, int *result)
bool getPosBorder (core::style::Length cssValue, int refLength, int *result)
bool allChildrenConsideredForSize ()
bool allChildrenConsideredForExtremes ()
bool doChildrenExceedContainer ()
virtual void sizeAllocateChildren ()=0
virtual bool posXAbsolute (Child *child)=0
virtual bool posYAbsolute (Child *child)=0
bool generatorPosDefined (Child *child)
int generatorPosX (Child *child)
int generatorPosY (Child *child)
bool posXDefined (Child *child)
bool posYDefined (Child *child)
Protected Attributes
OOFAwareWidget * container
core::Allocation containerAllocation
enum
dw::oof::OOFPositionedMgr:: { ... } containerAllocationState
lout::container::typed::Vector
< Child > * children
lout::container::typed::HashTable
< lout::object::TypedPointer
< dw::core::Widget >, Child > * childrenByWidget
Member Enumeration Documentation
anonymous enum protected
Enumerator
NOT_ALLOCATED
IN_ALLOCATION
WAS_ALLOCATED
Constructor & Destructor Documentation
dw::oof::OOFPositionedMgr::OOFPositionedMgr (OOFAwareWidget * container)
References DBG_OBJ_CREATE, DBG_OBJ_SET_NUM, and dw::core::Widget::getAllocation().
dw::oof::OOFPositionedMgr::~OOFPositionedMgr ()
References DBG_OBJ_DELETE.
Member Function Documentation
void dw::oof::OOFPositionedMgr::addWidgetInFlow (OOFAwareWidget * widget, OOFAwareWidget * parent, int externalIndex) virtual
Implements dw::oof::OutOfFlowMgr.
int dw::oof::OOFPositionedMgr::addWidgetOOF (core::Widget * widget, OOFAwareWidget * generator, int externalIndex) virtual
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_ARRSET_PTR, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, DBG_OBJ_SET_NUM, DBG_OBJ_SET_NUM_O, and DBG_OBJ_SET_PTR_O.
bool dw::oof::OOFPositionedMgr::affectsLeftBorder (core::Widget * widget) virtual
Implements dw::oof::OutOfFlowMgr.
bool dw::oof::OOFPositionedMgr::affectsRightBorder (core::Widget * widget) virtual
Implements dw::oof::OutOfFlowMgr.
bool dw::oof::OOFPositionedMgr::allChildrenConsideredForExtremes () protected
bool dw::oof::OOFPositionedMgr::allChildrenConsideredForSize () protected
bool dw::oof::OOFPositionedMgr::containerMustAdjustExtraSpace () virtual
Implements dw::oof::OutOfFlowMgr.
void dw::oof::OOFPositionedMgr::containerSizeChangedForChildren () virtual
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_ENTER0, and DBG_OBJ_LEAVE.
bool dw::oof::OOFPositionedMgr::dealingWithSizeOfChild (core::Widget * child) virtual
Implements dw::oof::OutOfFlowMgr.
Reimplemented in dw::oof::OOFPosRelMgr.
bool dw::oof::OOFPositionedMgr::doChildrenExceedContainer () protected
References dw::core::Allocation::ascent, dw::core::Requisition::ascent, DBG_OBJ_ENTER0, DBG_OBJ_LEAVE, DBG_OBJ_MSG, DBG_OBJ_MSG_END, DBG_OBJ_MSG_START, DBG_OBJ_MSGF, dw::core::Allocation::descent, dw::core::Requisition::descent, dw::core::Widget::getAllocation(), dw::oof::OOFPositionedMgr::Child::widget, dw::core::Allocation::width, dw::core::Requisition::width, dw::core::Allocation::x, and dw::core::Allocation::y.
void dw::oof::OOFPositionedMgr::draw (core::View * view, core::Rectangle * area, core::DrawingContext * context) virtual
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, dw::core::Widget::draw(), dw::core::StackingProcessingContext::hasWidgetBeenProcessedAsInterruption(), dw::core::Rectangle::height, dw::core::Widget::intersects(), dw::oof::OOFPositionedMgr::Child::widget, dw::core::Rectangle::width, dw::core::Rectangle::x, and dw::core::Rectangle::y.
bool dw::oof::OOFPositionedMgr::generatorPosDefined (Child * child) inline protected
References containerAllocationState, dw::oof::OOFPositionedMgr::Child::generator, NOT_ALLOCATED, and dw::core::Widget::wasAllocated().
Referenced by generatorPosX(), generatorPosY(), posXDefined(), and posYDefined().
int dw::oof::OOFPositionedMgr::generatorPosX (Child * child) inline protected
References dw::oof::OOFPositionedMgr::Child::generator, generatorPosDefined(), dw::core::Widget::getAllocation(), and dw::core::Allocation::x.
Referenced by dw::oof::OOFPosAbsLikeMgr::calcHPosAndSizeChildOfChild(), and dw::oof::OOFPosRelMgr::getChildPosX().
int dw::oof::OOFPositionedMgr::generatorPosY (Child * child) inline protected
References dw::oof::OOFPositionedMgr::Child::generator, generatorPosDefined(), dw::core::Widget::getAllocation(), and dw::core::Allocation::y.
Referenced by dw::oof::OOFPosAbsLikeMgr::calcVPosAndSizeChildOfChild(), and dw::oof::OOFPosRelMgr::getChildPosY().
int dw::oof::OOFPositionedMgr::getClearPosition (OOFAwareWidget * widget) virtual
Return value is relative to the calling generator (not container).
Implements dw::oof::OutOfFlowMgr.
int dw::oof::OOFPositionedMgr::getLeftBorder (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Get the left border for the vertical position of y, for a height of h", based on floats; relative to the *container.
The border includes marging/border/padding of the calling textblock but is 0 if there is no float, so a caller should also consider other borders.
Implements dw::oof::OutOfFlowMgr.
int dw::oof::OOFPositionedMgr::getLeftFloatHeight (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Assuming there is a float on the left side, return the rest height of it. y is relative to the container.
See also getLeftBorder().
Implements dw::oof::OutOfFlowMgr.
int dw::oof::OOFPositionedMgr::getNumWidgets () virtual
Implements dw::oof::OutOfFlowMgr.
bool dw::oof::OOFPositionedMgr::getPosBorder (core::style::Length cssValue, int refLength, int * result) protected
References dw::core::style::absLengthVal(), dw::core::style::isAbsLength(), dw::core::style::isPerLength(), and dw::core::style::multiplyWithPerLength().
Referenced by dw::oof::OOFPosRelMgr::getChildPosDim(), getPosBottom(), getPosLeft(), getPosRight(), and getPosTop().
bool dw::oof::OOFPositionedMgr::getPosBottom (core::Widget * child, int availHeight, int * result) inline protected
References dw::core::style::StyleAttrs::bottom, getPosBorder(), and dw::core::Widget::getStyle().
Referenced by dw::oof::OOFPosAbsLikeMgr::calcVPosAndSizeChildOfChild(), and dw::oof::OOFPosAbsLikeMgr::getAvailHeightOfChild().
bool dw::oof::OOFPositionedMgr::getPosLeft (core::Widget * child, int availWidth, int * result) inline protected
References getPosBorder(), dw::core::Widget::getStyle(), and dw::core::style::StyleAttrs::left.
Referenced by dw::oof::OOFPosAbsLikeMgr::calcHPosAndSizeChildOfChild(), and dw::oof::OOFPosAbsLikeMgr::getAvailWidthOfChild().
bool dw::oof::OOFPositionedMgr::getPosRight (core::Widget * child, int availWidth, int * result) inline protected
References getPosBorder(), dw::core::Widget::getStyle(), and dw::core::style::StyleAttrs::right.
Referenced by dw::oof::OOFPosAbsLikeMgr::calcHPosAndSizeChildOfChild(), and dw::oof::OOFPosAbsLikeMgr::getAvailWidthOfChild().
bool dw::oof::OOFPositionedMgr::getPosTop (core::Widget * child, int availHeight, int * result) inline protected
References getPosBorder(), dw::core::Widget::getStyle(), and dw::core::style::StyleAttrs::top.
Referenced by dw::oof::OOFPosAbsLikeMgr::calcVPosAndSizeChildOfChild(), and dw::oof::OOFPosAbsLikeMgr::getAvailHeightOfChild().
int dw::oof::OOFPositionedMgr::getRightBorder (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Get the right border for the vertical position of y, for a height of h, based on floats; relative to the container.
See also getLeftBorder().
Implements dw::oof::OutOfFlowMgr.
int dw::oof::OOFPositionedMgr::getRightFloatHeight (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Assuming there is a float on the right side, return the rest height of it. y is relative to the container.
See also getLeftFloatHeight(), getLeftBorder().
Implements dw::oof::OutOfFlowMgr.
Widget * dw::oof::OOFPositionedMgr::getWidget (int i) virtual
Implements dw::oof::OutOfFlowMgr.
Widget * dw::oof::OOFPositionedMgr::getWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext * context) virtual
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::core::Widget::getWidgetAtPoint(), and dw::core::StackingProcessingContext::hasWidgetBeenProcessedAsInterruption().
bool dw::oof::OOFPositionedMgr::hasFloatLeft (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Return whether there is a float on the left side. y is relative to the container.
See also getLeftBorder().
Implements dw::oof::OutOfFlowMgr.
bool dw::oof::OOFPositionedMgr::hasFloatRight (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Return whether there is a float on the right side. y is relative to the container.
See also hasFloatLeft(), getLeftBorder();
Implements dw::oof::OutOfFlowMgr.
void dw::oof::OOFPositionedMgr::markExtremesChange (int ref) virtual
Implements dw::oof::OutOfFlowMgr.
Reimplemented in dw::oof::OOFPosRelMgr.
void dw::oof::OOFPositionedMgr::markSizeChange (int ref) virtual
Implements dw::oof::OutOfFlowMgr.
Reimplemented in dw::oof::OOFPosRelMgr.
bool dw::oof::OOFPositionedMgr::mayAffectBordersAtAll () virtual
Implements dw::oof::OutOfFlowMgr.
void dw::oof::OOFPositionedMgr::moveExternalIndices (OOFAwareWidget * generator, int oldStartIndex, int diff) virtual
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_SET_NUM_O, dw::oof::OOFPositionedMgr::Child::externalIndex, and dw::oof::OOFPositionedMgr::Child::widget.
virtual bool dw::oof::OOFPositionedMgr::posXAbsolute (Child * child) protected pure virtual
Implemented in dw::oof::OOFPosAbsLikeMgr, and dw::oof::OOFPosRelMgr.
Referenced by posXDefined().
bool dw::oof::OOFPositionedMgr::posXDefined (Child * child) inline protected
References generatorPosDefined(), and posXAbsolute().
Referenced by dw::oof::OOFPosRelMgr::getExtremes(), dw::oof::OOFPosAbsLikeMgr::getExtremes(), dw::oof::OOFPosRelMgr::getSize(), and dw::oof::OOFPosAbsLikeMgr::getSize().
virtual bool dw::oof::OOFPositionedMgr::posYAbsolute (Child * child) protected pure virtual
Implemented in dw::oof::OOFPosAbsLikeMgr, and dw::oof::OOFPosRelMgr.
Referenced by posYDefined().
bool dw::oof::OOFPositionedMgr::posYDefined (Child * child) inline protected
References generatorPosDefined(), and posYAbsolute().
Referenced by dw::oof::OOFPosRelMgr::getSize(), and dw::oof::OOFPosAbsLikeMgr::getSize().
virtual void dw::oof::OOFPositionedMgr::sizeAllocateChildren () protected pure virtual
Implemented in dw::oof::OOFPosAbsLikeMgr, and dw::oof::OOFPosRelMgr.
void dw::oof::OOFPositionedMgr::sizeAllocateEnd (OOFAwareWidget * caller) virtual
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_ENTER, and DBG_OBJ_LEAVE.
void dw::oof::OOFPositionedMgr::sizeAllocateStart (OOFAwareWidget * caller, core::Allocation * allocation) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::Allocation::ascent, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, dw::core::Allocation::descent, dw::core::Allocation::width, dw::core::Allocation::x, and dw::core::Allocation::y.
void dw::oof::OOFPositionedMgr::tellIncompletePosition1 (core::Widget * generator, core::Widget * widget, int x, int y) virtual
Implements dw::oof::OutOfFlowMgr.
void dw::oof::OOFPositionedMgr::tellIncompletePosition2 (core::Widget * generator, core::Widget * widget, int x, int y) virtual
Implements dw::oof::OutOfFlowMgr.
void dw::oof::OOFPositionedMgr::tellPosition1 (core::Widget * widget, int x, int y) virtual
Called before tellPosition2, see there for more.
Implements dw::oof::OutOfFlowMgr.
void dw::oof::OOFPositionedMgr::tellPosition2 (core::Widget * widget, int x, int y) virtual
Called after tellPosition1.
An implementation should only implement either tellPosition1 or tellPosition2. Coordinates are relative to the container.
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_SET_NUM_O, dw::oof::OOFPositionedMgr::Child::widget, dw::oof::OOFPositionedMgr::Child::x, and dw::oof::OOFPositionedMgr::Child::y.
Member Data Documentation
lout::container::typed::Vector<Child>* dw::oof::OOFPositionedMgr::children protected
Referenced by dw::oof::OOFPosRelMgr::getExtremes(), dw::oof::OOFPosAbsLikeMgr::getExtremes(), dw::oof::OOFPosRelMgr::getSize(), dw::oof::OOFPosAbsLikeMgr::getSize(), dw::oof::OOFPosRelMgr::markSizeChange(), dw::oof::OOFPosRelMgr::sizeAllocateChildren(), and dw::oof::OOFPosAbsLikeMgr::sizeAllocateChildren().
lout::container::typed::HashTable<lout::object::TypedPointer <dw::core::Widget>, Child>* dw::oof::OOFPositionedMgr::childrenByWidget protected
OOFAwareWidget* dw::oof::OOFPositionedMgr::container protected
Referenced by dw::oof::OOFPosAbsMgr::containerBoxOffsetX(), dw::oof::OOFPosAbsMgr::containerBoxOffsetY(), dw::oof::OOFPosAbsMgr::containerBoxRestHeight(), dw::oof::OOFPosAbsMgr::containerBoxRestWidth(), dw::oof::OOFPosAbsLikeMgr::getAvailHeightOfChild(), dw::oof::OOFPosAbsLikeMgr::getAvailWidthOfChild(), dw::oof::OOFPosRelMgr::getChildPosX(), dw::oof::OOFPosRelMgr::getChildPosY(), dw::oof::OOFPosAbsLikeMgr::getSize(), and dw::oof::OOFPosAbsLikeMgr::sizeAllocateChildren().
core::Allocation dw::oof::OOFPositionedMgr::containerAllocation protected
Referenced by dw::oof::OOFPosRelMgr::sizeAllocateChildren(), and dw::oof::OOFPosAbsLikeMgr::sizeAllocateChildren().
enum { ... } dw::oof::OOFPositionedMgr::containerAllocationState
Referenced by generatorPosDefined().
The documentation for this class was generated from the following files:
dw/oofpositionedmgr.hh
dw/oofpositionedmgr.cc