Dillo: dw::core::StackingProcessingContext Class Reference
dw::core::StackingProcessingContext Class Reference
Base class for dw::core::DrawingContext and dw::core::GettingWidgetAtPointContext.
#include <types.hh>
Public Member Functions
StackingProcessingContext ()
~StackingProcessingContext ()
bool hasWidgetBeenProcessedAsInterruption (Widget *widget)
void addWidgetProcessedAsInterruption (Widget *widget)
Private Attributes
lout::container::typed::HashSet
< lout::object::TypedPointer
< Widget > > * widgetsProcessedAsInterruption
Detailed Description
Base class for dw::core::DrawingContext and dw::core::GettingWidgetAtPointContext.
Not to be confused with the stacking context as defined by CSS.
Constructor & Destructor Documentation
dw::core::StackingProcessingContext::StackingProcessingContext () inline
dw::core::StackingProcessingContext::~StackingProcessingContext () inline
Member Function Documentation
void dw::core::StackingProcessingContext::addWidgetProcessedAsInterruption (Widget * widget) inline
References dw::core::Content::widget.
Referenced by dw::core::Widget::drawInterruption(), and dw::core::Widget::getWidgetAtPointInterrupted().
bool dw::core::StackingProcessingContext::hasWidgetBeenProcessedAsInterruption (Widget * widget) inline
Referenced by dw::oof::OOFPositionedMgr::draw(), dw::oof::OOFFloatsMgr::drawFloats(), dw::oof::OOFFloatsMgr::getFloatWidgetAtPoint(), and dw::oof::OOFPositionedMgr::getWidgetAtPoint().
Member Data Documentation
lout::container::typed::HashSet<lout::object::TypedPointer<Widget> >* dw::core::StackingProcessingContext::widgetsProcessedAsInterruption private
The documentation for this class was generated from the following file:
dw/types.hh