Dillo: dw::core::CharIterator Class Reference
dw::core::CharIterator Class Reference
#include <iterator.hh>
Public Types
enum { START = 257, END = 258 }
Public Member Functions
CharIterator (Widget *widget, bool followReferences)
...
~CharIterator ()
lout::object::Object * clone ()
Return an exact copy of the object.
int compareTo (lout::object::Comparable *other)
Compare two objects, this and other.
bool next ()
bool prev ()
int getChar ()
CharIterator * cloneCharIterator ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Static Public Member Functions
static void highlight (CharIterator *it1, CharIterator *it2, HighlightLayer layer)
static void unhighlight (CharIterator *it1, CharIterator *it2, HighlightLayer layer)
static void scrollTo (CharIterator *it1, CharIterator *it2, HPosition hpos, VPosition vpos)
Private Member Functions
CharIterator ()
Private Attributes
DeepIterator * it
int pos
int ch
Member Enumeration Documentation
anonymous enum
Enumerator
START
END
Constructor & Destructor Documentation
dw::core::CharIterator::CharIterator () private
dw::core::CharIterator::CharIterator (Widget * widget, bool followReferences)
...
If followReferences is true, only the reference are followed, when the container and generator for a widget is different. If false, only the container is followed.
References dw::core::DeepIterator::DeepIterator(), dw::core::Widget::iterator(), dw::core::Content::maskForSelection(), and dw::core::Iterator::unref().
dw::core::CharIterator::~CharIterator ()
Member Function Documentation
object::Object * dw::core::CharIterator::clone () virtual
Return an exact copy of the object.
Reimplemented from lout::object::Object.
References ch, dw::core::DeepIterator::cloneDeepIterator(), it, and pos.
Referenced by cloneCharIterator().
CharIterator* dw::core::CharIterator::cloneCharIterator () inline
References clone().
Referenced by dw::core::FindtextState::search(), and dw::core::FindtextState::unhighlight().
int dw::core::CharIterator::compareTo (lout::object::Comparable * other) virtual
Compare two objects, this and other.
Return a value < 0, when this is less than other, a value > 0, when this is greater than other, or 0, when this and other are equal.
If c1.equals(c2) (as defined in Object), c1.compareTo(c2) must be 0, but, unlike you may expect, the reversed is not necessarily true. This method returns 0, if, according to the rules for sorting, there is no difference, but there may still be differences (not relevant for sorting), which "equals" will care about.
Implements lout::object::Comparable.
References lout::object::Comparable::compareTo(), it, and pos.
int dw::core::CharIterator::getChar () inline
References ch.
Referenced by highlight(), and dw::core::FindtextState::search0().
void dw::core::CharIterator::highlight (CharIterator * it1, CharIterator * it2, HighlightLayer layer) static
References dw::core::DeepIterator::cloneDeepIterator(), dw::core::DeepIterator::compareTo(), END, getChar(), dw::core::DeepIterator::getContent(), dw::core::DeepIterator::highlight(), it, dw::core::DeepIterator::next(), pos, prev(), dw::core::Content::TEXT, dw::core::Content::text, and dw::core::Content::type.
Referenced by dw::core::FindtextState::search().
bool dw::core::CharIterator::next ()
References dw::core::Content::BREAK, dw::core::DeepIterator::next(), and dw::core::Content::TEXT.
Referenced by dw::core::FindtextState::search(), and dw::core::FindtextState::search0().
bool dw::core::CharIterator::prev ()
References dw::core::Content::BREAK, dw::core::DeepIterator::prev(), and dw::core::Content::TEXT.
Referenced by highlight(), dw::core::FindtextState::search(), dw::core::FindtextState::search0(), and dw::core::FindtextState::unhighlight().
static void dw::core::CharIterator::scrollTo (CharIterator * it1, CharIterator * it2, HPosition hpos, VPosition vpos) inline static
References it, pos, and dw::core::DeepIterator::scrollTo().
Referenced by dw::core::FindtextState::search().
void dw::core::CharIterator::unhighlight (CharIterator * it1, CharIterator * it2, HighlightLayer layer) static
References dw::core::DeepIterator::cloneDeepIterator(), dw::core::DeepIterator::compareTo(), it, dw::core::DeepIterator::next(), and dw::core::DeepIterator::unhighlight().
Referenced by dw::core::FindtextState::unhighlight().
Member Data Documentation
int dw::core::CharIterator::ch private
Referenced by clone(), and getChar().
DeepIterator* dw::core::CharIterator::it private
Referenced by clone(), compareTo(), highlight(), scrollTo(), and unhighlight().
int dw::core::CharIterator::pos private
Referenced by clone(), compareTo(), highlight(), and scrollTo().
The documentation for this class was generated from the following files:
dw/iterator.hh
dw/iterator.cc