Dillo: dw::fltk::ui::FltkLabelButtonResource Class Reference
dw::fltk::ui::FltkLabelButtonResource Class Reference
#include <fltkui.hh>
Public Member Functions
FltkLabelButtonResource (FltkPlatform *platform, const char *label)
~FltkLabelButtonResource ()
void sizeRequest (core::Requisition *requisition)
const char * getLabel ()
void setLabel (const char *label)
Public Member Functions inherited from dw::fltk::ui::FltkSpecificResource< dw::core::ui::LabelButtonResource >
FltkSpecificResource (FltkPlatform *platform)
~FltkSpecificResource ()
void sizeAllocate (core::Allocation *allocation)
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void setStyle (core::style::Style *style)
bool isEnabled ()
void setEnabled (bool enabled)
Public Member Functions inherited from dw::core::ui::LabelButtonResource
Iterator * iterator (Content::Type mask, bool atEnd)
Public Member Functions inherited from dw::core::ui::Resource
Resource ()
virtual ~Resource ()
virtual void getExtremes (Extremes *extremes)
virtual int getAvailWidthOfChild (Widget *child, bool forceValue)
virtual int getAvailHeightOfChild (Widget *child, bool forceValue)
virtual void correctRequisitionOfChild (Widget *child, Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
virtual void correctExtremesOfChild (Widget *child, Extremes *extremes, bool useAdjustmentWidth)
virtual void containerSizeChangedForChildren ()
virtual void setDisplayed (bool displayed)
void connectActivate (ActivateReceiver *receiver)
void connectClicked (ClickedReceiver *receiver)
Public Member Functions inherited from dw::fltk::ui::FltkResource
~FltkResource ()
virtual void attachView (FltkView *view)
virtual void detachView (FltkView *view)
void sizeAllocate (core::Allocation *allocation)
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void setStyle (core::style::Style *style)
bool isEnabled ()
void setEnabled (bool enabled)
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions
Fl_Widget * createNewWidget (core::Allocation *allocation)
Protected Member Functions inherited from dw::core::ui::Resource
void queueResize (bool extremesChanged)
virtual Embed * getEmbed ()
virtual void setEmbed (Embed *embed)
void emitActivate ()
void emitClicked (EventButton *event)
Protected Member Functions inherited from dw::fltk::ui::FltkResource
FltkResource (FltkPlatform *platform)
void init (FltkPlatform *platform)
virtual void setWidgetStyle (Fl_Widget *widget, core::style::Style *style)
void setDisplayed (bool displayed)
bool displayed ()
Static Private Member Functions
static void widgetCallback (Fl_Widget *widget, void *data)
Private Attributes
const char * label
Additional Inherited Members
Protected Attributes inherited from dw::fltk::ui::FltkResource
FltkView * view
Fl_Widget * widget
core::Allocation allocation
FltkPlatform * platform
core::style::Style * style
Constructor & Destructor Documentation
dw::fltk::ui::FltkLabelButtonResource::FltkLabelButtonResource (FltkPlatform * platform, const char * label)
References dw::fltk::ui::FltkResource::init().
dw::fltk::ui::FltkLabelButtonResource::~FltkLabelButtonResource ()
References label.
Member Function Documentation
Fl_Widget * dw::fltk::ui::FltkLabelButtonResource::createNewWidget (core::Allocation * allocation) protected virtual
Implements dw::fltk::ui::FltkResource.
References dw::core::Allocation::ascent, dw::core::Allocation::descent, label, widgetCallback(), dw::core::Allocation::width, dw::core::Allocation::x, and dw::core::Allocation::y.
const char * dw::fltk::ui::FltkLabelButtonResource::getLabel () virtual
Implements dw::core::ui::LabelButtonResource.
References label.
void dw::fltk::ui::FltkLabelButtonResource::setLabel (const char * label) virtual
Implements dw::core::ui::LabelButtonResource.
References dw::core::ui::Resource::queueResize(), and dw::fltk::ui::FltkResource::widget.
void dw::fltk::ui::FltkLabelButtonResource::sizeRequest (core::Requisition * requisition) virtual
Implements dw::core::ui::Resource.
References dw::core::Requisition::ascent, dw::core::style::Font::ascent, DBG_OBJ_ENTER0, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::core::Requisition::descent, dw::core::style::Font::descent, dw::fltk::FltkFont::font, dw::core::style::StyleAttrs::font, label, dw::fltk::ui::RELIEF_X_THICKNESS, dw::fltk::ui::RELIEF_Y_THICKNESS, dw::core::style::FontAttrs::size, dw::fltk::ui::FltkResource::style, and dw::core::Requisition::width.
void dw::fltk::ui::FltkLabelButtonResource::widgetCallback (Fl_Widget * widget, void * data) static private
References dw::core::ui::Resource::emitClicked(), and dw::fltk::ui::setButtonEvent().
Referenced by createNewWidget().
Member Data Documentation
const char* dw::fltk::ui::FltkLabelButtonResource::label private
Referenced by createNewWidget(), getLabel(), sizeRequest(), and ~FltkLabelButtonResource().
The documentation for this class was generated from the following files:
dw/fltkui.hh
dw/fltkui.cc