Dillo: dw::core::Iterator Class Reference
dw::core::Iterator Class Reference abstract
Iterators are used to iterate through the contents of a widget.
#include <iterator.hh>
Public Member Functions
bool equals (Object *other)
Returns, whether two objects are equal.
void intoStringBuffer (lout::misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Widget * getWidget ()
Content * getContent ()
Content::Type getMask ()
virtual void unref ()
Delete the iterator.
virtual bool next ()=0
Move iterator forward and store content it.
virtual bool prev ()=0
Move iterator backward and store content it.
virtual void highlight (int start, int end, HighlightLayer layer)=0
Extend highlighted region to contain part of the current content.
virtual void unhighlight (int direction, HighlightLayer layer)=0
Shrink highlighted region to no longer contain the current content.
virtual void getAllocation (int start, int end, Allocation *allocation)=0
Return the shape, which a part of the item, the iterator points on, allocates.
Iterator * cloneIterator ()
Public Member Functions inherited from lout::object::Comparable
virtual int compareTo (Comparable *other)=0
Compare two objects, this and other.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Static Public Member Functions
static void scrollTo (Iterator *it1, Iterator *it2, int start, int end, HPosition hpos, VPosition vpos)
Scrolls the viewport, so that the region between it1 and it2 is seen, according to hpos and vpos.
Protected Member Functions
Iterator (Widget *widget, Content::Type mask, bool atEnd)
Iterator (Iterator &it)
~Iterator ()
Protected Attributes
Content content
Private Attributes
Widget * widget
Content::Type mask
Detailed Description
Iterators are used to iterate through the contents of a widget.
When using iterators, you should care about the results of dw::core::Widget::hasContents.
See also
dw::core::Widget::iterator
Constructor & Destructor Documentation
dw::core::Iterator::Iterator (Widget * widget, Content::Type mask, bool atEnd) protected
dw::core::Iterator::Iterator (Iterator & it) protected
References content, and widget.
dw::core::Iterator::~Iterator () protected
Member Function Documentation
Iterator* dw::core::Iterator::cloneIterator () inline
References lout::object::Object::clone().
Referenced by dw::core::DeepIterator::DeepIterator(), and dw::core::DeepIterator::searchSideward().
bool dw::core::Iterator::equals (Object * other) virtual
Returns, whether two objects are equal.
The caller should ensure, that this and the object have the same class; this makes casting of "other" safe. Typically, an implementation should check this == other first, the caller can assume a fast implementation.
Reimplemented from lout::object::Object.
References lout::object::Comparable::compareTo(), and getWidget().
Referenced by scrollTo().
virtual void dw::core::Iterator::getAllocation (int start, int end, Allocation * allocation) pure virtual
Return the shape, which a part of the item, the iterator points on, allocates.
The parameters start and end have the same meaning as in DwIterator::highlight().
Implemented in dw::core::TextIterator, dw::core::EmptyIterator, and dw::SimpleContainer::SimpleContainerIterator.
Referenced by dw::core::DeepIterator::getAllocation(), and scrollTo().
Content* dw::core::Iterator::getContent () inline
References content.
Referenced by dw::core::Widget::containerSizeChangedForChildren(), dw::core::SelectionState::copy(), dw::core::SelectionState::correctCharPos(), dw::core::DeepIterator::DeepIterator(), dw::core::Layout::detachWidget(), dw::core::DeepIterator::next(), dw::core::DeepIterator::prev(), dw::core::DeepIterator::searchDownward(), and dw::core::DeepIterator::searchSideward().
Content::Type dw::core::Iterator::getMask () inline
References mask.
Referenced by dw::core::DeepIterator::DeepIterator(), and dw::core::DeepIterator::searchSideward().
Widget* dw::core::Iterator::getWidget () inline
References widget.
Referenced by dw::core::SelectionState::buttonPress(), dw::core::SelectionState::buttonRelease(), dw::core::DeepIterator::DeepIterator(), equals(), dw::core::TextIterator::getAllocation(), scrollTo(), and dw::core::DeepIterator::searchSideward().
virtual void dw::core::Iterator::highlight (int start, int end, HighlightLayer layer) pure virtual
Extend highlighted region to contain part of the current content.
For text, start and end define the characters, otherwise, the shape is defined as [0, 1], i.e. for highlighting a whole dw::core::Content, pass 0 and >= 1. To unhighlight see also dw::core::Iterator::unhighlight.
Implemented in dw::core::EmptyIterator, and dw::SimpleContainer::SimpleContainerIterator.
Referenced by dw::core::DeepIterator::highlight().
void dw::core::Iterator::intoStringBuffer (lout::misc::StringBuffer * sb) virtual
Store a textual representation of the object in a misc::StringBuffer.
This is used by object::Object::toString.
Reimplemented from lout::object::Object.
Reimplemented in dw::oof::OOFAwareWidget::OOFAwareWidgetIterator.
References lout::misc::StringBuffer::append(), lout::misc::StringBuffer::appendPointer(), content, lout::identity::IdentifiableObject::getClassName(), dw::core::Content::intoStringBuffer(), mask, dw::core::Content::maskIntoStringBuffer(), and widget.
Referenced by dw::core::SelectionState::buttonPress(), dw::core::SelectionState::buttonRelease(), and dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::intoStringBuffer().
virtual bool dw::core::Iterator::next () pure virtual
Move iterator forward and store content it.
Returns true on success.
Implemented in dw::core::TextIterator, dw::oof::OOFAwareWidget::OOFAwareWidgetIterator, dw::core::EmptyIterator, and dw::SimpleContainer::SimpleContainerIterator.
Referenced by dw::core::Widget::containerSizeChangedForChildren(), dw::core::DeepIterator::DeepIterator(), dw::core::Layout::detachWidget(), and dw::core::DeepIterator::next().
virtual bool dw::core::Iterator::prev () pure virtual
Move iterator backward and store content it.
Returns true on success.
Implemented in dw::core::TextIterator, dw::oof::OOFAwareWidget::OOFAwareWidgetIterator, dw::core::EmptyIterator, and dw::SimpleContainer::SimpleContainerIterator.
Referenced by dw::core::DeepIterator::prev().
void dw::core::Iterator::scrollTo (Iterator * it1, Iterator * it2, int start, int end, HPosition hpos, VPosition vpos) static
Scrolls the viewport, so that the region between it1 and it2 is seen, according to hpos and vpos.
The parameters start and end have the same meaning as in dw::core::Iterator::getAllocation, start refers to it1, while end rerers to it2.
If it1 and it2 point to the same location (see code), only it1 is regarded, and both belowstart and belowend refer to it.
Todo:
Changes in the viewport size, until the idle function is called, are not regarded.
References dw::core::Allocation::ascent, dw::core::DeepIterator::clone(), dw::core::DeepIterator::compareTo(), dw::core::Allocation::descent, equals(), getAllocation(), dw::core::DeepIterator::getAllocation(), dw::core::Layout::getHeightViewport(), dw::core::Widget::getLayout(), dw::core::Layout::getUsesViewport(), getWidget(), dw::core::Layout::getWidthViewport(), lout::misc::max(), lout::misc::min(), dw::core::DeepIterator::next(), dw::core::Layout::scrollTo(), dw::core::Allocation::width, dw::core::Allocation::x, and dw::core::Allocation::y.
Referenced by dw::core::DeepIterator::scrollTo().
virtual void dw::core::Iterator::unhighlight (int direction, HighlightLayer layer) pure virtual
Shrink highlighted region to no longer contain the current content.
The direction parameter indicates whether the highlighted region should be reduced from the start (direction > 0) or from the end (direction < 0). If direction is 0 all content is unhighlighted.
Implemented in dw::core::EmptyIterator, and dw::SimpleContainer::SimpleContainerIterator.
Referenced by dw::core::DeepIterator::unhighlight().
void dw::core::Iterator::unref () virtual
Delete the iterator.
The destructor is hidden, implementations may use optimizations for the allocation. (Will soon be the case for dw::core::EmptyIteratorFactory.)
Referenced by dw::core::CharIterator::CharIterator(), dw::core::Widget::containerSizeChangedForChildren(), dw::core::DeepIterator::DeepIterator(), dw::core::Layout::detachWidget(), dw::core::DeepIterator::Stack::pop(), dw::core::DeepIterator::searchDownward(), dw::core::DeepIterator::searchSideward(), and dw::Textblock::sendSelectionEvent().
Member Data Documentation
Content dw::core::Iterator::content protected
Referenced by dw::SimpleContainer::SimpleContainerIterator::clone(), dw::core::EmptyIterator::compareTo(), dw::core::TextIterator::compareTo(), dw::core::EmptyIterator::EmptyIterator(), getContent(), intoStringBuffer(), Iterator(), dw::core::EmptyIterator::next(), dw::core::TextIterator::next(), dw::core::EmptyIterator::prev(), dw::core::TextIterator::prev(), and dw::core::TextIterator::TextIterator().
Content::Type dw::core::Iterator::mask private
Referenced by getMask(), and intoStringBuffer().
Widget* dw::core::Iterator::widget private
Referenced by getWidget(), intoStringBuffer(), and Iterator().
The documentation for this class was generated from the following files:
dw/iterator.hh
dw/iterator.cc