Dillo: lout::container::untyped::Collection0::AbstractIterator Class Reference
lout::container::untyped::Collection0::AbstractIterator Class Reference abstract
The base class for all iterators, as created by container::untyped::Collection::createIterator.
#include <container.hh>
Public Member Functions
AbstractIterator ()
void ref ()
void unref ()
virtual bool hasNext ()=0
virtual Object * getNext ()=0
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Private Attributes
int refcount
Detailed Description
The base class for all iterators, as created by container::untyped::Collection::createIterator.
Constructor & Destructor Documentation
lout::container::untyped::Collection0::AbstractIterator::AbstractIterator () inline
Member Function Documentation
virtual Object* lout::container::untyped::Collection0::AbstractIterator::getNext () pure virtual
Implemented in lout::container::untyped::Stack::StackIterator, lout::container::untyped::HashSet::HashSetIterator, and lout::container::untyped::Vector::VectorIterator.
Referenced by lout::container::untyped::Iterator::getNext().
virtual bool lout::container::untyped::Collection0::AbstractIterator::hasNext () pure virtual
Implemented in lout::container::untyped::Stack::StackIterator, lout::container::untyped::HashSet::HashSetIterator, and lout::container::untyped::Vector::VectorIterator.
Referenced by lout::container::untyped::Iterator::hasNext().
void lout::container::untyped::Collection0::AbstractIterator::ref () inline
Referenced by lout::container::untyped::Iterator::Iterator(), and lout::container::untyped::Iterator::operator=().
void lout::container::untyped::Collection0::AbstractIterator::unref () inline
Member Data Documentation
int lout::container::untyped::Collection0::AbstractIterator::refcount private
The documentation for this class was generated from the following file:
lout/container.hh