Dillo: dw::oof::OOFAwareWidget Class Reference
dw::oof::OOFAwareWidget Class Reference
Base class for widgets which can act as container and generator for widgets out of flow.
#include <oofawarewidget.hh>
Classes
class OOFAwareWidgetIterator
Public Types
enum {
SL_START, SL_BACKGROUND, SL_SC_BOTTOM, SL_IN_FLOW,
SL_OOF_REF, SL_OOF_CONT, SL_SC_TOP, SL_END
}
Public Member Functions
OOFAwareWidget ()
~OOFAwareWidget ()
core::Requisition * getRequisitionWithoutOOF ()
bool doesWidgetOOFInterruptDrawing (Widget *widget)
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
virtual void updateReference (int ref)
virtual void widgetRefSizeChanged (int externalIndex)
virtual void clearPositionChanged ()
virtual void oofSizeChanged (bool extremesChanged)
virtual int getGeneratorX (int oofmIndex)
virtual int getGeneratorY (int oofmIndex)
virtual int getGeneratorWidth (int callerX, int callerWidth)
virtual int getMaxGeneratorWidth ()
virtual bool usesMaxGeneratorWidth ()
virtual bool isPossibleOOFContainer (int oofmIndex)
virtual bool isPossibleOOFContainerParent (int oofmIndex)
Public Member Functions inherited from dw::core::Widget
void setDeleteCallback (DW_Callback_t func, void *data)
Widget ()
~Widget ()
bool resizeQueued ()
bool extremesQueued ()
bool needsResize ()
bool needsAllocate ()
bool allocateQueued ()
bool extremesChanged ()
bool wasAllocated ()
void setParent (Widget *parent)
void setQuasiParent (Widget *quasiParent)
void setGenerator (Widget *generator)
style::Style * getStyle ()
Allocation * getAllocation ()
bool inAllocation (int x, int y)
int boxOffsetX ()
int boxRestWidth ()
int boxDiffWidth ()
int boxOffsetY ()
int boxRestHeight ()
int boxDiffHeight ()
virtual int numSizeRequestReferences ()
See Sizes of Dillo Widgets (or Size requisitions depending on positions).
virtual Widget * sizeRequestReference (int index)
See Sizes of Dillo Widgets (or Size requisitions depending on positions).
virtual int numGetExtremesReferences ()
See Sizes of Dillo Widgets (or Size requisitions depending on positions).
virtual Widget * getExtremesReference (int index)
See Sizes of Dillo Widgets (or Size requisitions depending on positions).
void sizeRequest (Requisition *requisition, int numPos=0, Widget **references=NULL, int *x=NULL, int *y=NULL)
This method is a wrapper for Widget::sizeRequestImpl(); it calls the latter only when needed.
void getExtremes (Extremes *extremes, int numPos=0, Widget **references=NULL, int *x=NULL, int *y=NULL)
Wrapper for Widget::getExtremesImpl().
void sizeAllocate (Allocation *allocation)
Wrapper for Widget::sizeAllocateImpl, calls the latter only when needed.
void calcExtraSpace (int numPos, Widget **references, int *x, int *y)
Calculates dw::core::Widget::extraSpace.
int getAvailWidth (bool forceValue)
int getAvailHeight (bool forceValue)
virtual bool getAdjustMinWidth ()
void correctRequisition (Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
void correctExtremes (Extremes *extremes, bool useAdjustmentWidth)
int calcWidth (style::Length cssValue, int refWidth, Widget *refWidget, int limitMinWidth, bool forceValue)
void calcFinalWidth (style::Style *style, int refWidth, Widget *refWidget, int limitMinWidth, bool forceValue, int *finalWidth)
int calcHeight (style::Length cssValue, bool usePercentage, int refHeight, Widget *refWidget, bool forceValue)
virtual int applyPerWidth (int containerWidth, style::Length perWidth)
virtual int applyPerHeight (int containerHeight, style::Length perHeight)
int getMinWidth (Extremes *extremes, bool forceValue)
Used to evaluate Widget::adjustMinWidth.
virtual bool isBlockLevel ()
virtual bool isPossibleContainer ()
void containerSizeChanged ()
bool intersects (Widget *refWidget, Rectangle *area, Rectangle *intersection)
Calculates the intersection of the visible allocation (i. e. the intersection with the visible parent allocation) and "area" (in widget coordinates referring to "refWidget"), returned in intersection (in widget coordinates).
void drawInterruption (View *view, Rectangle *area, DrawingContext *context)
Widget * getWidgetAtPointInterrupted (int x, int y, GettingWidgetAtPointContext *context)
bool buttonPress (EventButton *event)
bool buttonRelease (EventButton *event)
bool motionNotify (EventMotion *event)
void enterNotify (EventCrossing *event)
void leaveNotify (EventCrossing *event)
virtual void setStyle (style::Style *style)
Change the style of a widget.
void setBgColor (style::Color *bgColor)
Set the background "behind" the widget, if it is not the background of the parent widget, e.g. the background of a table row.
style::Color * getBgColor ()
Get the actual background of a widget.
void drawBox (View *view, style::Style *style, Rectangle *area, int x, int y, int width, int height, bool inverse)
Draw borders and background of a widget part, which allocation is given by (x, y, width, height) (widget coordinates).
void drawWidgetBox (View *view, Rectangle *area, bool inverse)
Draw borders and background of a widget.
void drawSelected (View *view, Rectangle *area)
void setButtonSensitive (bool buttonSensitive)
bool isButtonSensitive ()
Widget * getParent ()
Widget * getContainer ()
Widget * getTopLevel ()
Get the widget at the root of the tree, this widget is part from.
int getLevel ()
Get the level of the widget within the tree.
int getGeneratorLevel ()
Get the level of the widget within the tree, regarting the generators, not the parents.
Widget * getNearestCommonAncestor (Widget *otherWidget)
Get the widget with the highest level, which is a direct ancestor of widget1 and widget2.
WidgetReference * getWidgetReference ()
void setWidgetReference (WidgetReference *widgetReference)
Widget * getGenerator ()
Layout * getLayout ()
void scrollTo (HPosition hpos, VPosition vpos, int x, int y, int width, int height)
void getMarginArea (int *xMar, int *yMar, int *widthMar, int *heightMar)
void getBorderArea (int *xBor, int *yBor, int *widthBor, int *heightBor)
void getPaddingArea (int *xPad, int *yPad, int *widthPad, int *heightPad)
Return the padding area (content plus padding).
virtual Iterator * iterator (Content::Type mask, bool atEnd)=0
Return an iterator for this widget.
virtual void removeChild (Widget *child)
Public Member Functions inherited from lout::identity::IdentifiableObject
IdentifiableObject ()
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
int getClassId ()
Returns the class identifier.
const char * getClassName ()
Return the name, under which the class of this object was registered.
bool instanceOf (int otherClassId)
Returns, whether this class is an instance of the class, given by otherClassId, or of a sub class of this class.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Static Public Member Functions
static const char * stackingLevelText (int level)
static bool testStyleFloat (core::style::Style *style)
static bool testStyleAbsolutelyPositioned (core::style::Style *style)
static bool testStyleFixedlyPositioned (core::style::Style *style)
static bool testStyleRelativelyPositioned (core::style::Style *style)
static bool testStylePositioned (core::style::Style *style)
static bool testStyleOutOfFlow (core::style::Style *style)
static bool testWidgetFloat (Widget *widget)
static bool testWidgetAbsolutelyPositioned (Widget *widget)
static bool testWidgetFixedlyPositioned (Widget *widget)
static bool testWidgetRelativelyPositioned (Widget *widget)
static bool testWidgetPositioned (Widget *widget)
static bool testWidgetOutOfFlow (Widget *widget)
Static Public Member Functions inherited from dw::core::Widget
static void setAdjustMinWidth (bool adjustMinWidth)
static void adjustHeight (int *height, bool allowDecreaseHeight, int ascent, int descent)
Static Public Attributes
static int CLASS_ID = -1
Static Public Attributes inherited from dw::core::Widget
static int CLASS_ID = -1
Protected Types
enum {
OOFM_FLOATS, OOFM_ABSOLUTE, OOFM_RELATIVE, OOFM_FIXED,
NUM_OOFM
}
enum { PARENT_REF_OOFM_BITS = 3, PARENT_REF_OOFM_MASK = (1 << PARENT_REF_OOFM_BITS) - 1 }
Protected Types inherited from dw::core::Widget
enum Flags {
RESIZE_QUEUED = 1 << 0, EXTREMES_QUEUED = 1 << 1, NEEDS_RESIZE = 1 << 2, NEEDS_ALLOCATE = 1 << 3,
ALLOCATE_QUEUED = 1 << 4, EXTREMES_CHANGED = 1 << 5, WAS_ALLOCATED = 1 << 6
}
Protected Member Functions
bool isParentRefOOF (int parentRef)
int makeParentRefInFlow (int inFlowSubRef)
int getParentRefInFlowSubRef (int parentRef)
int makeParentRefOOF (int oofmIndex, int oofmSubRef)
int getParentRefOOFSubRef (int parentRef)
int getParentRefOOFIndex (int parentRef)
oof::OutOfFlowMgr * getParentRefOutOfFlowMgr (int parentRef)
bool isWidgetOOF (Widget *widget)
int getWidgetInFlowSubRef (Widget *widget)
int getWidgetOOFSubRef (Widget *widget)
int getWidgetOOFIndex (Widget *widget)
oof::OutOfFlowMgr * getWidgetOutOfFlowMgr (Widget *widget)
OutOfFlowMgr * searchOutOfFlowMgr (int oofmIndex)
void initOutOfFlowMgrs ()
void correctRequisitionByOOF (core::Requisition *requisition, void(*splitHeightFun)(int, int *, int *))
void correctExtremesByOOF (core::Extremes *extremes)
void sizeAllocateStart (core::Allocation *allocation)
void sizeAllocateEnd ()
void containerSizeChangedForChildrenOOF ()
virtual void drawLevel (core::View *view, core::Rectangle *area, int level, core::DrawingContext *context)
void drawOOF (core::View *view, core::Rectangle *area, core::DrawingContext *context)
Widget * getWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext *context)
virtual Widget * getWidgetAtPointLevel (int x, int y, int level, core::GettingWidgetAtPointContext *context)
Widget * getWidgetOOFAtPoint (int x, int y, core::GettingWidgetAtPointContext *context)
void notifySetAsTopLevel ()
This method is called after a widget has been set as the top of a widget tree.
void notifySetParent ()
This method is called after a widget has been added to a parent.
void removeChild (Widget *child)
virtual bool adjustExtraSpaceWhenCorrectingRequisitionByOOF ()
Protected Member Functions inherited from dw::core::Widget
int getHeight ()
int getContentWidth ()
int getContentHeight ()
StackingContextMgr * getNextStackingContextMgr ()
void printFlag (Flags f)
void setFlags (Flags f)
void unsetFlags (Flags f)
void queueDraw ()
void queueDrawArea (int x, int y, int width, int height)
void queueResize (int ref, bool extremesChanged)
virtual void sizeRequestImpl (Requisition *requisition, int numPos, Widget **references, int *x, int *y)
See Sizes of Dillo Widgets.
virtual void sizeRequestSimpl (Requisition *requisition)
Simple variant, to be implemented by widgets with sizes not depending on positions.
virtual void getExtremesImpl (Extremes *extremes, int numPos, Widget **references, int *x, int *y)
See Sizes of Dillo Widgets.
virtual void getExtremesSimpl (Extremes *extremes)
Simple variant, to be implemented by widgets with extremes not depending on positions.
virtual void calcExtraSpaceImpl (int numPos, Widget **references, int *x, int *y)
The actual implementation for calculating dw::core::Widget::extraSpace.
virtual void sizeAllocateImpl (Allocation *allocation)
See Sizes of Dillo Widgets.
virtual void resizeDrawImpl ()
Called after sizeAllocateImpl() to redraw necessary areas. By default the whole widget is redrawn.
virtual void markSizeChange (int ref)
See Sizes of Dillo Widgets.
virtual void markExtremesChange (int ref)
See Sizes of Dillo Widgets.
virtual int getAvailWidthOfChild (Widget *child, bool forceValue)
virtual int getAvailHeightOfChild (Widget *child, bool forceValue)
virtual void correctRequisitionOfChild (Widget *child, Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
void correctReqWidthOfChild (Widget *child, Requisition *requisition, bool allowDecreaseWidth)
void correctReqHeightOfChild (Widget *child, Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseHeight)
virtual void correctExtremesOfChild (Widget *child, Extremes *extremes, bool useAdjustmentWidth)
virtual void containerSizeChangedForChildren ()
virtual bool affectedByContainerSizeChange ()
virtual bool affectsSizeChangeContainerChild (Widget *child)
virtual bool usesAvailWidth ()
Must be implemengted by a method returning true, when getAvailWidth() is called.
virtual bool usesAvailHeight ()
Must be implemengted by a method returning true, when getAvailHeight() is called.
virtual bool buttonPressImpl (EventButton *event)
virtual bool buttonReleaseImpl (EventButton *event)
virtual bool motionNotifyImpl (EventMotion *event)
virtual void enterNotifyImpl (EventCrossing *event)
virtual void leaveNotifyImpl (EventCrossing *event)
char * addAnchor (const char *name)
char * addAnchor (const char *name, int y)
void changeAnchor (char *name, int y)
void removeAnchor (char *name)
void setCursor (style::Cursor cursor)
bool selectionHandleEvent (SelectionState::EventType eventType, Iterator *it, int charPos, int linkNo, MousePositionEvent *event)
Protected Member Functions inherited from lout::identity::IdentifiableObject
void registerName (const char *className, int *classId)
This method must be called in the constructor for the sub class. See class comment for details.
Static Protected Member Functions
static int getOOFMIndex (Widget *widget)
static bool isOOFContainer (Widget *widget, int oofmIndex)
Protected Attributes
OOFAwareWidget * oofContainer [NUM_OOFM]
OutOfFlowMgr * outOfFlowMgr [NUM_OOFM]
core::Requisition requisitionWithoutOOF
Protected Attributes inherited from dw::core::Widget
WidgetImgRenderer * widgetImgRenderer
Allocation allocation
The current allocation: size and position, always relative to the canvas.
Layout * layout
style::Box extraSpace
Space around the margin box. Allocation is extraSpace + margin + border + padding + contents.
StackingContextMgr * stackingContextMgr
Set iff this widget constitutes a stacking context, as defined by CSS.
Widget * stackingContextWidget
The bottom-most ancestor (or this) for which stackingContextMgr is set.
Static Protected Attributes
static const char * OOFM_NAME [NUM_OOFM]
Additional Inherited Members
Public Attributes inherited from dw::core::Widget
int parentRef
This value is defined by the parent widget, and used for incremential resizing.
Detailed Description
Base class for widgets which can act as container and generator for widgets out of flow.
(Perhaps it should be diffenciated between the two roles, container and generator, but this would make multiple inheritance necessary.)
See Handling Elements Out Of Flow for an overview.
Requirements for sub classes (in most cases refer to dw::Textblock as a good example):
A sub class should at least take care to call these methods at the respective points:
dw::oof::OOFAwareWidget::correctRequisitionByOOF (from dw::core::Widget::getExtremesImpl)
dw::oof::OOFAwareWidget::correctExtremesByOOF (from dw::core::Widget::sizeRequestImpl)
dw::oof::OOFAwareWidget::sizeAllocateStart
dw::oof::OOFAwareWidget::sizeAllocateEnd (latter two from dw::core::Widget::sizeAllocateImpl)
dw::oof::OOFAwareWidget::containerSizeChangedForChildrenOOF (from dw::core::Widget::containerSizeChangedForChildren)
dw::oof::OOFAwareWidget::drawOOF (from dw::core::Widget::draw)
dw::oof::OOFAwareWidget::getWidgetOOFAtPoint (from dw::core::Widget::getWidgetAtPoint)
Implementations of dw::core::Widget::getAvailWidthOfChild and dw::core::Widget::getAvailHeightOfChild have to distinguish between widgets in flow and out of flow; general pattern:
if (isWidgetOOF (child) && getWidgetOutOfFlowMgr(child) &&
    getWidgetOutOfFlowMgr(child)->dealingWithSizeOfChild (child))
   width =
     getWidgetOutOfFlowMgr(child)->getAvailWidthOfChild (child,forceValue);
else {
   // ... specific implementation ...
See also implementations of dw::Textblock and dw::Table. (Open issue: What about dw::core::Widget::correctRequisitionOfChild and dw::core::Widget::correctExtremesOfChild? Currently, all widgets are used the default implementation.)
Iterators have to consider widgets out of flow; dw::oof::OOFAwareWidget::OOFAwareWidgetIterator is recommended as base class.
dw::core::Widget::parentRef has to be set for widgets in flow; if not used further, a simple makeParentRefInFlow(0) is sufficient (as dw::Table::addCell does). Widgets which are only containers, but not generators, do not have to care about widgets out of flow in this regard.
For both generators and containers of floats (which is only implemented by dw::Textblock) it gets a bit more complicated.
Todo:
Currently, on the level of dw::oof::OOFAwareWidget, nothing is done about dw::core::Widget::markSizeChange and dw::core::Widget::markExtremesChange. This does not matter, though: dw::Textblock takes care of these, and dw::Table is only connected to subclasses of dw::oof::OOFPositionedMgr, which do care about these. However, this should be considered for completeness.
Member Enumeration Documentation
anonymous enum protected
Enumerator
OOFM_FLOATS
OOFM_ABSOLUTE
OOFM_RELATIVE
OOFM_FIXED
NUM_OOFM
anonymous enum protected
Enumerator
PARENT_REF_OOFM_BITS
PARENT_REF_OOFM_MASK
anonymous enum
Enumerator
SL_START
SL_BACKGROUND
SL_SC_BOTTOM
SL_IN_FLOW
SL_OOF_REF
SL_OOF_CONT
SL_SC_TOP
SL_END
Constructor & Destructor Documentation
dw::oof::OOFAwareWidget::OOFAwareWidget ()
References DBG_OBJ_ARRSET_PTR, and DBG_OBJ_CREATE.
dw::oof::OOFAwareWidget::~OOFAwareWidget ()
References DBG_OBJ_DELETE.
Member Function Documentation
bool dw::oof::OOFAwareWidget::adjustExtraSpaceWhenCorrectingRequisitionByOOF () protected virtual
Reimplemented in dw::AlignedTableCell, and dw::SimpleTableCell.
void dw::oof::OOFAwareWidget::clearPositionChanged () virtual
TODO Needed after SRDOP?
Reimplemented in dw::Textblock.
References lout::misc::notImplemented().
void dw::oof::OOFAwareWidget::containerSizeChangedForChildrenOOF () protected
void dw::oof::OOFAwareWidget::correctExtremesByOOF (core::Extremes * extremes) protected
References dw::core::Extremes::adjustmentWidth, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSG_END, DBG_OBJ_MSG_START, DBG_OBJ_MSGF, lout::misc::max(), dw::core::Extremes::maxWidth, dw::core::Extremes::maxWidthIntrinsic, dw::core::Extremes::minWidth, and dw::core::Extremes::minWidthIntrinsic.
void dw::oof::OOFAwareWidget::correctRequisitionByOOF (core::Requisition * requisition, void(*)(int, int *, int *) splitHeightFun) protected
References dw::tablecell::adjustExtraSpaceWhenCorrectingRequisitionByOOF(), dw::core::Requisition::ascent, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSG_END, DBG_OBJ_MSG_START, DBG_OBJ_MSGF, DBG_OBJ_SET_NUM, dw::core::Requisition::descent, lout::misc::max(), and dw::core::Requisition::width.
bool dw::oof::OOFAwareWidget::doesWidgetOOFInterruptDrawing (Widget * widget)
References lout::misc::boolToStr(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, DBG_OBJ_MSGF, and dw::IMPL_POS.
void dw::oof::OOFAwareWidget::draw (core::View * view, core::Rectangle * area, core::DrawingContext * context) virtual
Area is given in widget coordinates.
Implements dw::core::Widget.
Reimplemented in dw::Ruler.
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, dw::core::Rectangle::height, dw::core::Rectangle::width, dw::core::Rectangle::x, and dw::core::Rectangle::y.
void dw::oof::OOFAwareWidget::drawLevel (core::View * view, core::Rectangle * area, int level, core::DrawingContext * context) protected virtual
Reimplemented in dw::Textblock, and dw::Table.
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, dw::core::Rectangle::height, dw::core::Rectangle::width, dw::core::Rectangle::x, and dw::core::Rectangle::y.
void dw::oof::OOFAwareWidget::drawOOF (core::View * view, core::Rectangle * area, core::DrawingContext * context) protected
int dw::oof::OOFAwareWidget::getGeneratorWidth (int callerX, int callerWidth) virtual
Return width including margin/border/padding Called by OOFFloatsMgr to position floats.
In somce cases (as in dw::Textblock::getGeneratorRest), the value is not up to date; for this, the caller may pass its position relative to this widget, as well as its width, which are used for adjustments. (See comment in dw::Textblock::getGeneratorRest.)
Reimplemented in dw::Textblock.
References lout::misc::notImplemented().
Referenced by dw::oof::OOFFloatsMgr::calcFloatX(), dw::oof::OOFFloatsMgr::collidesH(), and dw::oof::OOFFloatsMgr::getFloatsExtremes().
int dw::oof::OOFAwareWidget::getGeneratorX (int oofmIndex) virtual
Return position relative to container, not regarding margin/border/padding, Called by OOFFloatsMgr to position floats.
Reimplemented in dw::Textblock.
References lout::misc::notImplemented().
Referenced by dw::oof::OOFFloatsMgr::calcFloatX(), and dw::oof::OOFFloatsMgr::getBorder().
int dw::oof::OOFAwareWidget::getGeneratorY (int oofmIndex) virtual
Return position relative to container, not regarding margin/border/padding, Called by OOFFloatsMgr to position floats.
Reimplemented in dw::Textblock.
References lout::misc::notImplemented().
Referenced by dw::oof::OOFFloatsMgr::TBInfo::ComparePosition::compare(), and dw::oof::OOFFloatsMgr::getClearPosition().
int dw::oof::OOFAwareWidget::getMaxGeneratorWidth () virtual
Reimplemented in dw::Textblock.
References lout::misc::notImplemented().
Referenced by dw::oof::OOFFloatsMgr::calcFloatX(), and dw::oof::OOFFloatsMgr::getBorder().
int dw::oof::OOFAwareWidget::getOOFMIndex (Widget * widget) static protected
References lout::misc::assertNotReached(), DBG_OBJ_ENTER_O, DBG_OBJ_LEAVE_VAL_O, DBG_OBJ_MSGF_O, dw::core::style::FLOAT_LEFT, dw::core::style::FLOAT_NONE, dw::core::style::FLOAT_RIGHT, dw::core::Widget::getStyle(), dw::core::style::StyleAttrs::position, dw::core::style::POSITION_ABSOLUTE, dw::core::style::POSITION_FIXED, dw::core::style::POSITION_RELATIVE, dw::core::style::POSITION_STATIC, and dw::core::style::StyleAttrs::vloat.
int dw::oof::OOFAwareWidget::getParentRefInFlowSubRef (int parentRef) inline protected
References isParentRefOOF(), and PARENT_REF_OOFM_BITS.
Referenced by getWidgetInFlowSubRef().
int dw::oof::OOFAwareWidget::getParentRefOOFIndex (int parentRef) inline protected
References isParentRefOOF(), and PARENT_REF_OOFM_MASK.
Referenced by getParentRefOutOfFlowMgr(), and getWidgetOOFIndex().
int dw::oof::OOFAwareWidget::getParentRefOOFSubRef (int parentRef) inline protected
References isParentRefOOF(), and PARENT_REF_OOFM_BITS.
Referenced by getWidgetOOFSubRef().
oof::OutOfFlowMgr* dw::oof::OOFAwareWidget::getParentRefOutOfFlowMgr (int parentRef) inline protected
References getParentRefOOFIndex(), and outOfFlowMgr.
Referenced by getWidgetOutOfFlowMgr().
core::Requisition* dw::oof::OOFAwareWidget::getRequisitionWithoutOOF () inline
References requisitionWithoutOOF.
Widget * dw::oof::OOFAwareWidget::getWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext * context) protected virtual
Reimplemented from dw::core::Widget.
Reimplemented in dw::Ruler.
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, and DBG_OBJ_MSGF.
Widget * dw::oof::OOFAwareWidget::getWidgetAtPointLevel (int x, int y, int level, core::GettingWidgetAtPointContext * context) protected virtual
Reimplemented in dw::Textblock, and dw::Table.
References lout::misc::assertNotReached(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE, and DBG_OBJ_MSGF.
int dw::oof::OOFAwareWidget::getWidgetInFlowSubRef (Widget * widget) inline protected
References getParentRefInFlowSubRef().
Widget * dw::oof::OOFAwareWidget::getWidgetOOFAtPoint (int x, int y, core::GettingWidgetAtPointContext * context) protected
References dw::core::Widget::getWidgetAtPoint().
int dw::oof::OOFAwareWidget::getWidgetOOFIndex (Widget * widget) inline protected
References getParentRefOOFIndex().
int dw::oof::OOFAwareWidget::getWidgetOOFSubRef (Widget * widget) inline protected
References getParentRefOOFSubRef().
oof::OutOfFlowMgr* dw::oof::OOFAwareWidget::getWidgetOutOfFlowMgr (Widget * widget) inline protected
References getParentRefOutOfFlowMgr().
void dw::oof::OOFAwareWidget::initOutOfFlowMgrs () protected
References DBG_OBJ_ASSOC.
bool dw::oof::OOFAwareWidget::isOOFContainer (Widget * widget, int oofmIndex) static protected
References lout::misc::assertNotReached(), dw::core::style::DISPLAY_INLINE_BLOCK, lout::identity::IdentifiableObject::instanceOf(), and dw::core::style::OVERFLOW_VISIBLE.
bool dw::oof::OOFAwareWidget::isParentRefOOF (int parentRef) inline protected
References PARENT_REF_OOFM_MASK.
Referenced by getParentRefInFlowSubRef(), getParentRefOOFIndex(), getParentRefOOFSubRef(), and isWidgetOOF().
bool dw::oof::OOFAwareWidget::isPossibleOOFContainer (int oofmIndex) virtual
Reimplemented in dw::Textblock.
bool dw::oof::OOFAwareWidget::isPossibleOOFContainerParent (int oofmIndex) virtual
Reimplemented in dw::Textblock.
bool dw::oof::OOFAwareWidget::isWidgetOOF (Widget * widget) inline protected
References isParentRefOOF().
int dw::oof::OOFAwareWidget::makeParentRefInFlow (int inFlowSubRef) inline protected
References PARENT_REF_OOFM_BITS.
Referenced by dw::AlignedTableCell::setMaxValue().
int dw::oof::OOFAwareWidget::makeParentRefOOF (int oofmIndex, int oofmSubRef) inline protected
References PARENT_REF_OOFM_BITS.
void dw::oof::OOFAwareWidget::notifySetAsTopLevel () protected virtual
This method is called after a widget has been set as the top of a widget tree.
A widget may override this method when it is necessary to be notified.
Reimplemented from dw::core::Widget.
Reimplemented in dw::Textblock.
References DBG_OBJ_ARRSET_PTR.
void dw::oof::OOFAwareWidget::notifySetParent () protected virtual
This method is called after a widget has been added to a parent.
A widget may override this method when it is necessary to be notified.
Reimplemented from dw::core::Widget.
Reimplemented in dw::Textblock.
References DBG_OBJ_ARRSET_PTR, and dw::core::Widget::getParent().
void dw::oof::OOFAwareWidget::oofSizeChanged (bool extremesChanged) virtual
Called by an implementation of dw::oof::OutOfFlowMgr when the size of the container has changed, typically in sizeAllocateEnd.
Reimplemented in dw::Textblock.
References DBG_OBJ_ENTER, and DBG_OBJ_LEAVE.
void dw::oof::OOFAwareWidget::removeChild (Widget * child) protected
OutOfFlowMgr* dw::oof::OOFAwareWidget::searchOutOfFlowMgr (int oofmIndex) inline protected
References outOfFlowMgr.
void dw::oof::OOFAwareWidget::sizeAllocateEnd () protected
void dw::oof::OOFAwareWidget::sizeAllocateStart (core::Allocation * allocation) protected
const char * dw::oof::OOFAwareWidget::stackingLevelText (int level) static
static bool dw::oof::OOFAwareWidget::testStyleAbsolutelyPositioned (core::style::Style * style) inline static
References dw::IMPL_POS, dw::core::style::StyleAttrs::position, and dw::core::style::POSITION_ABSOLUTE.
Referenced by testStyleOutOfFlow(), testStylePositioned(), and testWidgetAbsolutelyPositioned().
static bool dw::oof::OOFAwareWidget::testStyleFixedlyPositioned (core::style::Style * style) inline static
References dw::IMPL_POS, dw::core::style::StyleAttrs::position, and dw::core::style::POSITION_FIXED.
Referenced by testStyleOutOfFlow(), testStylePositioned(), and testWidgetFixedlyPositioned().
static bool dw::oof::OOFAwareWidget::testStyleFloat (core::style::Style * style) inline static
References dw::core::style::FLOAT_NONE, and dw::core::style::StyleAttrs::vloat.
Referenced by testStyleOutOfFlow(), and testWidgetFloat().
static bool dw::oof::OOFAwareWidget::testStyleOutOfFlow (core::style::Style * style) inline static
References testStyleAbsolutelyPositioned(), testStyleFixedlyPositioned(), testStyleFloat(), and testStyleRelativelyPositioned().
Referenced by dw::Textblock::mustAddBreaks(), and testWidgetOutOfFlow().
static bool dw::oof::OOFAwareWidget::testStylePositioned (core::style::Style * style) inline static
References testStyleAbsolutelyPositioned(), testStyleFixedlyPositioned(), and testStyleRelativelyPositioned().
Referenced by testWidgetPositioned().
static bool dw::oof::OOFAwareWidget::testStyleRelativelyPositioned (core::style::Style * style) inline static
References dw::IMPL_POS, dw::core::style::StyleAttrs::position, and dw::core::style::POSITION_RELATIVE.
Referenced by dw::Textblock::mustAddBreaks(), testStyleOutOfFlow(), testStylePositioned(), and testWidgetRelativelyPositioned().
static bool dw::oof::OOFAwareWidget::testWidgetAbsolutelyPositioned (Widget * widget) inline static
References testStyleAbsolutelyPositioned().
static bool dw::oof::OOFAwareWidget::testWidgetFixedlyPositioned (Widget * widget) inline static
References testStyleFixedlyPositioned().
static bool dw::oof::OOFAwareWidget::testWidgetFloat (Widget * widget) inline static
References testStyleFloat().
static bool dw::oof::OOFAwareWidget::testWidgetOutOfFlow (Widget * widget) inline static
References testStyleOutOfFlow().
static bool dw::oof::OOFAwareWidget::testWidgetPositioned (Widget * widget) inline static
References testStylePositioned().
static bool dw::oof::OOFAwareWidget::testWidgetRelativelyPositioned (Widget * widget) inline static
References testStyleRelativelyPositioned().
void dw::oof::OOFAwareWidget::updateReference (int ref) virtual
...
Reimplemented in dw::Textblock.
References lout::misc::notImplemented().
bool dw::oof::OOFAwareWidget::usesMaxGeneratorWidth () virtual
Reimplemented in dw::Textblock, dw::AlignedTableCell, dw::SimpleTableCell, and dw::ListItem.
References lout::misc::notImplemented().
Referenced by dw::oof::OOFFloatsMgr::calcFloatX().
void dw::oof::OOFAwareWidget::widgetRefSizeChanged (int externalIndex) virtual
Called by an implementation of dw::oof::OutOfFlowMgr (actually only OOFPosRelMgr) for the generator of a widget out of flow, when the reference size has changed. (The size of the reference is 0 * 0 for all other implementations of dw::oof::OutOfFlowMgr.)
Reimplemented in dw::Textblock.
References lout::misc::notImplemented().
Referenced by dw::oof::OOFPosRelMgr::markSizeChange().
Member Data Documentation
int dw::oof::OOFAwareWidget::CLASS_ID = -1 static
Referenced by dw::oof::OOFPosRelMgr::calcWidgetRefSize().
OOFAwareWidget* dw::oof::OOFAwareWidget::oofContainer[NUM_OOFM] protected
Referenced by dw::Textblock::findSizeRequestReference().
const char * dw::oof::OOFAwareWidget::OOFM_NAME static protected
Initial value:
= {
   "FLOATS", "ABSOLUTE", "RELATIVE", "FIXED"
}
OutOfFlowMgr* dw::oof::OOFAwareWidget::outOfFlowMgr[NUM_OOFM] protected
Referenced by dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::getAllocationOOF(), getParentRefOutOfFlowMgr(), dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::getPart(), dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::numParts(), and searchOutOfFlowMgr().
core::Requisition dw::oof::OOFAwareWidget::requisitionWithoutOOF protected
Referenced by getRequisitionWithoutOOF().
The documentation for this class was generated from the following files:
dw/oofawarewidget.hh
dw/oofawarewidget.cc