Dillo: lout::misc::BitSet Class Reference
lout::misc::BitSet Class Reference
A bit set, which automatically reallocates when needed.
#include <misc.hh>
Public Member Functions
BitSet (int initBits)
~BitSet ()
void intoStringBuffer (misc::StringBuffer *sb)
bool get (int i) const
void set (int i, bool val)
void clear ()
Private Member Functions
int bytesForBits (int bits)
Private Attributes
unsigned char * bits
int numBits
int numBytes
Detailed Description
A bit set, which automatically reallocates when needed.
Constructor & Destructor Documentation
lout::misc::BitSet::BitSet (int initBits)
References bits, bytesForBits(), clear(), numBits, and numBytes.
lout::misc::BitSet::~BitSet ()
References bits.
Member Function Documentation
int lout::misc::BitSet::bytesForBits (int bits) inline private
Referenced by BitSet().
void lout::misc::BitSet::clear ()
References bits, and numBytes.
Referenced by BitSet(), and dw::fltk::FltkImgbuf::newScan().
bool lout::misc::BitSet::get (int i) const
References bits, and numBytes.
Referenced by dw::fltk::FltkImgbuf::init().
void lout::misc::BitSet::intoStringBuffer (misc::StringBuffer * sb)
References lout::misc::StringBuffer::append(), and numBits.
void lout::misc::BitSet::set (int i, bool val)
References bits, numBits, and numBytes.
Member Data Documentation
unsigned char* lout::misc::BitSet::bits private
Referenced by BitSet(), clear(), get(), set(), and ~BitSet().
int lout::misc::BitSet::numBits private
Referenced by BitSet(), intoStringBuffer(), and set().
int lout::misc::BitSet::numBytes private
Referenced by BitSet(), clear(), get(), and set().
The documentation for this class was generated from the following files:
lout/misc.hh
lout/misc.cc