Dillo: dw::core::ui::Resource Class Reference
dw::core::ui::Resource Class Reference abstract
Basic interface for all resources.
#include <ui.hh>
Classes
class ActivateEmitter
class ActivateReceiver
Receiver interface for the "activate" signal.
class ClickedEmitter
class ClickedReceiver
Receiver interface for the "clicked" signal.
Public Member Functions
Resource ()
virtual ~Resource ()
virtual void sizeRequest (Requisition *requisition)=0
virtual void getExtremes (Extremes *extremes)
virtual void sizeAllocate (Allocation *allocation)
virtual int getAvailWidthOfChild (Widget *child, bool forceValue)
virtual int getAvailHeightOfChild (Widget *child, bool forceValue)
virtual void correctRequisitionOfChild (Widget *child, Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
virtual void correctExtremesOfChild (Widget *child, Extremes *extremes, bool useAdjustmentWidth)
virtual void containerSizeChangedForChildren ()
virtual void setDisplayed (bool displayed)
virtual void draw (View *view, Rectangle *area, DrawingContext *context)
virtual Iterator * iterator (Content::Type mask, bool atEnd)=0
virtual void setStyle (style::Style *style)
virtual bool isEnabled ()=0
virtual void setEnabled (bool enabled)=0
void connectActivate (ActivateReceiver *receiver)
void connectClicked (ClickedReceiver *receiver)
Protected Member Functions
void queueResize (bool extremesChanged)
virtual Embed * getEmbed ()
virtual void setEmbed (Embed *embed)
void emitActivate ()
void emitClicked (EventButton *event)
Private Member Functions
void emitEnter ()
void emitLeave ()
Private Attributes
Embed * embed
ActivateEmitter activateEmitter
ClickedEmitter clickedEmitter
Friends
class Embed
Detailed Description
Basic interface for all resources.
See also
dw::core::ui
Constructor & Destructor Documentation
dw::core::ui::Resource::Resource () inline
References DBG_OBJ_CREATE.
dw::core::ui::Resource::~Resource () virtual
References DBG_OBJ_DELETE.
Member Function Documentation
void dw::core::ui::Resource::connectActivate (ActivateReceiver * receiver) inline
References dw::core::ui::Resource::ActivateEmitter::connectActivate().
Referenced by form::Form::addCheckButtonResource(), form::Form::addRadioButtonResource(), form::Form::addSelectionResource(), and form::Form::addTextResource().
void dw::core::ui::Resource::connectClicked (ClickedReceiver * receiver) inline
References dw::core::ui::Resource::ClickedEmitter::connectClicked().
Referenced by form::Form::addButtonResource().
void dw::core::ui::Resource::containerSizeChangedForChildren () virtual
Reimplemented in dw::core::ui::ComplexButtonResource.
void dw::core::ui::Resource::correctExtremesOfChild (Widget * child, Extremes * extremes, bool useAdjustmentWidth) virtual
Reimplemented in dw::core::ui::ComplexButtonResource.
References lout::misc::notImplemented().
void dw::core::ui::Resource::correctRequisitionOfChild (Widget * child, Requisition * requisition, void(*)(int, int *, int *) splitHeightFun, bool allowDecreaseWidth, bool allowDecreaseHeight) virtual
Reimplemented in dw::core::ui::ComplexButtonResource.
References lout::misc::notImplemented().
void dw::core::ui::Resource::draw (View * view, Rectangle * area, DrawingContext * context) virtual
Reimplemented in dw::fltk::ui::FltkSpecificResource< dw::core::ui::OptionMenuResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::RadioButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::ListResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::ComplexButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::LabelButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::MultiLineTextResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::CheckButtonResource >, and dw::fltk::ui::FltkSpecificResource< dw::core::ui::EntryResource >.
void dw::core::ui::Resource::emitActivate () inline protected
References dw::core::ui::Resource::ActivateEmitter::emitActivate().
void dw::core::ui::Resource::emitClicked (EventButton * event) inline protected
References dw::core::ui::Resource::ClickedEmitter::emitClicked().
Referenced by dw::fltk::ui::FltkLabelButtonResource::widgetCallback(), and dw::fltk::ui::FltkComplexButtonResource::widgetCallback().
void dw::core::ui::Resource::emitEnter () private
void dw::core::ui::Resource::emitLeave () private
int dw::core::ui::Resource::getAvailHeightOfChild (Widget * child, bool forceValue) virtual
Reimplemented in dw::core::ui::ComplexButtonResource.
References lout::misc::notImplemented().
int dw::core::ui::Resource::getAvailWidthOfChild (Widget * child, bool forceValue) virtual
Reimplemented in dw::core::ui::ComplexButtonResource.
References lout::misc::notImplemented().
virtual Embed* dw::core::ui::Resource::getEmbed () inline protected virtual
References embed.
void dw::core::ui::Resource::getExtremes (Extremes * extremes) virtual
Reimplemented in dw::core::ui::ComplexButtonResource.
References DBG_OBJ_ENTER0, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::core::Extremes::maxWidth, dw::core::Extremes::maxWidthIntrinsic, dw::core::Extremes::minWidth, dw::core::Extremes::minWidthIntrinsic, and dw::core::Requisition::width.
virtual bool dw::core::ui::Resource::isEnabled () pure virtual
Implemented in dw::fltk::ui::FltkSpecificResource< dw::core::ui::OptionMenuResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::RadioButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::ListResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::ComplexButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::LabelButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::MultiLineTextResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::CheckButtonResource >, and dw::fltk::ui::FltkSpecificResource< dw::core::ui::EntryResource >.
virtual Iterator* dw::core::ui::Resource::iterator (Content::Type mask, bool atEnd) pure virtual
Implemented in dw::core::ui::RadioButtonResource, dw::core::ui::CheckButtonResource, dw::core::ui::TextResource, dw::fltk::ui::FltkSelectionResource< dw::core::ui::OptionMenuResource >, dw::fltk::ui::FltkSelectionResource< dw::core::ui::ListResource >, dw::core::ui::ComplexButtonResource, and dw::core::ui::LabelButtonResource.
void dw::core::ui::Resource::queueResize (bool extremesChanged) inline protected
References dw::core::Widget::queueResize().
Referenced by dw::fltk::ui::FltkOptionMenuResource::addItem(), dw::fltk::ui::FltkListResource::newItem(), dw::fltk::ui::FltkOptionMenuResource::popGroup(), dw::fltk::ui::FltkOptionMenuResource::pushGroup(), dw::fltk::ui::FltkEntryResource::setDisplayed(), and dw::fltk::ui::FltkLabelButtonResource::setLabel().
void dw::core::ui::Resource::setDisplayed (bool displayed) virtual
Reimplemented in dw::fltk::ui::FltkEntryResource.
void dw::core::ui::Resource::setEmbed (Embed * embed) protected virtual
Reimplemented in dw::core::ui::ComplexButtonResource.
Referenced by dw::core::ui::Embed::Embed(), and dw::core::ui::ComplexButtonResource::setEmbed().
virtual void dw::core::ui::Resource::setEnabled (bool enabled) pure virtual
Implemented in dw::fltk::ui::FltkSpecificResource< dw::core::ui::OptionMenuResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::RadioButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::ListResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::ComplexButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::LabelButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::MultiLineTextResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::CheckButtonResource >, and dw::fltk::ui::FltkSpecificResource< dw::core::ui::EntryResource >.
void dw::core::ui::Resource::setStyle (style::Style * style) virtual
Reimplemented in dw::fltk::ui::FltkSpecificResource< dw::core::ui::OptionMenuResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::RadioButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::ListResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::ComplexButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::LabelButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::MultiLineTextResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::CheckButtonResource >, and dw::fltk::ui::FltkSpecificResource< dw::core::ui::EntryResource >.
void dw::core::ui::Resource::sizeAllocate (Allocation * allocation) virtual
Reimplemented in dw::core::ui::ComplexButtonResource, dw::fltk::ui::FltkEntryResource, dw::fltk::ui::FltkComplexButtonResource, dw::fltk::ui::FltkSpecificResource< dw::core::ui::OptionMenuResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::RadioButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::ListResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::ComplexButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::LabelButtonResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::MultiLineTextResource >, dw::fltk::ui::FltkSpecificResource< dw::core::ui::CheckButtonResource >, and dw::fltk::ui::FltkSpecificResource< dw::core::ui::EntryResource >.
virtual void dw::core::ui::Resource::sizeRequest (Requisition * requisition) pure virtual
Implemented in dw::fltk::ui::FltkListResource, dw::fltk::ui::FltkOptionMenuResource, dw::core::ui::ComplexButtonResource, dw::fltk::ui::FltkToggleButtonResource< dw::core::ui::RadioButtonResource >, dw::fltk::ui::FltkToggleButtonResource< dw::core::ui::CheckButtonResource >, dw::fltk::ui::FltkMultiLineTextResource, dw::fltk::ui::FltkEntryResource, and dw::fltk::ui::FltkLabelButtonResource.
Friends And Related Function Documentation
friend class Embed friend
Member Data Documentation
ActivateEmitter dw::core::ui::Resource::activateEmitter private
ClickedEmitter dw::core::ui::Resource::clickedEmitter private
Embed* dw::core::ui::Resource::embed private
Referenced by getEmbed().
The documentation for this class was generated from the following files:
dw/ui.hh
dw/ui.cc