Dillo: dw::core::ImgRendererDist Class Reference
dw::core::ImgRendererDist Class Reference
Implementation of ImgRenderer, which distributes all calls to a set of other implementations of ImgRenderer.
#include <imgrenderer.hh>
Public Member Functions
ImgRendererDist ()
~ImgRendererDist ()
void setBuffer (core::Imgbuf *buffer, bool resize)
Called, when an image buffer is attached.
void drawRow (int row)
Called, when data from a row is available and has been copied into the image buffer.
void finish ()
Called, when all image data has been retrieved.
void fatal ()
Called, when there are problems with the retrieval of image data.
void put (ImgRenderer *child)
void remove (ImgRenderer *child)
Public Member Functions inherited from dw::core::ImgRenderer
virtual ~ImgRenderer ()
Private Attributes
lout::container::typed::HashSet
< lout::object::TypedPointer
< ImgRenderer > > * children
Detailed Description
Implementation of ImgRenderer, which distributes all calls to a set of other implementations of ImgRenderer.
The order of the call children is not defined, especially not identical to the order in which they have been added.
Constructor & Destructor Documentation
dw::core::ImgRendererDist::ImgRendererDist () inline
References children.
dw::core::ImgRendererDist::~ImgRendererDist () inline
References children.
Member Function Documentation
void dw::core::ImgRendererDist::drawRow (int row) virtual
Called, when data from a row is available and has been copied into the image buffer.
The implementation will typically queue the respective area for drawing.
Implements dw::core::ImgRenderer.
References lout::object::TypedPointer< T >::getTypedValue().
void dw::core::ImgRendererDist::fatal () virtual
Called, when there are problems with the retrieval of image data.
The implementation may use this to indicate an error.
Implements dw::core::ImgRenderer.
References lout::object::TypedPointer< T >::getTypedValue().
void dw::core::ImgRendererDist::finish () virtual
Called, when all image data has been retrieved.
The implementation may use this instead of "drawRow" for drawing, to limit the number of draws.
Implements dw::core::ImgRenderer.
References lout::object::TypedPointer< T >::getTypedValue().
void dw::core::ImgRendererDist::put (ImgRenderer * child) inline
References children.
Referenced by dw::core::style::StyleImage::putExternalImgRenderer().
void dw::core::ImgRendererDist::remove (ImgRenderer * child) inline
References children.
Referenced by dw::core::style::StyleImage::removeExternalImgRenderer().
void dw::core::ImgRendererDist::setBuffer (core::Imgbuf * buffer, bool resize) virtual
Called, when an image buffer is attached.
This is typically the case when all meta data (size, depth) has been read.
Implements dw::core::ImgRenderer.
References lout::object::TypedPointer< T >::getTypedValue().
Member Data Documentation
lout::container::typed::HashSet<lout::object::TypedPointer <ImgRenderer> >* dw::core::ImgRendererDist::children private
Referenced by ImgRendererDist(), put(), remove(), and ~ImgRendererDist().
The documentation for this class was generated from the following files:
dw/imgrenderer.hh
dw/imgrenderer.cc