Dillo: dw::core::style::Style Class Reference
dw::core::style::Style Class Reference
#include <style.hh>
Public Member Functions
void ref ()
void unref ()
Public Member Functions inherited from dw::core::style::StyleAttrs
void initValues ()
void resetValues ()
Reset those style attributes to their standard values, which are not inherited, according to CSS.
bool sizeDiffs (StyleAttrs *otherStyleAttrs)
This method returns whether something may change its size, when its style changes from this style to otherStyle.
void setBorderColor (Color *val)
void setBorderStyle (BorderStyle val)
int boxOffsetX ()
int boxRestWidth ()
int boxDiffWidth ()
int boxOffsetY ()
int boxRestHeight ()
int boxDiffHeight ()
bool hasBackground ()
bool equals (lout::object::Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Static Public Member Functions
static Style * create (StyleAttrs *attrs)
Protected Member Functions
~Style ()
void copyAttrs (StyleAttrs *attrs)
Private Member Functions
Style (StyleAttrs *attrs)
Private Attributes
int refCount
Static Private Attributes
static int totalRef = 0
static
lout::container::typed::HashTable
< StyleAttrs, Style > * styleTable
Additional Inherited Members
Public Attributes inherited from dw::core::style::StyleAttrs
Font * font
int textDecoration
Color * color
Color * backgroundColor
StyleImage * backgroundImage
BackgroundRepeat backgroundRepeat
BackgroundAttachment backgroundAttachment
Length backgroundPositionX
Length backgroundPositionY
TextAlignType textAlign
VAlignType valign
char textAlignChar
TextTransform textTransform
FloatType vloat
ClearType clear
Overflow overflow
Position position
Length top
Length bottom
Length left
Length right
int hBorderSpacing
int vBorderSpacing
int wordSpacing
Length width
Length height
Length lineHeight
Length textIndent
Length minWidth
Length maxWidth
Length minHeight
Length maxHeight
Box margin
Box borderWidth
Box padding
BorderCollapse borderCollapse
struct {
Color * top
Color * right
Color * bottom
Color * left
} borderColor
struct {
BorderStyle top
BorderStyle right
BorderStyle bottom
BorderStyle left
} borderStyle
DisplayType display
WhiteSpace whiteSpace
ListStylePosition listStylePosition
ListStyleType listStyleType
Cursor cursor
int zIndex
int x_link
int x_img
Tooltip * x_tooltip
char x_lang [2]
Detailed Description
See also
dw::core::style
Constructor & Destructor Documentation
dw::core::style::Style::Style (StyleAttrs * attrs) private
References DBG_OBJ_ASSOC_CHILD, and DBG_OBJ_CREATE.
Referenced by create().
dw::core::style::Style::~Style () protected
References DBG_OBJ_DELETE.
Member Function Documentation
void dw::core::style::Style::copyAttrs (StyleAttrs * attrs) protected
References dw::core::style::StyleAttrs::backgroundAttachment, dw::core::style::StyleAttrs::backgroundColor, dw::core::style::StyleAttrs::backgroundImage, dw::core::style::StyleAttrs::backgroundPositionX, dw::core::style::StyleAttrs::backgroundPositionY, dw::core::style::StyleAttrs::backgroundRepeat, dw::core::style::StyleAttrs::borderCollapse, dw::core::style::StyleAttrs::borderColor, dw::core::style::StyleAttrs::borderStyle, dw::core::style::StyleAttrs::borderWidth, dw::core::style::StyleAttrs::bottom, dw::core::style::StyleAttrs::clear, dw::core::style::StyleAttrs::color, dw::core::style::StyleAttrs::cursor, dw::core::style::StyleAttrs::display, dw::core::style::StyleAttrs::font, dw::core::style::StyleAttrs::hBorderSpacing, dw::core::style::StyleAttrs::height, dw::core::style::StyleAttrs::left, dw::core::style::StyleAttrs::lineHeight, dw::core::style::StyleAttrs::listStylePosition, dw::core::style::StyleAttrs::listStyleType, dw::core::style::StyleAttrs::margin, dw::core::style::StyleAttrs::maxHeight, dw::core::style::StyleAttrs::maxWidth, dw::core::style::StyleAttrs::minHeight, dw::core::style::StyleAttrs::minWidth, dw::core::style::StyleAttrs::overflow, dw::core::style::StyleAttrs::padding, dw::core::style::StyleAttrs::position, dw::core::style::StyleAttrs::right, dw::core::style::StyleAttrs::textAlign, dw::core::style::StyleAttrs::textAlignChar, dw::core::style::StyleAttrs::textDecoration, dw::core::style::StyleAttrs::textIndent, dw::core::style::StyleAttrs::textTransform, dw::core::style::StyleAttrs::top, dw::core::style::StyleAttrs::valign, dw::core::style::StyleAttrs::vBorderSpacing, dw::core::style::StyleAttrs::vloat, dw::core::style::StyleAttrs::whiteSpace, dw::core::style::StyleAttrs::width, dw::core::style::StyleAttrs::wordSpacing, dw::core::style::StyleAttrs::x_img, dw::core::style::StyleAttrs::x_lang, dw::core::style::StyleAttrs::x_link, dw::core::style::StyleAttrs::x_tooltip, and dw::core::style::StyleAttrs::zIndex.
static Style* dw::core::style::Style::create (StyleAttrs * attrs) inline static
References lout::container::typed::HashTable< K, V >::get(), lout::container::typed::HashTable< K, V >::put(), ref(), and Style().
Referenced by main().
void dw::core::style::Style::ref () inline
Referenced by dw::Table::addRow(), create(), dw::Textblock::fillSpace(), dw::Textblock::fillWord(), dw::fltk::ui::FltkResource::setStyle(), and dw::core::Widget::setStyle().
void dw::core::style::Style::unref () inline
Referenced by dw::Textblock::changeLinkColor(), dw::Textblock::cleanupWord(), dw::Textblock::fillSpace(), dw::Textblock::hyphenateWord(), main(), dw::fltk::ui::FltkResource::setStyle(), and dw::core::Widget::setStyle().
Member Data Documentation
int dw::core::style::Style::refCount private
container::typed::HashTable< StyleAttrs, Style > * dw::core::style::Style::styleTable static private
Initial value:
=
   new container::typed::HashTable <StyleAttrs, Style> (false, false, 1024)
int dw::core::style::Style::totalRef = 0 static private
The documentation for this class was generated from the following files:
dw/style.hh
dw/style.cc