Dillo: dw::core::StackingContextMgr Class Reference
dw::core::StackingContextMgr Class Reference
See Handling stacking contexts.
#include <stackingcontextmgr.hh>
Public Member Functions
StackingContextMgr (Widget *widget)
~StackingContextMgr ()
void addChildSCWidget (Widget *widget)
int getNumZIndices ()
int getNumChildSCWidgets ()
void drawBottom (View *view, Rectangle *area, DrawingContext *context)
void drawTop (View *view, Rectangle *area, DrawingContext *context)
Widget * getTopWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext *context)
Widget * getBottomWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext *context)
Static Public Member Functions
static bool isEstablishingStackingContext (Widget *widget)
static bool handledByStackingContextMgr (Widget *widget)
Private Member Functions
int findZIndex (int zIndex, bool mustExist)
void draw (View *view, Rectangle *area, int startZIndex, int endZIndex, DrawingContext *context)
Widget * getWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext *context, int startZIndex, int endZIndex)
Private Attributes
Widget * widget
lout::container::typed::Vector
< Widget > * childSCWidgets
int * zIndices
int numZIndices
Detailed Description
See Handling stacking contexts.
Constructor & Destructor Documentation
dw::core::StackingContextMgr::StackingContextMgr (Widget * widget)
References DBG_OBJ_CREATE, and DBG_OBJ_SET_NUM.
dw::core::StackingContextMgr::~StackingContextMgr ()
References DBG_OBJ_DELETE.
Member Function Documentation
void dw::core::StackingContextMgr::addChildSCWidget (Widget * widget)
References DBG_OBJ_ARRSET_NUM, DBG_OBJ_ARRSET_PTR, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, DBG_OBJ_SET_NUM, dw::core::Widget::getStyle(), and dw::core::style::StyleAttrs::zIndex.
Referenced by dw::core::Widget::setParent().
void dw::core::StackingContextMgr::draw (View * view, Rectangle * area, int startZIndex, int endZIndex, DrawingContext * context) private
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSG_END, DBG_OBJ_MSG_START, DBG_OBJ_MSGF, dw::core::Widget::draw(), dw::core::Widget::getStyle(), dw::core::Rectangle::height, dw::core::Widget::intersects(), dw::core::Rectangle::width, dw::core::Rectangle::x, dw::core::Rectangle::y, and dw::core::style::StyleAttrs::zIndex.
Referenced by drawBottom(), and drawTop().
void dw::core::StackingContextMgr::drawBottom (View * view, Rectangle * area, DrawingContext * context) inline
References draw().
void dw::core::StackingContextMgr::drawTop (View * view, Rectangle * area, DrawingContext * context) inline
References draw().
int dw::core::StackingContextMgr::findZIndex (int zIndex, bool mustExist) private
Widget* dw::core::StackingContextMgr::getBottomWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext * context) inline
References getWidgetAtPoint().
int dw::core::StackingContextMgr::getNumChildSCWidgets () inline
References lout::container::typed::Collection< T >::size().
int dw::core::StackingContextMgr::getNumZIndices () inline
References numZIndices.
Widget* dw::core::StackingContextMgr::getTopWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext * context) inline
References getWidgetAtPoint().
Widget * dw::core::StackingContextMgr::getWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext * context, int startZIndex, int endZIndex) private
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSG_END, DBG_OBJ_MSG_START, DBG_OBJ_MSGF, dw::core::Widget::getStyle(), dw::core::Widget::getWidgetAtPoint(), and dw::core::style::StyleAttrs::zIndex.
Referenced by getBottomWidgetAtPoint(), and getTopWidgetAtPoint().
static bool dw::core::StackingContextMgr::handledByStackingContextMgr (Widget * widget) inline static
References dw::core::Widget::getParent(), and isEstablishingStackingContext().
static bool dw::core::StackingContextMgr::isEstablishingStackingContext (Widget * widget) inline static
References dw::core::Widget::getStyle(), dw::IMPL_POS, dw::core::style::StyleAttrs::position, dw::core::style::POSITION_STATIC, dw::core::style::Z_INDEX_AUTO, and dw::core::style::StyleAttrs::zIndex.
Referenced by handledByStackingContextMgr().
Member Data Documentation
lout::container::typed::Vector<Widget>* dw::core::StackingContextMgr::childSCWidgets private
int dw::core::StackingContextMgr::numZIndices private
Referenced by getNumZIndices().
Widget* dw::core::StackingContextMgr::widget private
int* dw::core::StackingContextMgr::zIndices private
The documentation for this class was generated from the following files:
dw/stackingcontextmgr.hh
dw/stackingcontextmgr.cc