Dillo: lout::container::untyped::Collection Class Reference
lout::container::untyped::Collection Class Reference abstract
Abstract base class for all container objects in container::untyped.
#include <container.hh>
Public Member Functions
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Iterator iterator ()
virtual int size ()=0
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Additional Inherited Members
Protected Member Functions inherited from lout::container::untyped::Collection0
virtual AbstractIterator * createIterator ()=0
Detailed Description
Abstract base class for all container objects in container::untyped.
Member Function Documentation
void lout::container::untyped::Collection::intoStringBuffer (misc::StringBuffer * sb) virtual
Store a textual representation of the object in a misc::StringBuffer.
This is used by object::Object::toString.
Reimplemented from lout::object::Object.
Reimplemented in lout::container::untyped::HashTable.
References lout::misc::StringBuffer::append(), and lout::container::untyped::Iterator::hasNext().
Referenced by lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::Widget > >::intoStringBuffer().
Iterator lout::container::untyped::Collection::iterator () inline
References lout::container::untyped::Collection0::createIterator().
Referenced by lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::Widget > >::iterator().
virtual int lout::container::untyped::Collection::size () pure virtual
Implemented in lout::container::untyped::Stack, lout::container::untyped::HashSet, lout::container::untyped::List, and lout::container::untyped::Vector.
Referenced by lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::Widget > >::size().
The documentation for this class was generated from the following files:
lout/container.hh
lout/container.cc