Dillo: dw::core::style::StyleImage Class Reference
dw::core::style::StyleImage Class Reference
#include <style.hh>
Classes
class ExternalImgRenderer
Useful (but not mandatory) base class for updates of areas with background images.
class ExternalWidgetImgRenderer
Suitable for widgets and parts of widgets.
class StyleImgRenderer
Public Member Functions
void ref ()
void unref ()
Imgbuf * getImgbufSrc ()
Imgbuf * getImgbufTiled (bool repeatX, bool repeatY)
int getTilesX (bool repeatX, bool repeatY)
int getTilesY (bool repeatX, bool repeatY)
ImgRenderer * getMainImgRenderer ()
void putExternalImgRenderer (ImgRenderer *ir)
Add an additional ImgRenderer, especially used for drawing.
void removeExternalImgRenderer (ImgRenderer *ir)
Remove a previously added additional ImgRenderer.
Public Member Functions inherited from lout::signal::ObservedObject
virtual ~ObservedObject ()
void connectDeletion (DeletionReceiver *receiver)
Static Public Member Functions
static StyleImage * create ()
Private Member Functions
StyleImage ()
~StyleImage ()
Private Attributes
int refCount
int tilesX
int tilesY
Imgbuf * imgbufSrc
Imgbuf * imgbufTiled
ImgRendererDist * imgRendererDist
StyleImgRenderer * styleImgRenderer
Constructor & Destructor Documentation
dw::core::style::StyleImage::StyleImage () private
References DBG_OBJ_CREATE.
Referenced by create().
dw::core::style::StyleImage::~StyleImage () private
References DBG_OBJ_DELETE.
Member Function Documentation
static StyleImage* dw::core::style::StyleImage::create () inline static
References StyleImage().
Imgbuf* dw::core::style::StyleImage::getImgbufSrc () inline
References imgbufSrc.
Referenced by dw::core::style::calcBackgroundRelatedValues(), dw::core::style::drawBackground(), dw::core::style::drawBackgroundImage(), dw::core::style::StyleImage::ExternalImgRenderer::drawRow(), and imageDrawTimeout().
Imgbuf* dw::core::style::StyleImage::getImgbufTiled (bool repeatX, bool repeatY) inline
References imgbufSrc.
Referenced by dw::core::style::drawBackgroundImage().
ImgRenderer* dw::core::style::StyleImage::getMainImgRenderer () inline
References imgRendererDist.
Referenced by imageDrawTimeout(), and imageInitTimeout().
int dw::core::style::StyleImage::getTilesX (bool repeatX, bool repeatY) inline
Referenced by dw::core::style::drawBackgroundImage().
int dw::core::style::StyleImage::getTilesY (bool repeatX, bool repeatY) inline
Referenced by dw::core::style::drawBackgroundImage().
void dw::core::style::StyleImage::putExternalImgRenderer (ImgRenderer * ir) inline
Add an additional ImgRenderer, especially used for drawing.
References dw::core::ImgRendererDist::put().
Referenced by dw::core::Layout::setBgImage(), dw::Textblock::setSpaceImgRenderer(), dw::core::Widget::setStyle(), and dw::Textblock::setWordImgRenderer().
void dw::core::style::StyleImage::ref () inline
Referenced by dw::core::Layout::setBgImage().
void dw::core::style::StyleImage::removeExternalImgRenderer (ImgRenderer * ir) inline
Remove a previously added additional ImgRenderer.
References dw::core::ImgRendererDist::remove().
Referenced by dw::Textblock::removeSpaceImgRenderer(), dw::Textblock::removeWordImgRenderer(), dw::core::Layout::setBgImage(), and dw::core::Widget::setStyle().
void dw::core::style::StyleImage::unref () inline
Referenced by dw::core::Layout::setBgImage().
Member Data Documentation
Imgbuf* dw::core::style::StyleImage::imgbufSrc private
Referenced by getImgbufSrc(), and getImgbufTiled().
Imgbuf * dw::core::style::StyleImage::imgbufTiled private
ImgRendererDist* dw::core::style::StyleImage::imgRendererDist private
Referenced by getMainImgRenderer().
int dw::core::style::StyleImage::refCount private
StyleImgRenderer* dw::core::style::StyleImage::styleImgRenderer private
int dw::core::style::StyleImage::tilesX private
int dw::core::style::StyleImage::tilesY private
The documentation for this class was generated from the following files:
dw/style.hh
dw/style.cc