Dillo: dw::core::DeepIterator::Stack Class Reference
dw::core::DeepIterator::Stack Class Reference
Public Member Functions
Stack ()
~Stack ()
Iterator * getTop ()
void push (Iterator *it)
void pop ()
Public Member Functions inherited from lout::container::typed::Vector< Iterator >
Vector (int initSize, bool ownerOfObjects)
void put (Iterator *newElement, int newPos=-1)
void insert (Iterator *newElement, int pos)
int insertSorted (Iterator *newElement, object::Comparator *comparator=&object::standardComparator)
void remove (int pos)
Iterator * get (int pos) const
void clear ()
void sort (object::Comparator *comparator=&object::standardComparator)
int bsearch (Iterator *key, bool mustExist, int start, int end, object::Comparator *comparator=&object::standardComparator)
int bsearch (Iterator *key, bool mustExist, object::Comparator *comparator=&object::standardComparator)
Public Member Functions inherited from lout::container::typed::Collection< Iterator >
Collection ()
~Collection ()
bool equals (Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Iterator< Iterator > iterator ()
int size ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Additional Inherited Members
Protected Attributes inherited from lout::container::typed::Collection< Iterator >
untyped::Collection * base
Constructor & Destructor Documentation
dw::core::DeepIterator::Stack::Stack () inline
dw::core::DeepIterator::Stack::~Stack ()
References lout::container::typed::Collection< Iterator >::size().
Member Function Documentation
Iterator* dw::core::DeepIterator::Stack::getTop () inline
References lout::container::typed::Collection< Iterator >::size().
Referenced by dw::core::DeepIterator::getAllocation(), dw::core::DeepIterator::getTopIterator(), dw::core::DeepIterator::highlight(), dw::core::DeepIterator::next(), pop(), dw::core::DeepIterator::prev(), dw::core::DeepIterator::scrollTo(), and dw::core::DeepIterator::unhighlight().
void dw::core::DeepIterator::Stack::pop () inline
References getTop(), lout::container::typed::Collection< Iterator >::size(), and dw::core::Iterator::unref().
Referenced by dw::core::DeepIterator::next(), and dw::core::DeepIterator::prev().
void dw::core::DeepIterator::Stack::push (Iterator * it) inline
References lout::container::typed::Vector< Iterator >::put().
Referenced by dw::core::DeepIterator::next(), and dw::core::DeepIterator::prev().
The documentation for this class was generated from the following files:
dw/iterator.hh
dw/iterator.cc