Dillo: dw::core::ui::Resource::ActivateReceiver Class Reference
dw::core::ui::Resource::ActivateReceiver Class Reference abstract
Receiver interface for the "activate" signal.
#include <ui.hh>
Public Member Functions
virtual void activate (Resource *resource)=0
virtual void enter (Resource *resource)=0
virtual void leave (Resource *resource)=0
Public Member Functions inherited from lout::signal::Receiver
Receiver ()
~Receiver ()
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Detailed Description
Receiver interface for the "activate" signal.
Member Function Documentation
virtual void dw::core::ui::Resource::ActivateReceiver::activate (Resource * resource) pure virtual
Implemented in form::Form::FormActivateReceiver.
Referenced by dw::core::ui::Resource::ActivateEmitter::emitToReceiver().
virtual void dw::core::ui::Resource::ActivateReceiver::enter (Resource * resource) pure virtual
Implemented in form::Form::FormActivateReceiver.
Referenced by dw::core::ui::Resource::ActivateEmitter::emitToReceiver().
virtual void dw::core::ui::Resource::ActivateReceiver::leave (Resource * resource) pure virtual
Implemented in form::Form::FormActivateReceiver.
Referenced by dw::core::ui::Resource::ActivateEmitter::emitToReceiver().
The documentation for this class was generated from the following file:
dw/ui.hh