Dillo: dw::core::Layout::LinkEmitter Class Reference
dw::core::Layout::LinkEmitter Class Reference
#include <layout.hh>
Public Member Functions
void connectLink (LinkReceiver *receiver)
bool emitEnter (Widget *widget, int link, int img, int x, int y)
bool emitPress (Widget *widget, int link, int img, int x, int y, EventButton *event)
bool emitRelease (Widget *widget, int link, int img, int x, int y, EventButton *event)
bool emitClick (Widget *widget, int link, int img, int x, int y, EventButton *event)
Public Member Functions inherited from lout::signal::Emitter
Emitter ()
~Emitter ()
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions
bool emitToReceiver (lout::signal::Receiver *receiver, int signalNo, int argc, lout::object::Object **argv)
A sub class must implement this for a call to a single receiver.
Protected Member Functions inherited from lout::signal::Emitter
void emitVoid (int signalNo, int argc, Object **argv)
Emit a void signal.
bool emitBool (int signalNo, int argc, Object **argv)
Emit a boolean signal.
void connect (Receiver *receiver)
Connect a receiver to the emitter.
Private Types
enum { ENTER, PRESS, RELEASE, CLICK }
Member Enumeration Documentation
anonymous enum private
Enumerator
ENTER
PRESS
RELEASE
CLICK
Member Function Documentation
void dw::core::Layout::LinkEmitter::connectLink (LinkReceiver * receiver) inline
References lout::signal::Emitter::connect().
Referenced by dw::core::Layout::connectLink().
bool dw::core::Layout::LinkEmitter::emitClick (Widget * widget, int link, int img, int x, int y, EventButton * event)
Referenced by dw::core::Layout::emitLinkClick().
bool dw::core::Layout::LinkEmitter::emitEnter (Widget * widget, int link, int img, int x, int y)
Referenced by dw::core::Layout::emitLinkEnter().
bool dw::core::Layout::LinkEmitter::emitPress (Widget * widget, int link, int img, int x, int y, EventButton * event)
Referenced by dw::core::Layout::emitLinkPress().
bool dw::core::Layout::LinkEmitter::emitRelease (Widget * widget, int link, int img, int x, int y, EventButton * event)
Referenced by dw::core::Layout::emitLinkRelease().
bool dw::core::Layout::LinkEmitter::emitToReceiver (lout::signal::Receiver * receiver, int signalNo, int argc, lout::object::Object ** argv) protected virtual
A sub class must implement this for a call to a single receiver.
This methods gets the signal in a folded representation, it has to unfold it, and pass it to a single receiver. For boolean signals, the return value of the receiver must be returned, for void signals, the return value is discarded.
Implements lout::signal::Emitter.
References lout::misc::assertNotReached(), dw::core::Layout::LinkReceiver::click(), dw::core::Layout::LinkReceiver::enter(), dw::core::Layout::LinkReceiver::press(), and dw::core::Layout::LinkReceiver::release().
The documentation for this class was generated from the following files:
dw/layout.hh
dw/layout.cc