Dillo: lout::signal::Emitter Class Reference
lout::signal::Emitter Class Reference abstract
The base class for signal emitters.
#include <signal.hh>
Public Member Functions
Emitter ()
~Emitter ()
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions
void emitVoid (int signalNo, int argc, Object **argv)
Emit a void signal.
bool emitBool (int signalNo, int argc, Object **argv)
Emit a boolean signal.
void connect (Receiver *receiver)
Connect a receiver to the emitter.
virtual bool emitToReceiver (Receiver *receiver, int signalNo, int argc, Object **argv)=0
A sub class must implement this for a call to a single receiver.
Private Member Functions
void unconnect (Receiver *receiver)
Private Attributes
container::typed::List
< Receiver > * receivers
Friends
class Receiver
Detailed Description
The base class for signal emitters.
If defining a signal group, a sub class of this class must be defined, with
a definition of the different signals (as enumeration),
an implementation of signal::Emitter::emitToReceiver,
wrappers for signal::Emitter::emitVoid and signal::Emitter::emitBool, respectively (one for each signal), and
a wrapper for signal::Emitter::connect.
There are two representations of signals:
In the unfolded representation, the signal itself is represented by the method itself (in the emitter or the receiver), and the arguments are represented as normal C++ types.
Folding signals means to represent the signal itself by an integer number (enumeration), and translate the arguments in an object::Object* array. (If a given argument is not an instance of object::Object*, the wrappers in object can be used.)
See also
signal
Constructor & Destructor Documentation
lout::signal::Emitter::Emitter ()
lout::signal::Emitter::~Emitter ()
References lout::container::typed::Iterator< T >::hasNext(), and lout::signal::Receiver::unconnectFrom().
Member Function Documentation
void lout::signal::Emitter::connect (Receiver * receiver) protected
Connect a receiver to the emitter.
This is protected, a sub class should define a wrapper, with the respective receiver as an argument, to gain type safety.
References lout::signal::Receiver::connectTo().
Referenced by dw::core::ui::Resource::ActivateEmitter::connectActivate(), dw::core::ui::Resource::ClickedEmitter::connectClicked(), lout::signal::ObservedObject::DeletionEmitter::connectDeletion(), dw::core::Layout::Emitter::connectLayout(), and dw::core::Layout::LinkEmitter::connectLink().
bool lout::signal::Emitter::emitBool (int signalNo, int argc, Object ** argv) protected
Emit a boolean signal.
This method should be called by a wrapper, which folds the signal, delegates the emission to here, and returns the same boolean value.
References lout::container::typed::Iterator< T >::hasNext().
virtual bool lout::signal::Emitter::emitToReceiver (Receiver * receiver, int signalNo, int argc, Object ** argv) protected pure virtual
A sub class must implement this for a call to a single receiver.
This methods gets the signal in a folded representation, it has to unfold it, and pass it to a single receiver. For boolean signals, the return value of the receiver must be returned, for void signals, the return value is discarded.
Implemented in dw::core::ui::Resource::ClickedEmitter, dw::core::ui::Resource::ActivateEmitter, lout::signal::ObservedObject::DeletionEmitter, dw::core::Layout::Emitter, and dw::core::Layout::LinkEmitter.
void lout::signal::Emitter::emitVoid (int signalNo, int argc, Object ** argv) protected
Emit a void signal.
This method should be called by a wrapper (return value void), which folds the signal, and delegates the emission to here.
References lout::container::typed::Iterator< T >::hasNext().
void lout::signal::Emitter::intoStringBuffer (misc::StringBuffer * sb) virtual
Store a textual representation of the object in a misc::StringBuffer.
This is used by object::Object::toString.
Reimplemented from lout::object::Object.
References lout::misc::StringBuffer::append().
void lout::signal::Emitter::unconnect (Receiver * receiver) private
Referenced by lout::signal::Receiver::~Receiver().
Friends And Related Function Documentation
friend class Receiver friend
Member Data Documentation
container::typed::List<Receiver>* lout::signal::Emitter::receivers private
The documentation for this class was generated from the following files:
lout/signal.hh
lout/signal.cc