Dillo: dw::fltk::ui::FltkComplexButtonResource Class Reference
dw::fltk::ui::FltkComplexButtonResource Class Reference
#include <fltkui.hh>
Public Member Functions
FltkComplexButtonResource (FltkPlatform *platform, dw::core::Widget *widget, bool relief)
~FltkComplexButtonResource ()
Public Member Functions inherited from dw::fltk::ui::FltkSpecificResource< dw::core::ui::ComplexButtonResource >
FltkSpecificResource (FltkPlatform *platform)
~FltkSpecificResource ()
void sizeAllocate (core::Allocation *allocation)
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void setStyle (core::style::Style *style)
bool isEnabled ()
void setEnabled (bool enabled)
Public Member Functions inherited from dw::core::ui::ComplexButtonResource
ComplexButtonResource ()
~ComplexButtonResource ()
void sizeRequest (Requisition *requisition)
void getExtremes (Extremes *extremes)
int getAvailWidthOfChild (Widget *child, bool forceValue)
int getAvailHeightOfChild (Widget *child, bool forceValue)
void correctRequisitionOfChild (Widget *child, Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
void correctExtremesOfChild (Widget *child, Extremes *extremes, bool useAdjustmentWidth)
void containerSizeChangedForChildren ()
Iterator * iterator (Content::Type mask, bool atEnd)
int getClickX ()
int getClickY ()
Public Member Functions inherited from dw::core::ui::Resource
Resource ()
virtual ~Resource ()
virtual void setDisplayed (bool displayed)
void connectActivate (ActivateReceiver *receiver)
void connectClicked (ClickedReceiver *receiver)
Public Member Functions inherited from dw::fltk::ui::FltkResource
~FltkResource ()
void sizeAllocate (core::Allocation *allocation)
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void setStyle (core::style::Style *style)
bool isEnabled ()
void setEnabled (bool enabled)
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions
void attachView (FltkView *view)
void detachView (FltkView *view)
void sizeAllocate (core::Allocation *allocation)
dw::core::Platform * createPlatform ()
void setLayout (dw::core::Layout *layout)
int reliefXThickness ()
int reliefYThickness ()
Fl_Widget * createNewWidget (core::Allocation *allocation)
Protected Member Functions inherited from dw::core::ui::ComplexButtonResource
void setEmbed (Embed *embed)
void init (Widget *widget)
Protected Member Functions inherited from dw::core::ui::Resource
void queueResize (bool extremesChanged)
virtual Embed * getEmbed ()
void emitActivate ()
void emitClicked (EventButton *event)
Protected Member Functions inherited from dw::fltk::ui::FltkResource
FltkResource (FltkPlatform *platform)
void init (FltkPlatform *platform)
virtual void setWidgetStyle (Fl_Widget *widget, core::style::Style *style)
void setDisplayed (bool displayed)
bool displayed ()
Protected Attributes
FltkView * topView
FltkView * flatView
Protected Attributes inherited from dw::core::ui::ComplexButtonResource
Layout * layout
int click_x
int click_y
Protected Attributes inherited from dw::fltk::ui::FltkResource
FltkView * view
Fl_Widget * widget
core::Allocation allocation
FltkPlatform * platform
core::style::Style * style
Static Private Member Functions
static void widgetCallback (Fl_Widget *widget, void *data)
Private Attributes
bool relief
Constructor & Destructor Documentation
dw::fltk::ui::FltkComplexButtonResource::FltkComplexButtonResource (FltkPlatform * platform, dw::core::Widget * widget, bool relief)
References flatView, lout::misc::init(), dw::fltk::ui::FltkResource::init(), relief, and topView.
dw::fltk::ui::FltkComplexButtonResource::~FltkComplexButtonResource ()
Member Function Documentation
void dw::fltk::ui::FltkComplexButtonResource::attachView (FltkView * view) protected virtual
Reimplemented from dw::fltk::ui::FltkResource.
References dw::fltk::ui::FltkResource::attachView(), topView, and dw::fltk::FltkView::usesFltkWidgets().
Fl_Widget * dw::fltk::ui::FltkComplexButtonResource::createNewWidget (core::Allocation * allocation) protected virtual
Implements dw::fltk::ui::FltkResource.
References dw::core::Allocation::ascent, dw::core::Layout::attachView(), dw::core::Allocation::descent, flatView, dw::core::ui::ComplexButtonResource::layout, relief, reliefXThickness(), reliefYThickness(), widgetCallback(), dw::core::Allocation::width, dw::core::Allocation::x, and dw::core::Allocation::y.
dw::core::Platform * dw::fltk::ui::FltkComplexButtonResource::createPlatform () protected virtual
Implements dw::core::ui::ComplexButtonResource.
void dw::fltk::ui::FltkComplexButtonResource::detachView (FltkView * view) protected virtual
Reimplemented from dw::fltk::ui::FltkResource.
References dw::fltk::ui::FltkResource::detachView().
int dw::fltk::ui::FltkComplexButtonResource::reliefXThickness () protected virtual
Implements dw::core::ui::ComplexButtonResource.
References relief, and dw::fltk::ui::RELIEF_X_THICKNESS.
Referenced by createNewWidget(), and sizeAllocate().
int dw::fltk::ui::FltkComplexButtonResource::reliefYThickness () protected virtual
Implements dw::core::ui::ComplexButtonResource.
References relief, and dw::fltk::ui::RELIEF_Y_THICKNESS.
Referenced by createNewWidget(), and sizeAllocate().
void dw::fltk::ui::FltkComplexButtonResource::setLayout (dw::core::Layout * layout) protected virtual
Implements dw::core::ui::ComplexButtonResource.
References dw::core::Layout::attachView(), and flatView.
void dw::fltk::ui::FltkComplexButtonResource::sizeAllocate (core::Allocation * allocation) protected virtual
Reimplemented from dw::core::ui::Resource.
References dw::core::Allocation::ascent, DBG_OBJ_MSGF_O, dw::core::Allocation::descent, flatView, reliefXThickness(), reliefYThickness(), dw::fltk::ui::FltkResource::sizeAllocate(), and dw::core::Allocation::width.
void dw::fltk::ui::FltkComplexButtonResource::widgetCallback (Fl_Widget * widget, void * data) static private
References dw::core::style::StyleAttrs::boxDiffHeight(), dw::core::style::StyleAttrs::boxDiffWidth(), dw::core::style::StyleAttrs::boxOffsetX(), dw::core::style::StyleAttrs::boxOffsetY(), dw::core::ui::ComplexButtonResource::click_x, dw::core::ui::ComplexButtonResource::click_y, dw::core::ui::Resource::emitClicked(), dw::fltk::ui::setButtonEvent(), and dw::fltk::ui::FltkResource::style.
Referenced by createNewWidget().
Member Data Documentation
FltkView * dw::fltk::ui::FltkComplexButtonResource::flatView protected
Referenced by createNewWidget(), FltkComplexButtonResource(), setLayout(), and sizeAllocate().
bool dw::fltk::ui::FltkComplexButtonResource::relief private
Referenced by createNewWidget(), FltkComplexButtonResource(), reliefXThickness(), and reliefYThickness().
FltkView* dw::fltk::ui::FltkComplexButtonResource::topView protected
Referenced by attachView(), and FltkComplexButtonResource().
The documentation for this class was generated from the following files:
dw/fltkui.hh
dw/fltkui.cc