Dillo: dw::core::ui::SelectionResource Class Reference
dw::core::ui::SelectionResource Class Reference abstract
Base interface for dw::core::ui::ListResource and dw::core::ui::OptionMenuResource.
#include <ui.hh>
Public Member Functions
virtual void addItem (const char *str, bool enabled, bool selected)=0
virtual void setItem (int index, bool selected)=0
virtual void pushGroup (const char *name, bool enabled)=0
virtual void popGroup ()=0
virtual int getNumberOfItems ()=0
virtual bool isSelected (int index)=0
Public Member Functions inherited from dw::core::ui::Resource
Resource ()
virtual ~Resource ()
virtual void sizeRequest (Requisition *requisition)=0
virtual void getExtremes (Extremes *extremes)
virtual void sizeAllocate (Allocation *allocation)
virtual int getAvailWidthOfChild (Widget *child, bool forceValue)
virtual int getAvailHeightOfChild (Widget *child, bool forceValue)
virtual void correctRequisitionOfChild (Widget *child, Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
virtual void correctExtremesOfChild (Widget *child, Extremes *extremes, bool useAdjustmentWidth)
virtual void containerSizeChangedForChildren ()
virtual void setDisplayed (bool displayed)
virtual void draw (View *view, Rectangle *area, DrawingContext *context)
virtual Iterator * iterator (Content::Type mask, bool atEnd)=0
virtual void setStyle (style::Style *style)
virtual bool isEnabled ()=0
virtual void setEnabled (bool enabled)=0
void connectActivate (ActivateReceiver *receiver)
void connectClicked (ClickedReceiver *receiver)
Additional Inherited Members
Protected Member Functions inherited from dw::core::ui::Resource
void queueResize (bool extremesChanged)
virtual Embed * getEmbed ()
virtual void setEmbed (Embed *embed)
void emitActivate ()
void emitClicked (EventButton *event)
Detailed Description
Base interface for dw::core::ui::ListResource and dw::core::ui::OptionMenuResource.
Member Function Documentation
virtual void dw::core::ui::SelectionResource::addItem (const char * str, bool enabled, bool selected) pure virtual
Implemented in dw::fltk::ui::FltkListResource, dw::fltk::ui::FltkOptionMenuResource, dw::fltk::ui::FltkSelectionResource< dw::core::ui::OptionMenuResource >, and dw::fltk::ui::FltkSelectionResource< dw::core::ui::ListResource >.
Referenced by main().
virtual int dw::core::ui::SelectionResource::getNumberOfItems () pure virtual
Implemented in dw::fltk::ui::FltkListResource, and dw::fltk::ui::FltkOptionMenuResource.
Referenced by form::Form::SelectionResourceDecorator::getValue().
virtual bool dw::core::ui::SelectionResource::isSelected (int index) pure virtual
Implemented in dw::fltk::ui::FltkListResource, and dw::fltk::ui::FltkOptionMenuResource.
Referenced by form::Form::SelectionResourceDecorator::getValue().
virtual void dw::core::ui::SelectionResource::popGroup () pure virtual
Implemented in dw::fltk::ui::FltkListResource, dw::fltk::ui::FltkOptionMenuResource, dw::fltk::ui::FltkSelectionResource< dw::core::ui::OptionMenuResource >, and dw::fltk::ui::FltkSelectionResource< dw::core::ui::ListResource >.
Referenced by main().
virtual void dw::core::ui::SelectionResource::pushGroup (const char * name, bool enabled) pure virtual
Implemented in dw::fltk::ui::FltkListResource, dw::fltk::ui::FltkOptionMenuResource, dw::fltk::ui::FltkSelectionResource< dw::core::ui::OptionMenuResource >, and dw::fltk::ui::FltkSelectionResource< dw::core::ui::ListResource >.
Referenced by main().
virtual void dw::core::ui::SelectionResource::setItem (int index, bool selected) pure virtual
Implemented in dw::fltk::ui::FltkListResource, dw::fltk::ui::FltkOptionMenuResource, dw::fltk::ui::FltkSelectionResource< dw::core::ui::OptionMenuResource >, and dw::fltk::ui::FltkSelectionResource< dw::core::ui::ListResource >.
The documentation for this class was generated from the following file:
dw/ui.hh