Dillo: lout::misc::StringBuffer Class Reference
lout::misc::StringBuffer Class Reference
A class for fast concatenation of a large number of strings.
#include <misc.hh>
Classes
struct Node
Public Member Functions
StringBuffer ()
~StringBuffer ()
void append (const char *str)
Append a NUL-terminated string to the buffer, with copying.
void appendInt (int n)
void appendPointer (void *p)
void appendBool (bool b)
void appendNoCopy (char *str)
Append a NUL-terminated string to the buffer, without copying.
const char * getChars ()
Return a NUL-terminated strings containing all appended strings.
void clear ()
Remove all strings appended to the string buffer.
Private Attributes
Node * firstNode
Node * lastNode
int numChars
char * str
bool strValid
Detailed Description
A class for fast concatenation of a large number of strings.
Constructor & Destructor Documentation
lout::misc::StringBuffer::StringBuffer ()
References firstNode, lastNode, numChars, str, and strValid.
lout::misc::StringBuffer::~StringBuffer ()
References clear(), and str.
Member Function Documentation
void lout::misc::StringBuffer::append (const char * str) inline
Append a NUL-terminated string to the buffer, with copying.
A copy is kept in the buffer, so the caller does not have to care about memory management.
References appendNoCopy().
Referenced by appendBool(), appendInt(), appendPointer(), dw::core::SelectionState::copy(), lout::object::Object::intoStringBuffer(), dw::core::Iterator::intoStringBuffer(), dw::oof::OOFFloatsMgr::Float::intoStringBuffer(), lout::container::untyped::Collection::intoStringBuffer(), lout::object::Pointer::intoStringBuffer(), lout::identity::IdentifiableObject::Class::intoStringBuffer(), dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::intoStringBuffer(), lout::identity::IdentifiableObject::intoStringBuffer(), lout::object::Integer::intoStringBuffer(), lout::object::Boolean::intoStringBuffer(), lout::object::ConstString::intoStringBuffer(), lout::object::PairBase::intoStringBuffer(), lout::signal::Emitter::intoStringBuffer(), dw::core::Content::intoStringBuffer(), lout::signal::Receiver::intoStringBuffer(), dw::Textblock::BadnessAndPenalty::intoStringBuffer(), lout::container::untyped::HashTable::intoStringBuffer(), lout::misc::BitSet::intoStringBuffer(), and dw::core::Content::maskIntoStringBuffer().
void lout::misc::StringBuffer::appendBool (bool b) inline
References append().
Referenced by dw::oof::OOFFloatsMgr::Float::intoStringBuffer().
void lout::misc::StringBuffer::appendInt (int n) inline
References append().
Referenced by dw::oof::OOFFloatsMgr::Float::intoStringBuffer(), lout::identity::IdentifiableObject::Class::intoStringBuffer(), dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::intoStringBuffer(), dw::core::Content::intoStringBuffer(), and dw::Textblock::BadnessAndPenalty::intoStringBuffer().
void lout::misc::StringBuffer::appendNoCopy (char * str)
Append a NUL-terminated string to the buffer, without copying.
No copy is made, so this method should only be used in cases, where the string would otherwise be freed again. (This method may then save some CPU cycles.)
References lout::misc::StringBuffer::Node::data, firstNode, lastNode, lout::misc::StringBuffer::Node::next, numChars, str, and strValid.
Referenced by append(), and dw::core::SelectionState::copy().
void lout::misc::StringBuffer::appendPointer (void * p) inline
References append().
Referenced by lout::object::Object::intoStringBuffer(), dw::core::Iterator::intoStringBuffer(), dw::oof::OOFFloatsMgr::Float::intoStringBuffer(), lout::identity::IdentifiableObject::intoStringBuffer(), and dw::core::Content::intoStringBuffer().
void lout::misc::StringBuffer::clear ()
Remove all strings appended to the string buffer.
References lout::misc::StringBuffer::Node::data, firstNode, lastNode, lout::misc::StringBuffer::Node::next, numChars, and strValid.
Referenced by ~StringBuffer().
const char * lout::misc::StringBuffer::getChars ()
Return a NUL-terminated strings containing all appended strings.
The caller does not have to free the string, this is done in misc::StringBuffer::~StringBuffer.
References firstNode, lout::misc::StringBuffer::Node::next, numChars, str, and strValid.
Referenced by dw::Textblock::accumulateWordData(), dw::core::SelectionState::buttonPress(), dw::core::SelectionState::buttonRelease(), dw::core::SelectionState::copy(), dw::fltk::FltkImgbuf::copyRow(), dw::Textblock::TextblockIterator::highlight(), dw::fltk::FltkImgbuf::init(), dw::fltk::FltkImgbuf::newScan(), dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::next(), dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::prev(), dw::core::Content::print(), dw::core::Content::printMask(), dw::fltk::FltkImgbuf::scaleRowBeautiful(), dw::fltk::FltkImgbuf::scaleRowSimple(), dw::Textblock::searchBreakPos(), dw::Textblock::searchMinBap(), lout::object::Object::toString(), and dw::Textblock::TextblockIterator::unhighlight().
Member Data Documentation
Node* lout::misc::StringBuffer::firstNode private
Referenced by appendNoCopy(), clear(), getChars(), and StringBuffer().
Node * lout::misc::StringBuffer::lastNode private
Referenced by appendNoCopy(), clear(), and StringBuffer().
int lout::misc::StringBuffer::numChars private
Referenced by appendNoCopy(), clear(), getChars(), and StringBuffer().
char* lout::misc::StringBuffer::str private
Referenced by appendNoCopy(), getChars(), StringBuffer(), and ~StringBuffer().
bool lout::misc::StringBuffer::strValid private
Referenced by appendNoCopy(), clear(), getChars(), and StringBuffer().
The documentation for this class was generated from the following files:
lout/misc.hh
lout/misc.cc