Dillo: dw::oof::OOFFloatsMgr Class Reference
dw::oof::OOFFloatsMgr Class Reference
OutOfFlowMgr implementation dealing with floats.
#include <ooffloatsmgr.hh>
Classes
class Float
class SortedFloatsVector
class TBInfo
class WidgetInfo
Public Member Functions
OOFFloatsMgr (OOFAwareWidget *container, int oofmIndex)
~OOFFloatsMgr ()
void sizeAllocateStart (OOFAwareWidget *caller, core::Allocation *allocation)
void sizeAllocateEnd (OOFAwareWidget *caller)
void containerSizeChangedForChildren ()
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void markSizeChange (int ref)
void markExtremesChange (int ref)
core::Widget * getWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext *context)
void addWidgetInFlow (OOFAwareWidget *textblock, OOFAwareWidget *parentBlock, int externalIndex)
int addWidgetOOF (core::Widget *widget, OOFAwareWidget *generatingBlock, int externalIndex)
void calcWidgetRefSize (core::Widget *widget, core::Requisition *size)
void moveExternalIndices (OOFAwareWidget *generatingBlock, int oldStartIndex, int diff)
void tellPosition1 (core::Widget *widget, int x, int y)
Called before tellPosition2, see there for more.
void tellPosition2 (core::Widget *widget, int x, int y)
Called after tellPosition1.
void tellIncompletePosition1 (core::Widget *generator, core::Widget *widget, int x, int y)
void tellIncompletePosition2 (core::Widget *generator, core::Widget *widget, int x, int y)
void getSize (core::Requisition *cbReq, int *oofWidth, int *oofHeight)
bool containerMustAdjustExtraSpace ()
void getExtremes (core::Extremes *cbExtr, int *oofMinWidth, int *oofMaxWidth)
int getLeftBorder (int y, int h, OOFAwareWidget *lastGB, int lastExtIndex)
int getRightBorder (int y, int h, OOFAwareWidget *lastGB, int lastExtIndex)
bool hasFloatLeft (int y, int h, OOFAwareWidget *lastGB, int lastExtIndex)
bool hasFloatRight (int y, int h, OOFAwareWidget *lastGB, int lastExtIndex)
int getLeftFloatHeight (int y, int h, OOFAwareWidget *lastGB, int lastExtIndex)
int getRightFloatHeight (int y, int h, OOFAwareWidget *lastGB, int lastExtIndex)
bool affectsLeftBorder (core::Widget *widget)
bool affectsRightBorder (core::Widget *widget)
bool mayAffectBordersAtAll ()
int getClearPosition (OOFAwareWidget *textblock)
bool dealingWithSizeOfChild (core::Widget *child)
int getAvailWidthOfChild (core::Widget *child, bool forceValue)
int getAvailHeightOfChild (core::Widget *child, bool forceValue)
int getNumWidgets ()
core::Widget * getWidget (int i)
Public Member Functions inherited from dw::oof::OutOfFlowMgr
OutOfFlowMgr ()
virtual ~OutOfFlowMgr ()
Private Types
enum Side { LEFT, RIGHT }
Private Member Functions
void moveExternalIndices (lout::container::typed::Vector< Float > *list, int oldStartIndex, int diff)
Float * findFloatByWidget (core::Widget *widget)
int findTBInfo (int y)
void sizeAllocateFloats (Side side)
int getGBWidthForAllocation (Float *vloat)
int calcFloatX (Float *vloat)
Return position of a float relative to the container.
void drawFloats (SortedFloatsVector *list, core::View *view, core::Rectangle *area, core::DrawingContext *context)
core::Widget * getFloatWidgetAtPoint (SortedFloatsVector *list, int x, int y, core::GettingWidgetAtPointContext *context)
bool collidesV (Float *vloat, Float *other, int *yReal)
bool collidesH (Float *vloat, Float *other)
void getFloatsListsAndSide (Float *vloat, SortedFloatsVector **listSame, SortedFloatsVector **listOpp, Side *side)
void getFloatsSize (core::Requisition *cbReq, Side side, int *width, int *height)
void getFloatsExtremes (core::Extremes *cbExtr, Side side, int *minWidth, int *maxWidth)
TBInfo * getOOFAwareWidget (OOFAwareWidget *widget)
TBInfo * getOOFAwareWidgetWhenRegistered (OOFAwareWidget *widget)
bool isOOFAwareWidgetRegistered (OOFAwareWidget *widget)
int getBorder (Side side, int y, int h, OOFAwareWidget *lastGB, int lastExtIndex)
bool hasFloat (Side side, int y, int h, OOFAwareWidget *lastGB, int lastExtIndex)
int getFloatHeight (Side side, int y, int h, OOFAwareWidget *lastGB, int lastExtIndex)
int getClearPosition (OOFAwareWidget *widget, Side side)
void ensureFloatSize (Float *vloat)
Static Private Member Functions
static int createSubRefLeftFloat (int index)
static int createSubRefRightFloat (int index)
static bool isSubRefLeftFloat (int ref)
static bool isSubRefRightFloat (int ref)
static int getFloatIndexFromSubRef (int ref)
Private Attributes
OOFAwareWidget * container
int oofmIndex
core::Allocation containerAllocation
SortedFloatsVector * leftFloats
SortedFloatsVector * rightFloats
lout::container::typed::HashTable
< lout::object::TypedPointer
< dw::core::Widget >, Float > * floatsByWidget
lout::container::typed::Vector
< TBInfo > * tbInfos
lout::container::typed::HashTable
< lout::object::TypedPointer
< OOFAwareWidget >, TBInfo > * tbInfosByOOFAwareWidget
int lastLeftTBIndex
int lastRightTBIndex
int leftFloatsMark
int rightFloatsMark
Friends
class WidgetInfo
Detailed Description
OutOfFlowMgr implementation dealing with floats.
Note: The identifiers and comments of this class still refer to "Textblock" instead of "OOFAwareWidget"; should be cleaned up some day. (OTOH, these widgets are always textblocks.)
Member Enumeration Documentation
enum dw::oof::OOFFloatsMgr::Side private
Enumerator
LEFT
RIGHT
Constructor & Destructor Documentation
dw::oof::OOFFloatsMgr::OOFFloatsMgr (OOFAwareWidget * container, int oofmIndex)
References addWidgetInFlow(), container, containerAllocation, DBG_OBJ_CREATE, DBG_OBJ_SET_NUM, floatsByWidget, dw::core::Widget::getAllocation(), lastLeftTBIndex, lastRightTBIndex, LEFT, leftFloats, leftFloatsMark, oofmIndex, RIGHT, rightFloats, rightFloatsMark, dw::oof::OOFFloatsMgr::SortedFloatsVector::size(), tbInfos, and tbInfosByOOFAwareWidget.
dw::oof::OOFFloatsMgr::~OOFFloatsMgr ()
References DBG_OBJ_DELETE, floatsByWidget, leftFloats, rightFloats, tbInfos, and tbInfosByOOFAwareWidget.
Member Function Documentation
void dw::oof::OOFFloatsMgr::addWidgetInFlow (OOFAwareWidget * textblock, OOFAwareWidget * parentBlock, int externalIndex) virtual
Implements dw::oof::OutOfFlowMgr.
References getOOFAwareWidget(), dw::oof::OOFFloatsMgr::TBInfo::index, tbInfos, and tbInfosByOOFAwareWidget.
Referenced by OOFFloatsMgr().
int dw::oof::OOFFloatsMgr::addWidgetOOF (core::Widget * widget, OOFAwareWidget * generatingBlock, int externalIndex) virtual
Implements dw::oof::OutOfFlowMgr.
References lout::misc::assertNotReached(), createSubRefLeftFloat(), createSubRefRightFloat(), DBG_OBJ_ARRATTRSET_PTR, DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, DBG_OBJ_SET_NUM, dw::core::style::FLOAT_LEFT, dw::core::style::FLOAT_RIGHT, floatsByWidget, getOOFAwareWidget(), dw::core::Widget::getStyle(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), dw::oof::OOFFloatsMgr::TBInfo::leftFloats, leftFloats, dw::oof::OOFFloatsMgr::SortedFloatsVector::put(), lout::container::typed::Vector< T >::put(), dw::oof::OOFFloatsMgr::TBInfo::rightFloats, rightFloats, dw::oof::OOFFloatsMgr::Float::sideSpanningIndex, dw::oof::OOFFloatsMgr::SortedFloatsVector::size(), and dw::core::style::StyleAttrs::vloat.
bool dw::oof::OOFFloatsMgr::affectsLeftBorder (core::Widget * widget) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::style::FLOAT_LEFT, dw::core::Widget::getStyle(), and dw::core::style::StyleAttrs::vloat.
bool dw::oof::OOFFloatsMgr::affectsRightBorder (core::Widget * widget) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::style::FLOAT_RIGHT, dw::core::Widget::getStyle(), and dw::core::style::StyleAttrs::vloat.
int dw::oof::OOFFloatsMgr::calcFloatX (Float * vloat) private
Return position of a float relative to the container.
References lout::misc::assertNotReached(), dw::core::style::StyleAttrs::boxOffsetX(), dw::core::style::StyleAttrs::boxRestWidth(), container, DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, ensureFloatSize(), dw::core::style::FLOAT_LEFT, dw::core::style::FLOAT_RIGHT, dw::oof::OOFFloatsMgr::Float::generator, dw::oof::OOFAwareWidget::getGeneratorWidth(), dw::oof::OOFAwareWidget::getGeneratorX(), dw::oof::OOFAwareWidget::getMaxGeneratorWidth(), dw::core::Widget::getStyle(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), lout::misc::max(), lout::misc::min(), oofmIndex, dw::oof::OOFFloatsMgr::Float::size, dw::oof::OOFAwareWidget::usesMaxGeneratorWidth(), dw::core::style::StyleAttrs::vloat, and dw::core::Requisition::width.
Referenced by collidesH(), getFloatsSize(), and sizeAllocateFloats().
void dw::oof::OOFFloatsMgr::calcWidgetRefSize (core::Widget * widget, core::Requisition * size) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::Requisition::ascent, dw::core::Requisition::descent, and dw::core::Requisition::width.
bool dw::oof::OOFFloatsMgr::collidesH (Float * vloat, Float * other) private
References dw::core::Widget::boxDiffWidth(), calcFloatX(), dw::core::style::FLOAT_LEFT, dw::oof::OOFFloatsMgr::Float::generator, dw::core::Widget::getAllocation(), dw::oof::OOFAwareWidget::getGeneratorWidth(), dw::core::Widget::getStyle(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), dw::oof::OOFFloatsMgr::Float::size, dw::core::style::StyleAttrs::vloat, dw::core::Widget::wasAllocated(), dw::core::Allocation::width, dw::core::Requisition::width, and dw::core::Allocation::x.
Referenced by tellPosition1().
bool dw::oof::OOFFloatsMgr::collidesV (Float * vloat, Float * other, int * yReal) private
References dw::core::Requisition::ascent, DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, DBG_OBJ_MSGF, dw::core::Requisition::descent, ensureFloatSize(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), dw::oof::OOFFloatsMgr::Float::index, dw::oof::OOFFloatsMgr::Float::size, and dw::oof::OOFFloatsMgr::Float::yReal.
Referenced by tellPosition1().
bool dw::oof::OOFFloatsMgr::containerMustAdjustExtraSpace () virtual
Implements dw::oof::OutOfFlowMgr.
void dw::oof::OOFFloatsMgr::containerSizeChangedForChildren () virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::Widget::containerSizeChanged(), DBG_OBJ_ENTER0, DBG_OBJ_LEAVE, dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), leftFloats, rightFloats, and dw::oof::OOFFloatsMgr::SortedFloatsVector::size().
static int dw::oof::OOFFloatsMgr::createSubRefLeftFloat (int index) inline static private
Referenced by addWidgetOOF().
static int dw::oof::OOFFloatsMgr::createSubRefRightFloat (int index) inline static private
Referenced by addWidgetOOF().
bool dw::oof::OOFFloatsMgr::dealingWithSizeOfChild (core::Widget * child) virtual
Implements dw::oof::OutOfFlowMgr.
void dw::oof::OOFFloatsMgr::draw (core::View * view, core::Rectangle * area, core::DrawingContext * context) virtual
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, drawFloats(), dw::core::Rectangle::height, leftFloats, rightFloats, dw::core::Rectangle::width, dw::core::Rectangle::x, and dw::core::Rectangle::y.
void dw::oof::OOFFloatsMgr::drawFloats (SortedFloatsVector * list, core::View * view, core::Rectangle * area, core::DrawingContext * context) private
References container, dw::core::Widget::draw(), dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), dw::core::StackingProcessingContext::hasWidgetBeenProcessedAsInterruption(), dw::core::Widget::intersects(), and dw::oof::OOFFloatsMgr::SortedFloatsVector::size().
Referenced by draw().
void dw::oof::OOFFloatsMgr::ensureFloatSize (Float * vloat) private
References dw::core::Requisition::ascent, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSG, DBG_OBJ_MSGF, DBG_OBJ_SET_BOOL_O, DBG_OBJ_SET_NUM_O, dw::core::Requisition::descent, dw::oof::OOFFloatsMgr::Float::dirty, dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), dw::oof::OOFFloatsMgr::Float::size, dw::core::Widget::sizeRequest(), and dw::core::Requisition::width.
Referenced by calcFloatX(), collidesV(), getClearPosition(), getFloatHeight(), getFloatsSize(), sizeAllocateFloats(), and tellPosition1().
OOFFloatsMgr::Float * dw::oof::OOFFloatsMgr::findFloatByWidget (core::Widget * widget) private
References floatsByWidget.
Referenced by tellPosition1().
int dw::oof::OOFFloatsMgr::findTBInfo (int y) private
y is given relative to the container.
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, oofmIndex, tbInfos, and dw::oof::OOFFloatsMgr::TBInfo::y.
int dw::oof::OOFFloatsMgr::getAvailHeightOfChild (core::Widget * child, bool forceValue) virtual
Implements dw::oof::OutOfFlowMgr.
References lout::misc::notImplemented().
int dw::oof::OOFFloatsMgr::getAvailWidthOfChild (core::Widget * child, bool forceValue) virtual
Implements dw::oof::OutOfFlowMgr.
References lout::misc::notImplemented().
int dw::oof::OOFFloatsMgr::getBorder (Side side, int y, int h, OOFAwareWidget * lastGB, int lastExtIndex) private
References lout::misc::assertNotReached(), dw::core::style::StyleAttrs::boxOffsetX(), dw::core::style::StyleAttrs::boxRestWidth(), container, dw::oof::OOFFloatsMgr::Float::covers(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, DBG_OBJ_MSGF, dw::oof::OOFFloatsMgr::SortedFloatsVector::findFirst(), dw::oof::OOFFloatsMgr::Float::generator, dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), dw::oof::OOFAwareWidget::getGeneratorX(), dw::oof::OOFAwareWidget::getMaxGeneratorWidth(), dw::core::Widget::getStyle(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), LEFT, leftFloats, lout::misc::max(), oofmIndex, RIGHT, rightFloats, dw::oof::OOFFloatsMgr::Float::size, and dw::core::Requisition::width.
Referenced by getLeftBorder(), and getRightBorder().
int dw::oof::OOFFloatsMgr::getClearPosition (OOFAwareWidget * widget, Side side) private
References dw::core::Requisition::ascent, DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, DBG_OBJ_MSGF, dw::core::Requisition::descent, ensureFloatSize(), dw::oof::OOFFloatsMgr::SortedFloatsVector::findFloatIndex(), dw::oof::OOFFloatsMgr::Float::generator, dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), dw::oof::OOFAwareWidget::getGeneratorY(), LEFT, leftFloats, lout::misc::max(), oofmIndex, rightFloats, dw::oof::OOFFloatsMgr::Float::size, and dw::oof::OOFFloatsMgr::Float::yReal.
Referenced by getClearPosition().
int dw::oof::OOFFloatsMgr::getClearPosition (OOFAwareWidget * widget) virtual
Return value is relative to the calling generator (not container).
Implements dw::oof::OutOfFlowMgr.
References lout::misc::assertNotReached(), dw::core::style::StyleAttrs::clear, dw::core::style::CLEAR_BOTH, dw::core::style::CLEAR_LEFT, dw::core::style::CLEAR_NONE, dw::core::style::CLEAR_RIGHT, DBG_OBJ_ENTER, DBG_OBJ_LEAVE_VAL, getClearPosition(), dw::core::Widget::getStyle(), LEFT, lout::misc::max(), and RIGHT.
void dw::oof::OOFFloatsMgr::getExtremes (core::Extremes * cbExtr, int * oofMinWidth, int * oofMaxWidth) virtual
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, getFloatsExtremes(), LEFT, lout::misc::max(), dw::core::Extremes::maxWidth, dw::core::Extremes::minWidth, and RIGHT.
int dw::oof::OOFFloatsMgr::getFloatHeight (Side side, int y, int h, OOFAwareWidget * lastGB, int lastExtIndex) private
References dw::core::Requisition::ascent, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::core::Requisition::descent, ensureFloatSize(), dw::oof::OOFFloatsMgr::SortedFloatsVector::findFirst(), dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), LEFT, leftFloats, rightFloats, dw::oof::OOFFloatsMgr::Float::size, and dw::oof::OOFFloatsMgr::Float::yReal.
Referenced by getLeftFloatHeight(), and getRightFloatHeight().
static int dw::oof::OOFFloatsMgr::getFloatIndexFromSubRef (int ref) inline static private
Referenced by markSizeChange().
void dw::oof::OOFFloatsMgr::getFloatsExtremes (core::Extremes * cbExtr, Side side, int * minWidth, int * maxWidth) private
References dw::core::style::StyleAttrs::boxDiffWidth(), container, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::oof::OOFFloatsMgr::Float::generator, dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), dw::core::Widget::getExtremes(), dw::oof::OOFAwareWidget::getGeneratorWidth(), dw::core::Widget::getStyle(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), LEFT, leftFloats, lout::misc::max(), dw::core::Extremes::maxWidth, dw::core::Extremes::minWidth, rightFloats, and dw::oof::OOFFloatsMgr::SortedFloatsVector::size().
Referenced by getExtremes().
void dw::oof::OOFFloatsMgr::getFloatsListsAndSide (Float * vloat, SortedFloatsVector ** listSame, SortedFloatsVector ** listOpp, Side * side) private
References lout::misc::assertNotReached(), dw::core::style::FLOAT_LEFT, dw::core::style::FLOAT_RIGHT, dw::core::Widget::getStyle(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), LEFT, leftFloats, RIGHT, rightFloats, and dw::core::style::StyleAttrs::vloat.
Referenced by tellPosition1().
void dw::oof::OOFFloatsMgr::getFloatsSize (core::Requisition * cbReq, Side side, int * width, int * height) private
References dw::core::Requisition::ascent, calcFloatX(), container, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::core::Requisition::descent, ensureFloatSize(), dw::oof::OOFFloatsMgr::Float::generator, dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), LEFT, leftFloats, lout::misc::max(), rightFloats, dw::oof::OOFFloatsMgr::Float::size, dw::oof::OOFFloatsMgr::SortedFloatsVector::size(), dw::core::Requisition::width, and dw::oof::OOFFloatsMgr::Float::yReal.
Referenced by getSize().
Widget * dw::oof::OOFFloatsMgr::getFloatWidgetAtPoint (SortedFloatsVector * list, int x, int y, core::GettingWidgetAtPointContext * context) private
References dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), dw::core::Widget::getWidgetAtPoint(), dw::core::StackingProcessingContext::hasWidgetBeenProcessedAsInterruption(), and dw::oof::OOFFloatsMgr::SortedFloatsVector::size().
Referenced by getWidgetAtPoint().
int dw::oof::OOFFloatsMgr::getGBWidthForAllocation (Float * vloat) private
int dw::oof::OOFFloatsMgr::getLeftBorder (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Get the left border for the vertical position of y, for a height of h", based on floats; relative to the *container.
The border includes marging/border/padding of the calling textblock but is 0 if there is no float, so a caller should also consider other borders.
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_MSGF, getBorder(), and LEFT.
int dw::oof::OOFFloatsMgr::getLeftFloatHeight (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Assuming there is a float on the left side, return the rest height of it. y is relative to the container.
See also getLeftBorder().
Implements dw::oof::OutOfFlowMgr.
References getFloatHeight(), and LEFT.
int dw::oof::OOFFloatsMgr::getNumWidgets () virtual
Implements dw::oof::OutOfFlowMgr.
References leftFloats, rightFloats, and dw::oof::OOFFloatsMgr::SortedFloatsVector::size().
OOFFloatsMgr::TBInfo * dw::oof::OOFFloatsMgr::getOOFAwareWidget (OOFAwareWidget * widget) private
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, and getOOFAwareWidgetWhenRegistered().
Referenced by addWidgetInFlow(), addWidgetOOF(), markSizeChange(), and moveExternalIndices().
OOFFloatsMgr::TBInfo * dw::oof::OOFFloatsMgr::getOOFAwareWidgetWhenRegistered (OOFAwareWidget * widget) private
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, and tbInfosByOOFAwareWidget.
Referenced by getOOFAwareWidget(), and isOOFAwareWidgetRegistered().
int dw::oof::OOFFloatsMgr::getRightBorder (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Get the right border for the vertical position of y, for a height of h, based on floats; relative to the container.
See also getLeftBorder().
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_MSGF, getBorder(), and RIGHT.
int dw::oof::OOFFloatsMgr::getRightFloatHeight (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Assuming there is a float on the right side, return the rest height of it. y is relative to the container.
See also getLeftFloatHeight(), getLeftBorder().
Implements dw::oof::OutOfFlowMgr.
References getFloatHeight(), and RIGHT.
void dw::oof::OOFFloatsMgr::getSize (core::Requisition * cbReq, int * oofWidth, int * oofHeight) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::Widget::boxRestHeight(), dw::core::Widget::boxRestWidth(), container, DBG_OBJ_ENTER0, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, getFloatsSize(), LEFT, lout::misc::max(), and RIGHT.
Widget * dw::oof::OOFFloatsMgr::getWidget (int i) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), leftFloats, rightFloats, and dw::oof::OOFFloatsMgr::SortedFloatsVector::size().
Referenced by dw::oof::OOFFloatsMgr::Float::covers(), and dw::oof::OOFFloatsMgr::Float::intoStringBuffer().
Widget * dw::oof::OOFFloatsMgr::getWidgetAtPoint (int x, int y, core::GettingWidgetAtPointContext * context) virtual
Implements dw::oof::OutOfFlowMgr.
References getFloatWidgetAtPoint(), leftFloats, and rightFloats.
bool dw::oof::OOFFloatsMgr::hasFloat (Side side, int y, int h, OOFAwareWidget * lastGB, int lastExtIndex) private
References DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::oof::OOFFloatsMgr::SortedFloatsVector::findFirst(), LEFT, leftFloats, and rightFloats.
Referenced by hasFloatLeft(), and hasFloatRight().
bool dw::oof::OOFFloatsMgr::hasFloatLeft (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Return whether there is a float on the left side. y is relative to the container.
See also getLeftBorder().
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_MSGF, hasFloat(), and LEFT.
bool dw::oof::OOFFloatsMgr::hasFloatRight (int y, int h, OOFAwareWidget * lastGen, int lastExtIndex) virtual
Return whether there is a float on the right side. y is relative to the container.
See also hasFloatLeft(), getLeftBorder();
Implements dw::oof::OutOfFlowMgr.
References DBG_OBJ_MSGF, hasFloat(), and RIGHT.
bool dw::oof::OOFFloatsMgr::isOOFAwareWidgetRegistered (OOFAwareWidget * widget) inline private
References getOOFAwareWidgetWhenRegistered().
static bool dw::oof::OOFFloatsMgr::isSubRefLeftFloat (int ref) inline static private
Referenced by markSizeChange().
static bool dw::oof::OOFFloatsMgr::isSubRefRightFloat (int ref) inline static private
Referenced by markSizeChange().
void dw::oof::OOFFloatsMgr::markExtremesChange (int ref) virtual
Implements dw::oof::OutOfFlowMgr.
void dw::oof::OOFFloatsMgr::markSizeChange (int ref) virtual
Implements dw::oof::OutOfFlowMgr.
References lout::misc::assertNotReached(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, DBG_OBJ_SET_BOOL_O, dw::oof::OOFFloatsMgr::Float::dirty, dw::oof::OOFFloatsMgr::Float::generator, dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), getFloatIndexFromSubRef(), getOOFAwareWidget(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), dw::core::Widget::getWidgetReference(), dw::oof::OOFFloatsMgr::TBInfo::index, isSubRefLeftFloat(), isSubRefRightFloat(), leftFloats, dw::core::WidgetReference::parentRef, rightFloats, and tbInfos.
bool dw::oof::OOFFloatsMgr::mayAffectBordersAtAll () virtual
Implements dw::oof::OutOfFlowMgr.
void dw::oof::OOFFloatsMgr::moveExternalIndices (lout::container::typed::Vector< Float > * list, int oldStartIndex, int diff) private
References DBG_OBJ_SET_NUM_O, dw::oof::OOFFloatsMgr::Float::externalIndex, lout::container::typed::Vector< T >::get(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), and lout::container::typed::Collection< T >::size().
Referenced by moveExternalIndices().
void dw::oof::OOFFloatsMgr::moveExternalIndices (OOFAwareWidget * generatingBlock, int oldStartIndex, int diff) virtual
Implements dw::oof::OutOfFlowMgr.
References getOOFAwareWidget(), dw::oof::OOFFloatsMgr::TBInfo::leftFloats, moveExternalIndices(), and dw::oof::OOFFloatsMgr::TBInfo::rightFloats.
void dw::oof::OOFFloatsMgr::sizeAllocateEnd (OOFAwareWidget * caller) virtual
Implements dw::oof::OutOfFlowMgr.
References container, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, LEFT, RIGHT, and sizeAllocateFloats().
void dw::oof::OOFFloatsMgr::sizeAllocateFloats (Side side) private
References dw::core::Allocation::ascent, dw::core::Requisition::ascent, calcFloatX(), containerAllocation, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, dw::core::Allocation::descent, dw::core::Requisition::descent, ensureFloatSize(), dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), LEFT, leftFloats, rightFloats, dw::oof::OOFFloatsMgr::Float::size, dw::oof::OOFFloatsMgr::SortedFloatsVector::size(), dw::core::Widget::sizeAllocate(), dw::core::Allocation::width, dw::core::Requisition::width, dw::core::Allocation::x, dw::core::Allocation::y, and dw::oof::OOFFloatsMgr::Float::yReal.
Referenced by sizeAllocateEnd().
void dw::oof::OOFFloatsMgr::sizeAllocateStart (OOFAwareWidget * caller, core::Allocation * allocation) virtual
Implements dw::oof::OutOfFlowMgr.
References dw::core::Allocation::ascent, container, containerAllocation, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, dw::core::Allocation::descent, dw::core::Allocation::width, dw::core::Allocation::x, and dw::core::Allocation::y.
void dw::oof::OOFFloatsMgr::tellIncompletePosition1 (core::Widget * generator, core::Widget * widget, int x, int y) virtual
Implements dw::oof::OutOfFlowMgr.
References lout::misc::notImplemented().
void dw::oof::OOFFloatsMgr::tellIncompletePosition2 (core::Widget * generator, core::Widget * widget, int x, int y) virtual
Implements dw::oof::OutOfFlowMgr.
References lout::misc::notImplemented().
void dw::oof::OOFFloatsMgr::tellPosition1 (core::Widget * widget, int x, int y) virtual
Called before tellPosition2, see there for more.
Implements dw::oof::OutOfFlowMgr.
References collidesH(), collidesV(), DBG_OBJ_ENTER, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, DBG_OBJ_SET_NUM_O, ensureFloatSize(), findFloatByWidget(), dw::oof::OOFFloatsMgr::SortedFloatsVector::findLastBeforeSideSpanningIndex(), dw::oof::OOFFloatsMgr::SortedFloatsVector::get(), getFloatsListsAndSide(), dw::oof::OOFFloatsMgr::WidgetInfo::getWidget(), dw::oof::OOFFloatsMgr::Float::index, dw::oof::OOFFloatsMgr::Float::sideSpanningIndex, dw::oof::OOFFloatsMgr::Float::yReal, and dw::oof::OOFFloatsMgr::Float::yReq.
void dw::oof::OOFFloatsMgr::tellPosition2 (core::Widget * widget, int x, int y) virtual
Called after tellPosition1.
An implementation should only implement either tellPosition1 or tellPosition2. Coordinates are relative to the container.
Implements dw::oof::OutOfFlowMgr.
Friends And Related Function Documentation
friend class WidgetInfo friend
Member Data Documentation
OOFAwareWidget* dw::oof::OOFFloatsMgr::container private
Referenced by calcFloatX(), drawFloats(), getBorder(), getFloatsExtremes(), getFloatsSize(), getSize(), OOFFloatsMgr(), sizeAllocateEnd(), and sizeAllocateStart().
core::Allocation dw::oof::OOFFloatsMgr::containerAllocation private
Referenced by OOFFloatsMgr(), sizeAllocateFloats(), and sizeAllocateStart().
lout::container::typed::HashTable<lout::object::TypedPointer <dw::core::Widget>, Float>* dw::oof::OOFFloatsMgr::floatsByWidget private
Referenced by addWidgetOOF(), findFloatByWidget(), OOFFloatsMgr(), and ~OOFFloatsMgr().
int dw::oof::OOFFloatsMgr::lastLeftTBIndex private
Referenced by OOFFloatsMgr().
int dw::oof::OOFFloatsMgr::lastRightTBIndex private
Referenced by OOFFloatsMgr().
SortedFloatsVector* dw::oof::OOFFloatsMgr::leftFloats private
Referenced by addWidgetOOF(), containerSizeChangedForChildren(), draw(), getBorder(), getClearPosition(), getFloatHeight(), getFloatsExtremes(), getFloatsListsAndSide(), getFloatsSize(), getNumWidgets(), getWidget(), getWidgetAtPoint(), hasFloat(), markSizeChange(), OOFFloatsMgr(), sizeAllocateFloats(), ~OOFFloatsMgr(), and dw::oof::OOFFloatsMgr::TBInfo::~TBInfo().
int dw::oof::OOFFloatsMgr::leftFloatsMark private
Referenced by OOFFloatsMgr().
int dw::oof::OOFFloatsMgr::oofmIndex private
Referenced by calcFloatX(), dw::oof::OOFFloatsMgr::TBInfo::ComparePosition::compare(), findTBInfo(), getBorder(), getClearPosition(), and OOFFloatsMgr().
SortedFloatsVector * dw::oof::OOFFloatsMgr::rightFloats private
Referenced by addWidgetOOF(), containerSizeChangedForChildren(), draw(), getBorder(), getClearPosition(), getFloatHeight(), getFloatsExtremes(), getFloatsListsAndSide(), getFloatsSize(), getNumWidgets(), getWidget(), getWidgetAtPoint(), hasFloat(), markSizeChange(), OOFFloatsMgr(), sizeAllocateFloats(), ~OOFFloatsMgr(), and dw::oof::OOFFloatsMgr::TBInfo::~TBInfo().
int dw::oof::OOFFloatsMgr::rightFloatsMark private
Referenced by OOFFloatsMgr().
lout::container::typed::Vector<TBInfo>* dw::oof::OOFFloatsMgr::tbInfos private
Referenced by addWidgetInFlow(), findTBInfo(), markSizeChange(), OOFFloatsMgr(), and ~OOFFloatsMgr().
lout::container::typed::HashTable<lout::object::TypedPointer<OOFAwareWidget>, TBInfo>* dw::oof::OOFFloatsMgr::tbInfosByOOFAwareWidget private
Referenced by addWidgetInFlow(), getOOFAwareWidgetWhenRegistered(), OOFFloatsMgr(), and ~OOFFloatsMgr().
The documentation for this class was generated from the following files:
dw/ooffloatsmgr.hh
dw/ooffloatsmgr.cc