Dillo: dw::core::ui::RadioButtonResource::GroupIterator Class Reference
dw::core::ui::RadioButtonResource::GroupIterator Class Reference abstract
#include <ui.hh>
Public Member Functions
virtual bool hasNext ()=0
virtual RadioButtonResource * getNext ()=0
virtual void unref ()=0
Protected Member Functions
GroupIterator ()
virtual ~GroupIterator ()
Constructor & Destructor Documentation
dw::core::ui::RadioButtonResource::GroupIterator::GroupIterator () inline protected
dw::core::ui::RadioButtonResource::GroupIterator::~GroupIterator () protected virtual
Member Function Documentation
virtual RadioButtonResource* dw::core::ui::RadioButtonResource::GroupIterator::getNext () pure virtual
Implemented in dw::fltk::ui::FltkRadioButtonResource::Group::FltkGroupIterator.
Referenced by form::Form::RadioButtonResourceDecorator::getValue().
virtual bool dw::core::ui::RadioButtonResource::GroupIterator::hasNext () pure virtual
Implemented in dw::fltk::ui::FltkRadioButtonResource::Group::FltkGroupIterator.
Referenced by form::Form::RadioButtonResourceDecorator::getValue().
virtual void dw::core::ui::RadioButtonResource::GroupIterator::unref () pure virtual
Implemented in dw::fltk::ui::FltkRadioButtonResource::Group::FltkGroupIterator.
Referenced by form::Form::RadioButtonResourceDecorator::getValue().
The documentation for this class was generated from the following files:
dw/ui.hh
dw/ui.cc