Dillo: dw::core::style::Tooltip Class Reference
dw::core::style::Tooltip Class Reference
#include <style.hh>
Public Member Functions
void ref ()
void unref ()
virtual void onEnter ()
virtual void onLeave ()
virtual void onMotion ()
Public Member Functions inherited from dw::core::style::TooltipAttrs
TooltipAttrs (const char *text)
Public Member Functions inherited from lout::object::String
String (const char *str)
~String ()
Public Member Functions inherited from lout::object::ConstString
ConstString (const char *str)
bool equals (Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
int compareTo (Comparable *other)
Compare two objects, this and other.
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * chars ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Static Public Member Functions
static Tooltip * create (dw::core::Layout *layout, const char *text)
Static Public Member Functions inherited from lout::object::ConstString
static int hashValue (const char *str)
Protected Member Functions
Tooltip (const char *text)
Private Attributes
int refCount
Additional Inherited Members
Protected Attributes inherited from lout::object::ConstString
const char * str
Detailed Description
See also
dw::core::style
Constructor & Destructor Documentation
dw::core::style::Tooltip::Tooltip (const char * text) inline protected
Member Function Documentation
Tooltip * dw::core::style::Tooltip::create (dw::core::Layout * layout, const char * text) static
References dw::core::Layout::createTooltip().
virtual void dw::core::style::Tooltip::onEnter () inline virtual
Reimplemented in dw::fltk::FltkTooltip.
Referenced by dw::core::Widget::enterNotifyImpl(), and dw::Textblock::motionNotifyImpl().
virtual void dw::core::style::Tooltip::onLeave () inline virtual
Reimplemented in dw::fltk::FltkTooltip.
Referenced by dw::core::Widget::leaveNotifyImpl(), dw::Textblock::leaveNotifyImpl(), and dw::Textblock::motionNotifyImpl().
virtual void dw::core::style::Tooltip::onMotion () inline virtual
Reimplemented in dw::fltk::FltkTooltip.
Referenced by dw::Textblock::motionNotifyImpl().
void dw::core::style::Tooltip::ref () inline
void dw::core::style::Tooltip::unref () inline
Member Data Documentation
int dw::core::style::Tooltip::refCount private
The documentation for this class was generated from the following files:
dw/style.hh
dw/style.cc