Dillo: dw::fltk::FltkFont::FontFamily Class Reference
dw::fltk::FltkFont::FontFamily Class Reference
Public Member Functions
FontFamily (Fl_Font fontNormal, Fl_Font fontBold, Fl_Font fontItalic, Fl_Font fontBoldItalic)
void set (Fl_Font, int attrs)
Fl_Font get (int attrs)
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Private Attributes
Fl_Font font [4]
Constructor & Destructor Documentation
dw::fltk::FltkFont::FontFamily::FontFamily (Fl_Font fontNormal, Fl_Font fontBold, Fl_Font fontItalic, Fl_Font fontBoldItalic)
Member Function Documentation
Fl_Font dw::fltk::FltkFont::FontFamily::get (int attrs)
Referenced by dw::fltk::FltkFont::FltkFont(), and dw::fltk::FltkFont::get().
void dw::fltk::FltkFont::FontFamily::set (Fl_Font f, int attrs)
Referenced by dw::fltk::FltkFont::initSystemFonts().
Member Data Documentation
Fl_Font dw::fltk::FltkFont::FontFamily::font[4] private
The documentation for this class was generated from the following files:
dw/fltkplatform.hh
dw/fltkplatform.cc