Dillo: dw::fltk::FltkPreviewWindow Class Reference
dw::fltk::FltkPreviewWindow Class Reference
#include <fltkpreview.hh>
Public Member Functions
FltkPreviewWindow (dw::core::Layout *layout)
~FltkPreviewWindow ()
void reallocate ()
void showWindow ()
void hideWindow ()
void scrollTo (int mouseX, int mouseY)
Private Types
enum { BORDER_WIDTH = 2 }
Private Attributes
FltkPreview * preview
int posX
int posY
Member Enumeration Documentation
anonymous enum private
Enumerator
BORDER_WIDTH
Constructor & Destructor Documentation
dw::fltk::FltkPreviewWindow::FltkPreviewWindow (dw::core::Layout * layout)
References BORDER_WIDTH, and preview.
dw::fltk::FltkPreviewWindow::~FltkPreviewWindow ()
Member Function Documentation
void dw::fltk::FltkPreviewWindow::hideWindow ()
Referenced by dw::fltk::FltkPreviewButton::handle().
void dw::fltk::FltkPreviewWindow::reallocate ()
References BORDER_WIDTH, dw::fltk::FltkViewBase::canvasHeight, dw::fltk::FltkViewBase::canvasWidth, posX, posY, preview, dw::fltk::misc::screenHeight(), dw::fltk::misc::screenWidth(), dw::fltk::FltkPreview::scrollHeight, dw::fltk::FltkPreview::scrollWidth, dw::fltk::FltkPreview::scrollX, dw::fltk::FltkPreview::scrollY, dw::fltk::FltkPreview::translateCanvasXToViewX(), dw::fltk::FltkPreview::translateCanvasYToViewY(), and dw::fltk::misc::warpPointer().
Referenced by showWindow().
void dw::fltk::FltkPreviewWindow::scrollTo (int mouseX, int mouseY)
References BORDER_WIDTH, posX, posY, preview, dw::fltk::FltkPreview::scrollHeight, dw::core::Layout::scrollPosChanged(), dw::fltk::FltkPreview::scrollWidth, dw::fltk::FltkPreview::scrollX, dw::fltk::FltkPreview::scrollY, dw::fltk::FltkViewBase::theLayout, dw::fltk::FltkPreview::translateViewXToCanvasX(), and dw::fltk::FltkPreview::translateViewYToCanvasY().
Referenced by dw::fltk::FltkPreviewButton::handle().
void dw::fltk::FltkPreviewWindow::showWindow ()
References reallocate().
Referenced by dw::fltk::FltkPreviewButton::handle().
Member Data Documentation
int dw::fltk::FltkPreviewWindow::posX private
Referenced by reallocate(), and scrollTo().
int dw::fltk::FltkPreviewWindow::posY private
Referenced by reallocate(), and scrollTo().
FltkPreview* dw::fltk::FltkPreviewWindow::preview private
Referenced by FltkPreviewWindow(), reallocate(), and scrollTo().
The documentation for this class was generated from the following files:
dw/fltkpreview.hh
dw/fltkpreview.cc