Dillo: lout::misc::SimpleVector< T > Class Template Reference
lout::misc::SimpleVector< T > Class Template Reference
Simple (simpler than container::untyped::Vector and container::typed::Vector) template based vector.
#include <misc.hh>
Public Member Functions
SimpleVector (int initAlloc=1)
SimpleVector (const SimpleVector &o)
~SimpleVector ()
int size () const
Return the number of elements put into this vector.
bool empty () const
T * getArray () const
T * detachArray ()
void increase ()
Increase the vector size by one.
void setSize (int newSize)
Set the size explicitly.
void setSize (int newSize, T t)
Set the size explicitly and initialize new values.
T * getRef (int i) const
Return the reference of one element.
T get (int i) const
Return the one element, explicitly.
T * getFirstRef () const
Return the reference of the first element (convenience method).
T getFirst () const
Return the first element, explicitly.
T * getLastRef () const
Return the reference of the last element (convenience method).
T getLast () const
Return the last element, explicitly.
void set (int i, T t)
Store an object in the vector.
void setLast (T t)
Store an object at the end of the vector.
void copyTo (SimpleVector< T > *dest, int thisStart=0, int thisLast=-1, int destStart=0)
Copies some elements into another vector of the same type.
Private Member Functions
void resize ()
Private Attributes
T * array
int num
int numAlloc
Detailed Description
template<class T>
class lout::misc::SimpleVector< T >
Simple (simpler than container::untyped::Vector and container::typed::Vector) template based vector.
Constructor & Destructor Documentation
template<class T> lout::misc::SimpleVector< T >::SimpleVector (int initAlloc = 1) inline
template<class T> lout::misc::SimpleVector< T >::SimpleVector (const SimpleVector< T > & o) inline
template<class T> lout::misc::SimpleVector< T >::~SimpleVector () inline
Member Function Documentation
template<class T> void lout::misc::SimpleVector< T >::copyTo (SimpleVector< T > * dest, int thisStart = 0, int thisLast = -1, int destStart = 0) inline
Copies some elements into another vector of the same type.
Cannot be used to copy elements within one vector. (For this, it would have to be extended to copy backwards in some cases.)
template<class T> T* lout::misc::SimpleVector< T >::detachArray () inline
Referenced by dw::Hyphenator::hyphenateWord(), and dw::Trie::load().
template<class T> bool lout::misc::SimpleVector< T >::empty () const inline
template<class T> T lout::misc::SimpleVector< T >::get (int i) const inline
Return the one element, explicitly.
The element is copied, so for complex elements, you should rather used misc::SimpleVector::getRef.
Referenced by dw::Table::actuallyCalcCellSizes(), dw::Table::calcAdjustmentWidthSpanMultiCols(), dw::Table::calcExtremesSpanMultiCols(), dw::Table::childDefined(), lout::misc::SimpleVector< dw::Trie::TrieNode >::copyTo(), dw::Table::forceCalcCellSizes(), dw::Table::forceCalcColumnExtremes(), dw::AlignedTextblock::List::getTextblock(), dw::AlignedTextblock::List::getValue(), dw::Hyphenator::hyphenateSingleWord(), dw::Table::setCumHeight(), lout::misc::ZoneAllocator::zoneAlloc(), and lout::misc::ZoneAllocator::zoneFree().
template<class T> T* lout::misc::SimpleVector< T >::getArray () const inline
Referenced by dw::Hyphenator::insertPattern().
template<class T> T lout::misc::SimpleVector< T >::getFirst () const inline
Return the first element, explicitly.
template<class T> T* lout::misc::SimpleVector< T >::getFirstRef () const inline
Return the reference of the first element (convenience method).
template<class T> T lout::misc::SimpleVector< T >::getLast () const inline
Return the last element, explicitly.
template<class T> T* lout::misc::SimpleVector< T >::getLastRef () const inline
Return the reference of the last element (convenience method).
Referenced by dw::Textblock::calcPenaltyIndexForNewLine(), and dw::Trie::load().
template<class T> T* lout::misc::SimpleVector< T >::getRef (int i) const inline
Return the reference of one element.
See also
misc::SimpleVector::get
Referenced by dw::Textblock::lineYOffsetCanvas(), and dw::Textblock::lineYOffsetWidget().
template<class T> void lout::misc::SimpleVector< T >::increase () inline
Increase the vector size by one.
May be necessary before calling misc::SimpleVector::set.
Referenced by dw::Table::forceCalcColumnExtremes(), dw::Hyphenator::hyphenateSingleWord(), dw::Trie::load(), and lout::misc::ZoneAllocator::zoneAlloc().
template<class T> void lout::misc::SimpleVector< T >::resize () inline private
Referenced by lout::misc::SimpleVector< dw::Trie::TrieNode >::setSize(), and lout::misc::SimpleVector< dw::Trie::TrieNode >::SimpleVector().
template<class T> void lout::misc::SimpleVector< T >::set (int i, T t) inline
Store an object in the vector.
Unlike in container::untyped::Vector and container::typed::Vector, you have to care about the size, so a call to misc::SimpleVector::increase or misc::SimpleVector::setSize may be necessary before.
Referenced by dw::Table::actuallyCalcCellSizes(), dw::Table::apportion2(), lout::misc::SimpleVector< dw::Trie::TrieNode >::copyTo(), dw::Hyphenator::hyphenateSingleWord(), dw::Hyphenator::insertPattern(), dw::Table::setCumHeight(), lout::misc::SimpleVector< dw::Trie::TrieNode >::setSize(), dw::AlignedTextblock::List::setValue(), and lout::misc::ZoneAllocator::zoneAlloc().
template<class T> void lout::misc::SimpleVector< T >::setLast (T t) inline
Store an object at the end of the vector.
Referenced by dw::Table::forceCalcColumnExtremes().
template<class T> void lout::misc::SimpleVector< T >::setSize (int newSize) inline
Set the size explicitly.
May be necessary before calling misc::SimpleVector::set.
Referenced by dw::Table::actuallyCalcCellSizes(), dw::Table::apportion2(), dw::Table::forceCalcCellSizes(), dw::Hyphenator::hyphenateSingleWord(), lout::misc::SimpleVector< dw::Trie::TrieNode >::increase(), dw::Hyphenator::insertPattern(), lout::misc::SimpleVector< dw::Trie::TrieNode >::setSize(), and lout::misc::ZoneAllocator::zoneFree().
template<class T> void lout::misc::SimpleVector< T >::setSize (int newSize, T t) inline
Set the size explicitly and initialize new values.
May be necessary before calling misc::SimpleVector::set.
template<class T> int lout::misc::SimpleVector< T >::size () const inline
Return the number of elements put into this vector.
Referenced by dw::Table::actuallyCalcCellSizes(), dw::Textblock::calcPenaltyIndexForNewLine(), dw::Table::childDefined(), lout::misc::SimpleVector< dw::Trie::TrieNode >::copyTo(), lout::misc::SimpleVector< dw::Trie::TrieNode >::empty(), dw::Table::forceCalcColumnExtremes(), dw::Hyphenator::hyphenateSingleWord(), dw::Hyphenator::hyphenateWord(), dw::Trie::load(), dw::AlignedTextblock::List::size(), dw::Textblock::Textblock(), lout::misc::ZoneAllocator::zoneAlloc(), and lout::misc::ZoneAllocator::zoneFree().
Member Data Documentation
template<class T> T* lout::misc::SimpleVector< T >::array private
Referenced by lout::misc::SimpleVector< dw::Trie::TrieNode >::detachArray(), lout::misc::SimpleVector< dw::Trie::TrieNode >::getArray(), lout::misc::SimpleVector< dw::Trie::TrieNode >::getFirstRef(), and lout::misc::SimpleVector< dw::Trie::TrieNode >::SimpleVector().
template<class T> int lout::misc::SimpleVector< T >::num private
Referenced by lout::misc::SimpleVector< dw::Trie::TrieNode >::setSize(), lout::misc::SimpleVector< dw::Trie::TrieNode >::SimpleVector(), and lout::misc::SimpleVector< dw::Trie::TrieNode >::size().
template<class T> int lout::misc::SimpleVector< T >::numAlloc private
Referenced by lout::misc::SimpleVector< dw::Trie::TrieNode >::SimpleVector().
The documentation for this class was generated from the following file:
lout/misc.hh