Dillo: dw::Trie Class Reference
dw::Trie Class Reference
#include <hyphenator.hh>
Classes
struct TrieNode
Public Member Functions
Trie (TrieNode *array=NULL, int size=0, bool freeArray=false, lout::misc::ZoneAllocator *dataZone=NULL)
~Trie ()
bool validState (int state)
const char * getData (unsigned char c, int *state)
void save (FILE *file)
int load (FILE *file)
Static Public Attributes
static const int root = 0
Private Attributes
TrieNode * array
int size
bool freeArray
lout::misc::ZoneAllocator * dataZone
Constructor & Destructor Documentation
dw::Trie::Trie (TrieNode * array = NULL, int size = 0, bool freeArray = false, lout::misc::ZoneAllocator * dataZone = NULL)
dw::Trie::~Trie ()
Member Function Documentation
const char* dw::Trie::getData (unsigned char c, int * state) inline
References dw::Trie::TrieNode::c, dw::Trie::TrieNode::data, dw::Trie::TrieNode::next, and validState().
int dw::Trie::load (FILE * file)
References lout::misc::SimpleVector< T >::detachArray(), lout::misc::SimpleVector< T >::getLastRef(), lout::misc::SimpleVector< T >::increase(), LEN, and lout::misc::SimpleVector< T >::size().
void dw::Trie::save (FILE * file)
References dw::Trie::TrieNode::c, dw::Trie::TrieNode::data, and dw::Trie::TrieNode::next.
Referenced by dw::Hyphenator::saveTrie().
bool dw::Trie::validState (int state) inline
References size.
Referenced by getData().
Member Data Documentation
TrieNode* dw::Trie::array private
lout::misc::ZoneAllocator* dw::Trie::dataZone private
bool dw::Trie::freeArray private
const int dw::Trie::root = 0 static
int dw::Trie::size private
Referenced by validState().
The documentation for this class was generated from the following files:
dw/hyphenator.hh
dw/hyphenator.cc