Dillo: lout::signal::ObservedObject Class Reference
lout::signal::ObservedObject Class Reference
An observed object has a signal emitter, which tells the receivers, when the object is deleted.
#include <signal.hh>
Classes
class DeletionEmitter
class DeletionReceiver
Public Member Functions
virtual ~ObservedObject ()
void connectDeletion (DeletionReceiver *receiver)
Private Attributes
DeletionEmitter deletionEmitter
Detailed Description
An observed object has a signal emitter, which tells the receivers, when the object is deleted.
Constructor & Destructor Documentation
lout::signal::ObservedObject::~ObservedObject () virtual
Member Function Documentation
void lout::signal::ObservedObject::connectDeletion (DeletionReceiver * receiver) inline
References lout::signal::ObservedObject::DeletionEmitter::connectDeletion().
Referenced by main(), and solution3().
Member Data Documentation
DeletionEmitter lout::signal::ObservedObject::deletionEmitter private
The documentation for this class was generated from the following files:
lout/signal.hh
lout/signal.cc