Dillo: dw::fltk::ui::FltkListResource Class Reference
dw::fltk::ui::FltkListResource Class Reference
#include <fltkui.hh>
Public Member Functions
FltkListResource (FltkPlatform *platform, core::ui::ListResource::SelectionMode selectionMode, int rows)
~FltkListResource ()
void addItem (const char *str, bool enabled, bool selected)
void setItem (int index, bool selected)
void pushGroup (const char *name, bool enabled)
void popGroup ()
void sizeRequest (core::Requisition *requisition)
bool isSelected (int index)
Public Member Functions inherited from dw::fltk::ui::FltkSelectionResource< dw::core::ui::ListResource >
FltkSelectionResource (FltkPlatform *platform)
dw::core::Iterator * iterator (dw::core::Content::Type mask, bool atEnd)
Public Member Functions inherited from dw::fltk::ui::FltkSpecificResource< dw::core::ui::ListResource >
FltkSpecificResource (FltkPlatform *platform)
~FltkSpecificResource ()
void sizeAllocate (core::Allocation *allocation)
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void setStyle (core::style::Style *style)
bool isEnabled ()
void setEnabled (bool enabled)
Public Member Functions inherited from dw::core::ui::Resource
Resource ()
virtual ~Resource ()
virtual void getExtremes (Extremes *extremes)
virtual int getAvailWidthOfChild (Widget *child, bool forceValue)
virtual int getAvailHeightOfChild (Widget *child, bool forceValue)
virtual void correctRequisitionOfChild (Widget *child, Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
virtual void correctExtremesOfChild (Widget *child, Extremes *extremes, bool useAdjustmentWidth)
virtual void containerSizeChangedForChildren ()
virtual void setDisplayed (bool displayed)
void connectActivate (ActivateReceiver *receiver)
void connectClicked (ClickedReceiver *receiver)
Public Member Functions inherited from dw::fltk::ui::FltkResource
~FltkResource ()
virtual void attachView (FltkView *view)
virtual void detachView (FltkView *view)
void sizeAllocate (core::Allocation *allocation)
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void setStyle (core::style::Style *style)
bool isEnabled ()
void setEnabled (bool enabled)
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions
Fl_Widget * createNewWidget (core::Allocation *allocation)
void setWidgetStyle (Fl_Widget *widget, core::style::Style *style)
int getNumberOfItems ()
int getMaxItemWidth ()
Protected Member Functions inherited from dw::fltk::ui::FltkSelectionResource< dw::core::ui::ListResource >
virtual bool setSelectedItems ()
Protected Member Functions inherited from dw::core::ui::Resource
void queueResize (bool extremesChanged)
virtual Embed * getEmbed ()
virtual void setEmbed (Embed *embed)
void emitActivate ()
void emitClicked (EventButton *event)
Protected Member Functions inherited from dw::fltk::ui::FltkResource
FltkResource (FltkPlatform *platform)
void init (FltkPlatform *platform)
void setDisplayed (bool displayed)
bool displayed ()
Private Member Functions
void * newItem (const char *str, bool enabled, bool selected)
Static Private Member Functions
static void widgetCallback (Fl_Widget *widget, void *data)
Private Attributes
int currDepth
int colWidths [4]
int showRows
ListResource::SelectionMode mode
Additional Inherited Members
Public Types inherited from dw::core::ui::ListResource
enum SelectionMode { SELECTION_EXACTLY_ONE, SELECTION_EXACTLY_ONE_BY_USER, SELECTION_AT_MOST_ONE, SELECTION_MULTIPLE }
Protected Attributes inherited from dw::fltk::ui::FltkResource
FltkView * view
Fl_Widget * widget
core::Allocation allocation
FltkPlatform * platform
core::style::Style * style
Constructor & Destructor Documentation
dw::fltk::ui::FltkListResource::FltkListResource (FltkPlatform * platform, core::ui::ListResource::SelectionMode selectionMode, int rows)
References dw::fltk::ui::FltkResource::init(), mode, and showRows.
dw::fltk::ui::FltkListResource::~FltkListResource ()
Member Function Documentation
void dw::fltk::ui::FltkListResource::addItem (const char * str, bool enabled, bool selected) virtual
Implements dw::fltk::ui::FltkSelectionResource< dw::core::ui::ListResource >.
References newItem().
Fl_Widget * dw::fltk::ui::FltkListResource::createNewWidget (core::Allocation * allocation) protected virtual
Implements dw::fltk::ui::FltkResource.
References dw::core::Allocation::ascent, colWidths, dw::core::Allocation::descent, mode, dw::core::ui::ListResource::SELECTION_MULTIPLE, widgetCallback(), dw::core::Allocation::width, dw::core::Allocation::x, and dw::core::Allocation::y.
int dw::fltk::ui::FltkListResource::getMaxItemWidth () protected
References dw::fltk::ui::FltkResource::widget.
Referenced by sizeRequest().
int dw::fltk::ui::FltkListResource::getNumberOfItems () protected virtual
Implements dw::core::ui::SelectionResource.
References dw::fltk::ui::FltkResource::widget.
bool dw::fltk::ui::FltkListResource::isSelected (int index) virtual
Implements dw::core::ui::SelectionResource.
References dw::fltk::ui::FltkResource::widget.
void * dw::fltk::ui::FltkListResource::newItem (const char * str, bool enabled, bool selected) private
References currDepth, dw::core::ui::Resource::queueResize(), showRows, and dw::fltk::ui::FltkResource::widget.
Referenced by addItem(), popGroup(), and pushGroup().
void dw::fltk::ui::FltkListResource::popGroup () virtual
Implements dw::fltk::ui::FltkSelectionResource< dw::core::ui::ListResource >.
References currDepth, newItem(), and dw::fltk::ui::FltkResource::widget.
void dw::fltk::ui::FltkListResource::pushGroup (const char * name, bool enabled) virtual
Implements dw::fltk::ui::FltkSelectionResource< dw::core::ui::ListResource >.
References currDepth, and newItem().
void dw::fltk::ui::FltkListResource::setItem (int index, bool selected) virtual
Implements dw::fltk::ui::FltkSelectionResource< dw::core::ui::ListResource >.
References dw::fltk::ui::FltkResource::widget.
void dw::fltk::ui::FltkListResource::setWidgetStyle (Fl_Widget * widget, core::style::Style * style) protected virtual
Reimplemented from dw::fltk::ui::FltkResource.
References colWidths, and dw::fltk::ui::FltkResource::setWidgetStyle().
void dw::fltk::ui::FltkListResource::sizeRequest (core::Requisition * requisition) virtual
Implements dw::core::ui::Resource.
References dw::core::Requisition::ascent, DBG_OBJ_ENTER0, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::core::Requisition::descent, dw::core::style::Font::descent, dw::core::style::StyleAttrs::font, getMaxItemWidth(), showRows, dw::fltk::ui::FltkResource::style, dw::fltk::ui::FltkResource::widget, and dw::core::Requisition::width.
void dw::fltk::ui::FltkListResource::widgetCallback (Fl_Widget * widget, void * data) static private
Referenced by createNewWidget().
Member Data Documentation
int dw::fltk::ui::FltkListResource::colWidths[4] private
Referenced by createNewWidget(), and setWidgetStyle().
int dw::fltk::ui::FltkListResource::currDepth private
Referenced by newItem(), popGroup(), and pushGroup().
ListResource::SelectionMode dw::fltk::ui::FltkListResource::mode private
Referenced by createNewWidget(), and FltkListResource().
int dw::fltk::ui::FltkListResource::showRows private
Referenced by FltkListResource(), newItem(), and sizeRequest().
The documentation for this class was generated from the following files:
dw/fltkui.hh
dw/fltkui.cc