Dillo: lout::object::Object Class Reference
lout::object::Object Class Reference
This is the base class for many other classes, which defines very common virtual methods.
#include <object.hh>
Public Member Functions
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Detailed Description
This is the base class for many other classes, which defines very common virtual methods.
For convenience, none of them are abstract, but they must be defined, when they are needed, especially for containers.
Constructor & Destructor Documentation
lout::object::Object::~Object () virtual
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
Member Function Documentation
Object * lout::object::Object::clone () virtual
Return an exact copy of the object.
Reimplemented in dw::core::CharIterator, dw::core::DeepIterator, dw::core::EmptyIterator, and dw::SimpleContainer::SimpleContainerIterator.
References lout::misc::assertNotReached().
Referenced by dw::core::Iterator::cloneIterator().
bool lout::object::Object::equals (Object * other) virtual
Returns, whether two objects are equal.
The caller should ensure, that this and the object have the same class; this makes casting of "other" safe. Typically, an implementation should check this == other first, the caller can assume a fast implementation.
Reimplemented in dw::core::style::ColorAttrs, dw::core::style::FontAttrs, dw::core::style::StyleAttrs, lout::container::typed::Collection< T >, lout::container::typed::Collection< dw::oof::OOFPositionedMgr::Child >, lout::container::typed::Collection< dw::core::style::StyleAttrs >, lout::container::typed::Collection< dw::fltk::FltkImgbuf >, lout::container::typed::Collection< lout::object::lout::object::String >, lout::container::typed::Collection< dw::core::Rectangle >, lout::container::typed::Collection< object::lout::object::ConstString >, lout::container::typed::Collection< lout::object::String >, lout::container::typed::Collection< dw::ImageMapsList::ImageMap::ShapeAndLink >, lout::container::typed::Collection< Float >, lout::container::typed::Collection< lout::signal::Receiver >, lout::container::typed::Collection< lout::object::TypedPointer< dw::core::Widget > >, lout::container::typed::Collection< lout::object::Object >, lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::ImgRenderer > >, lout::container::typed::Collection< form::Form::FormClickedReceiver >, lout::container::typed::Collection< lout::signal::Emitter >, lout::container::typed::Collection< dw::core::Widget >, lout::container::typed::Collection< dw::core::style::ColorAttrs >, lout::container::typed::Collection< dw::oof::OOFFloatsMgr::TBInfo >, lout::container::typed::Collection< dw::oof::OOFFloatsMgr::Float >, lout::container::typed::Collection< ui::FltkResource >, lout::container::typed::Collection< dw::fltk::FltkPlatform::IdleFunc >, lout::container::typed::Collection< dw::core::style::FontAttrs >, lout::container::typed::Collection< dw::fltk::ui::FltkRadioButtonResource >, lout::container::typed::Collection< Iterator >, lout::container::typed::Collection< lout::identity::IdentifiableObject::Class >, lout::container::typed::Collection< lout::object::ConstString >, lout::container::typed::Collection< dw::fltk::FltkImgbuf::GammaCorrectionTable >, lout::container::typed::Collection< K >, lout::container::typed::Collection< form::Form::ResourceDecorator >, lout::container::typed::Collection< lout::object::TypedPointer< Fl_Widget > >, lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::oof::OOFAwareWidget > >, lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::Widget > >, lout::object::PairBase, lout::container::untyped::List, lout::object::ConstString, lout::object::Boolean, lout::object::Integer, lout::object::Pointer, and dw::core::Iterator.
References lout::misc::assertNotReached().
Referenced by lout::container::untyped::HashSet::contains(), lout::container::untyped::List::equals(), lout::object::PairBase::equals(), lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::Widget > >::equals(), lout::container::untyped::HashSet::findNode(), lout::container::untyped::HashSet::remove(), and lout::container::untyped::List::remove0().
int lout::object::Object::hashValue () virtual
Return a hash value for the object.
Reimplemented in dw::core::style::ColorAttrs, dw::core::style::FontAttrs, dw::core::style::StyleAttrs, lout::container::typed::Collection< T >, lout::container::typed::Collection< dw::oof::OOFPositionedMgr::Child >, lout::container::typed::Collection< dw::core::style::StyleAttrs >, lout::container::typed::Collection< dw::fltk::FltkImgbuf >, lout::container::typed::Collection< lout::object::lout::object::String >, lout::container::typed::Collection< dw::core::Rectangle >, lout::container::typed::Collection< object::lout::object::ConstString >, lout::container::typed::Collection< lout::object::String >, lout::container::typed::Collection< dw::ImageMapsList::ImageMap::ShapeAndLink >, lout::container::typed::Collection< Float >, lout::container::typed::Collection< lout::signal::Receiver >, lout::container::typed::Collection< lout::object::TypedPointer< dw::core::Widget > >, lout::container::typed::Collection< lout::object::Object >, lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::ImgRenderer > >, lout::container::typed::Collection< form::Form::FormClickedReceiver >, lout::container::typed::Collection< lout::signal::Emitter >, lout::container::typed::Collection< dw::core::Widget >, lout::container::typed::Collection< dw::core::style::ColorAttrs >, lout::container::typed::Collection< dw::oof::OOFFloatsMgr::TBInfo >, lout::container::typed::Collection< dw::oof::OOFFloatsMgr::Float >, lout::container::typed::Collection< ui::FltkResource >, lout::container::typed::Collection< dw::fltk::FltkPlatform::IdleFunc >, lout::container::typed::Collection< dw::core::style::FontAttrs >, lout::container::typed::Collection< dw::fltk::ui::FltkRadioButtonResource >, lout::container::typed::Collection< Iterator >, lout::container::typed::Collection< lout::identity::IdentifiableObject::Class >, lout::container::typed::Collection< lout::object::ConstString >, lout::container::typed::Collection< dw::fltk::FltkImgbuf::GammaCorrectionTable >, lout::container::typed::Collection< K >, lout::container::typed::Collection< form::Form::ResourceDecorator >, lout::container::typed::Collection< lout::object::TypedPointer< Fl_Widget > >, lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::oof::OOFAwareWidget > >, lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::Widget > >, lout::object::PairBase, lout::container::untyped::List, lout::object::ConstString, lout::object::Boolean, lout::object::Integer, and lout::object::Pointer.
Referenced by lout::container::untyped::HashSet::calcHashValue(), lout::container::untyped::List::hashValue(), lout::object::PairBase::hashValue(), and lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::Widget > >::hashValue().
void lout::object::Object::intoStringBuffer (misc::StringBuffer * sb) virtual
Store a textual representation of the object in a misc::StringBuffer.
This is used by object::Object::toString.
Reimplemented in lout::container::typed::Collection< T >, lout::container::typed::Collection< dw::oof::OOFPositionedMgr::Child >, lout::container::typed::Collection< dw::core::style::StyleAttrs >, lout::container::typed::Collection< dw::fltk::FltkImgbuf >, lout::container::typed::Collection< lout::object::lout::object::String >, lout::container::typed::Collection< dw::core::Rectangle >, lout::container::typed::Collection< object::lout::object::ConstString >, lout::container::typed::Collection< lout::object::String >, lout::container::typed::Collection< dw::ImageMapsList::ImageMap::ShapeAndLink >, lout::container::typed::Collection< Float >, lout::container::typed::Collection< lout::signal::Receiver >, lout::container::typed::Collection< lout::object::TypedPointer< dw::core::Widget > >, lout::container::typed::Collection< lout::object::Object >, lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::ImgRenderer > >, lout::container::typed::Collection< form::Form::FormClickedReceiver >, lout::container::typed::Collection< lout::signal::Emitter >, lout::container::typed::Collection< dw::core::Widget >, lout::container::typed::Collection< dw::core::style::ColorAttrs >, lout::container::typed::Collection< dw::oof::OOFFloatsMgr::TBInfo >, lout::container::typed::Collection< dw::oof::OOFFloatsMgr::Float >, lout::container::typed::Collection< ui::FltkResource >, lout::container::typed::Collection< dw::fltk::FltkPlatform::IdleFunc >, lout::container::typed::Collection< dw::core::style::FontAttrs >, lout::container::typed::Collection< dw::fltk::ui::FltkRadioButtonResource >, lout::container::typed::Collection< Iterator >, lout::container::typed::Collection< lout::identity::IdentifiableObject::Class >, lout::container::typed::Collection< lout::object::ConstString >, lout::container::typed::Collection< dw::fltk::FltkImgbuf::GammaCorrectionTable >, lout::container::typed::Collection< K >, lout::container::typed::Collection< form::Form::ResourceDecorator >, lout::container::typed::Collection< lout::object::TypedPointer< Fl_Widget > >, lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::oof::OOFAwareWidget > >, lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::Widget > >, lout::container::untyped::HashTable, lout::signal::Receiver, lout::signal::Emitter, lout::object::PairBase, lout::object::ConstString, lout::object::Boolean, lout::object::Integer, lout::identity::IdentifiableObject, dw::oof::OOFAwareWidget::OOFAwareWidgetIterator, lout::identity::IdentifiableObject::Class, lout::object::Pointer, lout::container::untyped::Collection, dw::oof::OOFFloatsMgr::Float, and dw::core::Iterator.
References lout::misc::StringBuffer::append(), and lout::misc::StringBuffer::appendPointer().
Referenced by lout::object::PairBase::intoStringBuffer(), lout::container::untyped::HashTable::intoStringBuffer(), dw::fltk::FltkImgbuf::newScan(), and toString().
size_t lout::object::Object::sizeOf () virtual
Return the number of bytes, this object totally uses.
Reimplemented in lout::object::PairBase.
Referenced by lout::object::PairBase::sizeOf().
const char * lout::object::Object::toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
The caller does not have to free the memory, object::Object is responsible for this.
Todo:
garbage!
References lout::misc::StringBuffer::getChars(), and intoStringBuffer().
Referenced by lout::container::untyped::HashSet::clearNode(), lout::container::untyped::HashTable::clearNode(), testHashSet(), testHashTable(), testVector1(), testVector2(), lout::container::untyped::HashSet::~HashSet(), and lout::container::untyped::HashTable::~HashTable().
The documentation for this class was generated from the following files:
lout/object.hh
lout/object.cc