Dillo: dw::ImageMapsList::ImageMap Class Reference
dw::ImageMapsList::ImageMap Class Reference
Classes
class ShapeAndLink
Public Member Functions
ImageMap ()
~ImageMap ()
void draw (core::View *view, core::style::Style *style, int x, int y)
void add (core::Shape *shape, int link)
void setDefaultLink (int link)
int link (int x, int y)
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Private Attributes
lout::container::typed::List
< ShapeAndLink > * shapesAndLinks
int defaultLink
Constructor & Destructor Documentation
dw::ImageMapsList::ImageMap::ImageMap ()
dw::ImageMapsList::ImageMap::~ImageMap ()
Member Function Documentation
void dw::ImageMapsList::ImageMap::add (core::Shape * shape, int link)
References dw::ImageMapsList::ImageMap::ShapeAndLink::link, and dw::ImageMapsList::ImageMap::ShapeAndLink::shape.
void dw::ImageMapsList::ImageMap::draw (core::View * view, core::style::Style * style, int x, int y)
References dw::core::Shape::draw(), lout::container::typed::Iterator< T >::getNext(), lout::container::typed::Iterator< T >::hasNext(), and dw::ImageMapsList::ImageMap::ShapeAndLink::shape.
Referenced by dw::ImageMapsList::drawMap().
int dw::ImageMapsList::ImageMap::link (int x, int y)
References lout::container::typed::Iterator< T >::getNext(), lout::container::typed::Iterator< T >::hasNext(), dw::core::Shape::isPointWithin(), dw::ImageMapsList::ImageMap::ShapeAndLink::link, and dw::ImageMapsList::ImageMap::ShapeAndLink::shape.
Referenced by dw::ImageMapsList::link(), and setDefaultLink().
void dw::ImageMapsList::ImageMap::setDefaultLink (int link) inline
References link().
Member Data Documentation
int dw::ImageMapsList::ImageMap::defaultLink private
lout::container::typed::List<ShapeAndLink>* dw::ImageMapsList::ImageMap::shapesAndLinks private
The documentation for this class was generated from the following files:
dw/image.hh
dw/image.cc