Dillo: lout::container::untyped::HashSet Class Reference
lout::container::untyped::HashSet Class Reference
A hash set.
#include <container.hh>
Classes
class HashSetIterator
struct Node
Public Member Functions
HashSet (bool ownerOfObjects, int tableSize=251)
~HashSet ()
int size ()
void put (object::Object *object)
bool contains (object::Object *key) const
bool remove (object::Object *key)
Public Member Functions inherited from lout::container::untyped::Collection
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Iterator iterator ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions
int calcHashValue (object::Object *object) const
virtual Node * createNode ()
virtual void clearNode (Node *node)
Node * findNode (object::Object *object) const
Node * insertNode (object::Object *object)
AbstractIterator * createIterator ()
Protected Attributes
Node ** table
int tableSize
int numElements
bool ownerOfObjects
Friends
class HashSetIterator
Detailed Description
A hash set.
Constructor & Destructor Documentation
lout::container::untyped::HashSet::HashSet (bool ownerOfObjects, int tableSize = 251)
lout::container::untyped::HashSet::~HashSet ()
References lout::container::untyped::HashSet::Node::next, lout::container::untyped::HashSet::Node::object, PRINTF, and lout::object::Object::toString().
Member Function Documentation
int lout::container::untyped::HashSet::calcHashValue (object::Object * object) const inline protected
References lout::object::Object::hashValue().
void lout::container::untyped::HashSet::clearNode (HashSet::Node * node) protected virtual
Reimplemented in lout::container::untyped::HashTable.
References lout::container::untyped::HashSet::Node::object, PRINTF, and lout::object::Object::toString().
Referenced by lout::container::untyped::HashTable::clearNode().
bool lout::container::untyped::HashSet::contains (object::Object * key) const
References lout::object::Object::equals(), and lout::container::untyped::HashSet::Node::next.
Collection0::AbstractIterator * lout::container::untyped::HashSet::createIterator () protected virtual
Implements lout::container::untyped::Collection0.
HashSet::Node * lout::container::untyped::HashSet::createNode () protected virtual
Reimplemented in lout::container::untyped::HashTable.
HashSet::Node * lout::container::untyped::HashSet::findNode (object::Object * object) const protected
References lout::object::Object::equals(), and lout::container::untyped::HashSet::Node::next.
Referenced by lout::container::untyped::HashTable::get().
HashSet::Node * lout::container::untyped::HashSet::insertNode (object::Object * object) protected
References lout::container::untyped::HashSet::Node::next, and lout::container::untyped::HashSet::Node::object.
Referenced by lout::container::untyped::HashTable::put().
void lout::container::untyped::HashSet::put (object::Object * object)
bool lout::container::untyped::HashSet::remove (object::Object * key)
References lout::object::Object::equals(), and lout::container::untyped::HashSet::Node::next.
int lout::container::untyped::HashSet::size () virtual
Implements lout::container::untyped::Collection.
Friends And Related Function Documentation
friend class HashSetIterator friend
Member Data Documentation
int lout::container::untyped::HashSet::numElements protected
bool lout::container::untyped::HashSet::ownerOfObjects protected
Node** lout::container::untyped::HashSet::table protected
Referenced by lout::container::untyped::HashTable::intoStringBuffer(), and lout::container::untyped::HashTable::~HashTable().
int lout::container::untyped::HashSet::tableSize protected
Referenced by lout::container::untyped::HashTable::intoStringBuffer(), and lout::container::untyped::HashTable::~HashTable().
The documentation for this class was generated from the following files:
lout/container.hh
lout/container.cc