Dillo: dw::oof::OOFFloatsMgr::WidgetInfo Class Reference
dw::oof::OOFFloatsMgr::WidgetInfo Class Reference
Public Member Functions
WidgetInfo (OOFFloatsMgr *oofm, core::Widget *widget)
core::Widget * getWidget ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions
OOFFloatsMgr * getOOFFloatsMgr ()
Private Attributes
OOFFloatsMgr * oofm
core::Widget * widget
Constructor & Destructor Documentation
dw::oof::OOFFloatsMgr::WidgetInfo::WidgetInfo (OOFFloatsMgr * oofm, core::Widget * widget)
Member Function Documentation
OOFFloatsMgr* dw::oof::OOFFloatsMgr::WidgetInfo::getOOFFloatsMgr () inline protected
References oofm.
core::Widget* dw::oof::OOFFloatsMgr::WidgetInfo::getWidget () inline
References widget.
Referenced by dw::oof::OOFFloatsMgr::addWidgetOOF(), dw::oof::OOFFloatsMgr::calcFloatX(), dw::oof::OOFFloatsMgr::collidesH(), dw::oof::OOFFloatsMgr::collidesV(), dw::oof::OOFFloatsMgr::containerSizeChangedForChildren(), dw::oof::OOFFloatsMgr::drawFloats(), dw::oof::OOFFloatsMgr::ensureFloatSize(), dw::oof::OOFFloatsMgr::getBorder(), dw::oof::OOFFloatsMgr::getFloatsExtremes(), dw::oof::OOFFloatsMgr::getFloatsListsAndSide(), dw::oof::OOFFloatsMgr::getFloatsSize(), dw::oof::OOFFloatsMgr::getFloatWidgetAtPoint(), dw::oof::OOFFloatsMgr::TBInfo::getOOFAwareWidget(), dw::oof::OOFFloatsMgr::getWidget(), dw::oof::OOFFloatsMgr::markSizeChange(), dw::oof::OOFFloatsMgr::moveExternalIndices(), dw::oof::OOFFloatsMgr::sizeAllocateFloats(), and dw::oof::OOFFloatsMgr::tellPosition1().
Member Data Documentation
OOFFloatsMgr* dw::oof::OOFFloatsMgr::WidgetInfo::oofm private
Referenced by getOOFFloatsMgr().
core::Widget* dw::oof::OOFFloatsMgr::WidgetInfo::widget private
Referenced by getWidget().
The documentation for this class was generated from the following files:
dw/ooffloatsmgr.hh
dw/ooffloatsmgr.cc