Dillo: lout::object::TypedPointer< T > Class Template Reference
lout::object::TypedPointer< T > Class Template Reference
A typed version of object::Pointer.
#include <object.hh>
Public Member Functions
TypedPointer (T *value)
T * getTypedValue ()
Public Member Functions inherited from lout::object::Pointer
Pointer (void *value)
bool equals (Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
void * getValue ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Detailed Description
template<class T>
class lout::object::TypedPointer< T >
A typed version of object::Pointer.
Constructor & Destructor Documentation
template<class T> lout::object::TypedPointer< T >::TypedPointer (T * value) inline
Member Function Documentation
template<class T> T* lout::object::TypedPointer< T >::getTypedValue () inline
References lout::object::Pointer::getValue().
Referenced by dw::core::ImgRendererDist::drawRow(), lout::signal::ObservedObject::DeletionEmitter::emitToReceiver(), dw::core::ImgRendererDist::fatal(), dw::core::ImgRendererDist::finish(), and dw::core::ImgRendererDist::setBuffer().
The documentation for this class was generated from the following file:
lout/object.hh