Dillo: form::Form Class Reference
form::Form Class Reference
Handles HTML form data.
#include <form.hh>
Classes
class CheckButtonResourceDecorator
Decorates instances of dw::core::ui::CheckButtonResource.
class FormActivateReceiver
class FormClickedReceiver
class RadioButtonResourceDecorator
Decorates instances of dw::core::ui::RadioButtonResource.
class ResourceDecorator
Decorates instances of dw::core::ui::Resource.
class SelectionResourceDecorator
Decorates instances of dw::core::ui::SelectionResource.
class TextResourceDecorator
Decorates instances of dw::core::ui::TextResource.
Public Member Functions
Form ()
~Form ()
void addTextResource (const char *name, dw::core::ui::TextResource *resource)
Adds an instance of dw::core::ui::TextResource.
void addRadioButtonResource (const char *name, dw::core::ui::RadioButtonResource *resource, const char **values)
Adds an instance of dw::core::ui::RadioButtonResource.
void addCheckButtonResource (const char *name, dw::core::ui::CheckButtonResource *resource)
Adds an instance of dw::core::ui::CheckButtonResource.
void addSelectionResource (const char *name, dw::core::ui::SelectionResource *resource, const char **values)
Adds an instance of dw::core::ui::SelectionResource.
void addButtonResource (const char *name, dw::core::ui::ButtonResource *resource, const char *value)
void send (const char *buttonName, const char *buttonValue, int x, int y)
Private Attributes
lout::container::typed::List
< ResourceDecorator > * resources
FormActivateReceiver * activateReceiver
lout::container::typed::List
< FormClickedReceiver > * clickedReceivers
Detailed Description
Handles HTML form data.
Add resources by calling the respective add...Resource method. Furtermore, this class impelements dw::core::ui::ButtonResource::ClickedReceiver, the form data is printed to stdout, when the "clicked" signal is received.
Todo:
wrong comment
Constructor & Destructor Documentation
form::Form::Form ()
References activateReceiver, clickedReceivers, and resources.
form::Form::~Form ()
References activateReceiver, clickedReceivers, and resources.
Member Function Documentation
void form::Form::addButtonResource (const char * name, dw::core::ui::ButtonResource * resource, const char * value)
Todo:
Comment this;
References clickedReceivers, and dw::core::ui::Resource::connectClicked().
Referenced by main().
void form::Form::addCheckButtonResource (const char * name, dw::core::ui::CheckButtonResource * resource)
Adds an instance of dw::core::ui::CheckButtonResource.
References activateReceiver, dw::core::ui::Resource::connectActivate(), and resources.
Referenced by main().
void form::Form::addRadioButtonResource (const char * name, dw::core::ui::RadioButtonResource * resource, const char ** values)
Adds an instance of dw::core::ui::RadioButtonResource.
This method has to be called only once for a group of radio buttons.
References activateReceiver, dw::core::ui::Resource::connectActivate(), and resources.
Referenced by main().
void form::Form::addSelectionResource (const char * name, dw::core::ui::SelectionResource * resource, const char ** values)
Adds an instance of dw::core::ui::SelectionResource.
References activateReceiver, dw::core::ui::Resource::connectActivate(), and resources.
Referenced by main().
void form::Form::addTextResource (const char * name, dw::core::ui::TextResource * resource)
Adds an instance of dw::core::ui::TextResource.
References activateReceiver, dw::core::ui::Resource::connectActivate(), and resources.
Referenced by main().
void form::Form::send (const char * buttonName, const char * buttonValue, int x, int y)
Todo:
Comment this;
References form::Form::ResourceDecorator::getName(), form::Form::ResourceDecorator::getValue(), and resources.
Member Data Documentation
FormActivateReceiver* form::Form::activateReceiver private
Referenced by addCheckButtonResource(), addRadioButtonResource(), addSelectionResource(), addTextResource(), Form(), and ~Form().
lout::container::typed::List<FormClickedReceiver>* form::Form::clickedReceivers private
Referenced by addButtonResource(), Form(), and ~Form().
lout::container::typed::List<ResourceDecorator>* form::Form::resources private
Referenced by addCheckButtonResource(), addRadioButtonResource(), addSelectionResource(), addTextResource(), Form(), send(), and ~Form().
The documentation for this class was generated from the following files:
test/form.hh
test/form.cc