Dillo: dw::fltk::ui::FltkRadioButtonResource::Group Class Reference
dw::fltk::ui::FltkRadioButtonResource::Group Class Reference
Classes
class FltkGroupIterator
Public Member Functions
Group (FltkRadioButtonResource *radioButtonResource)
lout::container::typed::Iterator
< FltkRadioButtonResource > iterator ()
dw::core::ui::RadioButtonResource::GroupIterator * groupIterator ()
void connect (FltkRadioButtonResource *radioButtonResource)
void unconnect (FltkRadioButtonResource *radioButtonResource)
Protected Member Functions
~Group ()
Private Attributes
lout::container::typed::List
< FltkRadioButtonResource > * list
Constructor & Destructor Documentation
dw::fltk::ui::FltkRadioButtonResource::Group::~Group () protected
References list.
dw::fltk::ui::FltkRadioButtonResource::Group::Group (FltkRadioButtonResource * radioButtonResource)
References connect(), and list.
Member Function Documentation
void dw::fltk::ui::FltkRadioButtonResource::Group::connect (FltkRadioButtonResource * radioButtonResource)
References list.
Referenced by dw::fltk::ui::FltkRadioButtonResource::FltkRadioButtonResource(), and Group().
dw::core::ui::RadioButtonResource::GroupIterator* dw::fltk::ui::FltkRadioButtonResource::Group::groupIterator () inline
Referenced by dw::fltk::ui::FltkRadioButtonResource::groupIterator().
lout::container::typed::Iterator<FltkRadioButtonResource> dw::fltk::ui::FltkRadioButtonResource::Group::iterator () inline
References lout::container::typed::Collection< T >::iterator().
Referenced by dw::fltk::ui::FltkRadioButtonResource::buttonClicked().
void dw::fltk::ui::FltkRadioButtonResource::Group::unconnect (FltkRadioButtonResource * radioButtonResource)
References list.
Referenced by dw::fltk::ui::FltkRadioButtonResource::~FltkRadioButtonResource().
Member Data Documentation
lout::container::typed::List<FltkRadioButtonResource>* dw::fltk::ui::FltkRadioButtonResource::Group::list private
Referenced by connect(), dw::fltk::ui::FltkRadioButtonResource::Group::FltkGroupIterator::FltkGroupIterator(), Group(), unconnect(), and ~Group().
The documentation for this class was generated from the following files:
dw/fltkui.hh
dw/fltkui.cc