Dillo: dw::fltk::ui::FltkResource Class Reference
dw::fltk::ui::FltkResource Class Reference abstract
#include <fltkui.hh>
Public Member Functions
~FltkResource ()
virtual void attachView (FltkView *view)
virtual void detachView (FltkView *view)
void sizeAllocate (core::Allocation *allocation)
void draw (core::View *view, core::Rectangle *area, core::DrawingContext *context)
void setStyle (core::style::Style *style)
bool isEnabled ()
void setEnabled (bool enabled)
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions
FltkResource (FltkPlatform *platform)
void init (FltkPlatform *platform)
virtual Fl_Widget * createNewWidget (core::Allocation *allocation)=0
virtual void setWidgetStyle (Fl_Widget *widget, core::style::Style *style)
void setDisplayed (bool displayed)
bool displayed ()
Protected Attributes
FltkView * view
Fl_Widget * widget
core::Allocation allocation
FltkPlatform * platform
core::style::Style * style
Private Attributes
bool enabled
Detailed Description
...
Constructor & Destructor Documentation
dw::fltk::ui::FltkResource::FltkResource (FltkPlatform * platform) protected
References DBG_OBJ_CREATE, and platform.
dw::fltk::ui::FltkResource::~FltkResource ()
References DBG_OBJ_DELETE, and platform.
Member Function Documentation
void dw::fltk::ui::FltkResource::attachView (FltkView * view) virtual
Reimplemented in dw::fltk::ui::FltkComplexButtonResource.
References dw::fltk::FltkView::addFltkWidget(), and dw::fltk::FltkView::usesFltkWidgets().
Referenced by dw::fltk::FltkPlatform::attachResource(), dw::fltk::FltkPlatform::attachView(), and dw::fltk::ui::FltkComplexButtonResource::attachView().
virtual Fl_Widget* dw::fltk::ui::FltkResource::createNewWidget (core::Allocation * allocation) protected pure virtual
Implemented in dw::fltk::ui::FltkListResource, dw::fltk::ui::FltkOptionMenuResource, dw::fltk::ui::FltkToggleButtonResource< I >, dw::fltk::ui::FltkToggleButtonResource< dw::core::ui::RadioButtonResource >, dw::fltk::ui::FltkToggleButtonResource< dw::core::ui::CheckButtonResource >, dw::fltk::ui::FltkMultiLineTextResource, dw::fltk::ui::FltkEntryResource, dw::fltk::ui::FltkComplexButtonResource, and dw::fltk::ui::FltkLabelButtonResource.
void dw::fltk::ui::FltkResource::detachView (FltkView * view) virtual
Reimplemented in dw::fltk::ui::FltkComplexButtonResource.
Referenced by dw::fltk::FltkPlatform::detachView(), and dw::fltk::ui::FltkComplexButtonResource::detachView().
bool dw::fltk::ui::FltkResource::displayed () protected
Referenced by dw::fltk::ui::FltkEntryResource::sizeRequest().
void dw::fltk::ui::FltkResource::draw (core::View * view, core::Rectangle * area, core::DrawingContext * context)
References dw::fltk::FltkView::drawFltkWidget(), and dw::fltk::FltkView::usesFltkWidgets().
Referenced by dw::fltk::ui::FltkSpecificResource< I >::draw().
void dw::fltk::ui::FltkResource::init (FltkPlatform * platform) protected
This is not a constructor, since it calls some virtual methods, which should not be done in a C++ base constructor.
References dw::fltk::FltkPlatform::attachResource().
Referenced by dw::fltk::ui::FltkCheckButtonResource::FltkCheckButtonResource(), dw::fltk::ui::FltkComplexButtonResource::FltkComplexButtonResource(), dw::fltk::ui::FltkEntryResource::FltkEntryResource(), dw::fltk::ui::FltkLabelButtonResource::FltkLabelButtonResource(), dw::fltk::ui::FltkListResource::FltkListResource(), dw::fltk::ui::FltkMultiLineTextResource::FltkMultiLineTextResource(), dw::fltk::ui::FltkOptionMenuResource::FltkOptionMenuResource(), and dw::fltk::ui::FltkRadioButtonResource::FltkRadioButtonResource().
bool dw::fltk::ui::FltkResource::isEnabled ()
Referenced by dw::fltk::ui::FltkSpecificResource< I >::isEnabled().
void dw::fltk::ui::FltkResource::setDisplayed (bool displayed) protected
Referenced by dw::fltk::ui::FltkEntryResource::setDisplayed().
void dw::fltk::ui::FltkResource::setEnabled (bool enabled)
Referenced by dw::fltk::ui::FltkSpecificResource< I >::setEnabled().
void dw::fltk::ui::FltkResource::setStyle (core::style::Style * style)
References dw::core::style::Style::ref(), and dw::core::style::Style::unref().
Referenced by dw::fltk::ui::FltkSpecificResource< I >::setStyle().
void dw::fltk::ui::FltkResource::setWidgetStyle (Fl_Widget * widget, core::style::Style * style) protected virtual
Reimplemented in dw::fltk::ui::FltkListResource, dw::fltk::ui::FltkOptionMenuResource, dw::fltk::ui::FltkToggleButtonResource< I >, dw::fltk::ui::FltkToggleButtonResource< dw::core::ui::RadioButtonResource >, dw::fltk::ui::FltkToggleButtonResource< dw::core::ui::CheckButtonResource >, dw::fltk::ui::FltkMultiLineTextResource, and dw::fltk::ui::FltkEntryResource.
References dw::core::style::StyleAttrs::backgroundColor, dw::core::style::StyleAttrs::color, dw::fltk::FltkColor::colors, dw::fltk::FltkFont::font, dw::core::style::StyleAttrs::font, dw::core::style::Color::SHADING_NORMAL, and dw::core::style::FontAttrs::size.
Referenced by dw::fltk::ui::FltkEntryResource::setWidgetStyle(), dw::fltk::ui::FltkMultiLineTextResource::setWidgetStyle(), dw::fltk::ui::FltkToggleButtonResource< I >::setWidgetStyle(), dw::fltk::ui::FltkOptionMenuResource::setWidgetStyle(), and dw::fltk::ui::FltkListResource::setWidgetStyle().
void dw::fltk::ui::FltkResource::sizeAllocate (core::Allocation * allocation)
References dw::core::Allocation::ascent, DBG_OBJ_ENTER, DBG_OBJ_LEAVE, dw::core::Allocation::descent, dw::core::Allocation::width, dw::core::Allocation::x, and dw::core::Allocation::y.
Referenced by dw::fltk::ui::FltkSpecificResource< I >::sizeAllocate(), dw::fltk::ui::FltkComplexButtonResource::sizeAllocate(), and dw::fltk::ui::FltkEntryResource::sizeAllocate().
Member Data Documentation
core::Allocation dw::fltk::ui::FltkResource::allocation protected
Referenced by dw::fltk::ui::FltkEntryResource::sizeAllocate().
bool dw::fltk::ui::FltkResource::enabled private
FltkPlatform* dw::fltk::ui::FltkResource::platform protected
core::style::Style* dw::fltk::ui::FltkResource::style protected
Referenced by dw::fltk::ui::FltkLabelButtonResource::sizeRequest(), dw::fltk::ui::FltkEntryResource::sizeRequest(), dw::fltk::ui::FltkMultiLineTextResource::sizeRequest(), dw::fltk::ui::FltkToggleButtonResource< I >::sizeRequest(), dw::fltk::ui::FltkOptionMenuResource::sizeRequest(), dw::fltk::ui::FltkListResource::sizeRequest(), and dw::fltk::ui::FltkComplexButtonResource::widgetCallback().
FltkView* dw::fltk::ui::FltkResource::view protected
Referenced by dw::fltk::ui::FltkEntryResource::sizeAllocate().
Fl_Widget* dw::fltk::ui::FltkResource::widget protected
Referenced by dw::fltk::ui::FltkOptionMenuResource::addItem(), dw::fltk::ui::FltkOptionMenuResource::enlargeMenu(), dw::fltk::ui::FltkListResource::getMaxItemWidth(), dw::fltk::ui::FltkOptionMenuResource::getNumberOfItems(), dw::fltk::ui::FltkListResource::getNumberOfItems(), dw::fltk::ui::FltkEntryResource::getText(), dw::fltk::ui::FltkMultiLineTextResource::getText(), dw::fltk::ui::FltkOptionMenuResource::isSelected(), dw::fltk::ui::FltkListResource::isSelected(), dw::fltk::ui::FltkListResource::newItem(), dw::fltk::ui::FltkListResource::popGroup(), dw::fltk::ui::FltkOptionMenuResource::setItem(), dw::fltk::ui::FltkListResource::setItem(), dw::fltk::ui::FltkLabelButtonResource::setLabel(), dw::fltk::ui::FltkEntryResource::setMaxLength(), dw::fltk::ui::FltkEntryResource::setText(), dw::fltk::ui::FltkMultiLineTextResource::setText(), dw::fltk::ui::FltkEntryResource::sizeAllocate(), and dw::fltk::ui::FltkListResource::sizeRequest().
The documentation for this class was generated from the following files:
dw/fltkui.hh
dw/fltkui.cc