Dillo: dw::oof::OOFAwareWidget::OOFAwareWidgetIterator Class Reference
dw::oof::OOFAwareWidget::OOFAwareWidgetIterator Class Reference abstract
#include <oofawarewidget.hh>
Public Member Functions
OOFAwareWidgetIterator (OOFAwareWidget *widget, core::Content::Type mask, bool atEnd, int numContentsInFlow)
void intoStringBuffer (lout::misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
int compareTo (lout::object::Comparable *other)
Compare two objects, this and other.
bool next ()
Move iterator forward and store content it.
bool prev ()
Move iterator backward and store content it.
Public Member Functions inherited from dw::core::Iterator
bool equals (Object *other)
Returns, whether two objects are equal.
Widget * getWidget ()
Content * getContent ()
Content::Type getMask ()
virtual void unref ()
Delete the iterator.
virtual void highlight (int start, int end, HighlightLayer layer)=0
Extend highlighted region to contain part of the current content.
virtual void unhighlight (int direction, HighlightLayer layer)=0
Shrink highlighted region to no longer contain the current content.
virtual void getAllocation (int start, int end, Allocation *allocation)=0
Return the shape, which a part of the item, the iterator points on, allocates.
Iterator * cloneIterator ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions
virtual int numContentsInFlow ()=0
virtual void getContentInFlow (int index, core::Content *content)=0
void setValues (int sectionIndex, int index)
void cloneValues (OOFAwareWidgetIterator *other)
bool inFlow ()
int getInFlowIndex ()
void highlightOOF (int start, int end, core::HighlightLayer layer)
void unhighlightOOF (int direction, core::HighlightLayer layer)
void getAllocationOOF (int start, int end, core::Allocation *allocation)
Protected Member Functions inherited from dw::core::Iterator
Iterator (Widget *widget, Content::Type mask, bool atEnd)
Iterator (Iterator &it)
~Iterator ()
Private Types
enum { NUM_SECTIONS = NUM_OOFM + 1 }
Private Member Functions
int numParts (int sectionIndex, int numContentsInFlow=-1)
void getPart (int sectionIndex, int index, core::Content *content)
Private Attributes
int sectionIndex
int index
Additional Inherited Members
Static Public Member Functions inherited from dw::core::Iterator
static void scrollTo (Iterator *it1, Iterator *it2, int start, int end, HPosition hpos, VPosition vpos)
Scrolls the viewport, so that the region between it1 and it2 is seen, according to hpos and vpos.
Protected Attributes inherited from dw::core::Iterator
Content content
Member Enumeration Documentation
anonymous enum private
Enumerator
NUM_SECTIONS
Constructor & Destructor Documentation
dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::OOFAwareWidgetIterator (OOFAwareWidget * widget, core::Content::Type mask, bool atEnd, int numContentsInFlow)
References dw::core::Content::END, and dw::core::Content::START.
Member Function Documentation
void dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::cloneValues (OOFAwareWidgetIterator * other) inline protected
References setValues().
int dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::compareTo (lout::object::Comparable * other) virtual
Compare two objects, this and other.
Return a value < 0, when this is less than other, a value > 0, when this is greater than other, or 0, when this and other are equal.
If c1.equals(c2) (as defined in Object), c1.compareTo(c2) must be 0, but, unlike you may expect, the reversed is not necessarily true. This method returns 0, if, according to the rules for sorting, there is no difference, but there may still be differences (not relevant for sorting), which "equals" will care about.
Implements lout::object::Comparable.
References index, and sectionIndex.
void dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::getAllocationOOF (int start, int end, core::Allocation * allocation) protected
References dw::core::Widget::getAllocation(), dw::oof::OutOfFlowMgr::getWidget(), and dw::oof::OOFAwareWidget::outOfFlowMgr.
virtual void dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::getContentInFlow (int index, core::Content * content) protected pure virtual
int dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::getInFlowIndex () inline protected
References index, and inFlow().
void dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::getPart (int sectionIndex, int index, core::Content * content) private
References dw::oof::OutOfFlowMgr::getWidget(), dw::oof::OOFAwareWidget::outOfFlowMgr, dw::core::Content::type, dw::core::Content::widget, and dw::core::Content::WIDGET_OOF_CONT.
void dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::highlightOOF (int start, int end, core::HighlightLayer layer) protected
bool dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::inFlow () inline protected
Referenced by getInFlowIndex().
void dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::intoStringBuffer (lout::misc::StringBuffer * sb) virtual
Store a textual representation of the object in a misc::StringBuffer.
This is used by object::Object::toString.
Reimplemented from dw::core::Iterator.
References lout::misc::StringBuffer::append(), lout::misc::StringBuffer::appendInt(), and dw::core::Iterator::intoStringBuffer().
bool dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::next () virtual
Move iterator forward and store content it.
Returns true on success.
Implements dw::core::Iterator.
References lout::misc::boolToStr(), DBG_IF_RTFL, DBG_OBJ_ENTER0_O, DBG_OBJ_LEAVE_VAL_O, DBG_OBJ_MSGF_O, dw::core::Content::END, and lout::misc::StringBuffer::getChars().
virtual int dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::numContentsInFlow () protected pure virtual
int dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::numParts (int sectionIndex, int numContentsInFlow = -1) private
References DBG_OBJ_ENTER_O, DBG_OBJ_LEAVE_O, DBG_OBJ_MARKF_O, DBG_OBJ_MSGF_O, dw::oof::OutOfFlowMgr::getNumWidgets(), and dw::oof::OOFAwareWidget::outOfFlowMgr.
bool dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::prev () virtual
Move iterator backward and store content it.
Returns true on success.
Implements dw::core::Iterator.
References lout::misc::boolToStr(), DBG_IF_RTFL, DBG_OBJ_ENTER0_O, DBG_OBJ_LEAVE_VAL_O, DBG_OBJ_MSGF_O, lout::misc::StringBuffer::getChars(), and dw::core::Content::START.
void dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::setValues (int sectionIndex, int index) protected
References dw::core::Content::END, and dw::core::Content::START.
Referenced by cloneValues().
void dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::unhighlightOOF (int direction, core::HighlightLayer layer) protected
Member Data Documentation
int dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::index private
Referenced by compareTo(), and getInFlowIndex().
int dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::sectionIndex private
Referenced by compareTo().
The documentation for this class was generated from the following files:
dw/oofawarewidget.hh
dw/oofawarewidget_iterator.cc