Dillo: dw::core::ui::ComplexButtonResource Class Reference
dw::core::ui::ComplexButtonResource Class Reference abstract
#include <ui.hh>
Classes
class LayoutReceiver
Public Member Functions
ComplexButtonResource ()
~ComplexButtonResource ()
void sizeRequest (Requisition *requisition)
void getExtremes (Extremes *extremes)
void sizeAllocate (Allocation *allocation)
int getAvailWidthOfChild (Widget *child, bool forceValue)
int getAvailHeightOfChild (Widget *child, bool forceValue)
void correctRequisitionOfChild (Widget *child, Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
void correctExtremesOfChild (Widget *child, Extremes *extremes, bool useAdjustmentWidth)
void containerSizeChangedForChildren ()
Iterator * iterator (Content::Type mask, bool atEnd)
int getClickX ()
int getClickY ()
Public Member Functions inherited from dw::core::ui::Resource
Resource ()
virtual ~Resource ()
virtual void setDisplayed (bool displayed)
virtual void draw (View *view, Rectangle *area, DrawingContext *context)
virtual void setStyle (style::Style *style)
virtual bool isEnabled ()=0
virtual void setEnabled (bool enabled)=0
void connectActivate (ActivateReceiver *receiver)
void connectClicked (ClickedReceiver *receiver)
Protected Member Functions
void setEmbed (Embed *embed)
virtual Platform * createPlatform ()=0
virtual void setLayout (Layout *layout)=0
virtual int reliefXThickness ()=0
virtual int reliefYThickness ()=0
void init (Widget *widget)
Protected Member Functions inherited from dw::core::ui::Resource
void queueResize (bool extremesChanged)
virtual Embed * getEmbed ()
void emitActivate ()
void emitClicked (EventButton *event)
Protected Attributes
Layout * layout
int click_x
int click_y
Private Attributes
LayoutReceiver layoutReceiver
Widget * childWidget
Friends
class LayoutReceiver
Constructor & Destructor Documentation
dw::core::ui::ComplexButtonResource::ComplexButtonResource ()
References DBG_OBJ_CREATE, and layout.
dw::core::ui::ComplexButtonResource::~ComplexButtonResource ()
References DBG_OBJ_DELETE, and layout.
Member Function Documentation
void dw::core::ui::ComplexButtonResource::containerSizeChangedForChildren () virtual
Reimplemented from dw::core::ui::Resource.
References layout.
void dw::core::ui::ComplexButtonResource::correctExtremesOfChild (Widget * child, Extremes * extremes, bool useAdjustmentWidth) virtual
Reimplemented from dw::core::ui::Resource.
References dw::core::Widget::applyPerWidth(), dw::core::Widget::getStyle(), dw::core::style::isPerLength(), lout::misc::max(), dw::core::Extremes::maxWidth, dw::core::Extremes::minWidth, and dw::core::style::StyleAttrs::width.
void dw::core::ui::ComplexButtonResource::correctRequisitionOfChild (Widget * child, Requisition * requisition, void(*)(int, int *, int *) splitHeightFun, bool allowDecreaseWidth, bool allowDecreaseHeight) virtual
Reimplemented from dw::core::ui::Resource.
References dw::core::Widget::applyPerWidth(), dw::core::Widget::getStyle(), dw::core::style::isPerLength(), lout::misc::max(), dw::core::Requisition::width, and dw::core::style::StyleAttrs::width.
virtual Platform* dw::core::ui::ComplexButtonResource::createPlatform () protected pure virtual
Implemented in dw::fltk::ui::FltkComplexButtonResource.
int dw::core::ui::ComplexButtonResource::getAvailHeightOfChild (Widget * child, bool forceValue) virtual
Reimplemented from dw::core::ui::Resource.
References lout::misc::max().
int dw::core::ui::ComplexButtonResource::getAvailWidthOfChild (Widget * child, bool forceValue) virtual
Reimplemented from dw::core::ui::Resource.
References lout::misc::max().
int dw::core::ui::ComplexButtonResource::getClickX () inline
References click_x.
int dw::core::ui::ComplexButtonResource::getClickY () inline
References click_y.
void dw::core::ui::ComplexButtonResource::getExtremes (Extremes * extremes) virtual
Reimplemented from dw::core::ui::Resource.
References DBG_OBJ_ENTER0, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::core::Extremes::maxWidth, dw::core::Extremes::maxWidthIntrinsic, dw::core::Extremes::minWidth, and dw::core::Extremes::minWidthIntrinsic.
void dw::core::ui::ComplexButtonResource::init (Widget * widget) protected
References DBG_OBJ_ASSOC_CHILD, and layout.
Iterator * dw::core::ui::ComplexButtonResource::iterator (Content::Type mask, bool atEnd) virtual
Bug:
Implementation. This is a bit more complicated: We have two layouts here.
Implements dw::core::ui::Resource.
virtual int dw::core::ui::ComplexButtonResource::reliefXThickness () protected pure virtual
Implemented in dw::fltk::ui::FltkComplexButtonResource.
virtual int dw::core::ui::ComplexButtonResource::reliefYThickness () protected pure virtual
Implemented in dw::fltk::ui::FltkComplexButtonResource.
void dw::core::ui::ComplexButtonResource::setEmbed (Embed * embed) protected virtual
Reimplemented from dw::core::ui::Resource.
References dw::core::ui::Resource::setEmbed().
virtual void dw::core::ui::ComplexButtonResource::setLayout (Layout * layout) protected pure virtual
Implemented in dw::fltk::ui::FltkComplexButtonResource.
void dw::core::ui::ComplexButtonResource::sizeAllocate (Allocation * allocation) virtual
Reimplemented from dw::core::ui::Resource.
Reimplemented in dw::fltk::ui::FltkSpecificResource< dw::core::ui::ComplexButtonResource >.
void dw::core::ui::ComplexButtonResource::sizeRequest (Requisition * requisition) virtual
Implements dw::core::ui::Resource.
References dw::core::Requisition::ascent, DBG_OBJ_ENTER0, DBG_OBJ_LEAVE, DBG_OBJ_MSGF, dw::core::Requisition::descent, and dw::core::Requisition::width.
Friends And Related Function Documentation
friend class LayoutReceiver friend
Member Data Documentation
Widget* dw::core::ui::ComplexButtonResource::childWidget private
int dw::core::ui::ComplexButtonResource::click_x protected
Referenced by getClickX(), and dw::fltk::ui::FltkComplexButtonResource::widgetCallback().
int dw::core::ui::ComplexButtonResource::click_y protected
Referenced by getClickY(), and dw::fltk::ui::FltkComplexButtonResource::widgetCallback().
Layout* dw::core::ui::ComplexButtonResource::layout protected
Referenced by dw::fltk::ui::FltkComplexButtonResource::createNewWidget().
LayoutReceiver dw::core::ui::ComplexButtonResource::layoutReceiver private
The documentation for this class was generated from the following files:
dw/ui.hh
dw/ui.cc