Dillo: dw::core::style::Color Class Reference
dw::core::style::Color Class Reference
#include <style.hh>
Public Types
enum Shading {
SHADING_NORMAL, SHADING_INVERSE, SHADING_DARK, SHADING_LIGHT,
SHADING_NUM
}
Public Member Functions
void ref ()
void unref ()
Public Member Functions inherited from dw::core::style::ColorAttrs
ColorAttrs (int color)
int getColor ()
bool equals (lout::object::Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Static Public Member Functions
static Color * create (Layout *layout, int color)
Protected Member Functions
Color (int color)
virtual ~Color ()
int shadeColor (int color, Shading shading)
Private Member Functions
void remove (dw::core::Layout *layout)
int shadeColor (int color, int d)
Private Attributes
int refCount
Additional Inherited Members
Protected Attributes inherited from dw::core::style::ColorAttrs
int color
Detailed Description
See also
dw::core::style
Member Enumeration Documentation
enum dw::core::style::Color::Shading
Enumerator
SHADING_NORMAL
SHADING_INVERSE
SHADING_DARK
SHADING_LIGHT
SHADING_NUM
Constructor & Destructor Documentation
dw::core::style::Color::Color (int color) inline protected
References DBG_OBJ_CREATE.
dw::core::style::Color::~Color () protected virtual
References DBG_OBJ_DELETE.
Member Function Documentation
Color * dw::core::style::Color::create (Layout * layout, int color) static
References dw::core::Layout::createColor().
Referenced by main().
void dw::core::style::Color::ref () inline
Referenced by dw::core::Layout::setBgColor().
void dw::core::style::Color::remove (dw::core::Layout * layout) private
int dw::core::style::Color::shadeColor (int color, int d) private
References lout::misc::max().
Referenced by dw::fltk::FltkColor::FltkColor().
int dw::core::style::Color::shadeColor (int color, Shading shading) protected
References lout::misc::assertNotReached().
void dw::core::style::Color::unref () inline
Member Data Documentation
int dw::core::style::Color::refCount private
The documentation for this class was generated from the following files:
dw/style.hh
dw/style.cc