Dillo: dw::core::ui::Resource::ActivateEmitter Class Reference
dw::core::ui::Resource::ActivateEmitter Class Reference
Public Member Functions
void connectActivate (ActivateReceiver *receiver)
void emitActivate (Resource *resource)
void emitEnter (Resource *resource)
void emitLeave (Resource *resource)
Public Member Functions inherited from lout::signal::Emitter
Emitter ()
~Emitter ()
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions
bool emitToReceiver (lout::signal::Receiver *receiver, int signalNo, int argc, Object **argv)
A sub class must implement this for a call to a single receiver.
Protected Member Functions inherited from lout::signal::Emitter
void emitVoid (int signalNo, int argc, Object **argv)
Emit a void signal.
bool emitBool (int signalNo, int argc, Object **argv)
Emit a boolean signal.
void connect (Receiver *receiver)
Connect a receiver to the emitter.
Member Function Documentation
void dw::core::ui::Resource::ActivateEmitter::connectActivate (ActivateReceiver * receiver) inline
References lout::signal::Emitter::connect().
Referenced by dw::core::ui::Resource::connectActivate().
void dw::core::ui::Resource::ActivateEmitter::emitActivate (Resource * resource)
Referenced by dw::core::ui::Resource::emitActivate().
void dw::core::ui::Resource::ActivateEmitter::emitEnter (Resource * resource)
void dw::core::ui::Resource::ActivateEmitter::emitLeave (Resource * resource)
bool dw::core::ui::Resource::ActivateEmitter::emitToReceiver (lout::signal::Receiver * receiver, int signalNo, int argc, Object ** argv) protected virtual
A sub class must implement this for a call to a single receiver.
This methods gets the signal in a folded representation, it has to unfold it, and pass it to a single receiver. For boolean signals, the return value of the receiver must be returned, for void signals, the return value is discarded.
Implements lout::signal::Emitter.
References dw::core::ui::Resource::ActivateReceiver::activate(), lout::misc::assertNotReached(), dw::core::ui::Resource::ActivateReceiver::enter(), and dw::core::ui::Resource::ActivateReceiver::leave().
The documentation for this class was generated from the following files:
dw/ui.hh
dw/ui.cc