Dillo: dw::fltk::ui::ComplexButton Class Reference
dw::fltk::ui::ComplexButton Class Reference
#include <fltkcomplexbutton.hh>
Public Member Functions
virtual int handle (int)
ComplexButton (int X, int Y, int W, int H, const char *L=0)
~ComplexButton ()
int value (int v)
char value () const
Fl_Boxtype down_box () const
void down_box (Fl_Boxtype b)
Protected Member Functions
virtual void draw ()
Private Attributes
char value_
char oldval
uchar down_box_
Constructor & Destructor Documentation
ComplexButton::ComplexButton (int X, int Y, int W, int H, const char * L = 0)
The constructor creates the button using the given position, size and label.
Parameters
[in] X,Y,W,H position and size of the widget
[in] L widget label, default is no label
References down_box(), oldval, and value_.
ComplexButton::~ComplexButton ()
Member Function Documentation
Fl_Boxtype dw::fltk::ui::ComplexButton::down_box () const inline
Returns the current down box type, which is drawn when value() is non-zero.
Return values
Fl_Boxtype
References down_box_.
Referenced by ComplexButton(), and draw().
void dw::fltk::ui::ComplexButton::down_box (Fl_Boxtype b) inline
Sets the down box type. The default value of 0 causes FLTK to figure out the correct matching down version of box().
Parameters
[in] b down box type
void ComplexButton::draw () protected virtual
References down_box(), and value().
int ComplexButton::handle (int event) virtual
References oldval, value(), and value_.
int ComplexButton::value (int v)
Sets the current value of the button. A non-zero value sets the button to 1 (ON), and zero sets it to 0 (OFF).
Parameters
[in] v button value.
References oldval, and value_.
char dw::fltk::ui::ComplexButton::value () const inline
Returns the current value of the button (0 or 1).
References value_.
Referenced by draw(), and handle().
Member Data Documentation
uchar dw::fltk::ui::ComplexButton::down_box_ private
Referenced by down_box().
char dw::fltk::ui::ComplexButton::oldval private
Referenced by ComplexButton(), handle(), and value().
char dw::fltk::ui::ComplexButton::value_ private
Referenced by ComplexButton(), handle(), and value().
The documentation for this class was generated from the following files:
dw/fltkcomplexbutton.hh
dw/fltkcomplexbutton.cc