Dillo: dw::fltk::FltkPreview Class Reference
dw::fltk::FltkPreview Class Reference
#include <fltkpreview.hh>
Public Member Functions
FltkPreview (int x, int y, int w, int h, dw::core::Layout *layout, const char *label=0)
~FltkPreview ()
int handle (int event)
void setCanvasSize (int width, int ascent, int descent)
Set the canvas size.
bool usesViewport ()
Return, whether this view uses a viewport.
int getHScrollbarThickness ()
Get the thickness of the horizontal scrollbar, when it is visible.
int getVScrollbarThickness ()
Get the thickness of the vertical scrollbar, when it is visible.
void scrollTo (int x, int y)
Scroll the vieport to the given position.
void scroll (dw::core::ScrollCommand cmd)
Scroll the viewport as commanded.
void setViewportSize (int width, int height, int hScrollbarThickness, int vScrollbarThickness)
Set the viewport size.
void drawText (core::style::Font *font, core::style::Color *color, core::style::Color::Shading shading, int x, int y, const char *text, int len)
void drawSimpleWrappedText (core::style::Font *font, core::style::Color *color, core::style::Color::Shading shading, int x, int y, int w, int h, const char *text)
void drawImage (core::Imgbuf *imgbuf, int xRoot, int yRoot, int x, int y, int width, int height)
bool usesFltkWidgets ()
void drawFltkWidget (Fl_Widget *widget, core::Rectangle *area)
Public Member Functions inherited from dw::fltk::FltkViewBase
FltkViewBase (int x, int y, int w, int h, const char *label=0)
~FltkViewBase ()
void draw ()
int handle (int event)
void setLayout (core::Layout *layout)
This methods notifies the view, that it has been attached to a layout.
void setCanvasSize (int width, int ascent, int descent)
Set the canvas size.
void setCursor (core::style::Cursor cursor)
Set the cursor appearance.
void setBgColor (core::style::Color *color)
Set the background of the view.
void startDrawing (core::Rectangle *area)
Called before drawing.
void finishDrawing (core::Rectangle *area)
Called after drawing.
void queueDraw (core::Rectangle *area)
Queue a region, which is given in canvas coordinates, for drawing.
void queueDrawTotal ()
Queue the total viewport for drawing.
void cancelQueueDraw ()
Cancel a draw queue request.
void drawPoint (core::style::Color *color, core::style::Color::Shading shading, int x, int y)
void drawLine (core::style::Color *color, core::style::Color::Shading shading, int x1, int y1, int x2, int y2)
void drawTypedLine (core::style::Color *color, core::style::Color::Shading shading, core::style::LineType type, int width, int x1, int y1, int x2, int y2)
void drawRectangle (core::style::Color *color, core::style::Color::Shading shading, bool filled, int x, int y, int width, int height)
void drawArc (core::style::Color *color, core::style::Color::Shading shading, bool filled, int centerX, int centerY, int width, int height, int angle1, int angle2)
void drawPolygon (core::style::Color *color, core::style::Color::Shading shading, bool filled, bool convex, core::Point *points, int npoints)
core::View * getClippingView (int x, int y, int width, int height)
void mergeClippingView (core::View *clippingView)
void setBufferedDrawing (bool b)
Public Member Functions inherited from dw::fltk::FltkView
virtual void addFltkWidget (Fl_Widget *widget, core::Allocation *allocation)
virtual void removeFltkWidget (Fl_Widget *widget)
virtual void allocateFltkWidget (Fl_Widget *widget, core::Allocation *allocation)
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual bool equals (Object *other)
Returns, whether two objects are equal.
virtual int hashValue ()
Return a hash value for the object.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions
int translateViewXToCanvasX (int x)
int translateViewYToCanvasY (int y)
int translateCanvasXToViewX (int x)
int translateCanvasYToViewY (int y)
Private Attributes
int scrollX
int scrollY
int scrollWidth
int scrollHeight
Friends
class FltkPreviewWindow
Additional Inherited Members
Protected Attributes inherited from dw::fltk::FltkViewBase
core::Layout * theLayout
int canvasWidth
int canvasHeight
int mouse_x
int mouse_y
Fl_Widget * focused_child
Constructor & Destructor Documentation
dw::fltk::FltkPreview::FltkPreview (int x, int y, int w, int h, dw::core::Layout * layout, const char * label = 0)
References dw::core::Layout::attachView(), scrollHeight, scrollWidth, scrollX, and scrollY.
dw::fltk::FltkPreview::~FltkPreview ()
Member Function Documentation
void dw::fltk::FltkPreview::drawFltkWidget (Fl_Widget * widget, core::Rectangle * area) virtual
Reimplemented from dw::fltk::FltkView.
void dw::fltk::FltkPreview::drawImage (core::Imgbuf * imgbuf, int xRoot, int yRoot, int x, int y, int width, int height) virtual
Implements dw::core::View.
void dw::fltk::FltkPreview::drawSimpleWrappedText (core::style::Font * font, core::style::Color * color, core::style::Color::Shading shading, int x, int y, int w, int h, const char * text) virtual
Implements dw::core::View.
void dw::fltk::FltkPreview::drawText (core::style::Font * font, core::style::Color * color, core::style::Color::Shading shading, int x, int y, const char * text, int len) virtual
Implements dw::core::View.
References dw::core::style::Font::ascent, dw::fltk::FltkFont::font, dw::core::style::FontAttrs::size, translateCanvasXToViewX(), and translateCanvasYToViewY().
int dw::fltk::FltkPreview::getHScrollbarThickness () virtual
Get the thickness of the horizontal scrollbar, when it is visible.
Does not have to be implemented, when usesViewport returns false.
Implements dw::core::View.
int dw::fltk::FltkPreview::getVScrollbarThickness () virtual
Get the thickness of the vertical scrollbar, when it is visible.
Does not have to be implemented, when usesViewport returns false.
Implements dw::core::View.
int dw::fltk::FltkPreview::handle (int event)
References dw::fltk::FltkViewBase::handle().
void dw::fltk::FltkPreview::scroll (dw::core::ScrollCommand) virtual
Scroll the viewport as commanded.
Reimplemented from dw::core::View.
void dw::fltk::FltkPreview::scrollTo (int x, int y) virtual
Scroll the vieport to the given position.
Does not have to be implemented, when usesViewport returns false.
Implements dw::core::View.
References scrollX, and scrollY.
void dw::fltk::FltkPreview::setCanvasSize (int width, int ascent, int descent) virtual
Set the canvas size.
Implements dw::core::View.
References dw::fltk::FltkViewBase::setCanvasSize().
void dw::fltk::FltkPreview::setViewportSize (int width, int height, int hScrollbarThickness, int vScrollbarThickness) virtual
Set the viewport size.
Does not have to be implemented, when usesViewport returns false.
This will normally imply a resize of the UI widget. Width and height are the dimensions of the new size, including the scrollbar thicknesses.
Implements dw::core::View.
References scrollHeight, and scrollWidth.
int dw::fltk::FltkPreview::translateCanvasXToViewX (int x) protected virtual
Implements dw::fltk::FltkViewBase.
References dw::fltk::FltkViewBase::canvasWidth.
Referenced by drawText(), and dw::fltk::FltkPreviewWindow::reallocate().
int dw::fltk::FltkPreview::translateCanvasYToViewY (int y) protected virtual
Implements dw::fltk::FltkViewBase.
References dw::fltk::FltkViewBase::canvasHeight.
Referenced by drawText(), and dw::fltk::FltkPreviewWindow::reallocate().
int dw::fltk::FltkPreview::translateViewXToCanvasX (int x) protected virtual
Implements dw::fltk::FltkViewBase.
References dw::fltk::FltkViewBase::canvasWidth.
Referenced by dw::fltk::FltkPreviewWindow::scrollTo().
int dw::fltk::FltkPreview::translateViewYToCanvasY (int y) protected virtual
Implements dw::fltk::FltkViewBase.
References dw::fltk::FltkViewBase::canvasHeight.
Referenced by dw::fltk::FltkPreviewWindow::scrollTo().
bool dw::fltk::FltkPreview::usesFltkWidgets () virtual
Implements dw::fltk::FltkView.
bool dw::fltk::FltkPreview::usesViewport () virtual
Return, whether this view uses a viewport.
Implements dw::core::View.
Friends And Related Function Documentation
friend class FltkPreviewWindow friend
Member Data Documentation
int dw::fltk::FltkPreview::scrollHeight private
Referenced by FltkPreview(), dw::fltk::FltkPreviewWindow::reallocate(), dw::fltk::FltkPreviewWindow::scrollTo(), and setViewportSize().
int dw::fltk::FltkPreview::scrollWidth private
Referenced by FltkPreview(), dw::fltk::FltkPreviewWindow::reallocate(), dw::fltk::FltkPreviewWindow::scrollTo(), and setViewportSize().
int dw::fltk::FltkPreview::scrollX private
Referenced by FltkPreview(), dw::fltk::FltkPreviewWindow::reallocate(), scrollTo(), and dw::fltk::FltkPreviewWindow::scrollTo().
int dw::fltk::FltkPreview::scrollY private
Referenced by FltkPreview(), dw::fltk::FltkPreviewWindow::reallocate(), scrollTo(), and dw::fltk::FltkPreviewWindow::scrollTo().
The documentation for this class was generated from the following files:
dw/fltkpreview.hh
dw/fltkpreview.cc