Dillo: dw::fltk::FltkFont Class Reference
dw::fltk::FltkFont Class Reference
#include <fltkplatform.hh>
Classes
class FontFamily
Static Public Member Functions
static FltkFont * create (core::style::FontAttrs *attrs)
static bool fontExists (const char *name)
static Fl_Font get (const char *name, int attrs)
Static Public Member Functions inherited from dw::core::style::Font
static Font * create (Layout *layout, FontAttrs *attrs)
static bool exists (Layout *layout, const char *name)
Public Attributes
Fl_Font font
Public Attributes inherited from dw::core::style::Font
int ascent
int descent
int spaceWidth
int xHeight
Public Attributes inherited from dw::core::style::FontAttrs
const char * name
int size
int weight
int letterSpacing
FontVariant fontVariant
FontStyle style
Private Member Functions
FltkFont (core::style::FontAttrs *attrs)
~FltkFont ()
Static Private Member Functions
static void initSystemFonts ()
Static Private Attributes
static FontFamily standardFontFamily
static
lout::container::typed::HashTable
< lout::object::ConstString,
FontFamily > * systemFonts
static
lout::container::typed::HashTable
< dw::core::style::FontAttrs,
FltkFont > * fontsTable
Additional Inherited Members
Public Member Functions inherited from dw::core::style::Font
void ref ()
void unref ()
Public Member Functions inherited from dw::core::style::FontAttrs
bool equals (lout::object::Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
virtual void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Member Functions inherited from dw::core::style::Font
Font ()
virtual ~Font ()
void copyAttrs (FontAttrs *attrs)
Constructor & Destructor Documentation
dw::fltk::FltkFont::FltkFont (core::style::FontAttrs * attrs) private
References dw::core::style::FONT_STYLE_NORMAL, dw::fltk::FltkFont::FontFamily::get(), and lout::misc::max().
dw::fltk::FltkFont::~FltkFont () private
Member Function Documentation
FltkFont * dw::fltk::FltkFont::create (core::style::FontAttrs * attrs) static
References lout::container::typed::HashTable< K, V >::get().
Referenced by dw::fltk::FltkPlatform::createFont().
bool dw::fltk::FltkFont::fontExists (const char * name) static
Referenced by dw::fltk::FltkPlatform::fontExists().
Fl_Font dw::fltk::FltkFont::get (const char * name, int attrs) static
References dw::fltk::FltkFont::FontFamily::get().
void dw::fltk::FltkFont::initSystemFonts () static private
References lout::container::typed::HashTable< K, V >::get(), dw::fltk::FltkFont::FontFamily::set(), and dw::fltk::strstrip().
Member Data Documentation
Fl_Font dw::fltk::FltkFont::font
Referenced by dw::fltk::FltkWidgetView::drawSimpleWrappedText(), dw::fltk::FltkPreview::drawText(), dw::fltk::FltkWidgetView::drawText(), dw::fltk::ui::FltkResource::setWidgetStyle(), dw::fltk::ui::FltkLabelButtonResource::sizeRequest(), dw::fltk::ui::FltkEntryResource::sizeRequest(), dw::fltk::ui::FltkMultiLineTextResource::sizeRequest(), dw::fltk::ui::FltkToggleButtonResource< I >::sizeRequest(), dw::fltk::ui::FltkOptionMenuResource::sizeRequest(), and dw::fltk::FltkPlatform::textWidth().
container::typed::HashTable< dw::core::style::FontAttrs, FltkFont > * dw::fltk::FltkFont::fontsTable static private
Initial value:
=
   new container::typed::HashTable <dw::core::style::FontAttrs,
                                    FltkFont> (false, false)
Todo:
Distinction between italics and oblique would be nice.
FltkFont::FontFamily dw::fltk::FltkFont::standardFontFamily static private
container::typed::HashTable< lout::object::ConstString, FltkFont::FontFamily > * dw::fltk::FltkFont::systemFonts static private
Initial value:
=
                             NULL
The documentation for this class was generated from the following files:
dw/fltkplatform.hh
dw/fltkplatform.cc