Dillo: test/containers.cc File Reference
containers.cc File Reference
#include "../lout/object.hh"
#include "../lout/container.hh"
Functions
void testHashSet ()
void testHashTable ()
void testVector1 ()
void testVector2 ()
void testVector3 ()
void testStackAsQueue ()
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References testHashSet(), testHashTable(), testStackAsQueue(), testVector1(), testVector2(), and testVector3().
void testHashSet ()
References lout::container::typed::HashSet< T >::put(), and lout::object::Object::toString().
Referenced by main().
void testHashTable ()
References lout::container::typed::HashTable< K, V >::put(), and lout::object::Object::toString().
Referenced by main().
void testStackAsQueue ()
References lout::container::typed::Stack< T >::getTop(), lout::object::Integer::getValue(), lout::container::typed::Stack< T >::pop(), lout::container::typed::Stack< T >::pushUnder(), and lout::container::typed::Collection< T >::size().
Referenced by main().
void testVector1 ()
References lout::container::typed::Vector< T >::put(), lout::container::typed::Vector< T >::sort(), lout::object::standardComparator, and lout::object::Object::toString().
Referenced by main().
void testVector2 ()
References lout::container::typed::Vector< T >::bsearch(), lout::object::ConstString::chars(), lout::container::typed::Vector< T >::insertSorted(), lout::container::typed::Collection< T >::iterator(), and lout::object::Object::toString().
Referenced by main().
void testVector3 ()
References lout::container::typed::Vector< T >::bsearch(), and lout::container::typed::Vector< T >::put().
Referenced by main().