Dillo: test/dw_imgbuf_mem_test.cc File Reference
dw_imgbuf_mem_test.cc File Reference
#include "../dw/core.hh"
#include "../dw/fltkcore.hh"
Functions
void solution1 ()
void solution2 ()
void solution3 ()
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References solution1(), solution2(), and solution3().
void solution1 ()
References dw::core::Layout::createImgbuf(), dw::core::Imgbuf::getScaledBuf(), dw::core::Imgbuf::lastReference(), layout, platform, dw::core::Imgbuf::ref(), and dw::core::Imgbuf::unref().
Referenced by main().
void solution2 ()
References dw::core::Layout::createImgbuf(), dw::core::Imgbuf::getScaledBuf(), dw::core::Imgbuf::isReferred(), layout, platform, dw::core::Imgbuf::setDeleteOnUnref(), and dw::core::Imgbuf::unref().
Referenced by main().
void solution3 ()
References lout::signal::ObservedObject::connectDeletion(), dw::core::Layout::createImgbuf(), dw::core::Imgbuf::getScaledBuf(), layout, platform, and dw::core::Imgbuf::unref().
Referenced by main().