Dillo: test/dw_image_background.cc File Reference
dw_image_background.cc File Reference
#include <stdlib.h>
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "../dw/core.hh"
#include "../dw/fltkcore.hh"
#include "../dw/fltkviewport.hh"
#include "../dw/textblock.hh"
#include "../dw/image.hh"
Functions
static void imageInitTimeout (void *data)
static void imageDrawTimeout (void *data)
int main (int argc, char **argv)
Variables
static StyleImage * image1 = NULL
static StyleImage * image2 = NULL
static Layout * layout
static int imgRow1 = 0
static int imgRow2 = 0
static ImageStyleDeletionReceiver isdr
Function Documentation
static void imageDrawTimeout (void * data) static
References dw::core::Imgbuf::copyRow(), dw::core::ImgRenderer::drawRow(), dw::core::style::StyleImage::getImgbufSrc(), dw::core::style::StyleImage::getMainImgRenderer(), image2, imgRow1, and imgRow2.
Referenced by main().
static void imageInitTimeout (void * data) static
References dw::core::Layout::createImgbuf(), dw::core::style::StyleImage::getMainImgRenderer(), image2, and dw::core::ImgRenderer::setBuffer().
Referenced by main().
int main (int argc, char ** argv)
References dw::Textblock::addParbreak(), dw::Textblock::addSpace(), dw::Textblock::addText(), dw::core::Layout::attachView(), dw::core::style::BACKGROUND_ATTACHMENT_SCROLL, dw::core::style::BACKGROUND_REPEAT, dw::core::style::BACKGROUND_REPEAT_Y, dw::core::style::StyleAttrs::backgroundColor, dw::core::style::StyleAttrs::backgroundImage, dw::core::style::StyleAttrs::backgroundPositionX, dw::core::style::StyleAttrs::backgroundPositionY, dw::core::style::StyleAttrs::backgroundRepeat, dw::core::style::StyleAttrs::color, lout::signal::ObservedObject::connectDeletion(), dw::core::style::createAbsLength(), dw::core::style::createPerLength(), dw::Textblock::flush(), dw::core::style::StyleAttrs::font, dw::core::style::FONT_STYLE_NORMAL, dw::core::style::FONT_VARIANT_NORMAL, dw::core::style::FontAttrs::fontVariant, image2, imageDrawTimeout(), imageInitTimeout(), dw::core::style::StyleAttrs::initValues(), layout, dw::core::style::FontAttrs::letterSpacing, dw::core::style::StyleAttrs::margin, dw::core::style::FontAttrs::name, platform, dw::core::Layout::setBgImage(), dw::core::Widget::setStyle(), dw::core::style::Box::setVal(), dw::core::Layout::setWidget(), dw::core::style::FontAttrs::size, dw::core::style::FontAttrs::style, dw::core::style::Style::unref(), viewport, dw::core::style::FontAttrs::weight, widgetStyle, window, wordStyle, and dw::core::style::StyleAttrs::x_lang.
Variable Documentation
StyleImage* image1 = NULL static
StyleImage * image2 = NULL static
Referenced by imageDrawTimeout(), imageInitTimeout(), and main().
int imgRow1 = 0 static
Referenced by imageDrawTimeout().
int imgRow2 = 0 static
Referenced by imageDrawTimeout().
ImageStyleDeletionReceiver isdr static
Layout* layout static
Referenced by main().