Dillo: test/dw_resource_test.cc File Reference
dw_resource_test.cc File Reference
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "../dw/core.hh"
#include "../dw/fltkcore.hh"
#include "../dw/fltkviewport.hh"
#include "../dw/textblock.hh"
#include "../dw/ui.hh"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References dw::core::ui::SelectionResource::addItem(), dw::Textblock::addSpace(), dw::Textblock::addWidget(), dw::core::Layout::attachView(), dw::core::style::StyleAttrs::backgroundColor, dw::core::style::StyleAttrs::color, dw::core::style::Style::create(), dw::core::style::Font::create(), dw::core::style::Color::create(), dw::core::ui::ResourceFactory::createListResource(), dw::Textblock::flush(), dw::core::style::StyleAttrs::font, dw::core::style::FONT_STYLE_NORMAL, dw::core::style::FONT_VARIANT_NORMAL, dw::core::style::FontAttrs::fontVariant, dw::core::Layout::getResourceFactory(), dw::core::style::StyleAttrs::initValues(), layout, dw::core::style::FontAttrs::letterSpacing, dw::core::style::StyleAttrs::margin, dw::core::style::FontAttrs::name, platform, dw::core::Widget::setStyle(), dw::core::style::Box::setVal(), dw::core::Layout::setWidget(), dw::core::style::FontAttrs::size, dw::core::style::FontAttrs::style, dw::core::style::Style::unref(), viewport, dw::core::style::FontAttrs::weight, widgetStyle, and window.