Dillo: test/dw_table.cc File Reference
dw_table.cc File Reference
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "../dw/core.hh"
#include "../dw/fltkcore.hh"
#include "../dw/fltkviewport.hh"
#include "../dw/table.hh"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References dw::Table::addCell(), dw::Table::addRow(), dw::Textblock::addText(), dw::core::Layout::attachView(), dw::core::style::StyleAttrs::backgroundColor, dw::core::style::BORDER_INSET, dw::core::style::BORDER_OUTSET, dw::core::style::StyleAttrs::borderWidth, dw::core::style::StyleAttrs::color, dw::core::style::Style::create(), dw::core::style::Font::create(), dw::core::style::Color::create(), dw::core::style::StyleAttrs::cursor, dw::core::style::CURSOR_TEXT, dw::Textblock::flush(), dw::core::style::StyleAttrs::font, dw::core::style::FONT_STYLE_NORMAL, dw::core::style::FONT_VARIANT_NORMAL, dw::core::style::FontAttrs::fontVariant, dw::core::style::StyleAttrs::hBorderSpacing, dw::core::style::StyleAttrs::initValues(), layout, dw::core::style::FontAttrs::letterSpacing, dw::core::style::StyleAttrs::margin, dw::core::style::FontAttrs::name, dw::core::style::StyleAttrs::padding, platform, dw::core::style::StyleAttrs::setBorderColor(), dw::core::style::StyleAttrs::setBorderStyle(), dw::core::Widget::setStyle(), dw::core::style::Box::setVal(), dw::core::Layout::setWidget(), dw::core::style::FontAttrs::size, dw::core::style::FontAttrs::style, dw::core::style::StyleAttrs::textAlignChar, dw::core::style::Style::unref(), dw::core::style::StyleAttrs::vBorderSpacing, viewport, dw::core::style::FontAttrs::weight, window, and wordStyle.