Dillo: test/dw_ui_test.cc File Reference
dw_ui_test.cc File Reference
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "../dw/core.hh"
#include "../dw/fltkcore.hh"
#include "../dw/fltkviewport.hh"
#include "../dw/table.hh"
#include "../dw/textblock.hh"
#include "../dw/ui.hh"
#include "form.hh"
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References form::Form::addButtonResource(), dw::Table::addCell(), form::Form::addCheckButtonResource(), dw::core::ui::SelectionResource::addItem(), form::Form::addRadioButtonResource(), dw::Table::addRow(), form::Form::addSelectionResource(), dw::Textblock::addText(), form::Form::addTextResource(), dw::Textblock::addWidget(), dw::core::Layout::attachView(), dw::core::style::StyleAttrs::backgroundColor, dw::core::style::StyleAttrs::color, dw::core::style::Font::create(), dw::core::ui::ResourceFactory::createCheckButtonResource(), dw::core::ui::ResourceFactory::createComplexButtonResource(), dw::core::ui::ResourceFactory::createEntryResource(), dw::core::ui::ResourceFactory::createLabelButtonResource(), dw::core::ui::ResourceFactory::createListResource(), dw::core::ui::ResourceFactory::createMultiLineTextResource(), dw::core::ui::ResourceFactory::createOptionMenuResource(), dw::core::ui::ResourceFactory::createRadioButtonResource(), dw::Textblock::flush(), dw::core::style::StyleAttrs::font, dw::core::style::FONT_STYLE_NORMAL, dw::core::style::FONT_VARIANT_NORMAL, dw::core::style::FontAttrs::fontVariant, dw::core::Layout::getResourceFactory(), dw::core::style::StyleAttrs::initValues(), layout, dw::core::style::FontAttrs::letterSpacing, dw::core::style::StyleAttrs::margin, dw::core::style::FontAttrs::name, platform, dw::core::ui::SelectionResource::popGroup(), dw::core::ui::SelectionResource::pushGroup(), dw::core::ui::Embed::setStyle(), dw::core::Widget::setStyle(), dw::core::ui::TextResource::setText(), dw::core::style::Box::setVal(), dw::core::Layout::setWidget(), dw::core::style::FontAttrs::size, dw::core::style::FontAttrs::style, dw::core::style::Style::unref(), viewport, dw::core::style::FontAttrs::weight, and window.