Dillo: test/dw_images_simple.cc File Reference
dw_images_simple.cc File Reference
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include "../dw/core.hh"
#include "../dw/fltkcore.hh"
#include "../dw/fltkviewport.hh"
#include "../dw/textblock.hh"
#include "../dw/image.hh"
Functions
static void imageInitTimeout (void *data)
static void imageDrawTimeout (void *data)
int main (int argc, char **argv)
Variables
static Layout * layout
static Image * image
static core::Imgbuf * imgbuf = NULL
static int imgRow = 0
Function Documentation
static void imageDrawTimeout (void * data) static
References dw::core::Imgbuf::copyRow(), dw::Image::drawRow(), and imgRow.
Referenced by main().
static void imageInitTimeout (void * data) static
References dw::core::Layout::createImgbuf(), dw::core::Imgbuf::RGB, and dw::Image::setBuffer().
Referenced by main().
int main (int argc, char ** argv)
References dw::Textblock::addSpace(), dw::Textblock::addWidget(), dw::core::Layout::attachView(), dw::core::style::StyleAttrs::backgroundColor, dw::core::style::StyleAttrs::color, dw::core::style::Style::create(), dw::core::style::Font::create(), dw::core::style::Color::create(), dw::Textblock::flush(), dw::core::style::StyleAttrs::font, dw::core::style::FONT_STYLE_NORMAL, dw::core::style::FONT_VARIANT_NORMAL, dw::core::style::FontAttrs::fontVariant, imageDrawTimeout(), imageInitTimeout(), dw::core::style::StyleAttrs::initValues(), layout, dw::core::style::FontAttrs::letterSpacing, dw::core::style::StyleAttrs::margin, dw::core::style::FontAttrs::name, platform, dw::core::Widget::setStyle(), dw::core::style::Box::setVal(), dw::core::Layout::setWidget(), dw::core::style::FontAttrs::size, dw::core::style::FontAttrs::style, dw::core::style::Style::unref(), viewport, dw::core::style::FontAttrs::weight, widgetStyle, and window.
Variable Documentation
Image* image static
core::Imgbuf* imgbuf = NULL static
int imgRow = 0 static
Referenced by imageDrawTimeout().
Layout* layout static
Referenced by main().