Dillo: test/dw_find_test.cc File Reference
dw_find_test.cc File Reference
#include <FL/Fl.H>
#include <FL/Fl_Window.H>
#include <FL/Fl_Box.H>
#include "../dw/core.hh"
#include "../dw/fltkcore.hh"
#include "../dw/fltkviewport.hh"
#include "../dw/textblock.hh"
Functions
static void findCallback (Fl_Widget *widget, void *data)
static void resetCallback (Fl_Widget *widget, void *data)
int main (int argc, char **argv)
Variables
static FltkPlatform * platform
static Layout * layout
static Fl_Window * window
static FltkViewport * viewport
static Fl_Button * findButton
static Fl_Button * resetButton
static Fl_Widget * resultLabel
Function Documentation
static void findCallback (Fl_Widget * widget, void * data) static
References resultLabel, and dw::core::Layout::search().
Referenced by main().
int main (int argc, char ** argv)
References dw::Textblock::addLinebreak(), dw::Textblock::addText(), dw::Textblock::addWidget(), dw::core::Layout::attachView(), dw::core::style::StyleAttrs::backgroundColor, dw::core::style::StyleAttrs::color, dw::core::style::Font::create(), findButton, findCallback(), dw::Textblock::flush(), dw::core::style::StyleAttrs::font, dw::core::style::FONT_STYLE_NORMAL, dw::core::style::FONT_VARIANT_NORMAL, dw::core::style::FontAttrs::fontVariant, lout::container::typed::Stack< T >::getTop(), dw::core::style::StyleAttrs::initValues(), layout, dw::core::style::Box::left, dw::core::style::FontAttrs::letterSpacing, dw::core::style::StyleAttrs::margin, dw::core::style::FontAttrs::name, lout::container::typed::Stack< T >::pop(), lout::container::typed::Stack< T >::push(), resetButton, resetCallback(), resultLabel, dw::core::Widget::setStyle(), dw::core::style::Box::setVal(), dw::core::Layout::setWidget(), dw::core::style::FontAttrs::size, dw::core::style::FontAttrs::style, topWidgetStyle, dw::core::style::Style::unref(), dw::core::style::FontAttrs::weight, widgetStyle, window, and wordStyle.
static void resetCallback (Fl_Widget * widget, void * data) static
References dw::core::Layout::resetSearch(), and resultLabel.
Referenced by main().
Variable Documentation
Fl_Button* findButton static
Referenced by main().
Layout* layout static
Referenced by main().
FltkPlatform* platform static
Fl_Button * resetButton static
Referenced by main().
Fl_Widget* resultLabel static
Referenced by findCallback(), main(), and resetCallback().
FltkViewport* viewport static
Fl_Window* window static
Referenced by main().