Dillo: test/liang.cc File Reference
liang.cc File Reference
#include <unistd.h>
#include "../dw/fltkcore.hh"
#include "../dw/hyphenator.hh"
Functions
void hyphenateWord (dw::core::Platform *p, const char *lang, const char *word)
int main (int argc, char *argv[])
Function Documentation
void hyphenateWord (dw::core::Platform * p, const char * lang, const char * word)
References dw::Hyphenator::getHyphenator(), and dw::Hyphenator::hyphenateWord().
Referenced by main(), and dw::Textblock::searchBreakPos().
int main (int argc, char * argv[])
References hyphenateWord().