Dillo: dw::fltk::misc Namespace Reference
dw::fltk::misc Namespace Reference
Miscellaneous FLTK stuff.
Functions
int screenWidth ()
int screenHeight ()
void warpPointer (int x, int y)
Detailed Description
Miscellaneous FLTK stuff.
Function Documentation
int dw::fltk::misc::screenHeight ()
Referenced by dw::fltk::FltkPreviewWindow::reallocate().
int dw::fltk::misc::screenWidth ()
Referenced by dw::fltk::FltkPreviewWindow::reallocate().
void dw::fltk::misc::warpPointer (int x, int y)
Referenced by dw::fltk::FltkPreviewWindow::reallocate().