Dillo: dw::tablecell Namespace Reference
dw::tablecell Namespace Reference
Provided some common implementations of virtual widget methods.
Functions
bool getAdjustMinWidth ()
bool isBlockLevel ()
int correctAvailWidthOfChild (core::Widget *widget, core::Widget *child, int width, bool forceValue)
int correctAvailHeightOfChild (core::Widget *widget, core::Widget *child, int height, bool forceValue)
void correctCorrectedRequisitionOfChild (core::Widget *widget, core::Widget *child, core::Requisition *requisition, void(*splitHeightFun)(int, int *, int *), bool allowDecreaseWidth, bool allowDecreaseHeight)
void correctCorrectedExtremesOfChild (core::Widget *widget, core::Widget *child, core::Extremes *extremes, bool useAdjustmentWidth)
int applyPerWidth (core::Widget *widget, int containerWidth, core::style::Length perWidth)
int applyPerHeight (core::Widget *widget, int containerHeight, core::style::Length perHeight)
bool usesMaxGeneratorWidth ()
bool adjustExtraSpaceWhenCorrectingRequisitionByOOF ()
Detailed Description
Provided some common implementations of virtual widget methods.
Once I understand how diamond inheritance works, a class TableCell will be provided, from which SimpleTableCell and AlignedTableCell will inherit, additionaly (in a multiple way).
Function Documentation
bool dw::tablecell::adjustExtraSpaceWhenCorrectingRequisitionByOOF () inline
Referenced by dw::SimpleTableCell::adjustExtraSpaceWhenCorrectingRequisitionByOOF(), dw::AlignedTableCell::adjustExtraSpaceWhenCorrectingRequisitionByOOF(), and dw::oof::OOFAwareWidget::correctRequisitionByOOF().
int dw::tablecell::applyPerHeight (core::Widget * widget, int containerHeight, core::style::Length perHeight)
References dw::core::style::multiplyWithPerLength().
Referenced by dw::SimpleTableCell::applyPerHeight(), dw::AlignedTableCell::applyPerHeight(), dw::core::Widget::calcHeight(), and dw::core::Widget::getAvailHeight().
int dw::tablecell::applyPerWidth (core::Widget * widget, int containerWidth, core::style::Length perWidth)
References dw::core::style::multiplyWithPerLength().
Referenced by dw::SimpleTableCell::applyPerWidth(), dw::AlignedTableCell::applyPerWidth(), and dw::core::Widget::calcWidth().
int dw::tablecell::correctAvailHeightOfChild (core::Widget * widget, core::Widget * child, int height, bool forceValue)
Referenced by dw::SimpleTableCell::getAvailHeightOfChild(), and dw::AlignedTableCell::getAvailHeightOfChild().
int dw::tablecell::correctAvailWidthOfChild (core::Widget * widget, core::Widget * child, int width, bool forceValue)
References dw::core::Widget::boxDiffWidth(), DBG_OBJ_ENTER_O, DBG_OBJ_LEAVE_O, DBG_OBJ_MSGF_O, dw::core::Widget::getAvailWidth(), lout::misc::max(), and lout::misc::min().
Referenced by dw::SimpleTableCell::getAvailWidthOfChild(), and dw::AlignedTableCell::getAvailWidthOfChild().
void dw::tablecell::correctCorrectedExtremesOfChild (core::Widget * widget, core::Widget * child, core::Extremes * extremes, bool useAdjustmentWidth)
Referenced by dw::SimpleTableCell::correctExtremesOfChild(), and dw::AlignedTableCell::correctExtremesOfChild().
void dw::tablecell::correctCorrectedRequisitionOfChild (core::Widget * widget, core::Widget * child, core::Requisition * requisition, void(*)(int, int *, int *) splitHeightFun, bool allowDecreaseWidth, bool allowDecreaseHeight)
References dw::core::Requisition::ascent, lout::misc::boolToStr(), dw::core::Widget::boxDiffWidth(), DBG_OBJ_ENTER_O, DBG_OBJ_LEAVE_O, DBG_OBJ_MSGF_O, dw::core::Requisition::descent, dw::core::Widget::getAvailWidth(), lout::misc::max(), lout::misc::min(), and dw::core::Requisition::width.
Referenced by dw::SimpleTableCell::correctRequisitionOfChild(), and dw::AlignedTableCell::correctRequisitionOfChild().
bool dw::tablecell::getAdjustMinWidth ()
Referenced by dw::SimpleTableCell::getAdjustMinWidth(), dw::AlignedTableCell::getAdjustMinWidth(), and dw::core::Widget::getMinWidth().
bool dw::tablecell::isBlockLevel ()
Referenced by dw::SimpleTableCell::isBlockLevel(), dw::AlignedTableCell::isBlockLevel(), and dw::core::Widget::isPossibleContainer().
bool dw::tablecell::usesMaxGeneratorWidth () inline
Referenced by dw::Textblock::affectsSizeChangeContainerChild(), dw::Textblock::getAvailWidthOfChild(), dw::Textblock::getGeneratorWidth(), dw::Textblock::oofSizeChanged(), dw::Textblock::sizeRequestImpl(), dw::SimpleTableCell::usesMaxGeneratorWidth(), and dw::AlignedTableCell::usesMaxGeneratorWidth().