Dillo: dw::core Namespace Reference
dw::core Namespace Reference
The core of Dw is defined in this namespace.
Namespaces
style
Anything related to Dillo Widget styles is defined here.
ui
Anything related to embedded UI widgets is defined here.
Classes
struct Allocation
Represents the allocation, i.e. actual position and size of a dw::core::Widget.
class CharIterator
class Circle
dw::core::Shape implemtation for simple circles.
struct Content
class DeepIterator
A stack of iterators, to iterate recursively through a widget tree.
class DrawingContext
Set at the top when drawing.
class EmptyIterator
This implementation of dw::core::Iterator can be used by widgets with no contents.
class Event
Base class for all events.
class EventButton
Represents a button press or release event.
class EventCrossing
Represents a enter or leave notify event.
class EventMotion
Represents a mouse motion event.
struct Extremes
class FindtextState
class GettingWidgetAtPointContext
Set at the top when getting the widget at the point.
class Imgbuf
The platform independent interface for image buffers.
class ImgRenderer
...
class ImgRendererDist
Implementation of ImgRenderer, which distributes all calls to a set of other implementations of ImgRenderer.
class Iterator
Iterators are used to iterate through the contents of a widget.
class Layout
The central class for managing and drawing a widget tree.
class MouseEvent
Base class for all mouse events.
class MousePositionEvent
Base class for all mouse events related to a specific position.
class Platform
An interface to encapsulate some platform dependencies.
struct Point
class Polygon
dw::core::Shape implemtation for polygons.
class Rectangle
dw::core::Shape implemtation for simple rectangles.
class Region
struct Requisition
class SelectionState
This class handles selections, as well as activation of links, which is closely related.
class Shape
Abstract interface for different shapes.
class SizeParams
Hold arguments passed to dw::core::Widget::sizeRequest and dw::core::Widget::getExtremes, as described in Size requisitions depending on positions.
class StackingContextMgr
See Handling stacking contexts.
class StackingProcessingContext
Base class for dw::core::DrawingContext and dw::core::GettingWidgetAtPointContext.
class TextIterator
This implementation of dw::core::Iterator can be used by widgets having one text word as contents.
class View
An interface to encapsulate platform dependent drawing.
class Widget
The base class of all dillo widgets.
class WidgetReference
Typedefs
typedef unsigned char byte
Enumerations
enum ButtonState {
SHIFT_MASK = 1 << 0, CONTROL_MASK = 1 << 1, META_MASK = 1 << 2, BUTTON1_MASK = 1 << 3,
BUTTON2_MASK = 1 << 4, BUTTON3_MASK = 1 << 5
}
Platform independent representation.
enum HPosition {
HPOS_LEFT, HPOS_CENTER, HPOS_RIGHT, HPOS_INTO_VIEW,
HPOS_NO_CHANGE
}
enum VPosition {
VPOS_TOP, VPOS_CENTER, VPOS_BOTTOM, VPOS_INTO_VIEW,
VPOS_NO_CHANGE
}
enum ScrollCommand {
SCREEN_UP_CMD, SCREEN_DOWN_CMD, SCREEN_LEFT_CMD, SCREEN_RIGHT_CMD,
LINE_UP_CMD, LINE_DOWN_CMD, LEFT_CMD, RIGHT_CMD,
TOP_CMD, BOTTOM_CMD
}
enum HighlightLayer { HIGHLIGHT_SELECTION, HIGHLIGHT_FINDTEXT, HIGHLIGHT_NUM_LAYERS }
Functions
void freeall ()
void splitHeightPreserveAscent (int height, int *ascent, int *descent)
void splitHeightPreserveDescent (int height, int *ascent, int *descent)
Detailed Description
The core of Dw is defined in this namespace.
See also
Dillo Widget Overview
Typedef Documentation
typedef unsigned char dw::core::byte
Enumeration Type Documentation
enum dw::core::ButtonState
Platform independent representation.
Enumerator
SHIFT_MASK
CONTROL_MASK
META_MASK
BUTTON1_MASK
BUTTON2_MASK
BUTTON3_MASK
enum dw::core::HighlightLayer
Enumerator
HIGHLIGHT_SELECTION
HIGHLIGHT_FINDTEXT
HIGHLIGHT_NUM_LAYERS
enum dw::core::HPosition
Enumerator
HPOS_LEFT
HPOS_CENTER
HPOS_RIGHT
HPOS_INTO_VIEW
HPOS_NO_CHANGE
enum dw::core::ScrollCommand
Enumerator
SCREEN_UP_CMD
SCREEN_DOWN_CMD
SCREEN_LEFT_CMD
SCREEN_RIGHT_CMD
LINE_UP_CMD
LINE_DOWN_CMD
LEFT_CMD
RIGHT_CMD
TOP_CMD
BOTTOM_CMD
enum dw::core::VPosition
Enumerator
VPOS_TOP
VPOS_CENTER
VPOS_BOTTOM
VPOS_INTO_VIEW
VPOS_NO_CHANGE
Function Documentation
void dw::core::freeall () inline
void dw::core::splitHeightPreserveAscent (int height, int * ascent, int * descent)
References DBG_OBJ_ENTER_S, and DBG_OBJ_LEAVE_VAL_S.
Referenced by dw::oof::OOFPosAbsLikeMgr::calcVPosAndSizeChildOfChild(), dw::Textblock::sizeRequestImpl(), dw::SimpleContainer::sizeRequestSimpl(), and dw::core::ui::Embed::sizeRequestSimpl().
void dw::core::splitHeightPreserveDescent (int height, int * ascent, int * descent)
References DBG_OBJ_ENTER_S, and DBG_OBJ_LEAVE_VAL_S.
Referenced by dw::Table::actuallyCalcCellSizes(), dw::Image::sizeRequestSimpl(), and dw::Table::sizeRequestSimpl().