Dillo: lout::unicode Namespace Reference
lout::unicode Namespace Reference
Stuff dealing with Unicode characters: UTF-8, character classes etc.
Functions
bool isAlpha (int ch)
int decodeUtf8 (const char *s)
int decodeUtf8 (const char *s, int len)
const char * nextUtf8Char (const char *s)
const char * nextUtf8Char (const char *s, int len)
int numUtf8Chars (const char *s)
int numUtf8Chars (const char *s, int len)
Variables
static unsigned char alpha [0x500]
Detailed Description
Stuff dealing with Unicode characters: UTF-8, character classes etc.
Function Documentation
int lout::unicode::decodeUtf8 (const char * s)
Referenced by dw::Hyphenator::isCharPartOfActualWord(), and main().
int lout::unicode::decodeUtf8 (const char * s, int len)
bool lout::unicode::isAlpha (int ch)
Returns whether a given unicode character is an alphabetic character.
Referenced by dw::Hyphenator::isCharPartOfActualWord().
const char * lout::unicode::nextUtf8Char (const char * s)
Referenced by dw::Textblock::addText(), dw::Hyphenator::hyphenateSingleWord(), and main().
const char * lout::unicode::nextUtf8Char (const char * s, int len)
Referenced by numUtf8Chars().
int lout::unicode::numUtf8Chars (const char * s)
References nextUtf8Char().
Referenced by dw::Hyphenator::hyphenateSingleWord().
int lout::unicode::numUtf8Chars (const char * s, int len)
References nextUtf8Char().
Variable Documentation
unsigned char lout::unicode::alpha[0x500] static