Dillo: dw::fltk Namespace Reference
dw::fltk Namespace Reference
This namespace contains FLTK implementations of Dw interfaces.
Namespaces
misc
Miscellaneous FLTK stuff.
ui
FLTK implementation of dw::core::ui.
Classes
class FltkColor
class FltkFlatView
class FltkFont
class FltkImgbuf
class FltkPlatform
class FltkPreview
class FltkPreviewButton
class FltkPreviewWindow
class FltkTooltip
class FltkView
This interface adds some more methods for all flkt-based views.
class FltkViewBase
class FltkViewport
class FltkWidgetView
Enumerations
enum ScaleMode { SIMPLE, BEAUTIFUL, BEAUTIFUL_GAMMA }
Functions
void freeall ()
static void strstrip (char *big, const char *little)
static void tooltip_tcb (void *data)
core::ButtonState getDwButtonState ()
Variables
enum dw::fltk::ScaleMode scaleMode = BEAUTIFUL_GAMMA
Detailed Description
This namespace contains FLTK implementations of Dw interfaces.
Enumeration Type Documentation
enum dw::fltk::ScaleMode
Enumerator
SIMPLE
BEAUTIFUL
BEAUTIFUL_GAMMA
Function Documentation
void dw::fltk::freeall () inline
References dw::fltk::FltkImgbuf::freeall().
core::ButtonState dw::fltk::getDwButtonState ()
References dw::core::BUTTON1_MASK, dw::core::BUTTON2_MASK, dw::core::BUTTON3_MASK, dw::core::CONTROL_MASK, dw::core::META_MASK, and dw::core::SHIFT_MASK.
Referenced by dw::fltk::FltkViewBase::handle().
static void dw::fltk::strstrip (char * big, const char * little) static
References lout::misc::AsciiStrcasecmp().
Referenced by dw::fltk::FltkFont::initSystemFonts().
static void dw::fltk::tooltip_tcb (void * data) static
References req_tooltip.
Referenced by dw::fltk::FltkTooltip::cancel(), and dw::fltk::FltkTooltip::onEnter().
Variable Documentation
enum dw::fltk::ScaleMode dw::fltk::scaleMode = BEAUTIFUL_GAMMA
Referenced by dw::fltk::FltkImgbuf::scaleBuffer(), and dw::fltk::FltkImgbuf::scaleRow().