Dillo: lout::misc Namespace Reference
lout::misc Namespace Reference
Miscellaneous stuff, which does not fit anywhere else.
Classes
class BitSet
A bit set, which automatically reallocates when needed.
class NotSoSimpleVector
Container similar to lout::misc::SimpleVector, but some cases of insertion optimized (used for hyphenation).
class SimpleVector
Simple (simpler than container::untyped::Vector and container::typed::Vector) template based vector.
class StringBuffer
A class for fast concatenation of a large number of strings.
class ZoneAllocator
A simple allocator optimized to handle many small chunks of memory. The chunks can not be free'd individually. Instead the whole zone must be free'd with zoneFree().
Functions
void init (int argc, char *argv[])
template<class T >
T min (T a, T b)
template<class T >
T max (T a, T b)
template<class T >
T min (T a, T b, T c)
template<class T >
T max (T a, T b, T c)
void assertNotReached ()
void assertNotReached (const char *fmt,...)
void notImplemented (const char *name)
int roundInt (double d)
int AsciiTolower (char c)
int AsciiToupper (char c)
int AsciiStrcasecmp (const char *s1, const char *s2)
const char * boolToStr (bool b)
Variables
const char * prgName = PRGNAME
Detailed Description
Miscellaneous stuff, which does not fit anywhere else.
Actually, the other parts, beginning with object, depend on this.
Function Documentation
int lout::misc::AsciiStrcasecmp (const char * s1, const char * s2) inline
References AsciiTolower().
Referenced by dw::fltk::strstrip().
int lout::misc::AsciiTolower (char c) inline
Referenced by AsciiStrcasecmp(), and dw::core::style::strAsciiTolower().
int lout::misc::AsciiToupper (char c) inline
Referenced by main(), and textTimeout().
void lout::misc::assertNotReached () inline
Referenced by dw::oof::OOFFloatsMgr::addWidgetOOF(), dw::Textblock::BadnessAndPenalty::badnessValue(), dw::oof::OOFFloatsMgr::calcFloatX(), dw::Textblock::calcTextOffset(), lout::object::Object::clone(), dw::core::TextIterator::compareTo(), dw::core::Layout::LinkEmitter::emitToReceiver(), dw::core::Layout::Emitter::emitToReceiver(), dw::core::ui::Resource::ActivateEmitter::emitToReceiver(), lout::object::Object::equals(), dw::Table::forceCalcCellSizes(), dw::oof::OOFFloatsMgr::getBorder(), dw::oof::OOFFloatsMgr::getClearPosition(), dw::Table::getExtreme(), dw::Table::getExtrModName(), dw::oof::OOFFloatsMgr::getFloatsListsAndSide(), dw::Textblock::getGeneratorRest(), dw::Textblock::getGeneratorX(), dw::Textblock::getGeneratorY(), dw::oof::OOFAwareWidget::getOOFMIndex(), dw::oof::OOFAwareWidget::getWidgetAtPointLevel(), dw::core::SelectionState::handleEvent(), dw::SimpleContainer::SimpleContainerIterator::index(), dw::Textblock::isBreakAllowed(), dw::oof::OOFAwareWidget::isOOFContainer(), dw::oof::OOFFloatsMgr::markSizeChange(), dw::core::Layout::processMouseEvent(), dw::core::DeepIterator::searchSideward(), dw::Table::setExtreme(), and dw::core::style::Color::shadeColor().
void lout::misc::assertNotReached (const char * fmt, ...) inline
const char* lout::misc::boolToStr (bool b) inline
Referenced by dw::Textblock::addAnchor(), dw::core::Widget::affectedByContainerSizeChange(), dw::core::Widget::affectsSizeChangeContainerChild(), dw::Textblock::affectsSizeChangeContainerChild(), dw::Textblock::calcSizeOfWidgetInFlow(), dw::tablecell::correctCorrectedRequisitionOfChild(), dw::core::Widget::correctReqHeightOfChild(), dw::core::Widget::correctRequisition(), dw::SimpleTableCell::correctRequisitionOfChild(), dw::AlignedTableCell::correctRequisitionOfChild(), dw::core::Widget::correctRequisitionOfChild(), dw::core::Widget::correctReqWidthOfChild(), dw::oof::OOFAwareWidget::doesWidgetOOFInterruptDrawing(), dw::core::SizeParams::isEquivalent(), dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::next(), dw::oof::OOFPosAbsLikeMgr::posXAbsolute(), dw::oof::OOFPosAbsLikeMgr::posYAbsolute(), dw::oof::OOFAwareWidget::OOFAwareWidgetIterator::prev(), dw::Textblock::sendSelectionEvent(), dw::Textblock::usesMaxGeneratorWidth(), and dw::Textblock::wrapWordInFlow().
void lout::misc::init (int argc, char * argv[])
Referenced by dw::core::SizeParams::cleanup(), dw::fltk::ui::FltkComplexButtonResource::FltkComplexButtonResource(), dw::fltk::FltkImgbuf::FltkImgbuf(), dw::fltk::FltkImgbuf::init(), dw::core::SizeParams::operator=(), and dw::core::SizeParams::SizeParams().
template<class T > T lout::misc::max (T a, T b) inline
Referenced by dw::Textblock::accumulateWordData(), dw::Textblock::accumulateWordForLine(), dw::Table::actuallyCalcCellSizes(), dw::Table::addCell(), dw::Textblock::addLine(), dw::Textblock::addParbreak(), dw::core::Polygon::addPoint(), dw::core::Region::addRectangle(), dw::core::Layout::adjustScrollPos(), dw::Table::apportion2(), dw::core::Layout::attachView(), dw::Table::calcAvailWidthForDescendant(), dw::Textblock::calcBorders(), dw::Textblock::calcExtraSpaceImpl(), dw::Table::calcExtremesSpanMultiCols(), dw::oof::OOFFloatsMgr::calcFloatX(), dw::core::Widget::calcHeight(), dw::Textblock::calcLineBreakWidth(), dw::Textblock::calcLinePartHeight(), dw::Textblock::calcTextSize(), dw::core::Widget::calcWidth(), dw::Image::contentX(), dw::Image::contentY(), dw::tablecell::correctAvailWidthOfChild(), dw::tablecell::correctCorrectedRequisitionOfChild(), dw::oof::OOFAwareWidget::correctExtremesByOOF(), dw::core::ui::ComplexButtonResource::correctExtremesOfChild(), dw::oof::OOFAwareWidget::correctRequisitionByOOF(), dw::core::ui::ComplexButtonResource::correctRequisitionOfChild(), dw::core::Layout::draw(), dw::core::style::drawBackgroundImage(), dw::core::style::StyleImage::ExternalImgRenderer::drawRow(), dw::Textblock::fillParagraphs(), dw::fltk::FltkFont::FltkFont(), dw::Table::forceCalcColumnExtremes(), dw::Textblock::TextblockIterator::getAllocation(), dw::oof::OOFPosAbsLikeMgr::getAvailHeightOfChild(), dw::core::Widget::getAvailHeightOfChild(), dw::core::ui::ComplexButtonResource::getAvailHeightOfChild(), dw::oof::OOFPosAbsLikeMgr::getAvailWidthOfChild(), dw::core::Widget::getAvailWidthOfChild(), dw::core::ui::ComplexButtonResource::getAvailWidthOfChild(), dw::Textblock::getAvailWidthOfChild(), dw::oof::OOFFloatsMgr::getBorder(), dw::oof::OOFFloatsMgr::getClearPosition(), dw::Table::getExtreme(), dw::oof::OOFPosRelMgr::getExtremes(), dw::oof::OOFPosAbsLikeMgr::getExtremes(), dw::oof::OOFFloatsMgr::getExtremes(), dw::Bullet::getExtremesSimpl(), dw::oof::OOFFloatsMgr::getFloatsExtremes(), dw::oof::OOFFloatsMgr::getFloatsSize(), dw::Textblock::getGeneratorWidth(), dw::fltk::ui::FltkOptionMenuResource::getMaxItemWidth(), dw::core::Layout::LayoutImgRenderer::getRefArea(), dw::oof::OOFPosRelMgr::getSize(), dw::oof::OOFPosAbsLikeMgr::getSize(), dw::oof::OOFFloatsMgr::getSize(), dw::Textblock::handleWordExtremes(), dw::Hyphenator::hyphenateSingleWord(), dw::core::Rectangle::intersectsWith(), max(), dw::core::Layout::queueDrawExcept(), dw::Textblock::queueDrawRange(), dw::fltk::FltkImgbuf::scaleBuffer(), dw::fltk::FltkViewport::scrollTo(), dw::core::Iterator::scrollTo(), dw::core::style::StyleImage::StyleImgRenderer::setBuffer(), dw::core::style::Color::shadeColor(), dw::Bullet::sizeRequestSimpl(), dw::Ruler::sizeRequestSimpl(), dw::Textblock::Line::totalHeight(), and dw::Textblock::wrapWordInFlow().
template<class T > T lout::misc::max (T a, T b, T c) inline
References max().
template<class T > T lout::misc::min (T a, T b) inline
Referenced by dw::Table::actuallyCalcCellSizes(), dw::core::Polygon::addPoint(), dw::core::Region::addRectangle(), dw::core::Layout::adjustScrollPos(), dw::Table::apportion2(), dw::Table::calcAvailWidthForDescendant(), dw::oof::OOFFloatsMgr::calcFloatX(), dw::Textblock::calcSizeOfWidgetInFlow(), dw::Image::contentX(), dw::Image::contentY(), dw::fltk::FltkImgbuf::copyTo(), dw::tablecell::correctAvailWidthOfChild(), dw::core::SelectionState::correctCharPos(), dw::tablecell::correctCorrectedRequisitionOfChild(), dw::Bullet::draw(), dw::core::style::drawBackgroundImage(), dw::core::style::StyleImage::ExternalImgRenderer::drawRow(), dw::Textblock::drawWord0(), dw::Textblock::fillParagraphs(), dw::Textblock::TextblockIterator::getAllocation(), dw::Table::getExtreme(), dw::Ruler::getExtremesSimpl(), dw::Image::getExtremesSimpl(), dw::core::ui::Embed::getExtremesSimpl(), dw::Textblock::getGeneratorWidth(), dw::Hyphenator::hyphenateSingleWord(), dw::core::Rectangle::intersectsWith(), dw::Textblock::markExtremesChange(), dw::Textblock::markSizeChange(), min(), dw::core::Layout::processMouseEvent(), dw::core::Layout::queueDrawExcept(), dw::Textblock::queueDrawRange(), dw::Textblock::rewrap(), dw::fltk::FltkViewport::scrollTo(), dw::core::Iterator::scrollTo(), dw::Table::setCumHeight(), dw::Textblock::sizeAllocateImpl(), and dw::Textblock::wrapWordInFlow().
template<class T > T lout::misc::min (T a, T b, T c) inline
References min().
void lout::misc::notImplemented (const char * name) inline
Referenced by dw::oof::OOFAwareWidget::clearPositionChanged(), dw::core::ui::Resource::correctExtremesOfChild(), dw::core::ui::Resource::correctRequisitionOfChild(), dw::oof::OOFPosRelMgr::getAvailHeightOfChild(), dw::oof::OOFFloatsMgr::getAvailHeightOfChild(), dw::core::ui::Resource::getAvailHeightOfChild(), dw::oof::OOFPosRelMgr::getAvailWidthOfChild(), dw::oof::OOFFloatsMgr::getAvailWidthOfChild(), dw::core::ui::Resource::getAvailWidthOfChild(), dw::core::Widget::getExtremesReference(), dw::core::Widget::getExtremesSimpl(), dw::oof::OOFAwareWidget::getGeneratorWidth(), dw::oof::OOFAwareWidget::getGeneratorX(), dw::oof::OOFAwareWidget::getGeneratorY(), dw::oof::OOFAwareWidget::getMaxGeneratorWidth(), dw::core::Widget::removeChild(), dw::core::Widget::sizeRequestReference(), dw::core::Widget::sizeRequestSimpl(), dw::oof::OOFFloatsMgr::tellIncompletePosition1(), dw::oof::OOFFloatsMgr::tellIncompletePosition2(), dw::oof::OOFAwareWidget::updateReference(), dw::oof::OOFAwareWidget::usesMaxGeneratorWidth(), and dw::oof::OOFAwareWidget::widgetRefSizeChanged().
int lout::misc::roundInt (double d) inline
Referenced by dw::Textblock::calcTextSize(), dw::fltk::FltkWidgetView::drawText(), dw::core::style::multiplyWithPerLengthRounded(), and dw::fltk::FltkPlatform::textWidth().
Variable Documentation
const char * lout::misc::prgName = PRGNAME