Dillo: test/notsosimplevector.cc File Reference
notsosimplevector.cc File Reference
#include "../lout/misc.hh"
Functions
static void print (lout::misc::NotSoSimpleVector< int > *v)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
References lout::misc::NotSoSimpleVector< T >::increase(), lout::misc::NotSoSimpleVector< T >::insert(), print(), lout::misc::NotSoSimpleVector< T >::set(), and lout::misc::NotSoSimpleVector< T >::size().
static void print (lout::misc::NotSoSimpleVector< int > * v) static
References lout::misc::NotSoSimpleVector< T >::get(), and lout::misc::NotSoSimpleVector< T >::size().
Referenced by main().