Dillo: lout::container::typed::Collection< T > Class Template Reference
lout::container::typed::Collection< T > Class Template Reference
Abstract base class template for all container objects in container::typed.
#include <container.hh>
Public Member Functions
Collection ()
~Collection ()
bool equals (Object *other)
Returns, whether two objects are equal.
int hashValue ()
Return a hash value for the object.
void intoStringBuffer (misc::StringBuffer *sb)
Store a textual representation of the object in a misc::StringBuffer.
Iterator< T > iterator ()
int size ()
Public Member Functions inherited from lout::object::Object
virtual ~Object ()
The destructor is defined as virtual (but not abstract), so that destruction of Object's works properly.
virtual Object * clone ()
Return an exact copy of the object.
const char * toString ()
Use object::Object::intoStringBuffer to return a textual representation of the object.
virtual size_t sizeOf ()
Return the number of bytes, this object totally uses.
Protected Attributes
untyped::Collection * base
Detailed Description
template<class T>
class lout::container::typed::Collection< T >
Abstract base class template for all container objects in container::typed.
Actually, a wrapper for container::untyped::Collection.
Constructor & Destructor Documentation
template<class T> lout::container::typed::Collection< T >::Collection () inline
template<class T> lout::container::typed::Collection< T >::~Collection () inline
Member Function Documentation
template<class T> bool lout::container::typed::Collection< T >::equals (Object * other) inline virtual
Returns, whether two objects are equal.
The caller should ensure, that this and the object have the same class; this makes casting of "other" safe. Typically, an implementation should check this == other first, the caller can assume a fast implementation.
Reimplemented from lout::object::Object.
template<class T> int lout::container::typed::Collection< T >::hashValue () inline virtual
Return a hash value for the object.
Reimplemented from lout::object::Object.
template<class T> void lout::container::typed::Collection< T >::intoStringBuffer (misc::StringBuffer * sb) inline virtual
Store a textual representation of the object in a misc::StringBuffer.
This is used by object::Object::toString.
Reimplemented from lout::object::Object.
template<class T> Iterator<T> lout::container::typed::Collection< T >::iterator () inline
Referenced by dw::fltk::FltkViewport::adjustScrollbarsAndGadgetsAllocation(), dw::fltk::FltkPlatform::attachView(), dw::fltk::FltkPlatform::detachView(), dw::fltk::FltkViewport::draw_area(), dw::oof::OOFFloatsMgr::SortedFloatsVector::iterator(), dw::fltk::ui::FltkRadioButtonResource::Group::iterator(), dw::core::Region::rectangles(), and testVector2().
template<class T> int lout::container::typed::Collection< T >::size () inline
Referenced by dw::fltk::FltkViewport::adjustScrollbarsAndGadgetsAllocation(), dw::core::DeepIterator::clone(), dw::core::DeepIterator::compareTo(), dw::core::StackingContextMgr::getNumChildSCWidgets(), dw::Hyphenator::hyphenateSingleWord(), dw::Hyphenator::insertException(), dw::oof::OOFFloatsMgr::moveExternalIndices(), dw::core::DeepIterator::next(), dw::core::DeepIterator::prev(), dw::oof::OOFFloatsMgr::SortedFloatsVector::size(), and testStackAsQueue().
Member Data Documentation
template<class T> untyped::Collection* lout::container::typed::Collection< T >::base protected
Referenced by lout::container::typed::List< lout::object::TypedPointer< Fl_Widget > >::append(), lout::container::typed::Vector< dw::fltk::FltkImgbuf::GammaCorrectionTable >::bsearch(), lout::container::typed::Vector< dw::fltk::FltkImgbuf::GammaCorrectionTable >::clear(), lout::container::typed::List< lout::object::TypedPointer< Fl_Widget > >::clear(), lout::container::typed::HashSet< lout::object::lout::object::TypedPointer< dw::core::Widget > >::contains(), lout::container::typed::List< lout::object::TypedPointer< Fl_Widget > >::detachRef(), lout::container::typed::Vector< dw::fltk::FltkImgbuf::GammaCorrectionTable >::get(), lout::container::typed::List< lout::object::TypedPointer< Fl_Widget > >::getFirst(), lout::container::typed::List< lout::object::TypedPointer< Fl_Widget > >::getLast(), lout::container::typed::Stack< T >::getTop(), lout::container::typed::HashSet< lout::object::lout::object::TypedPointer< dw::core::Widget > >::HashSet(), lout::container::typed::Vector< dw::fltk::FltkImgbuf::GammaCorrectionTable >::insert(), lout::container::typed::List< lout::object::TypedPointer< Fl_Widget > >::insertBefore(), lout::container::typed::Vector< dw::fltk::FltkImgbuf::GammaCorrectionTable >::insertSorted(), lout::container::typed::List< lout::object::TypedPointer< Fl_Widget > >::isEmpty(), lout::container::typed::List< lout::object::TypedPointer< Fl_Widget > >::List(), lout::container::typed::Stack< T >::pop(), lout::container::typed::Stack< T >::push(), lout::container::typed::Stack< T >::pushUnder(), lout::container::typed::Vector< dw::fltk::FltkImgbuf::GammaCorrectionTable >::put(), lout::container::typed::HashSet< lout::object::lout::object::TypedPointer< dw::core::Widget > >::put(), lout::container::typed::Vector< dw::fltk::FltkImgbuf::GammaCorrectionTable >::remove(), lout::container::typed::List< lout::object::TypedPointer< Fl_Widget > >::remove(), lout::container::typed::HashSet< lout::object::lout::object::TypedPointer< dw::core::Widget > >::remove(), lout::container::typed::List< lout::object::TypedPointer< Fl_Widget > >::removeRef(), lout::container::typed::Vector< dw::fltk::FltkImgbuf::GammaCorrectionTable >::sort(), lout::container::typed::Stack< T >::Stack(), lout::container::typed::Vector< dw::fltk::FltkImgbuf::GammaCorrectionTable >::Vector(), and lout::container::typed::Collection< lout::object::lout::object::TypedPointer< dw::core::Widget > >::~Collection().
The documentation for this class was generated from the following file:
lout/container.hh