/*
 * File: pixmaps.h
 *
 * Copyright (C) 2000, 2001-2008 Jorge Arellano Cid <jcid@dillo.org>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 */

#ifndef __PIXMAPS_H__
#define __PIXMAPS_H__

/* XPM
static const char *const history_xpm[] = {
"11 20 6 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"O      c #FFFF9A690000",
"+      c #FFFFFFFF0000",
"@      c #FFFFFFFFFFFF",
"           ",
"     .     ",
"    .X.    ",
"   .XXX.   ",
"  .XXXXX.  ",
" .XXXXXXX. ",
" ...XXX... ",
"   .XXX.   ",
"   .XXX.   ",
"   .XXX.   ",
"   OOOOO   ",
"   .XXX.   ",
"   .XXX.   ",
" ...XXX... ",
" .XXXXXXX. ",
"  .XXXXX.  ",
"   .XXX.   ",
"    .X.    ",
"     .     ",
"           "};
*/
/* XPM */
static const char *const left_xpm[] = {
"26 20 6 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"O      c #FFFF9A690000",
"+      c #FFFFFFFF0000",
"@      c #FFFFFFFFFFFF",
"                          ",
"          ..              ",
"         .X.              ",
"        .XX.              ",
"       .XXX.              ",
"      .XXXX.              ",
"     .XXXXX........ +OO+O ",
"    .XXXXXXXXXXXXX. +OO+O ",
"   .XXXXXXXXXXXXXX. +OO+O ",
"  .XXXXXXXXXXXXXXX. +OO+O ",
"  .XXXXXXXXXXXXXXX. +OO+O ",
"   .XXXXXXXXXXXXXX. +OO+O ",
"    .XXXXXXXXXXXXX. +OO+O ",
"     .XXXXX........ +OO+O ",
"      .XXXX.              ",
"       .XXX.              ",
"        .XX.              ",
"         .X.              ",
"          ..              ",
"                          "};
/* XPM */
static const char *const right_xpm[] = {
"26 20 6 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"O      c #FFFF9A690000",
"+      c #FFFFFFFF0000",
"@      c #FFFFFFFFFFFF",
"                          ",
"              ..          ",
"              .X.         ",
"              .XX.        ",
"              .XXX.       ",
"              .XXXX.      ",
" O+OO+ ........XXXXX.     ",
" O+OO+ .XXXXXXXXXXXXX.    ",
" O+OO+ .XXXXXXXXXXXXXX.   ",
" O+OO+ .XXXXXXXXXXXXXXX.  ",
" O+OO+ .XXXXXXXXXXXXXXX.  ",
" O+OO+ .XXXXXXXXXXXXXX.   ",
" O+OO+ .XXXXXXXXXXXXX.    ",
" O+OO+ ........XXXXX.     ",
"              .XXXX.      ",
"              .XXX.       ",
"              .XX.        ",
"              .X.         ",
"              ..          ",
"                          "};
/* XPM */
static const char *const reload_xpm[] = {
"26 20 6 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"O      c #FFFF9A690000",
"+      c #FFFFFFFF0000",
"@      c #FFFFFFFFFFFF",
"         .    ....        ",
"         ..   .OOO.       ",
"      ....X.  .OOOO.      ",
"     .XXXXXX. .OOOOO.     ",
"    .XXXXXXXX....OOO.     ",
"   .XXXXXXXX.   .OOO.     ",
"   .XXX...X.  ...OOO...   ",
"   .XXX. ..    .OOOOO.    ",
"   ..... .      .OOO.     ",
"       .         .O.      ",
"      .O.         .       ",
"     .OOO.      . .....   ",
"    .OOOOO.    .. .XXX.   ",
"   ...OOO...  .X...XXX.   ",
"     .OOO.   .XXXXXXXX.   ",
"     .OOO....XXXXXXXX.    ",
"     .OOOOO. .XXXXXX.     ",
"      .OOOO.  .X....      ",
"       .OOO.   ..         ",
"        ....    .         "};
/* XPM */
static const char *const home_xpm[] = {
"26 20 9 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"O      c #FFFF9A690000",
"+      c #FFFFFFFF0000",
"z      c #0000FFFFFFFF",
"@      c #FFFFFFFFFFFF",
"I      c #FFFF00000000",
"#      c #FFFF0000FFFF",
"                          ",
"            XX            ",
"           ....           ",
"          ......          ",
"         ........         ",
"        ....oo....        ",
"       ....o..o....       ",
"      ..............      ",
"     ................     ",
"    .....zzzzzzzz.....    ",
"        .OOOOOOOO.        ",
"       .OOOOOOOOOO.       ",
"       .OOOOOOOOOO.       ",
"       .OOOO...OOO.       ",
"       .OOO.I@.OOO.       ",
"       .OOO.I#@.OO.       ",
"     X .OOO.I#@.OO.       ",
"   XXXX.OOO.I#@.OO. XXX   ",
" XXXXXX.OOO.I#@.OO.XXXXXX ",
"XXXXXXX............XXXXXXX"};
/* XPM */
static const char *const save_xpm[] = {
"26 20 6 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"O      c #FFFF9A690000",
"+      c #FFFFFFFF0000",
"@      c #FFFFFFFFFFFF",
"                          ",
"   ....................   ",
"   .XXXXXXXXXXXXXXXXXX.   ",
"   ...XXXXXXXXXXXXXXXX.   ",
"   .XX..............XX.   ",
"   .XX.@@@@@@@@@@@@.XX.   ",
"   .XX..............XX.   ",
"   .XX.@@@@@@@@@@@@.XX.   ",
"   .XX..............XX.   ",
"   .XX.@@@@@@@@@@@@.XX.   ",
"   .XX..............XX.   ",
"   .XXXXXXXXXXXXXXXXXX.   ",
"   .XXXXXXXXXXXXXXXXXX.   ",
"   .XXX...........XXXX.   ",
"   .XXX.OOOOOOOOOO.XXX.   ",
"   .XXX.O....OOOOO.XXX.   ",
"   .XXX.O.  .OOOOO.XXX.   ",
"   .XXX.O.  .OOOOO.XXX.   ",
"   .XXX.O.  .OOOOO.XXX.   ",
"    ..................    "};
/* XPM */
static const char *const stop_xpm[] = {
"26 20 6 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"O      c #FFFF9A690000",
"+      c #FFFFFFFF0000",
"@      c #FFFFFFFFFFFF",
"                          ",
"         ........         ",
"        .XXXXXXXX.        ",
"       .XXXX..XXXX.       ",
"      .XXXX.OO.XXXX.      ",
"     .XXXXX.OO.XXXXX.     ",
"    .XXXXXX.OO.XXXXXX.    ",
"    .XXXXXX.OO.XXXXXX.    ",
"    .XXXXXX.OO.XXXXXX.    ",
"    .XXXXXX.OO.XXXXXX.    ",
"    .XXXXXX.OO.XXXXXX.    ",
"    .XXXXXXX..XXXXXXX.    ",
"    .XXXXXXXXXXXXXXXX.    ",
"    .XXXXXXX..XXXXXXX.    ",
"     .XXXXX.OO.XXXXX.     ",
"      .XXXX.OO.XXXX.      ",
"       .XXXX..XXXX.       ",
"        .XXXXXXXX.        ",
"         ........         ",
"                          "};
/* XPM */
static const char *const bm_xpm[] = {
"26 20 6 1",
"       c None",
"@      c #FFFFFFFFFFFF",
"X      c #9658A289BEFB",
".      c #000000000000",
"O      c #FFFF9A690000",
"+      c #F8F8D4D49090",
"                          ",
"      @X@X@X@X@X@X@       ",
"      .X.X.X.X.X.X.X      ",
"     .XXXXXXXXXXXXX.X     ",
"     .XXXXXXXXXXXXX.OX    ",
"     .X......XXXXXX.+.    ",
"     .XX.XXX..X...X.+.    ",
"     .XX.XXXX.XXXXX.+.    ",
"     .XX.XXX..X...X.+.    ",
"     .XX.....XXXXXX.+.    ",
"     .XX.XXXX.X...X.+.    ",
"     .XX.XXXX.XXXXX.+.    ",
"     .XX.XXX..XXXXX.+.    ",
"     .X......XXXXXX.+.    ",
"     .XXXXXXXXXXXXX.+.    ",
"     .XXXXXXXXXXXXX.+.    ",
"     .XXXXXXXXXXXXX.+.    ",
"     ...............+.    ",
"      .++++++++++++++.    ",
"       ...............    "};

/* Small icons here */

/* XPM */
static const char *const left_s_xpm[] = {
"17 15 5 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"o      c #FFFF9A690000",
"O      c #FFFFFFFF0000",
"                 ",
"      ..         ",
"     .X.         ",
"    .XX.         ",
"   .XXX...... oOo",
"  .XXXXXXXXX. oOo",
" .XXXXXXXXXX. oOo",
".XXXXXXXXXXX. oOo",
" .XXXXXXXXXX. oOo",
"  .XXXXXXXXX. oOo",
"   .XXX...... oOo",
"    .XX.         ",
"     .X.         ",
"      ..         ",
"                 "};
/* XPM */
static const char *const right_s_xpm[] = {
"17 15 5 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"o      c #FFFF9A690000",
"O      c #FFFFFFFF0000",
"                 ",
"         ..      ",
"         .X.     ",
"         .XX.    ",
"oOo ......XXX.   ",
"oOo .XXXXXXXXX.  ",
"oOo .XXXXXXXXXX. ",
"oOo .XXXXXXXXXXX.",
"oOo .XXXXXXXXXX. ",
"oOo .XXXXXXXXX.  ",
"oOo ......XXX.   ",
"         .XX.    ",
"         .X.     ",
"         ..      ",
"                 "};
/* XPM */
static const char *const home_s_xpm[] = {
"17 15 7 1",
"       c None",
".      c #9658A289BEFB",
"X      c #000000000000",
"o      c #FFFF0000FFFF",
"O      c #FFFF9A690000",
"+      c #FFFF00000000",
"@      c #FFFFFFFFFFFF",
"        .        ",
"       XXX       ",
"      XXXXX      ",
"     XXXoXXX     ",
"    XXXoXoXXX    ",
"   XXXXXXXXXXX   ",
"  XXXXXXXXXXXXX  ",
"     XOOOOOX     ",
"    XOOOOOOOX    ",
"    XOOOXXOOX    ",
"    XOOX+oXOX    ",
"    XOOXo@XOX    ",
"    XOOXo@XOX..  ",
" ...XOOXo@XOX....",
"....XXXXXXXXX...."};
/* XPM */
static const char *const reload_s_xpm[] = {
"17 15 4 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"o      c #FFFF9A690000",
"      .   ..     ",
"   ...X. .oo.    ",
"  .XXXXX..ooo.   ",
" .XXXXXX. .oo.   ",
" .XX..X.  .oo.   ",
" .XX. .  .oooo.  ",
"  ..      .oo.   ",
"   ..      ..    ",
"  .oo.      ..   ",
" .oooo.  . .XX.  ",
"  .oo.  .X..XX.  ",
"  .oo. .XXXXXX.  ",
"  .ooo..XXXXX.   ",
"   .oo. .X...    ",
"    ..   .       "};
/* XPM */
static const char *const save_s_xpm[] = {
"17 15 5 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"o      c #FFFFFFFFFFFF",
"O      c #FFFF9A690000",
" ............... ",
" ..XXXXXXXXXXXX. ",
" .X...........X. ",
" .X.ooooooooo.X. ",
" .X...........X. ",
" .X.ooooooooo.X. ",
" .X...........X. ",
" .XXXXXXXXXXXXX. ",
" .XXXXXXXXXXXXX. ",
" .XX........XXX. ",
" .XX.OOOOOOO.XX. ",
" .XX.O...OOO.XX. ",
" .XX.O. .OOO.XX. ",
"  .............  ",
"                 "};
/* XPM */
static const char *const stop_s_xpm[] = {
"17 15 4 1",
"       c None",
".      c #000000000000",
"X      c #9658A289BEFB",
"o      c #FFFF9A690000",
"                 ",
"     .......     ",
"    .XXX.XXX.    ",
"   .XXX.o.XXX.   ",
"  .XXXX.o.XXXX.  ",
"  .XXXX.o.XXXX.  ",
"  .XXXX.o.XXXX.  ",
"  .XXXX.o.XXXX.  ",
"  .XXXXX.XXXXX.  ",
"  .XXXXXXXXXXX.  ",
"  .XXXXX.XXXXX.  ",
"   .XXX.o.XXX.   ",
"    .XXX.XXX.    ",
"     .......     ",
"                 "};

/* XPM */
static const char *const bm_s_xpm[] = {
"17 15 6 1",
"       c None",
"@      c #FFFFFFFFFFFF",
"X      c #9658A289BEFB",
".      c #000000000000",
"O      c #FFFF9A690000",
"+      c #FFFF9A690000",
"    @X@X@X@X@X@   ",
"  .XXXXXXXXXXX.X  ",
"  .X......XXXX.+  ",
"  .XX.XXX..X.X.+  ",
"  .XX.XXXX.XXX.+  ",
"  .XX.XXX..X.X.+  ",
"  .XX.....XXXX.+  ",
"  .XX.XXXX.X.X.+  ",
"  .XX.XXXX.XXX.+  ",
"  .XX.XXX..XXX.+  ",
"  .X......XXXX.+  ",
"  .XXXXXXXXXXX.+  ",
"  .............+  ",
"   .++++++++++++  ",
"                  "};

/* XPM */
static const char *const new_s_xpm[] = {
"10 10 2 1",
"       c None",
"X      c #9658A289BEFB",
"XX      XX",
" XX X  XX ",
"  XX  XX  ",
"          ",
" X  XX X  ",
"  X XX  X ",
"          ",
"  XX  XX  ",
" XX  X XX ",
"XX      XX"};

/* XPM */
static const char *const search_xpm[] = {
"14 16 11 1",
"       c None",
".      c #000000",
"+      c #EEEEEE",
"[      c #EE0000",
"}      c #FF9A00",
"|      c #BB0000",
"1      c #96A29B",
"2      c #880000",
"3      c #660000",
"4      c #440000",
"5      c #330000",
"   .....      ",    
"  .     .     ",    
" .  +    .    ",    
".  +++    .   ",    
".   +     .   ",    
".         .   ",    
".         .   ",    
" .       .    ",    
"  .     .     ",    
"   ...545     ",    
"       4}4    ",
"       3}3    ",
"        2}2   ",
"        2}2   ",
"         2}2  ",
"         121  "};

/* XPM */
static const char *const full_screen_on_xpm[] = {
"15 15 2 1",
"       c None",
".      c #000000",
"               ",
" ............. ",
" .     .     . ",
" .    ...    . ",
" .   .....   . ",
" .  .......  . ",
" .     .     . ",
" .     .     . ",
" .     .     . ",
" .  .......  . ",
" .   .....   . ",
" .    ...    . ",
" .     .     . ",
" ............. ",
"               "};

/* XPM */
static const char *const full_screen_off_xpm[] = {
"15 15 2 1",
"       c None",
".      c #000000",
"               ",
" ............. ",
" . . . . . . . ",
" .. . . . . .. ",
" ............. ",
" .           . ",
" .           . ",
" .           . ",
" .           . ",
" .           . ",
" .           . ",
" ............. ",
" . . . . . . . ",
" ............. ",
"               "};

/* XPM */
static const char *const mini_bug_xpm[] = {
"16 16 5 1",
"       c None s None",
".      c black",
"X      c #c0c0c0",
"o      c #808080",
"#      c white"
"                ",
"                ",
"      .   .     ",
"       ...      ",
"     X.....X    ",
"     o.#...o    ",
"    o.#...o.o   ",
"    ..#oXo...   ",
"   .....X.....  ",
"    ....X....   ",
"   .o...X...o.  ",
"     ...X...    ",
"    .X..X..X.   ",
"       .o.      ",
"                ",
"                "};

/* XPM */
static const char *const mini_ok_xpm[] = {
"11 11 2 1",
"@ c #000000",
"_ s none m none c none",
"__________@",
"_________@@",
"________@@@",
"_______@@@_",
"_@@___@@@__",
"@@@__@@@___",
"@@@_@@@____",
"@@@@@@_____",
"@@@@@______",
"@@@@_______",
"_@@________"
};



/* XPM */
static const char *const imgload_on_xpm[] = {
"15 15 2 1",
"       c #FFFFFFFFFFFF",
".      c #00000000CF3C",
"               ",
" . .   .  ...  ",
" . .. .. .   . ",
" . . . . .     ",
" . .   . .  .. ",
" . .   . .   . ",
" . .   .  ...  ",
"               ",
"   ...  .   .  ",
"  .   . ..  .  ",
"  .   . . . .  ",
"  .   . .  ..  ",
"  .   . .   .  ",
"   ...  .   .  ",
"               "};

/* XPM */
static const char *const imgload_off_xpm[] = {
"15 15 2 1",
"       c #FFFFFFFFFFFF",
".      c #CF3C00000000",
"               ",
" . .   .  ...  ",
" . .. .. .   . ",
" . . . . .     ",
" . .   . .  .. ",
" . .   . .   . ",
" . .   .  ...  ",
"               ",
"  ...  ... ... ",
" .   . .   .   ",
" .   . ... ... ",
" .   . .   .   ",
" .   . .   .   ",
"  ...  .   .   ",
"               "};

/* XPM */
static const char *const left_i_xpm[] = {
"22 22 3 1",
"  c None",
". c #000000",
"@ c gray70",
"                      ",
"                      ",
"                      ",
"                      ",
"        @@            ",
"       @@@            ",
"      @@@@            ",
"     @@@@@@@@@@ @@@@  ",
"    @@@@@@@@@@@ @@@@  ",
"   @@@@@@@@@@@@ @@@@  ",
"  @@@@@@@@@@@@@ @@@@  ",
"  @@@@@@@@@@@@@ @@@@  ",
"   @@@@@@@@@@@@ @@@@  ",
"    @@@@@@@@@@@ @@@@  ",
"     @@@@@@@@@@ @@@@  ",
"      @@@@            ",
"       @@@            ",
"        @@            ",
"                 @@@@@",
"                  @ @ ",
"                   @  ",
"                      "};

/* XPM */
static const char *const right_i_xpm[] = {
"22 22 3 1",
"  c None",
". c #000000",
"@ c gray70",
"                      ",
"                      ",
"                      ",
"                      ",
"            @@        ",
"            @@@       ",
"            @@@@      ",
"  @@@@ @@@@@@@@@@     ",
"  @@@@ @@@@@@@@@@@    ",
"  @@@@ @@@@@@@@@@@@   ",
"  @@@@ @@@@@@@@@@@@@  ",
"  @@@@ @@@@@@@@@@@@@  ",
"  @@@@ @@@@@@@@@@@@   ",
"  @@@@ @@@@@@@@@@@    ",
"  @@@@ @@@@@@@@@@     ",
"            @@@@      ",
"            @@@       ",
"            @@        ",
"                 @@@@@",
"                  @ @ ",
"                   @  ",
"                      "};

/* XPM */
static const char *const stop_i_xpm[] = {
/* columns rows colors chars-per-pixel */
"22 22 2 1",
"       c None",
"@      c gray70",
/* pixels */
"                      ",
"                      ",
"      @@@@@@@@@       ",
"     @@@@@@@@@@@      ",
"    @@@@@@@@@@@@@     ",
"   @@@@@@@@@@@@@@@    ",
"  @@@@@@@@@@@@@@@@@   ",
" @@@@@@@@@@@@@@@@@@@  ",
" @@@@@@  @@@  @@@@@@  ",
" @@@@@@   @   @@@@@@  ",
" @@@@@@@     @@@@@@@  ",
" @@@@@@@@   @@@@@@@@  ",
" @@@@@@@     @@@@@@@  ",
" @@@@@@   @   @@@@@@  ",
" @@@@@@  @@@  @@@@@@  ",
" @@@@@@@@@@@@@@@@@@@  ",
"  @@@@@@@@@@@@@@@@@   ",
"   @@@@@@@@@@@@@@@    ",
"    @@@@@@@@@@@@@     ",
"     @@@@@@@@@@@      ",
"      @@@@@@@@@       ",
"                      "
};

/* XPM */
static const char *const stop_si_xpm[] = {
"16 16 2 1",
"       c None",
"@      c gray70",
"    @@@@@@@@    ",
"   @@@@@@@@@@   ",
"  @@@@@@@@@@@@  ",
" @@@@@@@@@@@@@@ ",
"@@@@@@@@@@@@@@@@",
"@@@@@ @@@@ @@@@@",
"@@@@@@ @@ @@@@@@",
"@@@@@@@  @@@@@@@",
"@@@@@@@  @@@@@@@",
"@@@@@@ @@ @@@@@@",
"@@@@@ @@@@ @@@@@",
"@@@@@@@@@@@@@@@@",
" @@@@@@@@@@@@@@ ",
"  @@@@@@@@@@@@  ",
"   @@@@@@@@@@   ",
"    @@@@@@@@    "};

/* XPM */
static const char *const left_si_xpm[] = {
"16 16 2 1",
"       c None",
"@      c gray70",
"                ",
"      @@        ",
"     @@@        ",
"    @@@@        ",
"   @@@@@@@@ @@@@",
"  @@@@@@@@@ @@@@",
" @@@@@@@@@@ @@@@",
"@@@@@@@@@@@ @@@@",
"@@@@@@@@@@@ @@@@",
" @@@@@@@@@@ @@@@",
"  @@@@@@@@@ @@@@",
"   @@@@@@@@ @@@@",
"    @@@@        ",
"     @@@   @@@@@",
"      @@    @ @ ",
"             @  "};

/* XPM */
static const char *const right_si_xpm[] = {
"16 16 2 1",
"       c None",
"@      c gray70",
"                ",
"        @@      ",
"        @@@     ",
"        @@@@    ",
"@@@@ @@@@@@@@   ",
"@@@@ @@@@@@@@@  ",
"@@@@ @@@@@@@@@@ ",
"@@@@ @@@@@@@@@@@",
"@@@@ @@@@@@@@@@@",
"@@@@ @@@@@@@@@@ ",
"@@@@ @@@@@@@@@  ",
"@@@@ @@@@@@@@   ",
"        @@@@    ",
"        @@@@@@@@",
"        @@  @ @ ",
"             @  "};

#endif /* __PIXMAPS_H__ */
